#ifndef POKEPLATINUM_BATTLE_BTLCMD_H
#define POKEPLATINUM_BATTLE_BTLCMD_H

#ifndef __ASM_PM_
#include "consts/btlcmd.h"
#endif

// TODO: move these to constgen
#define TRAINER_MESSAGE_LOSE   1
#define TRAINER_MESSAGE_LOSE_1 4
#define TRAINER_MESSAGE_LOSE_2 8
#define TRAINER_MESSAGE_WIN    100

#define BTLSCR_MSG_TEMP (0xFF)

#define WEATHER_EFFECT_HYDRATION   1
#define WEATHER_EFFECT_SOLAR_POWER 2

#endif // POKEPLATINUM_BATTLE_BTLCMD_H
