#ifndef POKEPLATINUM_BATTLE_GIVE_UP_MOVE_DATA_H
#define POKEPLATINUM_BATTLE_GIVE_UP_MOVE_DATA_H

typedef struct {
    u16 move;
    u16 unused_02;
} GiveUpMoveData;

#endif // POKEPLATINUM_BATTLE_GIVE_UP_MOVE_DATA_H
