#ifndef POKEPLATINUM_STRUCT_GIVE_UP_MOVE_DATA_H
#define POKEPLATINUM_STRUCT_GIVE_UP_MOVE_DATA_H

typedef struct {
    u16 unk_00;
    u16 unk_02;
} GiveUpMoveData;

#endif // POKEPLATINUM_STRUCT_GIVE_UP_MOVE_DATA_H
