#include "battle_sub_menus/battle_bag_buttons.h"

#include "battle_sub_menus/battle_bag.h"
#include "battle_sub_menus/battle_bag_text.h"
#include "battle_sub_menus/battle_bag_utils.h"
#include "battle_sub_menus/battle_sub_menu_buttons_defs.h"

#include "bg_window.h"
#include "heap.h"
#include "sprite_system.h"

#define BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET 17

#define USE_ITEM_BUTTON_DATA_Y_OFFSET              27
#define CANCEL_BUTTON_DATA_Y_OFFSET                57
#define POCKET_ITEM_BUTTON_DATA_X_OFFSET           16
#define POCKET_MENU_PREV_PAGE_BUTTON_DATA_Y_OFFSET 47
#define POCKET_MENU_NEXT_PAGE_BUTTON_DATA_Y_OFFSET 52
#define MENU_POCKET_ICON_DATA_X_OFFSET             20
#define MENU_POCKET_ICON_DATA_Y_OFFSET             47

enum Button {
    BUTTON_MENU_SCREEN_RECOVER_HP_POCKET = BATTLE_BAG_MENU_SCREEN_BUTTON_RECOVER_HP_POCKET,
    BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET = BATTLE_BAG_MENU_SCREEN_BUTTON_RECOVER_STATUS_POCKET,
    BUTTON_MENU_SCREEN_POKE_BALLS_POCKET = BATTLE_BAG_MENU_SCREEN_BUTTON_POKE_BALLS_POCKET,
    BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET = BATTLE_BAG_MENU_SCREEN_BUTTON_BATTLE_ITEMS_POCKET,
    BUTTON_MENU_SCREEN_LAST_USED_ITEM = BATTLE_BAG_MENU_SCREEN_BUTTON_LAST_USED_ITEM,
    BUTTON_MENU_SCREEN_CANCEL = BATTLE_BAG_MENU_SCREEN_BUTTON_CANCEL,
    BUTTON_POCKET_MENU_SCREEN_ITEM_1 = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_1,
    BUTTON_POCKET_MENU_SCREEN_ITEM_2 = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_2,
    BUTTON_POCKET_MENU_SCREEN_ITEM_3 = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_3,
    BUTTON_POCKET_MENU_SCREEN_ITEM_4 = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_4,
    BUTTON_POCKET_MENU_SCREEN_ITEM_5 = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_5,
    BUTTON_POCKET_MENU_SCREEN_ITEM_6 = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_6,
    BUTTON_POCKET_MENU_SCREEN_PREV_PAGE = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_PREV_PAGE,
    BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_NEXT_PAGE,
    BUTTON_POCKET_MENU_SCREEN_CANCEL = BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_CANCEL,
    BUTTON_USE_ITEM_SCREEN_USE = BATTLE_BAG_USE_ITEM_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_USE_ITEM_SCREEN_BUTTON_USE,
    BUTTON_USE_ITEM_SCREEN_CANCEL = BATTLE_BAG_USE_ITEM_MENU_SCREEN_BUTTON_OFFSET + BATTLE_BAG_USE_ITEM_SCREEN_BUTTON_CANCEL,
    BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_1 = BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_1,
    BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_2 = BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_2,
    BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_3 = BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_3,
    BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_4 = BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_4,
    BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_5 = BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_5,
    BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_6 = BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_ITEM_6,
};

static void LoadButtonData(u16 *buttonData, u16 *screenData, u8 xOffset, u8 yOffset, u8 width, u8 height);

static const BattleSubMenuButtonDimensions sButtonDimensions[] = {
    [BUTTON_MENU_SCREEN_RECOVER_HP_POCKET] = { .xCoord = 0, .yCoord = 1, .width = MENU_POCKET_BUTTON_WIDTH_TILES, .height = MENU_POCKET_BUTTON_HEIGHT_TILES },
    [BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET] = { .xCoord = 0, .yCoord = 10, .width = MENU_POCKET_BUTTON_WIDTH_TILES, .height = MENU_POCKET_BUTTON_HEIGHT_TILES },
    [BUTTON_MENU_SCREEN_POKE_BALLS_POCKET] = { .xCoord = 16, .yCoord = 1, .width = MENU_POCKET_BUTTON_WIDTH_TILES, .height = MENU_POCKET_BUTTON_HEIGHT_TILES },
    [BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET] = { .xCoord = 16, .yCoord = 10, .width = MENU_POCKET_BUTTON_WIDTH_TILES, .height = MENU_POCKET_BUTTON_HEIGHT_TILES },
    [BUTTON_MENU_SCREEN_LAST_USED_ITEM] = { .xCoord = 0, .yCoord = 19, .width = BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES },
    [BUTTON_MENU_SCREEN_CANCEL] = { .xCoord = 27, .yCoord = 19, .width = BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_ITEM_1] = { .xCoord = 32, .yCoord = 1, .width = POCKET_ITEM_BUTTON_WIDTH_TILES, .height = POCKET_ITEM_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_ITEM_2] = { .xCoord = 48, .yCoord = 1, .width = POCKET_ITEM_BUTTON_WIDTH_TILES, .height = POCKET_ITEM_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_ITEM_3] = { .xCoord = 32, .yCoord = 7, .width = POCKET_ITEM_BUTTON_WIDTH_TILES, .height = POCKET_ITEM_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_ITEM_4] = { .xCoord = 48, .yCoord = 7, .width = POCKET_ITEM_BUTTON_WIDTH_TILES, .height = POCKET_ITEM_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_ITEM_5] = { .xCoord = 32, .yCoord = 13, .width = POCKET_ITEM_BUTTON_WIDTH_TILES, .height = POCKET_ITEM_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_ITEM_6] = { .xCoord = 48, .yCoord = 13, .width = POCKET_ITEM_BUTTON_WIDTH_TILES, .height = POCKET_ITEM_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_PREV_PAGE] = { .xCoord = 32, .yCoord = 19, .width = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE] = { .xCoord = 37, .yCoord = 19, .width = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES },
    [BUTTON_POCKET_MENU_SCREEN_CANCEL] = { .xCoord = 59, .yCoord = 19, .width = BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES },
    [BUTTON_USE_ITEM_SCREEN_USE] = { .xCoord = 0, .yCoord = 51, .width = BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES },
    [BUTTON_USE_ITEM_SCREEN_CANCEL] = { .xCoord = 27, .yCoord = 51, .width = BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES }
};

static const u8 sMenuRecoverHPPocketButtonWindows[] = {
    BATTLE_BAG_MENU_WINDOW_HP_PP_RESTORE,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sMenuRecoverStatusPocketButtonWindows[] = {
    BATTLE_BAG_MENU_WINDOW_STATUS_HEALERS,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sMenuPokeBallsPocketButtonWindows[] = {
    BATTLE_BAG_MENU_WINDOW_POKE_BALLS,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sMenuBattleItemsPocketButtonWindows[] = {
    BATTLE_BAG_MENU_WINDOW_BATTLE_ITEMS,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sMenuLastUsedItemButtonWindows[] = {
    BATTLE_BAG_MENU_WINDOW_LAST_USED_ITEM,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenItem1ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_1_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_1_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenItem2ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_2_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_2_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenItem3ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_3_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_3_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenItem4ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_4_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_4_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenItem5ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_5_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_5_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenItem6ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_6_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ITEM_SLOT_6_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenAltItem1ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_1_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_1_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenAltItem2ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_2_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_2_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenAltItem3ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_3_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_3_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenAltItem4ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_4_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_4_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenAltItem5ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_5_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_5_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sPocketMenuScreenAltItem6ButtonWindows[] = {
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_6_NAME,
    BATTLE_BAG_POCKET_MENU_WINDOW_ALT_ITEM_SLOT_6_AMOUNT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 sUseItemScreenUseButtonWindows[] = {
    BATTLE_BAG_USE_ITEM_MENU_WINDOW_ITEM_USE,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 *const sScrollableWindows[] = {
    [BUTTON_MENU_SCREEN_RECOVER_HP_POCKET] = sMenuRecoverHPPocketButtonWindows,
    [BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET] = sMenuRecoverStatusPocketButtonWindows,
    [BUTTON_MENU_SCREEN_POKE_BALLS_POCKET] = sMenuPokeBallsPocketButtonWindows,
    [BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET] = sMenuBattleItemsPocketButtonWindows,
    [BUTTON_MENU_SCREEN_LAST_USED_ITEM] = sMenuLastUsedItemButtonWindows,
    [BUTTON_MENU_SCREEN_CANCEL] = NULL,
    [BUTTON_POCKET_MENU_SCREEN_ITEM_1] = sPocketMenuScreenItem1ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ITEM_2] = sPocketMenuScreenItem2ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ITEM_3] = sPocketMenuScreenItem3ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ITEM_4] = sPocketMenuScreenItem4ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ITEM_5] = sPocketMenuScreenItem5ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ITEM_6] = sPocketMenuScreenItem6ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_PREV_PAGE] = NULL,
    [BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE] = NULL,
    [BUTTON_POCKET_MENU_SCREEN_CANCEL] = NULL,
    [BUTTON_USE_ITEM_SCREEN_USE] = sUseItemScreenUseButtonWindows,
    [BUTTON_USE_ITEM_SCREEN_CANCEL] = NULL,
    [BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_1] = sPocketMenuScreenAltItem1ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_2] = sPocketMenuScreenAltItem2ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_3] = sPocketMenuScreenAltItem3ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_4] = sPocketMenuScreenAltItem4ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_5] = sPocketMenuScreenAltItem5ButtonWindows,
    [BUTTON_POCKET_MENU_SCREEN_ALT_ITEM_6] = sPocketMenuScreenAltItem6ButtonWindows
};

void BattleBagButtons_InitializeButtonData(BattleBag *battleBag, u16 *screenData)
{
    LoadButtonData(battleBag->menuPocketButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, 0, MENU_POCKET_BUTTON_WIDTH_TILES, MENU_POCKET_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuPocketButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, 0, MENU_POCKET_BUTTON_HEIGHT_TILES, MENU_POCKET_BUTTON_WIDTH_TILES, MENU_POCKET_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuPocketButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, 0, MENU_POCKET_BUTTON_HEIGHT_TILES * 2, MENU_POCKET_BUTTON_WIDTH_TILES, MENU_POCKET_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleBag->useItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, USE_ITEM_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->useItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, 0, USE_ITEM_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->useItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, 0, USE_ITEM_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES * 2, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->useItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, 0, USE_ITEM_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES * 2, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleBag->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, CANCEL_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, CANCEL_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES * 2, CANCEL_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleBag->pocketItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, POCKET_ITEM_BUTTON_DATA_X_OFFSET, 0, POCKET_ITEM_BUTTON_WIDTH_TILES, POCKET_ITEM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, POCKET_ITEM_BUTTON_DATA_X_OFFSET, POCKET_ITEM_BUTTON_HEIGHT_TILES, POCKET_ITEM_BUTTON_WIDTH_TILES, POCKET_ITEM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, POCKET_ITEM_BUTTON_DATA_X_OFFSET, POCKET_ITEM_BUTTON_HEIGHT_TILES * 2, POCKET_ITEM_BUTTON_WIDTH_TILES, POCKET_ITEM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketItemButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, POCKET_ITEM_BUTTON_DATA_X_OFFSET, POCKET_ITEM_BUTTON_HEIGHT_TILES * 3, POCKET_ITEM_BUTTON_WIDTH_TILES, POCKET_ITEM_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleBag->pocketPrevPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, POCKET_MENU_PREV_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketPrevPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, POCKET_MENU_PREV_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketPrevPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 2, POCKET_MENU_PREV_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketPrevPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 3, POCKET_MENU_PREV_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleBag->pocketNextPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, POCKET_MENU_NEXT_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketNextPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, POCKET_MENU_NEXT_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketNextPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 2, POCKET_MENU_NEXT_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleBag->pocketNextPageButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 3, POCKET_MENU_NEXT_PAGE_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleBag->menuScreenRecoverHPPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET, MENU_POCKET_ICON_DATA_Y_OFFSET, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenRecoverHPPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_DATA_Y_OFFSET, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenRecoverHPPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES * 2, MENU_POCKET_ICON_DATA_Y_OFFSET, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);

    LoadButtonData(battleBag->menuScreenRecoverStatusPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenRecoverStatusPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenRecoverStatusPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES * 2, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);

    LoadButtonData(battleBag->menuScreenPokeBallsPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES * 2, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenPokeBallsPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES * 2, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenPokeBallsPocketIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES * 2, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES * 2, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);

    LoadButtonData(battleBag->menuScreenBattleItemsIconData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES * 3, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenBattleItemsIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES * 3, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
    LoadButtonData(battleBag->menuScreenBattleItemsIconData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, MENU_POCKET_ICON_DATA_X_OFFSET + MENU_POCKET_ICON_WIDTH_TILES * 2, MENU_POCKET_ICON_DATA_Y_OFFSET + MENU_POCKET_ICON_HEIGHT_TILES * 3, MENU_POCKET_ICON_WIDTH_TILES, MENU_POCKET_ICON_HEIGHT_TILES);
}

static void LoadButtonData(u16 *buttonData, u16 *screenData, u8 xOffset, u8 yOffset, u8 width, u8 height)
{
    for (u16 i = 0; i < height; i++) {
        for (u16 l = 0; l < width; l++) {
            buttonData[i * width + l] = screenData[(yOffset + i) * TILE_SIZE_4BPP + xOffset + l];
        }
    }
}

static u16 *RetrieveRawButtonData(BattleBag *battleBag, enum Button button, enum BattleSubMenuButtonState buttonState)
{
    switch (button) {
    case BUTTON_MENU_SCREEN_RECOVER_HP_POCKET:
    case BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET:
    case BUTTON_MENU_SCREEN_POKE_BALLS_POCKET:
    case BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET:
        return battleBag->menuPocketButtonData[buttonState];
    case BUTTON_MENU_SCREEN_LAST_USED_ITEM:
        return battleBag->useItemButtonData[buttonState];
    case BUTTON_MENU_SCREEN_CANCEL:
    case BUTTON_POCKET_MENU_SCREEN_CANCEL:
    case BUTTON_USE_ITEM_SCREEN_CANCEL:
        return battleBag->cancelButtonData[buttonState];
    case BUTTON_POCKET_MENU_SCREEN_ITEM_1:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_2:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_3:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_4:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_5:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_6:
        return battleBag->pocketItemButtonData[buttonState];
    case BUTTON_POCKET_MENU_SCREEN_PREV_PAGE:
        return battleBag->pocketPrevPageButtonData[buttonState];
    case BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE:
        return battleBag->pocketNextPageButtonData[buttonState];
    case BUTTON_USE_ITEM_SCREEN_USE:
        return battleBag->useItemButtonData[buttonState];
    }

    return NULL;
}

static u16 GetButtonColor(BattleBag *battleBag, enum Button button, enum BattleSubMenuButtonState buttonState, enum BattleBagScreen screen)
{
    if (buttonState == BATTLE_SUB_MENU_BUTTON_STATE_DISABLED) {
        return 5;
    }

    switch (button) {
    case BUTTON_MENU_SCREEN_RECOVER_HP_POCKET:
    case BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET:
    case BUTTON_MENU_SCREEN_POKE_BALLS_POCKET:
    case BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET:
        return 0;
    case BUTTON_MENU_SCREEN_LAST_USED_ITEM:
        return 3;
    case BUTTON_MENU_SCREEN_CANCEL:
    case BUTTON_POCKET_MENU_SCREEN_CANCEL:
    case BUTTON_USE_ITEM_SCREEN_CANCEL:
    case BUTTON_POCKET_MENU_SCREEN_PREV_PAGE:
    case BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE:
        return 2;
    case BUTTON_POCKET_MENU_SCREEN_ITEM_1:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_2:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_3:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_4:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_5:
    case BUTTON_POCKET_MENU_SCREEN_ITEM_6:
        return 8 + battleBag->currentBattlePocket;
    case BUTTON_USE_ITEM_SCREEN_USE:
        if (screen == BATTLE_BAG_SCREEN_USE_ITEM) {
            return 8 + battleBag->currentBattlePocket;
        } else {
            return 1;
        }
    }

    return 0;
}

static void AddIconDataToButtonData(BattleBag *battleBag, u16 *buttonData, enum Button button, enum BattleSubMenuButtonState buttonState)
{
    u16 *iconData;

    if (button == BUTTON_MENU_SCREEN_RECOVER_HP_POCKET) {
        iconData = battleBag->menuScreenRecoverHPPocketIconData[buttonState];
    } else if (button == BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET) {
        iconData = battleBag->menuScreenRecoverStatusPocketIconData[buttonState];
    } else if (button == BUTTON_MENU_SCREEN_POKE_BALLS_POCKET) {
        iconData = battleBag->menuScreenPokeBallsPocketIconData[buttonState];
    } else if (button == BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET) {
        iconData = battleBag->menuScreenBattleItemsIconData[buttonState];
    } else {
        return;
    }

    for (u16 i = 0; i < MENU_POCKET_ICON_HEIGHT_TILES; i++) {
        for (u16 l = 0; l < MENU_POCKET_ICON_WIDTH_TILES; l++) {
            buttonData[MENU_POCKET_BUTTON_WIDTH_TILES * i + ((MENU_POCKET_BUTTON_WIDTH_TILES - MENU_POCKET_ICON_WIDTH_TILES) / 2) + l] = iconData[MENU_POCKET_ICON_WIDTH_TILES * i + l];
        }
    }
}

static void RetrieveButtonData(BattleBag *battleBag, u16 *buttonData, u8 button, u8 buttonState, u8 screen)
{
    u16 *rawButtonData = RetrieveRawButtonData(battleBag, button, buttonState);
    u16 colorData = GetButtonColor(battleBag, button, buttonState, screen) << 12;

    for (u16 i = 0; i < sButtonDimensions[button].width * sButtonDimensions[button].height; i++) {
        buttonData[i] = colorData | (rawButtonData[i] & 0xfff);
    }

    AddIconDataToButtonData(battleBag, buttonData, button, buttonState);
}

static void DrawButton(BattleBag *battleBag, u8 button, u8 buttonState, u8 screen)
{
    u16 *buttonData = Heap_Alloc(battleBag->context->heapID, sButtonDimensions[button].width * sButtonDimensions[button].height * sizeof(u16));

    RetrieveButtonData(battleBag, buttonData, button, buttonState, screen);

    Bg_LoadToTilemapRect(battleBag->background, BG_LAYER_SUB_2, buttonData, sButtonDimensions[button].xCoord, sButtonDimensions[button].yCoord, sButtonDimensions[button].width, sButtonDimensions[button].height);
    Bg_ScheduleTilemapTransfer(battleBag->background, BG_LAYER_SUB_2);
    Heap_Free(buttonData);
}

static void UpdateWindowScroll(BattleBag *battleBag, u8 button, enum BattleSubMenuButtonState buttonState)
{
    const u8 *windowsToScroll;
    u8 scrollDirection, scrollDistance;

    if (button >= BUTTON_POCKET_MENU_SCREEN_ITEM_1 && button <= BUTTON_POCKET_MENU_SCREEN_ITEM_6 && battleBag->useAltPocketMenuWindows == FALSE) {
        windowsToScroll = sScrollableWindows[BATTLE_BAG_POCKET_MENU_SCREEN_ALT_BUTTON_OFFSET + button - BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET];
    } else {
        windowsToScroll = sScrollableWindows[button];
    }

    if (windowsToScroll == NULL) {
        return;
    }

    switch (buttonState) {
    case BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED:
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSED:
        scrollDirection = SCROLL_DIRECTION_DOWN;
        scrollDistance = BATTLE_SUB_MENU_WINDOW_SCROLL_DEFAULT;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSING:
        scrollDirection = SCROLL_DIRECTION_UP;
        scrollDistance = BATTLE_SUB_MENU_WINDOW_SCROLL_PRESSING;
        break;
    }

    for (u16 i = 0; i < BATTLE_SUB_MENU_MAX_SCROLLABLE_WINDOWS; i++) {
        if (windowsToScroll[i] == BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR) {
            break;
        }

        Window_Scroll(&battleBag->windows[windowsToScroll[i]], scrollDirection, scrollDistance, 0);
        Window_ScheduleCopyToVRAM(&battleBag->windows[windowsToScroll[i]]);
    }
}

static void UpdateSpritePositions(BattleBag *battleBag, u8 button, enum BattleSubMenuButtonState buttonState)
{
    ManagedSprite *sprite;

    if (button >= BUTTON_POCKET_MENU_SCREEN_ITEM_1 && button <= BUTTON_POCKET_MENU_SCREEN_ITEM_6) {
        sprite = battleBag->sprites[button - BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET];
    } else if (button == BUTTON_MENU_SCREEN_LAST_USED_ITEM) {
        for (u8 i = 0; i < BATTLE_POCKET_ITEMS_PER_PAGE; i++) {
            sprite = battleBag->sprites[i];

            if (ManagedSprite_GetDrawFlag(sprite) != FALSE) {
                break;
            }
        }
    } else {
        return;
    }

    switch (buttonState) {
    case BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED:
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSED:
        ManagedSprite_OffsetPositionXY(sprite, 0, BATTLE_SUB_MENU_SPRITE_Y_POSITION_DEFAULT);
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSING:
        ManagedSprite_OffsetPositionXY(sprite, 0, BATTLE_SUB_MENU_SPRITE_Y_POSITION_PRESSING);
        break;
    }
}

void BattleBagButtons_PressButton(BattleBag *battleBag, u8 pressedButton, u8 unused)
{
    battleBag->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED;
    battleBag->unused2 = 0;
    battleBag->pressedButton = pressedButton;
    battleBag->unused3 = unused;
    battleBag->isAButtonPressed = TRUE;
}

void BattleBagButtons_Tick(BattleBag *battleBag)
{
    if (battleBag->isAButtonPressed == FALSE) {
        return;
    }

    switch (battleBag->pressedButtonState) {
    case BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED:
        DrawButton(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSING, battleBag->currentScreen);
        UpdateWindowScroll(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSING);
        UpdateSpritePositions(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSING);
        battleBag->unused2 = 0;
        battleBag->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_PRESSING;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSING:
        DrawButton(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED, battleBag->currentScreen);
        UpdateWindowScroll(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED);
        UpdateSpritePositions(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED);
        battleBag->unused2 = 0;
        battleBag->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_PRESSED;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSED:
        DrawButton(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, battleBag->currentScreen);
        UpdateWindowScroll(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED);
        UpdateSpritePositions(battleBag, battleBag->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED);
        battleBag->unused2 = 0;
        battleBag->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED;
        battleBag->isAButtonPressed = FALSE;
        break;
    }
}

void BattleBagButtons_InitializeButtons(BattleBag *battleBag, u8 screen)
{
    switch (screen) {
    case BATTLE_BAG_SCREEN_MENU:
        DrawButton(battleBag, BUTTON_MENU_SCREEN_RECOVER_HP_POCKET, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        DrawButton(battleBag, BUTTON_MENU_SCREEN_RECOVER_STATUS_POCKET, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        DrawButton(battleBag, BUTTON_MENU_SCREEN_POKE_BALLS_POCKET, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        DrawButton(battleBag, BUTTON_MENU_SCREEN_BATTLE_ITEMS_POCKET, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);

        if (battleBag->context->lastUsedItem == ITEM_NONE) {
            DrawButton(battleBag, BUTTON_MENU_SCREEN_LAST_USED_ITEM, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, screen);
        } else {
            DrawButton(battleBag, BUTTON_MENU_SCREEN_LAST_USED_ITEM, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        }

        DrawButton(battleBag, BUTTON_MENU_SCREEN_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        break;
    case BATTLE_BAG_SCREEN_POCKET_MENU: {
        for (u32 i = 0; i < BATTLE_POCKET_ITEMS_PER_PAGE; i++) {
            if (BattleBag_GetItem(battleBag, i) == ITEM_NONE) {
                DrawButton(battleBag, BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + i, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, screen);
            } else {
                DrawButton(battleBag, BATTLE_BAG_POCKET_MENU_SCREEN_BUTTON_OFFSET + i, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
            }
        }
    }

        if (battleBag->numBattlePocketPages[battleBag->currentBattlePocket] == 0) {
            DrawButton(battleBag, BUTTON_POCKET_MENU_SCREEN_PREV_PAGE, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, screen);
            DrawButton(battleBag, BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, screen);
        } else {
            DrawButton(battleBag, BUTTON_POCKET_MENU_SCREEN_PREV_PAGE, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
            DrawButton(battleBag, BUTTON_POCKET_MENU_SCREEN_NEXT_PAGE, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        }

        DrawButton(battleBag, BUTTON_POCKET_MENU_SCREEN_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        break;
    case BATTLE_BAG_SCREEN_USE_ITEM:
        DrawButton(battleBag, BUTTON_USE_ITEM_SCREEN_USE, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
        DrawButton(battleBag, BUTTON_USE_ITEM_SCREEN_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, screen);
    }
}
