WAVE_ARC_BASIC = custom_target('WAVE_ARC_BASIC.swar',
    input: [ files([
        '000.wav',
        '001.wav',
        '002.wav',
        '003.wav',
        '004.wav',
        '005.wav',
        '006.wav',
        '007.wav',
        '008.wav',
        '009.wav',
        '010.wav',
        '011.wav',
        '012.wav',
        '013.wav',
        '014.wav',
        '015.wav',
        '016.wav',
        '017.wav',
        '018.wav',
        '019.wav',
        '020.wav',
        '021.wav',
        '022.wav',
        '023.wav',
        '024.wav',
        '025.wav',
        '026.wav',
        '027.wav',
        '028.wav',
        '029.wav',
        '030.wav',
        '031.wav',
        '032.wav',
        '033.wav',
        '034.wav',
        '035.wav',
        '036.wav',
        '037.wav',
        '038.wav',
        '039.wav',
        '040.wav',
        '041.wav',
        '042.wav',
        '043.wav',
        '044.wav',
        '045.wav',
        '046.wav',
        '047.wav',
        '048.wav',
        '049.wav',
        '050.wav',
        '051.wav',
        '052.wav',
        '053.wav',
        '054.wav',
        '055.wav',
        '056.wav',
        '057.wav',
        '058.wav',
        '059.wav',
        '060.wav',
        '061.wav',
        '062.wav',
        '063.wav',
        '064.wav',
        '065.wav',
        '066.wav',
        '067.wav',
        '068.wav',
        '069.wav',
        '070.wav',
        '071.wav',
        '072.wav',
        '073.wav',
        '074.wav',
        '075.wav',
        '076.wav',
        '077.wav',
        '078.wav',
        '079.wav',
        '080.wav',
        '081.wav',
        '082.wav',
        '083.wav',
        '084.wav',
        '085.wav',
        '086.wav',
        '087.wav',
        '088.wav',
        '089.wav',
        '090.wav',
        '091.wav',
        '092.wav',
        '093.wav',
        '094.wav',
        '095.wav',
        '096.wav',
        '097.wav',
        '098.wav',
        '099.wav',
        '100.wav',
        '101.wav',
        '102.wav',
        '103.wav',
        '104.wav',
        '105.wav',
        '106.wav',
        '107.wav',
        '108.wav',
        '109.wav',
        '110.wav',
        '111.wav',
        '112.wav',
        '113.wav',
        '114.wav',
        '115.wav',
        '116.wav',
        '117.wav',
        '118.wav',
        '119.wav',
        '120.wav',
        '121.wav',
        '122.wav',
        '123.wav',
        '124.wav',
        '125.wav',
        '126.wav',
        '127.wav',
        '128.wav',
        '129.wav',
        '130.wav',
        '131.wav',
        '132.wav',
        '133.wav',
        '134.wav',
        '135.wav',
        '136.wav',
        '137.wav',
        '138.wav',
        '139.wav',
        '140.wav',
        '141.wav',
        '142.wav',
        '143.wav',
        '144.wav',
        '145.wav',
        '146.wav',
        '147.wav',
        '148.wav',
        '149.wav',
        '150.wav',
        '151.wav',
        '152.wav',
        '153.wav',
        '154.wav',
        '155.wav',
        '156.wav',
        '157.wav',
        '158.wav',
        '159.wav',
        '160.wav',
        '161.wav',
        '162.wav',
    ]),],
    output: 'WAVE_ARC_BASIC.swar',
    command: [
        nitrosfx_exe,
        '@CURRENT_SOURCE_DIR@', '@OUTPUT0@',
    ],
)
