#ifndef POKEPLATINUM_CONSTANTS_UNDERGROUND_H
#define POKEPLATINUM_CONSTANTS_UNDERGROUND_H

#define MAX_TREASURE_SLOTS  40
#define MAX_SPHERE_SLOTS    40
#define MAX_TRAP_SLOTS      40
#define MAX_GOODS_BAG_SLOTS 40
#define MAX_GOODS_PC_SLOTS  200

#define MAX_PLACED_GOODS  15
#define MAX_BASE_BOULDERS 16

#define MAX_BURIED_SPHERES 100
#define MAX_PLACED_TRAPS   16
#define MAX_SPAWNED_TRAPS  64
#define MAX_MINING_SPOTS   250

#define MAX_SPHERE_SIZE 99

#define PC_COORDINATE_X 15
#define PC_COORDINATE_Z 12

#define UNDERGROUND_MAIN_AREA_START_X 32
#define UNDERGROUND_MAIN_AREA_START_Z 64

#define UNDERGROUND_MAX_X 479
#define UNDERGROUND_MAX_Z 479

#define UNDERGROUND_MAIN_AREA_WIDTH (UNDERGROUND_MAX_X - UNDERGROUND_MAIN_AREA_START_X)
#define UNDERGROUND_MAIN_AREA_DEPTH (UNDERGROUND_MAX_Z - UNDERGROUND_MAIN_AREA_START_Z)

#define MAX_SECRET_BASE_GOODS (MAX_PLACED_GOODS + MAX_BASE_BOULDERS + 1)

#define MAX_GOOD_WIDTH 3
#define MAX_GOOD_DEPTH 3

typedef struct Coordinates {
    u16 x;
    u16 z;
} Coordinates;

typedef struct Coordinates2D {
    u16 x;
    u16 y;
} Coordinates2D;

typedef struct SpherePrice {
    u8 sphereType;
    u8 minSize;
    u8 maxSize;
} SpherePrice;

#endif // POKEPLATINUM_UNDERGROUND_TYPES_H
