from enum import Enum, Flag, auto


class EvoMethod(Flag):
    NONE                = 0
    HAPPINESS           = auto()
    HAPPINESS_DAY       = auto()
    HAPPINESS_NIGHT     = auto()
    LEVEL_UP            = auto()
    TRADE               = auto()
    TRADE_WITH_ITEM     = auto()
    USE_ITEM            = auto()
    LEVEL_ATK_GT_DEF    = auto()
    LEVEL_ATK_EQ_DEF    = auto()
    LEVEL_ATK_LT_DEF    = auto()
    LEVEL_PID_LOW       = auto()
    LEVEL_PID_HIGH      = auto()
    LEVEL_NINJASK       = auto()
    LEVEL_SHEDINJA      = auto()
    BEAUTY              = auto()
    USE_ITEM_MALE       = auto()
    USE_ITEM_FEMALE     = auto()
    USE_ITEM_DAY        = auto()
    USE_ITEM_NIGHT      = auto()
    KNOW_MOVE           = auto()
    MON_IN_PARTY        = auto()
    LEVEL_MALE          = auto()
    LEVEL_FEMALE        = auto()
    ELECTRIC_FIELD      = auto()
    MOSSY_STONE         = auto()
    ICY_STONE           = auto()
    LEVEL_DAY           = auto()
    LEVEL_NIGHT         = auto()
    LEVEL_DUSK          = auto()
    LEVEL_RAIN          = auto()
    HAS_MOVE_TYPE       = auto()
    DARK_TYPE_IN_PARTY  = auto()
    TRADE_SPECIFIC_MON  = auto()
    NATURE_AMPED        = auto()
    NATURE_LOWKEY       = auto()
    NUM_CRITICAL_HITS   = auto()
    HURT_IN_BATTLE      = auto()
