#ifndef POKEPLATINUM_STRUCT_0202D764_DECL_H
#define POKEPLATINUM_STRUCT_0202D764_DECL_H

typedef struct WifiBattleTowerDownloadData_t WifiBattleTowerDownloadData;

#endif // POKEPLATINUM_STRUCT_0202D764_DECL_H
