#ifndef POKEPLATINUM_STRUCT_0200C704_DECL_H
#define POKEPLATINUM_STRUCT_0200C704_DECL_H

typedef struct AnimationResourceCollection_t AnimationResourceCollection;

#endif // POKEPLATINUM_STRUCT_0200C704_DECL_H
