#ifndef POKEPLATINUM_CONSTANTS_ACCESSORIES_H
#define POKEPLATINUM_CONSTANTS_ACCESSORIES_H

#include "generated/accessories.h"

#define MAX_NON_UNIQUE_ACCESSORIES_PER_TYPE 9
#define MAX_UNIQUE_ACCESSORIES_PER_TYPE     1

#endif // POKEPLATINUM_CONSTANTS_ACCESSORIES_H
