#ifndef POKEPLATINUM_CONSTANTS_ACCESSORIES_H
#define POKEPLATINUM_CONSTANTS_ACCESSORIES_H

#include "generated/accessories.h"

#define MAX_ACCESORIES_PER_TYPE 9

#endif // POKEPLATINUM_CONSTANTS_ACCESSORIES_H
