#ifndef POKEPLATINUM_CONSTANTS_ANIMATION_TAGS_H
#define POKEPLATINUM_CONSTANTS_ANIMATION_TAGS_H

#define ANIMATION_TAG_DOOR_1 77
#define ANIMATION_TAG_DOOR_2 78

#endif // POKEPLATINUM_CONSTANTS_ANIMATION_TAGS_H
