#ifndef POKEPLATINUM_CONSTANTS_APPROACH_TYPE_H
#define POKEPLATINUM_CONSTANTS_APPROACH_TYPE_H

enum ApproachType {
    APPROACH_TYPE_SINGLES = 0,
    APPROACH_TYPE_DOUBLES,
    APPROACH_TYPE_VS2
};

#endif // POKEPLATINUM_CONSTANTS_APPROACH_TYPE_H
