#ifndef POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H
#define POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H

#define FRONTIER_CHALLENGE_SINGLE    0
#define FRONTIER_CHALLENGE_DOUBLE    1
#define FRONTIER_CHALLENGE_MULTI     2
#define FRONTIER_CHALLENGE_MULTI_WFC 3

#endif // POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H
