#ifndef POKEPLATINUM_CONSTANTS_BATTLE_ARCADE_FUNCTIONS_H
#define POKEPLATINUM_CONSTANTS_BATTLE_ARCADE_FUNCTIONS_H

#define BA_FUNC_UNK_0                    0
#define BA_FUNC_UNK_1                    1
#define BA_FUNC_SET_CHALLENGE_TYPE       2
#define BA_FUNC_UNK_3                    3
#define BA_FUNC_UNK_4                    4
#define BA_FUNC_INCREMENT_CURRENT_STREAK 5
#define BA_FUNC_UNK_6                    6
#define BA_FUNC_RESET_SYSTEM             7
#define BA_FUNC_UNK_8                    8
#define BA_FUNC_UNK_9                    9
#define BA_FUNC_UNK_10                   10
#define BA_FUNC_UNK_11                   11
#define BA_FUNC_UNK_12                   12
#define BA_FUNC_UNK_13                   13
#define BA_FUNC_UNK_14                   14
#define BA_FUNC_UNK_15                   15
#define BA_FUNC_UNK_16                   16
#define BA_FUNC_GET_CHALLENGE_TYPE       17
#define BA_FUNC_UNK_18                   18
#define BA_FUNC_UNK_19                   19
#define BA_FUNC_UNK_20                   20
#define BA_FUNC_UNK_21                   21
#define BA_FUNC_UNK_22                   22
#define BA_FUNC_UNK_23                   23
#define BA_FUNC_UNK_24                   24
#define BA_FUNC_UNK_25                   25
#define BA_FUNC_UNK_26                   26
#define BA_FUNC_UNK_27                   27
#define BA_FUNC_IS_MULTIPLAYER_CHALLENGE 28
#define BA_FUNC_UNK_29                   29
#define BA_FUNC_UNK_30                   30
#define BA_FUNC_UNK_31                   31
#define BA_FUNC_UNK_32                   32
#define BA_FUNC_UNK_33                   33
#define BA_FUNC_UNK_34                   34
#define BA_FUNC_UNK_35                   35
#define BA_FUNC_UNK_36                   36
#define BA_FUNC_UNK_37                   37
#define BA_FUNC_UNK_38                   38
#define BA_FUNC_UNK_39                   39
#define BA_FUNC_UNK_40                   40
#define BA_FUNC_UNK_41                   41
#define BA_FUNC_UNK_42                   42
#define BA_FUNC_UNK_43                   43
#define BA_FUNC_UNK_44                   44
#define BA_FUNC_UNK_45                   45
#define BA_FUNC_UNK_46                   46
#define BA_FUNC_UNK_47                   47
#define BA_FUNC_UNK_48                   48
#define BA_FUNC_UNK_49                   49
#define BA_FUNC_UNK_50                   50
#define BA_FUNC_UNK_51                   51
#define BA_FUNC_UNK_52                   52

#endif // POKEPLATINUM_CONSTANTS_BATTLE_ARCADE_FUNCTIONS_H
