#ifndef POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H
#define POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H

#define FRONTIER_CHALLENGE_SINGLE    0
#define FRONTIER_CHALLENGE_DOUBLE    1
#define FRONTIER_CHALLENGE_MULTI     2
#define FRONTIER_CHALLENGE_MULTI_WFC 3

#define BATTLES_PER_ROUND_ARCADE 7

#define ARCADE_PARTY_SIZE_SOLO  3
#define ARCADE_PARTY_SIZE_MULTI 2

#define ARCADE_EFFECT_LOWER_FOE_HP     0
#define ARCADE_EFFECT_POISON_FOE       1
#define ARCADE_EFFECT_PARALYZE_FOE     2
#define ARCADE_EFFECT_BURN_FOE         3
#define ARCADE_EFFECT_SLEEP_FOE        4
#define ARCADE_EFFECT_FREEZE_FOE       5
#define ARCADE_EFFECT_FOE_GET_BERRY    6
#define ARCADE_EFFECT_FOE_GET_ITEM     7
#define ARCADE_EFFECT_FOE_GET_LEVELS   8
#define ARCADE_EFFECT_LOWER_ALLY_HP    9
#define ARCADE_EFFECT_POISON_ALLY      10
#define ARCADE_EFFECT_PARALYZE_ALLY    11
#define ARCADE_EFFECT_BURN_ALLY        12
#define ARCADE_EFFECT_SLEEP_ALLY       13
#define ARCADE_EFFECT_FREEZE_ALLY      14
#define ARCADE_EFFECT_ALLY_GET_BERRY   15
#define ARCADE_EFFECT_ALLY_GET_ITEM    16
#define ARCADE_EFFECT_ALLY_GET_LEVELS  17
#define ARCADE_EFFECT_SUNNY_BATTLE     18
#define ARCADE_EFFECT_RAINY_BATTLE     19
#define ARCADE_EFFECT_SANDY_BATTLE     20
#define ARCADE_EFFECT_HAIL_BATTLE      21
#define ARCADE_EFFECT_FOGGY_BATTLE     22
#define ARCADE_EFFECT_TRICK_ROOM       23
#define ARCADE_EFFECT_SWAP_MONS        24
#define ARCADE_EFFECT_SPEED_UP         25
#define ARCADE_EFFECT_SLOW_DOWN        26
#define ARCADE_EFFECT_RANDOMIZE_CURSOR 27
#define ARCADE_EFFECT_GET_1_BP         28
#define ARCADE_EFFECT_NO_BATTLE        29
#define ARCADE_EFFECT_NO_EVENT         30
#define ARCADE_EFFECT_GET_3_BP         31
#define NUM_ARCADE_EFFECTS             32

#define ARCADE_EFFECT_CATEGORY_FOE   0
#define ARCADE_EFFECT_CATEGORY_ALLY  1
#define ARCADE_EFFECT_CATEGORY_ENV   2
#define ARCADE_EFFECT_CATEGORY_BONUS 3
#define NUM_ARCADE_EFFECT_CATEGORIES 4

#endif // POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H
