#ifndef POKEPLATINUM_CONSTANTS_BATTLE_HALL_FUNCTIONS_H
#define POKEPLATINUM_CONSTANTS_BATTLE_HALL_FUNCTIONS_H

enum BattleHallLobbyFunction {
    BH_LOBBY_FUNC_CHECK_PARTY_ELIGIBLE = 0,
    BH_LOBBY_FUNC_CHECK_STREAK_ACTIVE,
    BH_LOBBY_FUNC_GET_CURRENT_STREAK_SPECIES,
    BH_LOBBY_FUNC_DELETE_ACTIVE_STREAK,
    BH_LOBBY_FUNC_SELECT_POKEMON,
};

enum BattleHallFunction {
    BH_FUNC_UNK_0 = 0,
    BH_FUNC_UNK_1,
    BH_FUNC_SET_CHALLENGE_TYPE,
    BH_FUNC_GET_SELECTED_TYPE_INDEX,
    BH_FUNC_GET_CURRENT_STREAK,
    BH_FUNC_INCREMENT_CURRENT_STREAK,
    BH_FUNC_UNK_6,
    BH_FUNC_RESET_SYSTEM,
    BH_FUNC_UNK_8,
    BH_FUNC_CHECK_HAS_SAVED,
    BH_FUNC_QUICKSAVE,
    BH_FUNC_UNK_11,
    BH_FUNC_UNK_12,
    BH_FUNC_UNK_13,
    BH_FUNC_INCREMENT_CURRENT_BATTLE,
    BH_FUNC_GET_PLAYERS_MONS_SPECIES,
    BH_FUNC_UNK_16,
    BH_FUNC_GET_CHALLENGE_TYPE,
    BH_FUNC_UNK_18,
    BH_FUNC_GET_CURRENT_ROUND,
    BH_FUNC_GET_OPPONENT_OBJECT_ID,
    BH_FUNC_SAVE_ON_LOSS,
    BH_FUNC_SAVE_ON_COMPLETING_ROUND,
    BH_FUNC_GET_CURRENT_BATTLE,
    BH_FUNC_UNK_24,
    BH_FUNC_UNK_25,
    BH_FUNC_UNK_26,
    BH_FUNC_RESTORE_HELD_ITEMS,
    BH_FUNC_INCREMENT_RANK_OF_BEATEN_TYPE,
    BH_FUNC_UNK_29,
    BH_FUNC_IS_MULTIPLAYER_CHALLENGE,
    BH_FUNC_TOGGLE_ENGINE_LAYER,
    BH_FUNC_LOAD_TRAINERS,
    BH_FUNC_GET_RANK_OF_BEATEN_TYPE,
    BH_FUNC_GET_EARNED_BP,
    BH_FUNC_CAP_TYPE_RANKS,
    BH_FUNC_SET_BASE_LEVEL,
    BH_FUNC_GET_NEXT_BATTLE_TYPE,
    BH_FUNC_DUMMY,
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_HALL_FUNCTIONS_H
