#ifndef POKEPLATINUM_CONSTANTS_BATTLE_TOWER_H
#define POKEPLATINUM_CONSTANTS_BATTLE_TOWER_H

#define BT_PARAM_PLAYER_GRAPHICS_ID  0
#define BT_PARAM_PARTNER_GRAPHICS_ID 1
#define BT_PARAM_PARTNER_ID          2

#define BT_PARTNER_CHERYL 0
#define BT_PARTNER_MIRA   1
#define BT_PARTNER_RILEY  2
#define BT_PARTNER_MARLEY 3
#define BT_PARTNER_BUCK   4
#define BT_PARTNERS_COUNT 5

#define BT_OPPONENTS_COUNT 7

#define BT_SINGLES_PARTY_SIZE 3
#define BT_DOUBLES_PARTY_SIZE 4

#endif // POKEPLATINUM_CONSTANTS_BATTLE_TOWER_H
