#ifndef POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H
#define POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H

enum BattleFrontierScene {
    FRONTIER_SCENE_0 = 0,
    FRONTIER_SCENE_1,
    FRONTIER_SCENE_2,
    FRONTIER_SCENE_FACTORY_CORRIDOR,
    FRONTIER_SCENE_FACTORY_BATTLE_ROOM,
    FRONTIER_SCENE_TOWER_CORRIDOR,
    FRONTIER_SCENE_TOWER_MULTI_CORRIDOR,
    FRONTIER_SCENE_TOWER_BATTLE_ROOM,
    FRONTIER_SCENE_TOWER_MULTI_BATTLE_ROOM,
    FRONTIER_SCENE_HALL_CORRIDOR,
    FRONTIER_SCENE_HALL_BATTLE_ROOM,
    FRONTIER_SCENE_CASTLE_CORRIDOR,
    FRONTIER_SCENE_CASTLE_BATTLE_ROOM,
    FRONTIER_SCENE_13,
    FRONTIER_SCENE_14,
    FRONTIER_SCENE_ARCADE_CORRIDOR,
    FRONTIER_SCENE_ARCADE_BATTLE_ROOM,
};

#define FRONTIER_CHALLENGE_SINGLE    0
#define FRONTIER_CHALLENGE_DOUBLE    1
#define FRONTIER_CHALLENGE_MULTI     2
#define FRONTIER_CHALLENGE_MULTI_WFC 3

#define FRONTIER_RECORDS_APP_TOWER   1
#define FRONTIER_RECORDS_APP_FACTORY 2
#define FRONTIER_RECORDS_APP_CASTLE  4
#define FRONTIER_RECORDS_APP_HALL    5
#define FRONTIER_RECORDS_APP_ARCADE  6

#define HALL_BATTLES_PER_ROUND    10
#define HALL_STREAK_SILVER_BATTLE 50
#define HALL_STREAK_GOLD_BATTLE   170
#define HALL_MAX_DISTINCT_ROUNDS  ((HALL_STREAK_GOLD_BATTLE / HALL_BATTLES_PER_ROUND) + 1)

#define HALL_NEXT_BATTLE_NORMAL 0
#define HALL_NEXT_BATTLE_SILVER 1
#define HALL_NEXT_BATTLE_GOLD   2

#define HALL_MAX_TYPE_RANK 10

#define BATTLES_PER_ROUND_ARCADE 7

#define ARCADE_PARTY_SIZE_SOLO  3
#define ARCADE_PARTY_SIZE_MULTI 2

#define ARCADE_EFFECT_LOWER_FOE_HP     0
#define ARCADE_EFFECT_POISON_FOE       1
#define ARCADE_EFFECT_PARALYZE_FOE     2
#define ARCADE_EFFECT_BURN_FOE         3
#define ARCADE_EFFECT_SLEEP_FOE        4
#define ARCADE_EFFECT_FREEZE_FOE       5
#define ARCADE_EFFECT_FOE_GET_BERRY    6
#define ARCADE_EFFECT_FOE_GET_ITEM     7
#define ARCADE_EFFECT_FOE_LEVEL_UP     8
#define ARCADE_EFFECT_LOWER_ALLY_HP    9
#define ARCADE_EFFECT_POISON_ALLY      10
#define ARCADE_EFFECT_PARALYZE_ALLY    11
#define ARCADE_EFFECT_BURN_ALLY        12
#define ARCADE_EFFECT_SLEEP_ALLY       13
#define ARCADE_EFFECT_FREEZE_ALLY      14
#define ARCADE_EFFECT_ALLY_GET_BERRY   15
#define ARCADE_EFFECT_ALLY_GET_ITEM    16
#define ARCADE_EFFECT_ALLY_LEVEL_UP    17
#define ARCADE_EFFECT_SUNNY_BATTLE     18
#define ARCADE_EFFECT_RAINY_BATTLE     19
#define ARCADE_EFFECT_SANDY_BATTLE     20
#define ARCADE_EFFECT_HAIL_BATTLE      21
#define ARCADE_EFFECT_FOGGY_BATTLE     22
#define ARCADE_EFFECT_TRICK_ROOM       23
#define ARCADE_EFFECT_SPEED_UP         24
#define ARCADE_EFFECT_SLOW_DOWN        25
#define ARCADE_EFFECT_RANDOMIZE_CURSOR 26
#define ARCADE_EFFECT_SWAP_MONS        27
#define ARCADE_EFFECT_GET_1_BP         28
#define ARCADE_EFFECT_NO_BATTLE        29
#define ARCADE_EFFECT_NO_EVENT         30
#define ARCADE_EFFECT_GET_3_BP         31
#define NUM_ARCADE_EFFECTS             32

#define ARCADE_EFFECT_CATEGORY_FOE   0
#define ARCADE_EFFECT_CATEGORY_ALLY  1
#define ARCADE_EFFECT_CATEGORY_ENV   2
#define ARCADE_EFFECT_CATEGORY_BONUS 3
#define NUM_ARCADE_EFFECT_CATEGORIES 4

#endif // POKEPLATINUM_CONSTANTS_BATTLE_FRONTIER_H
