#ifndef POKEPLATINUM_BATTLE_FRONTIER_MOVEMENTS_H
#define POKEPLATINUM_BATTLE_FRONTIER_MOVEMENTS_H

#define FRONTIER_MOVEMENT_FACE_NORTH                0
#define FRONTIER_MOVEMENT_FACE_SOUTH                1
#define FRONTIER_MOVEMENT_FACE_WEST                 2
#define FRONTIER_MOVEMENT_FACE_EAST                 3
#define FRONTIER_MOVEMENT_WALK_NORTH                4
#define FRONTIER_MOVEMENT_WALK_SOUTH                5
#define FRONTIER_MOVEMENT_WALK_WEST                 6
#define FRONTIER_MOVEMENT_WALK_EAST                 7
#define FRONTIER_MOVEMENT_WALK_SLOW_NORTH           8
#define FRONTIER_MOVEMENT_WALK_SLOW_SOUTH           9
#define FRONTIER_MOVEMENT_WALK_SLOW_WEST            10
#define FRONTIER_MOVEMENT_WALK_SLOW_EAST            11
#define FRONTIER_MOVEMENT_WALK_FAST_NORTH           12
#define FRONTIER_MOVEMENT_WALK_FAST_SOUTH           13
#define FRONTIER_MOVEMENT_WALK_FAST_WEST            14
#define FRONTIER_MOVEMENT_WALK_FAST_EAST            15
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_NORTH        16
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_SOUTH        17
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_WEST         18
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_EAST         19
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_SLOW_NORTH   20
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_SLOW_SOUTH   21
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_SLOW_WEST    22
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_SLOW_EAST    23
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FAST_NORTH   24
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FAST_SOUTH   25
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FAST_WEST    26
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FAST_EAST    27
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FASTER_NORTH 28
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FASTER_SOUTH 29
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FASTER_WEST  30
#define FRONTIER_MOVEMENT_WALK_ON_SPOT_FASTER_EAST  31

#define FRONTIER_MOVEMENT_DELAY_OFFSET 32

#define FRONTIER_MOVEMENT_DELAY_1  32
#define FRONTIER_MOVEMENT_DELAY_2  33
#define FRONTIER_MOVEMENT_DELAY_4  34
#define FRONTIER_MOVEMENT_DELAY_8  35
#define FRONTIER_MOVEMENT_DELAY_15 36
#define FRONTIER_MOVEMENT_DELAY_16 37
#define FRONTIER_MOVEMENT_DELAY_32 38

#define FRONTIER_MOVEMENT_WARP_IN  39
#define FRONTIER_MOVEMENT_WARP_OUT 40

#define NUM_FRONTIER_MOVEMENTS 41

#define FRONTIER_MOVEMENT_END_MOVEMENT 0xFD13

#endif // POKEPLATINUM_BATTLE_FRONTIER_MOVEMENTS_H
