#ifndef POKEPLATINUM_CONSTANTS_BATTLE_TOWER_H
#define POKEPLATINUM_CONSTANTS_BATTLE_TOWER_H

#define BT_PARAM_PLAYER_GRAPHICS_ID  0
#define BT_PARAM_PARTNER_GRAPHICS_ID 1
#define BT_PARAM_PARTNER_ID          2

#define BT_PARTNER_CHERYL 0
#define BT_PARTNER_MIRA   1
#define BT_PARTNER_RILEY  2
#define BT_PARTNER_MARLEY 3
#define BT_PARTNER_BUCK   4
#define BT_PARTNERS_COUNT 5

#define BT_OPPONENTS_COUNT 7

#define BT_SINGLES_PARTY_SIZE 3
#define BT_DOUBLES_PARTY_SIZE 4

#define BT_WIFI_SAVE_FIELD_CHALLENGE_MODE    0
#define BT_WIFI_SAVE_FIELD_NEXT_OPPONENT_NUM 1
#define BT_WIFI_SAVE_FIELD_UNK_03            2
#define BT_WIFI_SAVE_FIELD_UNK_04            3
#define BT_WIFI_SAVE_FIELD_UNK_06            4
#define BT_WIFI_SAVE_FIELD_PARTY_SLOTS       5
#define BT_WIFI_SAVE_FIELD_PARTNER_DATA      6
#define BT_WIFI_SAVE_FIELD_UNK_00_0          7
#define BT_WIFI_SAVE_FIELD_TRAINER_IDS       8
#define BT_WIFI_SAVE_FIELD_PARTNER_ID        9
#define BT_WIFI_SAVE_FIELD_RNG_SEED          10

#define TOWER_RECORDS_RESULTS_SOLO  0
#define TOWER_RECORDS_RESULTS_MULTI 1
#define TOWER_RECORDS_RESULTS_WIFI  2

#endif // POKEPLATINUM_CONSTANTS_BATTLE_TOWER_H
