#ifndef POKEPLATINUM_BATTLE_FRONTIER_EMITTERS_H
#define POKEPLATINUM_BATTLE_FRONTIER_EMITTERS_H

#define CASTLE_EMITTER_TWINKLE 0

#define FACTORY_EMITTER_GREEN_SMOKE   0
#define FACTORY_EMITTER_SMOKE_CLOUDS  1
#define FACTORY_EMITTER_RISING_BLOCKS 2

#define HALL_EMITTER_UNK_0    0
#define HALL_EMITTER_UNK_1    1
#define HALL_EMITTER_UNK_2    2
#define HALL_EMITTER_UNK_3    3
#define HALL_EMITTER_UNK_4    4
#define HALL_EMITTER_UNUSED   5
#define HALL_EMITTER_UNK_6    6
#define HALL_EMITTER_UNUSED_2 7
#define HALL_EMITTER_UNK_8    8
#define HALL_EMITTER_UNK_9    9
#define HALL_EMITTER_UNK_10   10
#define HALL_EMITTER_UNK_11   11
#define HALL_EMITTER_UNK_12   12
#define HALL_EMITTER_UNK_13   13
#define HALL_EMITTER_UNK_14   14
#define HALL_EMITTER_UNUSED_3 15
#define HALL_EMITTER_UNK_16   16
#define HALL_EMITTER_UNK_17   17
#define HALL_EMITTER_UNK_18   18
#define HALL_EMITTER_UNK_19   19
#define HALL_EMITTER_UNK_20   20

#define ARCADE_EMITTERS_UNK_0  0
#define ARCADE_EMITTERS_UNK_1  1
#define ARCADE_EMITTERS_UNK_2  2
#define ARCADE_EMITTERS_UNK_3  3
#define ARCADE_EMITTERS_UNK_4  4
#define ARCADE_EMITTERS_UNK_5  5
#define ARCADE_EMITTERS_UNK_6  6
#define ARCADE_EMITTERS_UNK_7  7
#define ARCADE_EMITTERS_UNK_8  8
#define ARCADE_EMITTERS_UNK_9  9
#define ARCADE_EMITTERS_UNK_10 10
#define ARCADE_EMITTERS_UNK_11 11

#define ARCADE_2_EMITTER_UNK_0 0
#define ARCADE_2_EMITTER_UNK_1 1

#endif // POKEPLATINUM_BATTLE_FRONTIER_EMITTERS_H
