#ifndef POKEPLATINUM_CONSTANTS_BATTLE_CASTLE_FUNCTIONS_H
#define POKEPLATINUM_CONSTANTS_BATTLE_CASTLE_FUNCTIONS_H

#define BC_FUNC_UNK_0                    0
#define BC_FUNC_UNK_1                    1
#define BC_FUNC_SET_CHALLENGE_TYPE       2
#define BC_FUNC_UNK_3                    3
#define BC_FUNC_GET_CURRENT_STREAK       4
#define BC_FUNC_INCREMENT_CURRENT_STREAK 5
#define BC_FUNC_UNK_6                    6
#define BC_FUNC_RESET_SYSTEM             7
#define BC_FUNC_UNK_8                    8
#define BC_FUNC_UNK_9                    9
#define BC_FUNC_UNK_10                   10
#define BC_FUNC_UNK_11                   11
#define BC_FUNC_UNK_12                   12
#define BC_FUNC_UNK_13                   13
#define BC_FUNC_UNK_14                   14
#define BC_FUNC_UNK_15                   15
#define BC_FUNC_UNK_16                   16
#define BC_FUNC_GET_CHALLENGE_TYPE       17
#define BC_FUNC_UNK_18                   18
#define BC_FUNC_UNK_19                   19
#define BC_FUNC_UNK_20                   20
#define BC_FUNC_UNK_21                   21
#define BC_FUNC_UNK_22                   22
#define BC_FUNC_UNK_23                   23
#define BC_FUNC_UNK_24                   24
#define BC_FUNC_UNK_25                   25
#define BC_FUNC_UNK_26                   26
#define BC_FUNC_UNK_27                   27
#define BC_FUNC_UNK_28                   28
#define BC_FUNC_UNK_29                   29
#define BC_FUNC_UNK_30                   30
#define BC_FUNC_UNK_31                   31
#define BC_FUNC_UNK_32                   32
#define BC_FUNC_UNK_33                   33
#define BC_FUNC_UNK_34                   34
#define BC_FUNC_IS_MULTIPLAYER_CHALLENGE 35
#define BC_FUNC_UNK_36                   36
#define BC_FUNC_UNK_37                   37
#define BC_FUNC_UNK_38                   38
#define BC_FUNC_UNK_39                   39
#define BC_FUNC_UNK_40                   40
#define BC_FUNC_UNK_41                   41
#define BC_FUNC_UNK_42                   42
#define BC_FUNC_UNK_43                   43
#define BC_FUNC_UNK_44                   44

#endif // POKEPLATINUM_CONSTANTS_BATTLE_CASTLE_FUNCTIONS_H
