#ifndef POKEPLATINUM_CONSTANTS_BATTLE_H
#define POKEPLATINUM_CONSTANTS_BATTLE_H

#define BATTLE_TYPE_SINGLES         (0 << 0)
#define BATTLE_TYPE_WILD_MON        (0 << 0)
#define BATTLE_TYPE_TRAINER         (1 << 0)
#define BATTLE_TYPE_DOUBLES         (1 << 1)
#define BATTLE_TYPE_LINK            (1 << 2)
#define BATTLE_TYPE_2vs2            (1 << 3) // This is, explicitly, two distinct battlers on each side
#define BATTLE_TYPE_TAG             (1 << 4) // This is, explicitly, a battle with a partner
#define BATTLE_TYPE_SAFARI          (1 << 5)
#define BATTLE_TYPE_AI              (1 << 6)
#define BATTLE_TYPE_FRONTIER        (1 << 7)
#define BATTLE_TYPE_ROAMER          (1 << 8)
#define BATTLE_TYPE_PAL_PARK        (1 << 9)
#define BATTLE_TYPE_CATCH_TUTORIAL  (1 << 10)
#define BATTLE_TYPE_DEBUG           (1 << 31)

#define BATTLE_TYPE_TRAINER_DOUBLES     (BATTLE_TYPE_DOUBLES | BATTLE_TYPE_TRAINER)
#define BATTLE_TYPE_LINK_DOUBLES        (BATTLE_TYPE_LINK | BATTLE_TYPE_TRAINER_DOUBLES)
#define BATTLE_TYPE_FRONTIER_DOUBLES    (BATTLE_TYPE_FRONTIER | BATTLE_TYPE_TRAINER_DOUBLES)
#define BATTLE_TYPE_TAG_DOUBLES         (BATTLE_TYPE_TAG | BATTLE_TYPE_TRAINER_DOUBLES)
#define BATTLE_TYPE_NO_ITEMS            (BATTLE_TYPE_LINK | BATTLE_TYPE_FRONTIER)
#define BATTLE_TYPE_AI_PARTNER          (BATTLE_TYPE_DOUBLES | BATTLE_TYPE_2vs2 | BATTLE_TYPE_AI)
#define BATTLE_TYPE_SPECIAL_WILD        (BATTLE_TYPE_SAFARI | BATTLE_TYPE_ROAMER | BATTLE_TYPE_PAL_PARK | BATTLE_TYPE_CATCH_TUTORIAL)

#define MAX_LINK_BATTLERS       4
#define MAX_BATTLERS            4
#define NUM_BATTLE_SIDES        2
#define MAX_BATTLERS_PER_SIDE   2

#define BATTLE_IO_QUEUE_SIZE    16
#define BATTLE_IO_BUFFER_SIZE   256
#define BATTLE_SCRIPT_SIZE_MAX  400
#define BATTLE_SCRIPT_STACK_MAX 4

#define MAX_OPPONENTS     2
#define MAX_TRAINER_ITEMS 4

#define BATTLE_RESULT_WIN           (1 << 0)
#define BATTLE_RESULT_LOSE          (1 << 1)
#define BATTLE_RESULT_CAPTURED_MON  (1 << 2)
#define BATTLE_RESULT_TRY_FLEE_WAIT (1 << 6)
#define BATTLE_RESULT_TRY_FLEE      (1 << 7)

#define BATTLE_RESULT_DRAW          (BATTLE_RESULT_WIN | BATTLE_RESULT_LOSE)
#define BATTLE_RESULT_PLAYER_FLED   (BATTLE_RESULT_CAPTURED_MON | BATTLE_RESULT_WIN)
#define BATTLE_RESULT_ENEMY_FLED    (BATTLE_RESULT_CAPTURED_MON | BATTLE_RESULT_LOSE)

/*
 * Slot 1 is always on the controller's left; slot 2 is always on their right.
 *
 * e.g., in a single-battle:
 *                  ENEMY_SLOT_1
 * 
 *      PLAYER_SLOT_1
 * 
 * or, in a double-battle:
 *              ENEMY_SLOT_2    ENEMY_SLOT_1
 *  
 *      PLAYER_SLOT_1   PLAYER_SLOT_2
 */
#define BATTLER_PLAYER_SLOT_1   0
#define BATTLER_ENEMY_SLOT_1    1
#define BATTLER_PLAYER_SLOT_2   2
#define BATTLER_ENEMY_SLOT_2    3

#define BATTLE_SIDE_PLAYER      0
#define BATTLE_SIDE_ENEMY       1

#define BATTLER_SINGLES_PLAYER          0
#define BATTLER_SINGLES_ENEMY           1
#define BATTLER_DOUBLES_PLAYER_SLOT_1   2
#define BATTLER_DOUBLES_ENEMY_SLOT_1    3
#define BATTLER_DOUBLES_PLAYER_SLOT_2   4
#define BATTLER_DOUBLES_ENEMY_SLOT_2    5

#define BATTLE_STATUS_FIRST_BATTLE  (1 << 0)
#define BATTLE_STATUS_HONEY_TREE    (1 << 1)
#define BATTLE_STATUS_NO_RUNNING    (1 << 2)
#define BATTLE_STATUS_LEGENDARY     (1 << 3)
#define BATTLE_STATUS_RECORDING     (1 << 4)
#define BATTLE_STATUS_RECORDED      (1 << 5)
#define BATTLE_STATUS_GIRATINA      (1 << 6)
#define BATTLE_STATUS_DISTORTION    (1 << 7)

enum BattleActions {
    BATTLE_ACTION_PICK_COMMAND = 0,
    BATTLE_ACTION_CHOOSE_TARGET,
    BATTLE_ACTION_TEMP_VALUE,
    BATTLE_ACTION_SELECTED_COMMAND,

    MAX_BATTLE_ACTIONS
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_H
