#ifndef POKEPLATINUM_CONSTANTS_BOAT_CUTSCENE_H
#define POKEPLATINUM_CONSTANTS_BOAT_CUTSCENE_H

#define BOAT_TRAVEL_DIR_SOUTH_TO_NORTH 0
#define BOAT_TRAVEL_DIR_EAST_TO_WEST   1
#define BOAT_TRAVEL_DIR_WEST_TO_EAST   2
#define BOAT_TRAVEL_DIR_NORTH_TO_SOUTH 3

#endif // POKEPLATINUM_CONSTANTS_BOAT_CUTSCENE_H
