#ifndef POKEPLATINUM_CONSTANTS_CAMERA_TYPES_H
#define POKEPLATINUM_CONSTANTS_CAMERA_TYPES_H

enum CameraType {
    CAMERA_TYPE_DEFAULT,
    CAMERA_TYPE_PASTORIA_GYM,
    CAMERA_TYPE_ZOOMED_IN,
    CAMERA_TYPE_CANALAVE_GYM,
    CAMERA_TYPE_INTERIOR_ORTHOGRAPHIC,
    CAMERA_TYPE_SPEAR_PILLAR,
    CAMERA_TYPE_MT_CORONET_EXT_SOUTH,
    CAMERA_TYPE_MT_CORONET_EXT_NORTH,
    CAMERA_TYPE_STARK_MOUNTAIN_ROOM_2,
    CAMERA_TYPE_OREBURGH_GYM,
    CAMERA_TYPE_VEILSTONE_GYM,
    CAMERA_TYPE_SLIGHTLY_ZOOMED_OUT,
    CAMERA_TYPE_CAVE,
    CAMERA_TYPE_IRON_ISLAND_CAVE,
    CAMERA_TYPE_HALL_OF_ORIGIN,
    CAMERA_TYPE_LAKE_ACUITY,
    CAMERA_TYPE_UNUSED_16,
};

#endif // POKEPLATINUM_CONSTANTS_CAMERA_TYPES_H
