#ifndef POKEPLATINUM_CONSTANTS_CHARCODE_H
#define POKEPLATINUM_CONSTANTS_CHARCODE_H

enum {
    CHAR_EMPTY = 0,
    CHAR_JP_SPACE,

    CHAR_JP_0 = 0x00A2,
    CHAR_JP_1,
    CHAR_JP_2,
    CHAR_JP_3,
    CHAR_JP_4,
    CHAR_JP_5,
    CHAR_JP_6,
    CHAR_JP_7,
    CHAR_JP_8,
    CHAR_JP_9,

    CHAR_JP_QUESTION = 0x00E2,

    CHAR_JP_MINUS = 0x00F1,

    CHAR_MENU_ARROW = 0x011F,
    CHAR_WIDE_AMPERSAND,
    CHAR_EN_0,
    CHAR_EN_1,
    CHAR_EN_2,
    CHAR_EN_3,
    CHAR_EN_4,
    CHAR_EN_5,
    CHAR_EN_6,
    CHAR_EN_7,
    CHAR_EN_8,
    CHAR_EN_9,

    CHAR_EN_A = 0x012B,
    CHAR_EN_B,
    CHAR_EN_C,
    CHAR_EN_D,
    CHAR_EN_E,
    CHAR_EN_F,
    CHAR_EN_G,
    CHAR_EN_H,
    CHAR_EN_I,
    CHAR_EN_J,
    CHAR_EN_K,
    CHAR_EN_L,
    CHAR_EN_M,
    CHAR_EN_N,
    CHAR_EN_O,
    CHAR_EN_P,
    CHAR_EN_Q,
    CHAR_EN_R,
    CHAR_EN_S,
    CHAR_EN_T,
    CHAR_EN_U,
    CHAR_EN_V,
    CHAR_EN_W,
    CHAR_EN_X,
    CHAR_EN_Y,
    CHAR_EN_Z, // 0x0144

    CHAR_EN_a = 0x0145,
    CHAR_EN_b,
    CHAR_EN_c,
    CHAR_EN_d,
    CHAR_EN_e,
    CHAR_EN_f,
    CHAR_EN_g,
    CHAR_EN_h,
    CHAR_EN_i,
    CHAR_EN_j,
    CHAR_EN_k,
    CHAR_EN_l,
    CHAR_EN_m,
    CHAR_EN_n,
    CHAR_EN_o,
    CHAR_EN_p,
    CHAR_EN_q,
    CHAR_EN_r,
    CHAR_EN_s,
    CHAR_EN_t,
    CHAR_EN_u,
    CHAR_EN_v,
    CHAR_EN_w,
    CHAR_EN_x,
    CHAR_EN_y,
    CHAR_EN_z, // 0x015E

    CHAR_EN_QUESTION_MARK = 0x01AC,

    CHAR_EN_MINUS = 0x01BE,

    CHAR_EN_SPACE = 0x01DE,

    CHAR_NUM_SPACE = 0x01E2,

    CHAR_CONTROL_SCREEN_INDICATOR = 0x0200,
    CHAR_CONTROL_PAUSE,
    CHAR_CONTROL_CALLBACK,
    CHAR_CONTROL_CURSOR_X,
    CHAR_CONTROL_CURSOR_Y,

    CHAR_CONTROL_CLEAR = 0x25BC,
    CHAR_CONTROL_SCROLL,

    CHAR_CR = 0xE000,

    CHAR_PLACEHOLDER_BEGIN = 0xF0FD,

    CHAR_COMPRESSED_MARK = 0xF100,

    CHAR_CONTROL_MOVE = 0xFE06,

    CHAR_CONTROL_SET_COLOR = 0xFF00,
    CHAR_CONTROL_SET_SIZE,

    CHAR_FORMAT_ARG = 0xFFFE,
    CHAR_EOS,
};

#endif // POKEPLATINUM_CONSTANTS_CHARCODE_H
