#ifndef POKEPLATINUM_CONSTANTS_COMMON_SCRIPTS_H
#define POKEPLATINUM_CONSTANTS_COMMON_SCRIPTS_H

#define COMMON_SCRIPT_POKECENTER_VISIT             0x7D2
#define COMMON_SCRIPT_HOME_BLACK_OUT_RECOVER       0x7E4
#define COMMON_SCRIPT_POKECENTER_BLACK_OUT_RECOVER 0x7E5

#endif // POKEPLATINUM_CONSTANTS_COMMON_SCRIPTS_H
