#ifndef POKEPLATINUM_CONSTANTS_CONTESTS_H
#define POKEPLATINUM_CONSTANTS_CONTESTS_H

#define CONTEST_MODE_SUPER    0
#define CONTEST_MODE_LINK     1
#define CONTEST_MODE_PRACTICE 2

#define CONTEST_COMPETITION_UNK0            0
#define CONTEST_COMPETITION_UNK1            1
#define CONTEST_COMPETITION_LINK_OR_SUPER   2
#define CONTEST_COMPETITION_PRACTICE_VISUAL 3
#define CONTEST_COMPETITION_VISUAL          4
#define CONTEST_COMPETITION_PRACTICE_DANCE  5
#define CONTEST_COMPETITION_DANCE           6
#define CONTEST_COMPETITION_PRACTICE_ACTING 7
#define CONTEST_COMPETITION_ACTING          8

#define CONTEST_NUM_PARTICIPANTS 4
#define CONTEST_NUM_JUDGES       3

#define POINTS_PER_APPEAL_HEART 10
#define MAX_APPEAL_HEARTS       6

#define PLAYER_CONTESTANT_ID 0

#endif // POKEPLATINUM_CONSTANTS_CONTESTS_H
