#ifndef POKEPLATINUM_CONSTANTS_CONTESTS_H
#define POKEPLATINUM_CONSTANTS_CONTESTS_H

#define CONTEST_NUM_PARTICIPANTS 4

#define POINTS_PER_APPEAL_HEART 10
#define MAX_APPEAL_HEARTS       6

#endif // POKEPLATINUM_CONSTANTS_CONTESTS_H
