#ifndef POKEPLATINUM_CONSTANTS_DISTORTION_WORLD_H
#define POKEPLATINUM_CONSTANTS_DISTORTION_WORLD_H

enum DistWorldProgress {
    DIST_WORLD_PROGRESS_NONE = 0,
    DIST_WORLD_PROGRESS_ENTERED_1F,
    DIST_WORLD_PROGRESS_JUMPED_ON_1F_ELEVATOR,
    DIST_WORLD_PROGRESS_ENTERED_B1F,
    DIST_WORLD_PROGRESS_SAW_B1F_MESPRIT,
    DIST_WORLD_PROGRESS_TALKED_TO_B2F_CYNTHIA,
    DIST_WORLD_PROGRESS_TALKED_TO_B3F_CYRUS,
    DIST_WORLD_PROGRESS_FINISHED_BOULDER_PUZZLE,
    DIST_WORLD_PROGRESS_ENTERED_B7F,
    DIST_WORLD_PROGRESS_LISTENED_TO_CYNTHIA_CYRUS,
    DIST_WORLD_PROGRESS_WON_CYRUS_BATTLE,
    DIST_WORLD_PROGRESS_GIRATINA_ROOM_FIRST_SHADOW,
    DIST_WORLD_PROGRESS_GIRATINA_ROOM_SECOND_SHADOW,
    DIST_WORLD_PROGRESS_GIRATINA_ARRIVED,
    DIST_WORLD_PROGRESS_BATTLED_GIRATINA
};

#define DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID 128

enum DistWorldMapObjectEvent1FLocalID {
    DIST_WORLD_MAP_OBJECT_1F_CYNTHIA_PORTAL = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_1F_CYNTHIA_ELEVATOR,
};

enum DistWorldMapObjectEventB1FLocalID {
    DIST_WORLD_MAP_OBJECT_B1F_CYNTHIA_ELEVATOR = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_B1F_MESPRIT,
};

enum DistWorldMapObjectEventB2FLocalID {
    DIST_WORLD_MAP_OBJECT_B2F_CYNTHIA = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
};

enum DistWorldMapObjectEventB3FLocalID {
    DIST_WORLD_MAP_OBJECT_B3F_CYRUS = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
};

enum DistWorldMapObjectEventB4FLocalID {
    DIST_WORLD_MAP_OBJECT_B4F_CYRUS = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID + 6,
};

enum DistWorldMapObjectEventB5FLocalID {
    DIST_WORLD_MAP_OBJECT_B5F_MESPRIT_BOULDER = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_B5F_AZELF_BOULDER,
    DIST_WORLD_MAP_OBJECT_B5F_UXIE_BOULDER,
    DIST_WORLD_MAP_OBJECT_B5F_UXIE,
    DIST_WORLD_MAP_OBJECT_B5F_AZELF,
    DIST_WORLD_MAP_OBJECT_B5F_MESPRIT,
};

enum DistWorldMapObjectEventB6FLocalID {
    DIST_WORLD_MAP_OBJECT_B6F_MESPRIT_BOULDER_OUTSIDE = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_B6F_AZELF_BOULDER_OUTSIDE,
    DIST_WORLD_MAP_OBJECT_B6F_UXIE_BOULDER_OUTSIDE,
    DIST_WORLD_MAP_OBJECT_B6F_MESPRIT,
    DIST_WORLD_MAP_OBJECT_B6F_UXIE,
    DIST_WORLD_MAP_OBJECT_B6F_AZELF,
    DIST_WORLD_MAP_OBJECT_B6F_CYNTHIA,
    DIST_WORLD_MAP_OBJECT_B6F_MESPRIT_BOULDER_PIT_TEXT_1,
    DIST_WORLD_MAP_OBJECT_B6F_MESPRIT_BOULDER_PIT_TEXT_2,
    DIST_WORLD_MAP_OBJECT_B6F_MESPRIT_BOULDER_PIT_TEXT_3,
    DIST_WORLD_MAP_OBJECT_B6F_UXIE_BOULDER_PIT_TEXT_1,
    DIST_WORLD_MAP_OBJECT_B6F_UXIE_BOULDER_PIT_TEXT_2,
    DIST_WORLD_MAP_OBJECT_B6F_UXIE_BOULDER_PIT_TEXT_3,
    DIST_WORLD_MAP_OBJECT_B6F_AZELF_BOULDER_PIT_TEXT_1,
    DIST_WORLD_MAP_OBJECT_B6F_AZELF_BOULDER_PIT_TEXT_2,
    DIST_WORLD_MAP_OBJECT_B6F_AZELF_BOULDER_PIT_TEXT_3,
    DIST_WORLD_MAP_OBJECT_B6F_MESPRIT_BOULDER_IN_PIT,
    DIST_WORLD_MAP_OBJECT_B6F_AZELF_BOULDER_IN_PIT,
    DIST_WORLD_MAP_OBJECT_B6F_UXIE_BOULDER_IN_PIT,
};

enum DistWorldMapObjectEventB7FLocalID {
    DIST_WORLD_MAP_OBJECT_B7F_CYNTHIA = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_B7F_CYRUS,
};

enum DistWorldMapObjectEventGiratinaRoomLocalID {
    DIST_WORLD_MAP_OBJECT_GIRATINA_ROOM_GIRATINA = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_GIRATINA_ROOM_CYNTHIA,
    DIST_WORLD_MAP_OBJECT_GIRATINA_ROOM_CYRUS,
    DIST_WORLD_MAP_OBJECT_GIRATINA_ROOM_PORTAL,
    DIST_WORLD_MAP_OBJECT_GIRATINA_ROOM_CYNTHIA_TEXT,
};

enum DistWorldMapObjectEventTurnbackCaveLocalID {
    DIST_WORLD_MAP_OBJECT_TURNBACK_CAVE_PORTAL = DIST_WORLD_MAP_OBJECT_BASE_LOCAL_ID,
    DIST_WORLD_MAP_OBJECT_TURNBACK_CAVE_GRISEOUS_ORB_ITEM,
};

#endif // POKEPLATINUM_CONSTANTS_DISTORTION_WORLD_H
