#ifndef POKEPLATINUM_CONSTANTS_DISTORTION_WORLD_H
#define POKEPLATINUM_CONSTANTS_DISTORTION_WORLD_H

enum DistWorldProgress {
    DIST_WORLD_PROGRESS_NONE = 0,
    DIST_WORLD_PROGRESS_ENTERED_1F,
    DIST_WORLD_PROGRESS_JUMPED_ON_1F_ELEVATOR,
    DIST_WORLD_PROGRESS_ENTERED_B1F,
    DIST_WORLD_PROGRESS_SAW_B1F_MESPRIT,
    DIST_WORLD_PROGRESS_TALKED_TO_B2F_CYNTHIA,
    DIST_WORLD_PROGRESS_TALKED_TO_B3F_CYRUS,
    DIST_WORLD_PROGRESS_FINISHED_BOULDER_PUZZLE,
    DIST_WORLD_PROGRESS_ENTERED_B7F,
    DIST_WORLD_PROGRESS_LISTENED_TO_CYNTHIA_CYRUS,
    DIST_WORLD_PROGRESS_WON_CYRUS_BATTLE,
    DIST_WORLD_PROGRESS_GIRATINA_ROOM_FIRST_SHADOW,
    DIST_WORLD_PROGRESS_GIRATINA_ROOM_SECOND_SHADOW,
    DIST_WORLD_PROGRESS_GIRATINA_ARRIVED,
    DIST_WORLD_PROGRESS_BATTLED_GIRATINA
};

#endif // POKEPLATINUM_CONSTANTS_DISTORTION_WORLD_H
