#ifndef POKEPLATINUM_CONSTANTS_DWC_H
#define POKEPLATINUM_CONSTANTS_DWC_H

#define DEFAULT_DWC_DMA_NUMBER   2
#define DEFAULT_DWC_POWER_MODE   1
#define DEFAULT_DWC_SSL_PRIORITY 20

#endif // POKEPLATINUM_CONSTANTS_DWC_H
