#ifndef POKEPLATINUM_CONSTANTS_ELEVATOR_DIRS_H
#define POKEPLATINUM_CONSTANTS_ELEVATOR_DIRS_H

#define ELEVATOR_DIR_UP   0
#define ELEVATOR_DIR_DOWN 1

#endif // POKEPLATINUM_CONSTANTS_ELEVATOR_DIRS_H
