#ifndef POKEPLATINUM_CONSTANTS_FADE_SCREEN_H
#define POKEPLATINUM_CONSTANTS_FADE_SCREEN_H

#define FADE_SCREEN_CMD_STEPS    6
#define FADE_SCREEN_SPEED_FAST   1
#define FADE_SCREEN_SPEED_MEDIUM 3
#define FADE_SCREEN_SPEED_SLOW   6

#endif // POKEPLATINUM_CONSTANTS_FADE_SCREEN_H
