#ifndef POKEPLATINUM_CONSTANTS_FIELD_POISON_H
#define POKEPLATINUM_CONSTANTS_FIELD_POISON_H

#define FLDPSN_NONE     0
#define FLDPSN_POISONED 1
#define FLDPSN_FAINTED  2

#endif // POKEPLATINUM_CONSTANTS_FIELD_POISON_H
