#ifndef POKEPLATINUM_CONSTANTS_FIELD_BASE_TILES_H
#define POKEPLATINUM_CONSTANTS_FIELD_BASE_TILES_H

#include "render_window.h"

#define BASE_TILE_SCROLLING_MESSAGE_BOX   (1024 - SCROLLING_MESSAGE_BOX_TILE_COUNT)
#define BASE_TILE_STANDARD_WINDOW_FRAME   (BASE_TILE_SCROLLING_MESSAGE_BOX - STANDARD_WINDOW_TILE_COUNT)
#define BASE_TILE_MAP_TRANSITION_DROPDOWN (BASE_TILE_STANDARD_WINDOW_FRAME - MAP_TRANSITION_DROPDOWN_TILE_COUNT)
#define BASE_TILE_SIGNPOST                (BASE_TILE_MAP_TRANSITION_DROPDOWN - (SIGNPOST_FRAME_TILE_COUNT + SCROLLING_CURSOR_TILE_COUNT + SIGNPOST_CONTENT_SIZE_TILES))
#define BASE_TILE_MESSAGE_WINDOW          (BASE_TILE_SIGNPOST - MESSAGE_WINDOW_TILE_COUNT)

#endif // POKEPLATINUM_CONSTANTS_FIELD_BASE_TILES_H
