#ifndef POKEPLATINUM_CONSTANTS_FLAGS_H
#define POKEPLATINUM_CONSTANTS_FLAGS_H

#define FLAG_DEFEATED_IDOL_GRACE                0x0ABC
#define FLAG_DEFEATED_REPORTERS_KINSEY          0x0ABD
#define FLAG_DEFEATED_CAMERAMAN_TEVIN           0x0ABE
#define FLAG_DEFEATED_CLOWN_LEE                 0x0ABF
#define FLAG_DEFEATED_INTERVIEWERS_ROXY_AND_OLI 0x0AC0
#define FLAG_DEFEATED_POKE_KID_ARIEL            0x0AC1
#define FLAG_DEFEATED_GUITARIST_ARTURO          0x0AC2

#endif // POKEPLATINUM_CONSTANTS_FLAGS_H
