#ifndef POKEPLATINUM_CONSTANTS_FLAVOR_H
#define POKEPLATINUM_CONSTANTS_FLAVOR_H

enum Flavor {
    FLAVOR_SPICY = 0,
    FLAVOR_DRY,
    FLAVOR_SWEET,
    FLAVOR_BITTER,
    FLAVOR_SOUR,

    FLAVOR_COUNT,
};

#endif // POKEPLATINUM_CONSTANTS_FLAVOR_H
