#ifndef POKEPLATINUM_CONSTANTS_FOOTSTEP_HOUSE_H
#define POKEPLATINUM_CONSTANTS_FOOTSTEP_HOUSE_H

#define FOOTPRINT_TYPE_NONE   0
#define FOOTPRINT_TYPE_CUTE   1
#define FOOTPRINT_TYPE_TOUGH  2
#define FOOTPRINT_TYPE_SCARY  3
#define FOOTPRINT_TYPE_SLOW   4
#define FOOTPRINT_TYPE_SILENT 5

#endif // POKEPLATINUM_CONSTANTS_FOOTSTEP_HOUSE_H
