#ifndef POKEPLATINUM_CONSTANTS_FORMS_H
#define POKEPLATINUM_CONSTANTS_FORMS_H

#include "species.h"

#define MOVESET_FORM_DEOXYS_ATTACK    NATIONAL_DEX_COUNT + 1
#define MOVESET_FORM_DEOXYS_DEFENSE   NATIONAL_DEX_COUNT + 2
#define MOVESET_FORM_DEOXYS_SPEED     NATIONAL_DEX_COUNT + 3
#define MOVESET_FORM_WORMADAM_SANDY   NATIONAL_DEX_COUNT + 4
#define MOVESET_FORM_WORMADAM_TRASH   NATIONAL_DEX_COUNT + 5
#define MOVESET_FORM_GIRATINA_ORIGIN  NATIONAL_DEX_COUNT + 6
#define MOVESET_FORM_SHAYMIN_SKY      NATIONAL_DEX_COUNT + 7
#define MOVESET_FORM_ROTOM_HEAT       NATIONAL_DEX_COUNT + 8
#define MOVESET_FORM_ROTOM_WASH       NATIONAL_DEX_COUNT + 9
#define MOVESET_FORM_ROTOM_FROST      NATIONAL_DEX_COUNT + 10
#define MOVESET_FORM_ROTOM_FAN        NATIONAL_DEX_COUNT + 11
#define MOVESET_FORM_ROTOM_MOW        NATIONAL_DEX_COUNT + 12

#define MOVESET_MAX                   MOVESET_FORM_ROTOM_MOW

enum UnownForms {
    UNOWN_FORM_A = 0,
    UNOWN_FORM_B,
    UNOWN_FORM_C,
    UNOWN_FORM_D,
    UNOWN_FORM_E,
    UNOWN_FORM_F,
    UNOWN_FORM_G,
    UNOWN_FORM_H,
    UNOWN_FORM_I,
    UNOWN_FORM_J,
    UNOWN_FORM_K,
    UNOWN_FORM_L,
    UNOWN_FORM_M,
    UNOWN_FORM_N,
    UNOWN_FORM_O,
    UNOWN_FORM_P,
    UNOWN_FORM_Q,
    UNOWN_FORM_R,
    UNOWN_FORM_S,
    UNOWN_FORM_T,
    UNOWN_FORM_U,
    UNOWN_FORM_V,
    UNOWN_FORM_W,
    UNOWN_FORM_X,
    UNOWN_FORM_Y,
    UNOWN_FORM_Z,
    UNOWN_FORM_EXC,
    UNOWN_FORM_QUE
};

#endif