#ifndef POKEPLATINUM_CONSTANTS_GAME_OPTIONS_H
#define POKEPLATINUM_CONSTANTS_GAME_OPTIONS_H

enum OptionsTextSpeed {
    OPTIONS_TEXT_SPEED_SLOW = 0,
    OPTIONS_TEXT_SPEED_NORMAL,
    OPTIONS_TEXT_SPEED_FAST
};

enum OptionsSoundMode {
    OPTIONS_SOUND_MODE_STEREO = 0,
    OPTIONS_SOUND_MODE_MONO
};

enum OptionsBattleStyle {
    OPTIONS_BATTLE_STYLE_SHIFT = 0,
    OPTIONS_BATTLE_STYLE_SET
};

enum OptionsBattleScene {
    OPTIONS_BATTLE_SCENE_ON = 0,
    OPTIONS_BATTLE_SCENE_OFF
};

enum OptionsButtonMode {
    OPTIONS_BUTTON_MODE_NORMAL = 0,
    OPTIONS_BUTTON_MODE_START_IS_X,
    OPTIONS_BUTTON_MODE_L_IS_A
};

enum OptionsFrame {
    OPTIONS_FRAME_1 = 0,
    OPTIONS_FRAME_2,
    OPTIONS_FRAME_3,
    OPTIONS_FRAME_4,
    OPTIONS_FRAME_5,
    OPTIONS_FRAME_6,
    OPTIONS_FRAME_7,
    OPTIONS_FRAME_8,
    OPTIONS_FRAME_9,
    OPTIONS_FRAME_10,
    OPTIONS_FRAME_11,
    OPTIONS_FRAME_12,
    OPTIONS_FRAME_13,
    OPTIONS_FRAME_14,
    OPTIONS_FRAME_15,
    OPTIONS_FRAME_16,
    OPTIONS_FRAME_17,
    OPTIONS_FRAME_18,
    OPTIONS_FRAME_19,
    OPTIONS_FRAME_20
};

#endif // POKEPLATINUM_CONSTANTS_GAME_OPTIONS_H
