#ifndef POKEPLATINUM_CONSTANTS_GOODS_H
#define POKEPLATINUM_CONSTANTS_GOODS_H

#define GOOD_NONE                  0
#define GOOD_PC_NORMAL_FLAG        1
#define GOOD_PC_BRONZE_FLAG        2
#define GOOD_PC_SILVER_FLAG        3
#define GOOD_PC_GOLD_FLAG          4
#define GOOD_PC_PLATINUM_FLAG      5
#define GOOD_BIG_BOULDER           6
#define GOOD_YELLOW_CUSHION        7
#define GOOD_BLUE_CUSHION          8
#define GOOD_WOODEN_CHAIR          9
#define GOOD_BIG_TABLE             10
#define GOOD_PLAIN_TABLE           11
#define GOOD_SMALL_TABLE           12
#define GOOD_LONG_TABLE            13
#define GOOD_WIDE_TABLE            14
#define GOOD_POKE_TABLE            15
#define GOOD_BIG_BOOKSHELF         16
#define GOOD_SMALL_BOOKSHELF       17
#define GOOD_RESEARCH_SHELF        18
#define GOOD_BIKE_RACK             19
#define GOOD_SHOP_SHELF            20
#define GOOD_DISPLAY_SHELF         21
#define GOOD_CUPBOARD              22
#define GOOD_WOOD_DRESSER          23
#define GOOD_PINK_DRESSER          24
#define GOOD_TV                    25
#define GOOD_REFRIGERATOR          26
#define GOOD_PRETTY_SINK           27
#define GOOD_FEATHERY_BED          28
#define GOOD_TRASH_CAN             29
#define GOOD_CARDBOARD_BOX         30
#define GOOD_CRATE                 31
#define GOOD_CONTAINER             32
#define GOOD_OIL_DRUM              33
#define GOOD_BIG_OIL_DRUM          34
#define GOOD_IRON_BEAM             35
#define GOOD_POTTED_PLANT          36
#define GOOD_POKE_FLOWER           37
#define GOOD_HEALING_MACHINE       38
#define GOOD_LAB_MACHINE           39
#define GOOD_TEST_MACHINE          40
#define GOOD_GAME_SYSTEM           41
#define GOOD_VENDING_MACHINE       42
#define GOOD_RED_BIKE              43
#define GOOD_GREEN_BIKE            44
#define GOOD_BINOCULARS            45
#define GOOD_GLOBE                 46
#define GOOD_GYM_STATUE            47
#define GOOD_RED_TENT              48
#define GOOD_BLUE_TENT             49
#define GOOD_CLEAR_TENT            50
#define GOOD_MAZE_BLOCK_1          51
#define GOOD_MAZE_BLOCK_2          52
#define GOOD_MAZE_BLOCK_3          53
#define GOOD_MAZE_BLOCK_4          54
#define GOOD_MAZE_BLOCK_5          55
#define GOOD_HOLE_TOOL             56
#define GOOD_PIT_TOOL              57
#define GOOD_SMOKE_TOOL            58
#define GOOD_BIG_SMOKE_TOOL        59
#define GOOD_ROCK_TOOL             60
#define GOOD_ROCKFALL_TOOL         61
#define GOOD_FOAM_TOOL             62
#define GOOD_BUBBLE_TOOL           63
#define GOOD_ALERT_TOOL_1          64
#define GOOD_ALERT_TOOL_2          65
#define GOOD_ALERT_TOOL_3          66
#define GOOD_ALERT_TOOL_4          67
#define GOOD_LEAF_TOOL             68
#define GOOD_FLOWER_TOOL           69
#define GOOD_EMBER_TOOL            70
#define GOOD_FIRE_TOOL             71
#define GOOD_CUTE_CUP              72
#define GOOD_COOL_CUP              73
#define GOOD_BEAUTY_CUP            74
#define GOOD_TOUGH_CUP             75
#define GOOD_CLEVER_CUP            76
#define GOOD_BLUE_CRYSTAL          77
#define GOOD_PINK_CRYSTAL          78
#define GOOD_RED_CRYSTAL           79
#define GOOD_YELLOW_CRYSTAL        80
#define GOOD_PRETTY_GEM            81
#define GOOD_SHINY_GEM             82
#define GOOD_MYSTIC_GEM            83
#define GOOD_GLITTER_GEM           84
#define GOOD_BRONZE_TROPHY         85
#define GOOD_SILVER_TROPHY         86
#define GOOD_GOLD_TROPHY           87
#define GOOD_GREAT_TROPHY_UNUSED   88
#define GOOD_BALL_ORNAMENT_UNUSED  89
#define GOOD_ROUND_ORNAMENT_UNUSED 90
#define GOOD_CLEAR_ORNAMENT_UNUSED 91
#define GOOD_CHARMANDER_DOLL       92
#define GOOD_BULBASAUR_DOLL        93
#define GOOD_SQUIRTLE_DOLL         94
#define GOOD_CYNDAQUIL_DOLL        95
#define GOOD_CHIKORITA_DOLL        96
#define GOOD_TOTODILE_DOLL         97
#define GOOD_TORCHIC_DOLL          98
#define GOOD_TREECKO_DOLL          99
#define GOOD_MUDKIP_DOLL           100
#define GOOD_CHIMCHAR_DOLL         101
#define GOOD_TURTWIG_DOLL          102
#define GOOD_PIPLUP_DOLL           103
#define GOOD_PIKACHU_DOLL          104
#define GOOD_PLUSLE_DOLL           105
#define GOOD_MINUN_DOLL            106
#define GOOD_CLEFAIRY_DOLL         107
#define GOOD_JIGGLYPUFF_DOLL       108
#define GOOD_WOBBUFFET_DOLL        109
#define GOOD_MEOWTH_DOLL           110
#define GOOD_SKITTY_DOLL           111
#define GOOD_GLAMEOW_DOLL          112
#define GOOD_BUNEARY_DOLL          113
#define GOOD_WEAVILE_DOLL          114
#define GOOD_MUNCHLAX_DOLL         115
#define GOOD_BONSLY_DOLL           116
#define GOOD_MIME_JR_DOLL          117
#define GOOD_LUCARIO_DOLL          118
#define GOOD_MANTYKE_DOLL          119
#define GOOD_BUIZEL_DOLL           120
#define GOOD_CHATOT_DOLL           121
#define GOOD_MANAPHY_DOLL_UNUSED   122
#define GOOD_SNORLAX_DOLL          123
#define GOOD_WAILORD_DOLL          124
#define GOOD_MAGNEZONE_DOLL_UNUSED 125
#define GOOD_DRIFLOON_DOLL         126
#define GOOD_HAPPINY_DOLL          127
#define GOOD_PACHIRISU_DOLL        128
#define GOOD_BASE_ENTRANCE_SOUTH   129
#define GOOD_BASE_ENTRANCE_NORTH   130
#define GOOD_BASE_ENTRANCE_EAST    131
#define GOOD_BASE_ENTRANCE_WEST    132
#define GOOD_WIDE_SOFA             133
#define GOOD_BONSAI                134
#define GOOD_DAINTY_FLOWERS        135
#define GOOD_LOVELY_FLOWERS        136
#define GOOD_PRETTY_FLOWERS        137
#define GOOD_LAVISH_FLOWERS        138

#endif // POKEPLATINUM_CONSTANTS_GOODS_H
