#ifndef POKEPLATINUM_CONSTANTS_GOODS_H
#define POKEPLATINUM_CONSTANTS_GOODS_H

#define UG_GOOD_NONE                  0
#define UG_GOOD_PC_NORMAL_FLAG        1
#define UG_GOOD_PC_BRONZE_FLAG        2
#define UG_GOOD_PC_SILVER_FLAG        3
#define UG_GOOD_PC_GOLD_FLAG          4
#define UG_GOOD_PC_PLATINUM_FLAG      5
#define UG_GOOD_BIG_BOULDER           6
#define UG_GOOD_YELLOW_CUSHION        7
#define UG_GOOD_BLUE_CUSHION          8
#define UG_GOOD_WOODEN_CHAIR          9
#define UG_GOOD_BIG_TABLE             10
#define UG_GOOD_PLAIN_TABLE           11
#define UG_GOOD_SMALL_TABLE           12
#define UG_GOOD_LONG_TABLE            13
#define UG_GOOD_WIDE_TABLE            14
#define UG_GOOD_POKE_TABLE            15
#define UG_GOOD_BIG_BOOKSHELF         16
#define UG_GOOD_SMALL_BOOKSHELF       17
#define UG_GOOD_RESEARCH_SHELF        18
#define UG_GOOD_BIKE_RACK             19
#define UG_GOOD_SHOP_SHELF            20
#define UG_GOOD_DISPLAY_SHELF         21
#define UG_GOOD_CUPBOARD              22
#define UG_GOOD_WOOD_DRESSER          23
#define UG_GOOD_PINK_DRESSER          24
#define UG_GOOD_TV                    25
#define UG_GOOD_REFRIGERATOR          26
#define UG_GOOD_PRETTY_SINK           27
#define UG_GOOD_FEATHERY_BED          28
#define UG_GOOD_TRASH_CAN             29
#define UG_GOOD_CARDBOARD_BOX         30
#define UG_GOOD_CRATE                 31
#define UG_GOOD_CONTAINER             32
#define UG_GOOD_OIL_DRUM              33
#define UG_GOOD_BIG_OIL_DRUM          34
#define UG_GOOD_IRON_BEAM             35
#define UG_GOOD_POTTED_PLANT          36
#define UG_GOOD_POKE_FLOWER           37
#define UG_GOOD_HEALING_MACHINE       38
#define UG_GOOD_LAB_MACHINE           39
#define UG_GOOD_TEST_MACHINE          40
#define UG_GOOD_GAME_SYSTEM           41
#define UG_GOOD_VENDING_MACHINE       42
#define UG_GOOD_RED_BIKE              43
#define UG_GOOD_GREEN_BIKE            44
#define UG_GOOD_BINOCULARS            45
#define UG_GOOD_GLOBE                 46
#define UG_GOOD_GYM_STATUE            47
#define UG_GOOD_RED_TENT              48
#define UG_GOOD_BLUE_TENT             49
#define UG_GOOD_CLEAR_TENT            50
#define UG_GOOD_MAZE_BLOCK_1          51
#define UG_GOOD_MAZE_BLOCK_2          52
#define UG_GOOD_MAZE_BLOCK_3          53
#define UG_GOOD_MAZE_BLOCK_4          54
#define UG_GOOD_MAZE_BLOCK_5          55
#define UG_GOOD_HOLE_TOOL             56
#define UG_GOOD_PIT_TOOL              57
#define UG_GOOD_SMOKE_TOOL            58
#define UG_GOOD_BIG_SMOKE_TOOL        59
#define UG_GOOD_ROCK_TOOL             60
#define UG_GOOD_ROCKFALL_TOOL         61
#define UG_GOOD_FOAM_TOOL             62
#define UG_GOOD_BUBBLE_TOOL           63
#define UG_GOOD_ALERT_TOOL_1          64
#define UG_GOOD_ALERT_TOOL_2          65
#define UG_GOOD_ALERT_TOOL_3          66
#define UG_GOOD_ALERT_TOOL_4          67
#define UG_GOOD_LEAF_TOOL             68
#define UG_GOOD_FLOWER_TOOL           69
#define UG_GOOD_EMBER_TOOL            70
#define UG_GOOD_FIRE_TOOL             71
#define UG_GOOD_CUTE_CUP              72
#define UG_GOOD_COOL_CUP              73
#define UG_GOOD_BEAUTY_CUP            74
#define UG_GOOD_TOUGH_CUP             75
#define UG_GOOD_CLEVER_CUP            76
#define UG_GOOD_BLUE_CRYSTAL          77
#define UG_GOOD_PINK_CRYSTAL          78
#define UG_GOOD_RED_CRYSTAL           79
#define UG_GOOD_YELLOW_CRYSTAL        80
#define UG_GOOD_PRETTY_GEM            81
#define UG_GOOD_SHINY_GEM             82
#define UG_GOOD_MYSTIC_GEM            83
#define UG_GOOD_GLITTER_GEM           84
#define UG_GOOD_BRONZE_TROPHY         85
#define UG_GOOD_SILVER_TROPHY         86
#define UG_GOOD_GOLD_TROPHY           87
#define UG_GOOD_GREAT_TROPHY_UNUSED   88
#define UG_GOOD_BALL_ORNAMENT_UNUSED  89
#define UG_GOOD_ROUND_ORNAMENT_UNUSED 90
#define UG_GOOD_CLEAR_ORNAMENT_UNUSED 91
#define UG_GOOD_CHARMANDER_DOLL       92
#define UG_GOOD_BULBASAUR_DOLL        93
#define UG_GOOD_SQUIRTLE_DOLL         94
#define UG_GOOD_CYNDAQUIL_DOLL        95
#define UG_GOOD_CHIKORITA_DOLL        96
#define UG_GOOD_TOTODILE_DOLL         97
#define UG_GOOD_TORCHIC_DOLL          98
#define UG_GOOD_TREECKO_DOLL          99
#define UG_GOOD_MUDKIP_DOLL           100
#define UG_GOOD_CHIMCHAR_DOLL         101
#define UG_GOOD_TURTWIG_DOLL          102
#define UG_GOOD_PIPLUP_DOLL           103
#define UG_GOOD_PIKACHU_DOLL          104
#define UG_GOOD_PLUSLE_DOLL           105
#define UG_GOOD_MINUN_DOLL            106
#define UG_GOOD_CLEFAIRY_DOLL         107
#define UG_GOOD_JIGGLYPUFF_DOLL       108
#define UG_GOOD_WOBBUFFET_DOLL        109
#define UG_GOOD_MEOWTH_DOLL           110
#define UG_GOOD_SKITTY_DOLL           111
#define UG_GOOD_GLAMEOW_DOLL          112
#define UG_GOOD_BUNEARY_DOLL          113
#define UG_GOOD_WEAVILE_DOLL          114
#define UG_GOOD_MUNCHLAX_DOLL         115
#define UG_GOOD_BONSLY_DOLL           116
#define UG_GOOD_MIME_JR_DOLL          117
#define UG_GOOD_LUCARIO_DOLL          118
#define UG_GOOD_MANTYKE_DOLL          119
#define UG_GOOD_BUIZEL_DOLL           120
#define UG_GOOD_CHATOT_DOLL           121
#define UG_GOOD_MANAPHY_DOLL_UNUSED   122
#define UG_GOOD_SNORLAX_DOLL          123
#define UG_GOOD_WAILORD_DOLL          124
#define UG_GOOD_MAGNEZONE_DOLL_UNUSED 125
#define UG_GOOD_DRIFLOON_DOLL         126
#define UG_GOOD_HAPPINY_DOLL          127
#define UG_GOOD_PACHIRISU_DOLL        128
#define UG_GOOD_BASE_ENTRANCE_NORTH   129
#define UG_GOOD_BASE_ENTRANCE_SOUTH   130
#define UG_GOOD_BASE_ENTRANCE_WEST    131
#define UG_GOOD_BASE_ENTRANCE_EAST    132
#define UG_GOOD_WIDE_SOFA             133
#define UG_GOOD_BONSAI                134
#define UG_GOOD_DAINTY_FLOWERS        135
#define UG_GOOD_LOVELY_FLOWERS        136
#define UG_GOOD_PRETTY_FLOWERS        137
#define UG_GOOD_LAVISH_FLOWERS        138

#endif // POKEPLATINUM_CONSTANTS_GOODS_H
