#ifndef POKEPLATINUM_CONSTANTS_GREAT_MARSH_TRAM_H
#define POKEPLATINUM_CONSTANTS_GREAT_MARSH_TRAM_H

#define GREAT_MARSH_TRAM_LOCATION_AREA_1_2 0
#define GREAT_MARSH_TRAM_LOCATION_AREA_3_4 1
#define GREAT_MARSH_TRAM_LOCATION_AREA_5_6 2
#define GREAT_MARSH_TRAM_MOVEMENT_CALL     3
#define GREAT_MARSH_TRAM_MOVEMENT_RIDE     4
#define GREAT_MARSH_TRAM_AT_LOCATION       5
#define GREAT_MARSH_TRAM_NOT_AT_LOCATION   6

#endif // POKEPLATINUM_CONSTANTS_GREAT_MARSH_TRAM_H
