#ifndef POKEPLATINUM_CONSTANTS_GROUP_CONNECTION_H
#define POKEPLATINUM_CONSTANTS_GROUP_CONNECTION_H

#define GC_ACTION_CHECK_IS_ENTRY_VALID     0
#define GC_ACTION_CHECK_IS_ENTRY_OVERRIDE  1
#define GC_ACTION_BUFFER_GROUP_NAME        2
#define GC_ACTION_BUFFER_LEADER_NAME       3
#define GC_ACTION_OPEN_GROUP_NAMING_SCREEN 4
#define GC_ACTION_JOIN_GROUP               5
#define GC_ACTION_MAKE_NEW_GROUP           6

#endif // POKEPLATINUM_CONSTANTS_GROUP_CONNECTION_H
