#ifndef POKEPLATINUM_CONSTANTS_GTS_H
#define POKEPLATINUM_CONSTANTS_GTS_H

#define GTS_TIMESTAMPS_TRADE_BY_DEPOSITING 0
#define GTS_TIMESTAMPS_TRADE_BY_SEARCHING  1

#endif // POKEPLATINUM_CONSTANTS_GTS_H
