#ifndef POKEPLATINUM_CONSTANTS_GTS_H
#define POKEPLATINUM_CONSTANTS_GTS_H

#define GTS_APPLICATION_LOOP_STATE_WAIT_FOR_WIRELESS_DRIVER 0
#define GTS_APPLICATION_LOOP_STATE_INIT                     1
#define GTS_APPLICATION_LOOP_STATE_WAIT_FADE                2
#define GTS_APPLICATION_LOOP_STATE_MAIN                     3
#define GTS_APPLICATION_LOOP_STATE_FINISH                   4
#define GTS_APPLICATION_LOOP_STATE_EXIT                     5

#endif // POKEPLATINUM_CONSTANTS_GTS_H
