#ifndef POKEPLATINUM_CONSTANTS_GX_COLORS_H
#define POKEPLATINUM_CONSTANTS_GX_COLORS_H

#define COLOR_BLACK       GX_RGB(0, 0, 0)
#define COLOR_DARK_GRAY   GX_RGB(4, 4, 4)
#define COLOR_TRANSPARENT GX_RGB(31, 31, 16)

#endif // POKEPLATINUM_CONSTANTS_GX_COLORS_H
