#ifndef POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H
#define POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H

#define INIT_SCRIPT_TYPE_CONDITION_MET  1
#define INIT_SCRIPT_TYPE_ENTER_LOCATION 2
#define INIT_SCRIPT_TYPE_MAP_READY      3
#define INIT_SCRIPT_TYPE_MAP_LOAD       4

#endif // POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H
