#ifndef POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H
#define POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H

#define INIT_SCRIPT_ON_FRAME_TABLE 1
#define INIT_SCRIPT_ON_TRANSITION  2
#define INIT_SCRIPT_ON_RESUME      3
#define INIT_SCRIPT_ON_LOAD        4

#endif // POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H
