#ifndef POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H
#define POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H

#define INIT_SCRIPT_TYPE_CONDITION_MET   1
#define INIT_SCRIPT_TYPE_ENTER_LOCATION  2
#define INIT_SCRIPT_TYPE_MAP_LOAD_FINISH 3
#define INIT_SCRIPT_TYPE_MAP_LOAD_START  4

#endif // POKEPLATINUM_CONSTANTS_INIT_SCRIPT_TYPE_H
