#ifndef POKEPLATINUM_CONSTANTS_MAP_PROP_H
#define POKEPLATINUM_CONSTANTS_MAP_PROP_H

enum MapPropModelId {
    MAP_PROP_MODEL_ID_HONEY_TREE = 26,
    MAP_PROP_MODEL_ID_UNK_124 = 124,
    MAP_PROP_MODEL_ID_UNK_242 = 242,
    MAP_PROP_MODEL_ID_UNK_258 = 258,
    MAP_PROP_MODEL_ID_UNK_475 = 475,
    MAP_PROP_MODEL_ID_UNK_498 = 498,
    MAP_PROP_MODEL_ID_UNK_517 = 517,
};

#endif // POKEPLATINUM_CONSTANTS_MAP_PROP_H
