#ifndef POKEPLATINUM_CONSTANTS_MAP_PROP_H
#define POKEPLATINUM_CONSTANTS_MAP_PROP_H

enum MapPropId {
    MAP_PROP_ID_HONEY_TREE = 26,
    MAP_PROP_ID_UNK_242 = 242,
    MAP_PROP_ID_UNK_258 = 258,
    MAP_PROP_ID_UNK_475 = 475,
};

#endif // POKEPLATINUM_CONSTANTS_MAP_PROP_H
