#ifndef POKEPLATINUM_CONSTANTS_MESSAGE_BANKS_H
#define POKEPLATINUM_CONSTANTS_MESSAGE_BANKS_H

enum ArchiveMessageBank {
    MESSAGE_BANK_SPECIES_NAMES = 412,
};

#endif // POKEPLATINUM_CONSTANTS_MESSAGE_BANKS_H