#ifndef POKEPLATINUM_CONSTANTS_MESSAGE_BANKS_H
#define POKEPLATINUM_CONSTANTS_MESSAGE_BANKS_H

enum ArchiveMessageBank {
    MESSAGE_BANK_BALL_SEAL_NAMES = 12,
    MESSAGE_BANK_BALL_SEAL_NAMES_PLURAL,

    MESSAGE_BANK_FRONTIER_TRAINER_NAMES = 21,

    MESSAGE_BANK_NATURE_NAMES = 202,

    MESSAGE_BANK_CONTEST_TEXT = 204,

    MESSAGE_BANK_CONTEST_JUDGE_NAMES = 207,

    MESSAGE_BANK_COMMON_STRINGS = 213,

    MESSAGE_BANK_STATUS_CONDITION_NAMES = 219,

    MESSAGE_BANK_COMMON_STRINGS_2 = 361,

    MESSAGE_BANK_FURNITURE_NAMES = 371,

    MESSAGE_BANK_GYM_NAMES = 378,

    MESSAGE_BANK_CONTEST_ACCESSORY_NAMES = 386,
    MESSAGE_BANK_CONTEST_ACCESSORY_NAMES_WITH_ARTICLES,
    MESSAGE_BANK_CONTEST_BACKDROP_NAMES,

    MESSAGE_BANK_ITEM_NAMES = 392,
    MESSAGE_BANK_ITEM_NAMES_WITH_ARTICLES,
    MESSAGE_BANK_ITEM_NAMES_PLURAL,

    MESSAGE_BANK_BAG_POCKET_NAMES_WITH_ICONS = 396,

    MESSAGE_BANK_SPECIES_NAMES = 412,
    MESSAGE_BANK_SPECIES_NAMES_WITH_ARTICLES,
    MESSAGE_BANK_MONTH_NAMES,

    MESSAGE_BANK_LOCATION_NAMES = 433,
    MESSAGE_BANK_MYSTERY_GIFT_EVENT_NAMES,
    MESSAGE_BANK_SPECIAL_MET_LOCATION_NAMES,

    MESSAGE_BANK_POKETCH_APP_NAMES = 457,

    MESSAGE_BANK_POFFIN_NAMES = 465,

    MESSAGE_BANK_RIBBON_NAMES = 535,

    MESSAGE_BANK_POKEMON_STAT_NAMES = 551,

    MESSAGE_BANK_COUNTERPART_NAMES = 553,

    MESSAGE_BANK_FLAVOR_NAMES = 606,

    MESSAGE_BANK_TIMES_OF_DAY = 608,

    MESSAGE_BANK_ABILITY_NAMES = 610,

    MESSAGE_BANK_NPC_TRAINER_NAMES = 618,
    MESSAGE_BANK_TRAINER_CLASS_NAMES,
    MESSAGE_BANK_TRAINER_CLASS_NAMES_WITH_ARTICLES,

    MESSAGE_BANK_POKEMON_TYPE_NAMES = 624,

    MESSAGE_BANK_UNDERGROUND_GOODS = 626,
    MESSAGE_BANK_UNDERGROUND_GOODS_WITH_ARTICLES,
    MESSAGE_BANK_UNDERGROUND_ITEM_NAMES,
    MESSAGE_BANK_UNDERGROUND_ITEM_NAMES_WITH_ARTICLES,
    MESSAGE_BANK_UNDERGROUND_TRAP_NAMES,
    MESSAGE_BANK_UNDERGROUND_TRAP_NAMES_WITH_ARTICLES,
    MESSAGE_BANK_UNDERGROUND_ANSWERS,
    MESSAGE_BANK_UNDERGROUND_QUESTIONS,

    MESSAGE_BANK_MOVE_NAMES = 647,

    MESSAGE_BANK_PLAZA_EVENT_NAMES = 649,

    MESSAGE_BANK_PLAZA_MINIGAME_NAMES = 651,
    MESSAGE_BANK_PLAZA_ITEM_NAMES,

    MESSAGE_BANK_GREETINGS_EN = 663,
    MESSAGE_BANK_GREETINGS_FR,
    MESSAGE_BANK_GREETINGS_DE,
    MESSAGE_BANK_GREETINGS_IT,
    MESSAGE_BANK_GREETINGS_JP,
    MESSAGE_BANK_GREETINGS_ES,

    MESSAGE_BANK_COUNTRY_NAMES = 694,
};

#endif // POKEPLATINUM_CONSTANTS_MESSAGE_BANKS_H
