#ifndef POKEPLATINUM_CONSTANTS_MOVES_H
#define POKEPLATINUM_CONSTANTS_MOVES_H

#include "consts/generated/c/moves.h"

#define LEARNED_MOVES_MAX     4

#define CLASS_PHYSICAL 0
#define CLASS_SPECIAL  1
#define CLASS_STATUS   2

#define NUM_MOVES MOVE_SHADOW_FORCE

#endif //POKEPLATINUM_CONSTANTS_MOVES_H
