#ifndef POKEPLATINUM_CONSTANTS_NARC_H
#define POKEPLATINUM_CONSTANTS_NARC_H

enum {
    MOVE_SCRIPTS = 0,
    BATTLE_SUBSCRIPTS,
    POKEMON_BASE_STATS,
    POKEMON_EXP_TABLES,
    POKEMON_SPRITES,
    POKEMON_HEIGHTS,
    TRAINER_BACKSPRITES,
    BATTLE_BACKGROUNDS,
    MOVE_ANIMATIONS,
    MOVE_DATA_TABLE,
    FIELD_SCRIPTS,
    SCRIPT_MESSAGES,
    POKETCH_GRAPHICS,
    BAG_GRAPHICS,
    FONT_GRAPHICS,
    ITEM_DATA_TABLE,
    ITEM_ICONS,
    TOWN_MAP_GRAPHICS,
    BOX_GRAPHICS,
    POKEMON_ICONS,
    PARTY_LIST_GRAPHICS,
    MOVE_ANIMATION_DATA,
    MOVE_ANIMATION_PALETTES,
    MOVE_ANIMATION_CELLS,
    MOVE_ANIMATION_CELL_ANIMATIONS,
    IMAGE_CLIPS,
    MSG_DATA,
    // etc.
};

#endif // POKEPLATINUM_CONSTANTS_NARC_H