#ifndef POKEPLATINUM_CONSTANTS_NET_H
#define POKEPLATINUM_CONSTANTS_NET_H

#define DEFAULT_DWC_DMA_NUMBER   2
#define DEFAULT_DWC_POWER_MODE   1
#define DEFAULT_DWC_SSL_PRIORITY 20

#define WIRELESS_DRIVER_STATUS_DISCONNECTED 0
#define WIRELESS_DRIVER_STATUS_CONNECTING   1
#define WIRELESS_DRIVER_STATUS_CONNECTED    2

#endif // POKEPLATINUM_CONSTANTS_NET_H
