#ifndef POKEPLATINUM_CONSTANTS_NPC_TRADES_H
#define POKEPLATINUM_CONSTANTS_NPC_TRADES_H

enum NPCTradeID {
    NPC_TRADE_KAZZA_ABRA = 0,
    NPC_TRADE_CHARAP_CHATOT,
    NPC_TRADE_GASPAR_HAUNTER,
    NPC_TRADE_FOPPA_MAGIKARP,
    MAX_NPC_TRADES,
};

#endif // POKEPLATINUM_CONSTANTS_NPC_TRADES_H
