#ifndef POKEPLATINUM_CONSTANTS_OVERWORLD_WEATHER_H
#define POKEPLATINUM_CONSTANTS_OVERWORLD_WEATHER_H

#define OVERWORLD_WEATHER_CLEAR        0
#define OVERWORLD_WEATHER_CLOUDY       1
#define OVERWORLD_WEATHER_RAINING      2
#define OVERWORLD_WEATHER_HEAVY_RAIN   3
#define OVERWORLD_WEATHER_THUNDERSTORM 4
#define OVERWORLD_WEATHER_SNOWING      5
#define OVERWORLD_WEATHER_HEAVY_SNOW   6
#define OVERWORLD_WEATHER_BLIZZARD     7
#define OVERWORLD_WEATHER_CLEAR_8      8
#define OVERWORLD_WEATHER_SLOW_ASHFALL 9
#define OVERWORLD_WEATHER_SANDSTORM    10
#define OVERWORLD_WEATHER_HAILING      11
#define OVERWORLD_WEATHER_SPIRITS      12
#define OVERWORLD_WEATHER_CLEAR_13     13
#define OVERWORLD_WEATHER_FOG          14
#define OVERWORLD_WEATHER_DEEP_FOG     15
#define OVERWORLD_WEATHER_DARK_FLASH   16

#define OVERWORLD_WEATHER_23 23
#define OVERWORLD_WEATHER_26 26
#define OVERWORLD_WEATHER_27 27
#define OVERWORLD_WEATHER_28 28
#define OVERWORLD_WEATHER_29 29
#define OVERWORLD_WEATHER_30 30

#define OVERWORLD_WEATHER_32 32
#define OVERWORLD_WEATHER_33 33
#define OVERWORLD_WEATHER_34 34
#define OVERWORLD_WEATHER_35 35
#define OVERWORLD_WEATHER_36 36

// these are only for the Battle Frontier
#define OVERWORLD_WEATHER_HARSH_SUN  1001
#define OVERWORLD_WEATHER_TRICK_ROOM 1002

#endif // POKEPLATINUM_CONSTANTS_OVERWORLD_WEATHER_H
