#ifndef POKEPLATINUM_CONSTANTS_PALETTE_H
#define POKEPLATINUM_CONSTANTS_PALETTE_H

enum Palette {
    PLTT_0 = 0,
    PLTT_1,
    PLTT_2,
    PLTT_3,
    PLTT_4,
    PLTT_5,
    PLTT_6,
    PLTT_7,
    PLTT_8,
    PLTT_9,
    PLTT_10,
    PLTT_11,
    PLTT_12,
    PLTT_13,
    PLTT_14,
    PLTT_15,
};

#endif // POKEPLATINUM_CONSTANTS_PALETTE_H
