#ifndef POKEPLATINUM_CONSTANTS_PC_BOXES_H
#define POKEPLATINUM_CONSTANTS_PC_BOXES_H

#define MAX_PC_BOXES              18
#define MAX_PC_ROWS               5
#define MAX_PC_COLS               6
#define MAX_MONS_PER_BOX          (MAX_PC_ROWS * MAX_PC_COLS)
#define MAX_DEFAULT_WALLPAPERS    16
#define MAX_UNLOCKABLE_WALLPAPERS 8
#define MAX_WALLPAPERS            (MAX_DEFAULT_WALLPAPERS + MAX_UNLOCKABLE_WALLPAPERS)
#define PC_BOX_NAME_BUFFER_LEN    20

#define USE_CURRENT_BOX -1

#endif // POKEPLATINUM_CONSTANTS_PC_BOXES_H
