#ifndef POKEPLATINUM_CONSTANTS_PLAYER_AVATAR_H
#define POKEPLATINUM_CONSTANTS_PLAYER_AVATAR_H

#include "generated/player_transitions.h";

// Player State
enum PlayerAvatarState {
    PLAYER_AVATAR_WALKING = 0,
    PLAYER_AVATAR_CYCLING,
    PLAYER_AVATAR_SURFING,

    PLAYER_AVATAR_USE_FIELD_MOVE = 16,
    PLAYER_AVATAR_SPRAYDUCK,
    PLAYER_AVATAR_CONTEST,
    PLAYER_AVATAR_FISHING,
    PLAYER_AVATAR_POKETCH,
    PLAYER_AVATAR_SAVE,
    PLAYER_AVATAR_HEAL,
    PLAYER_AVATAR_VS_SEEKER,
    PLAYER_AVATAR_DISTORTION_WORLD,
    PLAYER_AVATAR_DISTORTION_WORLD_SURF,
    PLAYER_AVATAR_26,
    PLAYER_AVATAR_27,
    PLAYER_AVATAR_HEARTHOME_GYM,
    PLAYER_AVATAR_29,
    PLAYER_AVATAR_30,
};

#define PLAYER_EVENT_NONE             0
#define PLAYER_EVENT_USED_STRENGTH    (1 << 0)
#define PLAYER_EVENT_USED_WATERFALL   (1 << 1)
#define PLAYER_EVENT_DISTORTION_WORLD (1 << 2)

enum PlayerMoveState {
    PLAYER_MOVE_STATE_NONE = 0,
    PLAYER_MOVE_STATE_START,
    PLAYER_MOVE_STATE_MOVING,
    PLAYER_MOVE_STATE_END,
};

enum AvatarMoveState {
    AVATAR_MOVE_STATE_NONE = 0,
    AVATAR_MOVE_STATE_MOVING,
    AVATAR_MOVE_STATE_TURNING,
};

enum AvatarDistortionState {
    AVATAR_DISTORTION_STATE_NONE = 0,
    AVATAR_DISTORTION_STATE_ACTIVE,
    AVATAR_DISTORTION_STATE_FLOOR,
    AVATAR_DISTORTION_STATE_WEST_WALL,
    AVATAR_DISTORTION_STATE_EAST_WALL,
    AVATAR_DISTORTION_STATE_CEILING,
    AVATAR_DISTORTION_STATE_MAX,
};

enum PlayerMovementActionSpeed {
    PLAYER_ACTION_SPEED_NONE,
    PLAYER_ACTION_SPEED_NOT_MOVING,
    PLAYER_ACTION_SPEED_SLOWER,
    PLAYER_ACTION_SPEED_SLOW,
    PLAYER_ACTION_SPEED_NORMAL,
    PLAYER_ACTION_SPEED_FAST,
    PLAYER_ACTION_SPEED_FASTER
};

// Tiles that affect and override the default movement function
enum PlayerTileMovement {
    TILE_MOVE_NONE = 0,
    TILE_MOVE_ICE,
    TILE_MOVE_BIKE_SLOPE,
    TILE_MOVE_BIKE_RAMP_EAST,
    TILE_MOVE_BIKE_RAMP_WEST,
    TILE_MOVE_CYCLING_ROAD_DOWN,
    TILE_MOVE_MAX,
};

// Player Avatar collision flags
#define PLAYER_COLLISION_NONE       0
#define PLAYER_COLLISION_WILL_COLLIDE   (1 << 0)
#define PLAYER_COLLISION_1   (1 << 1)
#define PLAYER_COLLISION_JUMP   (1 << 2)
#define PLAYER_COLLISION_WARP   (1 << 3)
#define PLAYER_COLLISION_BIKE_RAMP   (1 << 4)
#define PLAYER_COLLISION_WATER   (1 << 5)
#define PLAYER_COLLISION_BIKE_BRIDGE   (1 << 6)
#define PLAYER_COLLISION_JUMP_TWICE   (1 << 7)

#endif // POKEPLATINUM_CONSTANTS_PLAYER_AVATAR_H
