#ifndef POKEPLATINUM_CONSTANTS_PLAYER_AVATAR_H
#define POKEPLATINUM_CONSTANTS_PLAYER_AVATAR_H

#include "generated/player_transitions.h"

// Player State
#define PLAYER_STATE_WALKING 0
#define PLAYER_STATE_CYCLING 1
#define PLAYER_STATE_SURFING 2

#define PLAYER_EVENT_NONE             0
#define PLAYER_EVENT_USED_STRENGTH    (1 << 0)
#define PLAYER_EVENT_USED_WATERFALL   (1 << 1)
#define PLAYER_EVENT_DISTORTION_WORLD (1 << 2)

enum PlayerMoveState {
    PLAYER_MOVE_STATE_NONE = 0,
    PLAYER_MOVE_STATE_START,
    PLAYER_MOVE_STATE_MOVING,
    PLAYER_MOVE_STATE_END,
};

enum AvatarMoveState {
    AVATAR_MOVE_STATE_NONE = 0,
    AVATAR_MOVE_STATE_MOVING,
    AVATAR_MOVE_STATE_TURNING,
};

enum AvatarDistortionState {
    AVATAR_DISTORTION_STATE_NONE = 0,
    AVATAR_DISTORTION_STATE_ACTIVE,
    AVATAR_DISTORTION_STATE_FLOOR,
    AVATAR_DISTORTION_STATE_WEST_WALL,
    AVATAR_DISTORTION_STATE_EAST_WALL,
    AVATAR_DISTORTION_STATE_CEILING,
    AVATAR_DISTORTION_STATE_MAX,
};

enum CyclingSpeed {
    CYCLING_SPEED_STOPPED = 0,
    CYCLING_SPEED_SLOW,
    CYCLING_SPEED_MEDIUM,
    CYCLING_SPEED_FAST,
};

enum WalkingSpeed {
    WALKING_SPEED_SLOWER = 0,
    WALKING_SPEED_SLOW,
    WALKING_SPEED_NORMAL,
    WALKING_SPEED_SLIGHTLY_FAST,
    WALKING_SPEED_FAST,
    WALKING_SPEED_FASTER,
};

enum CyclingMovementType {
    CYCLING_MOVEMENT_TURN_IN_PLACE = 0,
    CYCLING_MOVEMENT_NORMAL,
    CYCLING_MOVEMENT_TURN,
    CYCLING_MOVEMENT_DECELERATION,
};

enum ElevationChange {
    ELEVATION_CHANGE_NONE = 0,
    ELEVATION_CHANGE_UP,
    ELEVATION_CHANGE_DOWN,
};

enum CyclingGear {
    CYCLING_GEAR_LOW = 0,
    CYCLING_GEAR_HIGH,
};

#endif // POKEPLATINUM_CONSTANTS_PLAYER_AVATAR_H
