#ifndef POKEPLATINUM_CONSTANTS_RECORD_MIXED_RNG_H
#define POKEPLATINUM_CONSTANTS_RECORD_MIXED_RNG_H

enum RecordMixedRNGEntry {
    RECORD_MIXED_RNG_PLAYER_ORIGINAL,
    RECORD_MIXED_RNG_PLAYER_OVERRIDE,
    RECORD_MIXED_RNG_QUEUE_0,
    RECORD_MIXED_RNG_QUEUE_1,
    RECORD_MIXED_RNG_QUEUE_2,
    RECORD_MIXED_RNG_QUEUE_3,

    RECORD_MIXED_RNG_MAX,
};

#define GC_ACTION_CHECK_IS_ENTRY_VALID     0
#define GC_ACTION_CHECK_IS_ENTRY_OVERRIDE  1
#define GC_ACTION_BUFFER_GROUP_NAME        2
#define GC_ACTION_BUFFER_LEADER_NAME       3
#define GC_ACTION_OPEN_GROUP_NAMING_SCREEN 4
#define GC_ACTION_JOIN_GROUP               5
#define GC_ACTION_MAKE_NEW_GROUP           6

#endif // POKEPLATINUM_CONSTANTS_RECORD_MIXED_RNG_H
