#ifndef POKEPLATINUM_CONSTANTS_RECORD_MIXED_RNG_H
#define POKEPLATINUM_CONSTANTS_RECORD_MIXED_RNG_H

enum RecordMixedRNGEntry {
    RECORD_MIXED_RNG_PLAYER_ORIGINAL,
    RECORD_MIXED_RNG_PLAYER_OVERRIDE,
    RECORD_MIXED_RNG_QUEUE_0,
    RECORD_MIXED_RNG_QUEUE_1,
    RECORD_MIXED_RNG_QUEUE_2,
    RECORD_MIXED_RNG_QUEUE_3,

    RECORD_MIXED_RNG_MAX,
};

#endif // POKEPLATINUM_CONSTANTS_RECORD_MIXED_RNG_H
