#ifndef POKEPLATINUM_CONSTANTS_REGI_RUINS_H
#define POKEPLATINUM_CONSTANTS_REGI_RUINS_H

#define RUINS_STATE_ACTIVATED_ALL_DOTS 260
#define RUINS_STATE_ACTIVATED_STATUE   270
#define RUINS_STATE_DID_NOT_CATCH_REGI 280
#define RUINS_STATE_CAUGHT_REGI        290

#define DOT_TYPE_IRON_RUINS      588
#define DOT_TYPE_ICEBERG_RUINS   590
#define DOT_TYPE_ROCK_PEAK_RUINS 592

#endif // POKEPLATINUM_CONSTANTS_REGI_RUINS_H
