#ifndef POKEPLATINUM_CONSTANTS_ROAMER_STATES_H
#define POKEPLATINUM_CONSTANTS_ROAMER_STATES_H

#define ROAMER_STATE_ROAMING  0
#define ROAMER_STATE_CAPTURED 1
#define ROAMER_STATE_DEFEATED 2
#define ROAMER_STATE_RESET    3

#endif // POKEPLATINUM_CONSTANTS_ROAMER_STATES_H
