#ifndef POKEPLATINUM_CONSTANTS_SCRCMD_H
#define POKEPLATINUM_CONSTANTS_SCRCMD_H

#include "constants/accessories.h"
#include "constants/menu.h"
#include "generated/backdrops.h"

#define BATTLEGROUND_TRAINER_NONE 0xFFF

#define BERRY_WATERING_START 0
#define BERRY_WATERING_END   1

#define LOCALID_CAMERA   0xF1
#define LOCALID_FOLLOWER 0xF2
#define LOCALID_PLAYER   0xFF

#define LIST_MENU_ENTRY_NO_ALT_TEXT 0xff

#define LIST_MENU_BUILDER_HEADER 0xfa

#define NO_EXIT_ON_B FALSE

#define NUM_MASSAGE_GIRL_ACCESSORIES (ACCESSORY_GLITTER_POWDER - ACCESSORY_PRETTY_DEWDROP + 1)

#define SAFARI_GAME_ACTIVE   0
#define SAFARI_GAME_INACTIVE 1

#endif // POKEPLATINUM_CONSTANTS_SCRCMD_H
