#ifndef POKEPLATINUM_CONSTANTS_SCRCMD_H
#define POKEPLATINUM_CONSTANTS_SCRCMD_H

#define MENU_YES 0
#define MENU_NO  1

#define LOCALID_PLAYER 0xFF

#define LIST_MENU_ENTRY_NO_ALT_TEXT 0xff

#define FIELD_MENU_ANCHOR_LEFT   0
#define FIELD_MENU_ANCHOR_RIGHT  1
#define FIELD_MENU_ANCHOR_TOP    0
#define FIELD_MENU_ANCHOR_BOTTOM 1

#endif // POKEPLATINUM_CONSTANTS_SCRCMD_H
