#ifndef POKEPLATINUM_CONSTANTS_SCRCMD_H
#define POKEPLATINUM_CONSTANTS_SCRCMD_H

#include "generated/accessories.h"
#include "generated/backdrops.h"

#define MENU_YES 0
#define MENU_NO  1

#define LOCALID_PLAYER 0xFF

#define LIST_MENU_ENTRY_NO_ALT_TEXT 0xff

#define LIST_MENU_BUILDER_HEADER 0xfa

#define NO_EXIT_ON_B FALSE

#define NUM_MASSAGE_GIRL_ACCESSORIES (ACCESSORY_GLITTER_POWDER - ACCESSORY_PRETTY_DEWDROP + 1)

#endif // POKEPLATINUM_CONSTANTS_SCRCMD_H
