#ifndef POKEPLATINUM_SCRIPTS_COMMON_H
#define POKEPLATINUM_SCRIPTS_COMMON_H

// TODO: This ideally should be generated as part of the build process from the ScriptEntry is the scripts_common.s file
#define HandleSignpostInput                 0x7D0
#define CheckBagPocketForItem               0x7D1
#define Pokecenter_SpeakWithNurse           0x7D2
#define UNK_03E8                            0x7D3
#define UNK_043B                            0x7D4
#define UNK_0479                            0x7D5
#define SaveGame                            0x7D6
#define EmptyScript2                        0x7D7
#define UNK_05EA                            0x7D8
#define ObtainPoketchApp                    0x7D9
#define EmptyScript1                        0x7DA
#define EmptyScript3                        0x7DB
#define SendToUndergroundPC                 0x7DC
#define ObtainUndergroundTrap               0x7DD
#define ObtainUndergroundSphere             0x7DE
#define ObtainAccessoryWaitForConfirm       0x7DF
#define AddItemQuantityNoLineFeed           0x7E0
#define BagIsFull                           0x7E1
#define UNK_0BEE                            0x7E2
#define VendorGreetingGeneric               0x7E3
#define UNK_0FCA                            0x7E4
#define UNK_103A                            0x7E5
#define EmptyScript4                        0x7E6
#define UNK_0FA7                            0x7E7
#define EmptyScript5                        0x7E8
#define UNK_1282                            0x7E9
#define UNK_12A8                            0x7EA
#define UNK_12BA                            0x7EB
#define UNK_12CD                            0x7EC
#define UNK_12E0                            0x7ED
#define UNK_12F3                            0x7EE
#define UNK_1361                            0x7EF
#define UNK_138C                            0x7F0
#define UNK_139D                            0x7F1
#define UNK_048B                            0x7F2
#define UNK_13AB                            0x7F3
#define ObtainContestBackdropWaitForConfirm 0x7F4
#define EmptyScript6                        0x7F5
#define PrintPlateObtainedMessage           0x7F6
#define UNK_1477                            0x7F7
#define SetCounterpartBGM                   0x7F8
#define FadeToDefaultMusic                  0x7F9
#define SetRivalBGM                         0x7FA
#define FadeToDefaultMusic_duplicate1       0x7FB
#define AddItemQuantity                     0x7FC
#define ObtainContestBackdrop               0x7FD
#define SendToUndergroundPCWithLinefeed     0x7FE
#define ObtainAccessory                     0x7FF
#define UNK_15BF                            0x800
#define FadeToDefaultMusic_duplicate2       0x801
#define UNK_15E7                            0x802
#define UNK_1636                            0x803
#define UNK_164A                            0x804
#define UNK_165E                            0x805
#define CheckAllFrontierGoldPrintsObtained  0x806
#define SetLookerBGM                        0x807
#define FadeToDefaultMusic_duplicate3       0x808
#define UNK_170A                            0x809

#endif // POKEPLATINUM_SCRIPTS_COMMON_H
