#ifndef POKEPLATINUM_CONSTANTS_SDAT_H
#define POKEPLATINUM_CONSTANTS_SDAT_H

#define SEQ_BATTLE_WILD_POKEMON     (1116)
#define SEQ_BATTLE_GYM_LEADER       (1117)
#define SEQ_BATTLE_LAKE_GUARDIAN    (1118)
#define SEQ_BATTLE_TRAINER          (1119)
#define SEQ_BATTLE_CYRUS            (1120)
#define SEQ_BATTLE_DIALGA_PALKIA    (1121)
#define SEQ_BATTLE_CHAMPION         (1122)
#define SEQ_BATTLE_GALACTIC_GRUNT   (1123)
#define SEQ_BATTLE_RIVAL            (1124)
#define SEQ_BATTLE_ARCEUS           (1125)
#define SEQ_BATTLE_LEGENDARY        (1126)
#define SEQ_BATTLE_GALACTIC_CMDR    (1134)
#define SEQ_BATTLE_ELITE_FOUR       (1136)
#define SEQ_BATTLE_GIRATINA         (1201)
#define SEQ_BATTLE_FRONTIER_BRAIN   (1202)
#define SEQ_BATTLE_REGI_TRIO        (1204)

#endif // POKEPLATINUM_CONSTANTS_SDAT_H
