#ifndef POKEPLATINUM_CONSTANTS_SDAT_H
#define POKEPLATINUM_CONSTANTS_SDAT_H

enum SDATID {
    SEQ_BATTLE_WILD_POKEMON = 1116,
    SEQ_BATTLE_GYM_LEADER,
    SEQ_BATTLE_LAKE_GUARDIAN,
    SEQ_BATTLE_TRAINER,
    SEQ_BATTLE_CYRUS,
    SEQ_BATTLE_DIALGA_PALKIA,
    SEQ_BATTLE_CHAMPION,
    SEQ_BATTLE_GALACTIC_GRUNT,
    SEQ_BATTLE_RIVAL,
    SEQ_BATTLE_ARCEUS,
    SEQ_BATTLE_LEGENDARY,
    SEQ_VICTORY_WILD_POKEMON,
    SEQ_VICTORY_TRAINER,
    SEQ_VICTORY_GYM_LEADER,
    SEQ_VICTORY_CHAMPION,
    SEQ_VICTORY_GALACTIC_GRUNT,
    SEQ_VICTORY_CYRUS,
    SEQ_VICTORY_ELITE_FOUR,
    SEQ_BATTLE_GALACTIC_CMDR,
    SEQ_CONTEST_DRESSING_ROOM,
    SEQ_BATTLE_ELITE_FOUR,

    SEQ_POKERADAR = 1150,

    SEQ_BATTLE_GIRATINA = 1201,
    SEQ_BATTLE_FRONTIER_BRAIN,
    SEQ_VICTORY_FRONTIER_BRAIN,
    SEQ_BATTLE_REGI_TRIO,

    SEQ_CONFIRM = 1500,

    SEQ_PARTY_GAUGE_ARROW_IN = 1809,
    SEQ_PARTY_GAUGE_BALL_IN,
    SEQ_PARTY_GAUGE_BALL_EMPTY,
};

#endif // POKEPLATINUM_CONSTANTS_SDAT_H
