#ifndef POKEPLATINUM_CONSTANTS_SOUND_H
#define POKEPLATINUM_CONSTANTS_SOUND_H

enum PokemonCryMod {
    POKECRY_NORMAL = 0,
    POKECRY_HALF_DURATION,
    POKECRY_FIELD_EVENT,
    POKECRY_MID_MOVE,
    POKECRY_HYPERVOICE_1,
    POKECRY_FAINT,
    POKECRY_HYPERVOICE_2,
    POKECRY_HOWL_1,
    POKECRY_HOWL_2,
    POKECRY_UPROAR_1,
    POKECRY_UPROAR_2,
    POKECRY_PINCH_NORMAL,
    POKECRY_PINCH_HALF_DURATION,
    POKECRY_POKEDEX_CHORUS,
    POKECRY_POKEDEX,
};

#endif // POKEPLATINUM_CONSTANTS_SOUND_H
