#ifndef POKEPLATINUM_CONSTANTS_SOUND_H
#define POKEPLATINUM_CONSTANTS_SOUND_H

enum PokemonCryMod {
    POKECRY_NORMAL = 0,

    POKECRY_PINCH_NORMAL = 11,
};

#endif // POKEPLATINUM_CONSTANTS_SOUND_H
