#ifndef POKEPLATINUM_CONSTANTS_SPECIES_H
#define POKEPLATINUM_CONSTANTS_SPECIES_H

#include "generated/species.h"

#define MAX_SPECIES        SPECIES_BAD_EGG
#define NATIONAL_DEX_COUNT (MAX_SPECIES - 2)

#endif // POKEPLATINUM_CONSTANTS_SPECIES_H
