#ifndef POKEPLATINUM_CONSTANTS_START_MENU_H
#define POKEPLATINUM_CONSTANTS_START_MENU_H

#define ICON_ANIM_NONE   0
#define ICON_ANIM_SWELL  1
#define ICON_ANIM_WIGGLE 2
#define ICON_ANIM_COUNT  3

#define PALETTE_GRAYSCALE 0
#define PALETTE_COLORED   1

#define CURSOR_TEMPLATE 0
#define ICON_TEMPLATE   1

#define CURSOR_SPRITE_INDEX 0

#endif // POKEPLATINUM_CONSTANTS_START_MENU_H
