#ifndef POKEPLATINUM_CONSTANTS_TIME_H
#define POKEPLATINUM_CONSTANTS_TIME_H

enum Time {
    TIME_MORNING = 0,
    TIME_DAY,
    TIME_DUSK,
    TIME_NIGHT,
    TIME_MIDNIGHT,
};

#endif // POKEPLATINUM_CONSTANTS_TIME_H