#ifndef POKEPLATINUM_TRAINER_H
#define POKEPLATINUM_TRAINER_H

#define TRMSG_ACTIVE_BATTLER_HALF_HP_FLAG 2
#define TRMSG_LAST_BATTLER_FLAG           3
#define TRMSG_LAST_BATTLER_HALF_HP_FLAG   4

enum TrainerMessageType {
    TRMSG_FIRST_DAMAGE = 13,
    TRMSG_ACTIVE_BATTLER_HALF_HP,
    TRMSG_LAST_BATTLER,
    TRMSG_LAST_BATTLER_HALF_HP,
};

#endif // POKEPLATINUM_TRAINER_H
