#ifndef POKEPLATINUM_CONSTANTS_TRAINER_CARD_LEVELS_H
#define POKEPLATINUM_CONSTANTS_TRAINER_CARD_LEVELS_H

#define TRAINER_CARD_LEVEL_NORMAL 0
#define TRAINER_CARD_LEVEL_COBALT 1
#define TRAINER_CARD_LEVEL_BRONZE 2
#define TRAINER_CARD_LEVEL_SILVER 3
#define TRAINER_CARD_LEVEL_GOLD   4
#define TRAINER_CARD_LEVEL_BLACK  5

#endif // POKEPLATINUM_CONSTANTS_TRAINER_CARD_LEVELS_H
