#ifndef POKEPLATINUM_CONSTANTS_TV_BROADCAST_H
#define POKEPLATINUM_CONSTANTS_TV_BROADCAST_H

#define TV_BROADCAST_CALL_CHECK_STATUS         0
#define TV_BROADCAST_CALL_LOAD_FRAMING_MESSAGE 1
#define TV_BROADCAST_CALL_FINISH_PROGRAM       2
#define TV_BROADCAST_CALL_LOAD_SEGMENT         3
#define TV_BROADCAST_CALL_LOAD_COMMERCIAL      4
#define TV_BROADCAST_CALL_UNUSED               5
#define TV_BROADCAST_CALL_GET_NEXT_SEGMENT_ID  6

#define TV_BROADCAST_STATUS_FINISHED 0
#define TV_BROADCAST_STATUS_FINISH   1
#define TV_BROADCAST_STATUS_BEGIN    2
#define TV_BROADCAST_STATUS_CONTINUE 3

#define TV_INTERVIEW_CALL_LOAD_MESSAGE  0
#define TV_INTERVIEW_CALL_SAVE_RESPONSE 1

#define TV_PROGRAM_TYPE_INTERVIEWS        1
#define TV_PROGRAM_TYPE_TRAINER_SIGHTINGS 2
#define TV_PROGRAM_TYPE_RECORDS           3
#define TV_PROGRAM_TYPE_SINNOH_NOW        4
#define TV_PROGRAM_TYPE_VARIETY_HOUR      5
#define TV_PROGRAM_TYPE_MAX               6

#define TV_PROGRAM_FRAMING_MESSAGE_GREETING          0
#define TV_PROGRAM_FRAMING_MESSAGE_SEGMENT_INTRO     1
#define TV_PROGRAM_FRAMING_MESSAGE_FAREWELL          2
#define TV_PROGRAM_FRAMING_MESSAGE_FAREWELL_EXTENDED 3

#define TV_PROGRAM_TYPE_INTERVIEWS_NUM_SEGMENTS        19
#define TV_PROGRAM_TYPE_TRAINER_SIGHTINGS_NUM_SEGMENTS 26
#define TV_PROGRAM_TYPE_RECORDS_NUM_SEGMENTS           11
#define TV_PROGRAM_TYPE_SINNOH_NOW_NUM_SEGMENTS        17
#define TV_PROGRAM_TYPE_VARIETY_HOUR_NUM_SEGMENTS      8

#define TV_PROGRAM_SEGMENT_BATTLE_TOWER_CORNER                   2
#define TV_PROGRAM_SEGMENT_YOUR_POKEMON_CORNER                   4
#define TV_PROGRAM_SEGMENT_THE_POKETCH_WATCH                     6
#define TV_PROGRAM_SEGMENT_CONTEST_HALL                          7
#define TV_PROGRAM_SEGMENT_RIGHT_ON_PHOTO_CORNER                 9
#define TV_PROGRAM_SEGMENT_STREET_CORNER_PERSONALITY_CHECKUP     10
#define TV_PROGRAM_SEGMENT_THREE_CHEERS_FOR_POFFIN_CORNER        11
#define TV_PROGRAM_SEGMENT_AMITY_SQUARE_WATCH                    13
#define TV_PROGRAM_SEGMENT_BATTLE_FRONTIER_FRONTLINE_NEWS_SINGLE 14
#define TV_PROGRAM_SEGMENT_IN_YOUR_FACE_INTERVIEW_QUESTION_1     15
#define TV_PROGRAM_SEGMENT_IN_YOUR_FACE_INTERVIEW_QUESTION_2     16
#define TV_PROGRAM_SEGMENT_IN_YOUR_FACE_INTERVIEW_QUESTION_3     17
#define TV_PROGRAM_SEGMENT_IN_YOUR_FACE_INTERVIEW_QUESTION_4     18
#define TV_PROGRAM_SEGMENT_BATTLE_FRONTIER_FRONTLINE_NEWS_MULTI  19

#endif // POKEPLATINUM_CONSTANTS_TV_BROADCAST_H
