#ifndef POKEPLATINUM_CONSTANTS_TV_BROADCAST_H
#define POKEPLATINUM_CONSTANTS_TV_BROADCAST_H

#define TV_BROADCAST_CALL_CHECK_STATUS    0
#define TV_BROADCAST_CALL_FRAMING_MESSAGE 1
#define TV_BROADCAST_CALL_FINISH_PROGRAM  2
#define TV_BROADCAST_CALL_LOAD_SEGMENT    3
#define TV_BROADCAST_CALL_LOAD_COMMERCIAL 4
#define TV_BROADCAST_CALL_UNUSED          5
#define TV_BROADCAST_CALL_NEXT_SEGMENT    6

#define TV_BROADCAST_STATUS_FINISHED 0
#define TV_BROADCAST_STATUS_FINISH   1
#define TV_BROADCAST_STATUS_BEGIN    2
#define TV_BROADCAST_STATUS_CONTINUE 3

#define TV_PROGRAM_TYPE_INTERVIEWS        1
#define TV_PROGRAM_TYPE_TRAINER_SIGHTINGS 2
#define TV_PROGRAM_TYPE_RECORDS           3
#define TV_PROGRAM_TYPE_SINNOH_NOW        4
#define TV_PROGRAM_TYPE_VARIETY_HOUR      5

#define TV_PROGRAM_FRAMING_MESSAGE_GREETING          0
#define TV_PROGRAM_FRAMING_MESSAGE_SEGMENT_INTRO     1
#define TV_PROGRAM_FRAMING_MESSAGE_FAREWELL          2
#define TV_PROGRAM_FRAMING_MESSAGE_FAREWELL_EXTENDED 3

#endif // POKEPLATINUM_CONSTANTS_TV_BROADCAST_H
