#ifndef POKEPLATINUM_CONSTANTS_VERSIONS_H
#define POKEPLATINUM_CONSTANTS_VERSIONS_H

enum Version {
    VERSION_NONE = 0,
    VERSION_SAPPHIRE,
    VERSION_RUBY,
    VERSION_EMERALD,
    VERSION_FIRERED,
    VERSION_LEAFGREEN,
    VERSION_UNUSED_6,
    VERSION_HEARTGOLD,
    VERSION_SOULSILVER,
    VERSION_UNUSED_9,
    VERSION_DIAMOND,
    VERSION_PEARL,
    VERSION_PLATINUM,
    VERSION_UNUSED_13,
    VERSION_UNUSED_14,
    VERSION_GAMECUBE, // Both Colosseum and XD use the same ID
};

enum Language {
    LANGUAGE_NONE = 0,
    LANGUAGE_JAPANESE,
    LANGUAGE_ENGLISH,
    LANGUAGE_FRENCH,
    LANGUAGE_ITALIAN,
    LANGUAGE_GERMAN,
    LANGUAGE_UNUSED_6,
    LANGUAGE_SPANISH,
    LANGUAGE_KOREAN,
};

#endif // POKEPLATINUM_CONSTANTS_VERSIONS_H
