#ifndef POKEPLATINUM_CONSTANTS_VILLA_VISITORS_H
#define POKEPLATINUM_CONSTANTS_VILLA_VISITORS_H

#define VILLA_VISITOR_NONE 0xFF

#define VILLA_VISITOR_RIVAL           0
#define VILLA_VISITOR_COUNTERPART     1
#define VILLA_VISITOR_PROF_ROWAN      2
#define VILLA_VISITOR_MOM             3
#define VILLA_VISITOR_ROARK           4
#define VILLA_VISITOR_GARDENIA        5
#define VILLA_VISITOR_FANTINA         6
#define VILLA_VISITOR_MAYLENE         7
#define VILLA_VISITOR_CRASHER_WAKE    8
#define VILLA_VISITOR_BYRON           9
#define VILLA_VISITOR_CANDICE         10
#define VILLA_VISITOR_VOLKNER         11
#define VILLA_VISITOR_CYNTHIA         12
#define VILLA_VISITOR_FLINT_VOLKNER   13
#define VILLA_VISITOR_MAYLENE_CANDICE 14

#endif // POKEPLATINUM_CONSTANTS_VILLA_VISITORS_H
