#ifndef POKEPLATINUM_CONSTANTS_WFC_FACILITY_SELECTOR_FUNCTIONS_H
#define POKEPLATINUM_CONSTANTS_WFC_FACILITY_SELECTOR_FUNCTIONS_H

enum WFCFacilitySelectorFunction {
    WFCFS_FUNC_INIT_COMM_MANAGER = 0,
    WFCFS_FUNC_GET_PARTNERS_FIRST_PICK,
    WFCFS_FUNC_CHECK_MON_SELECTIONS_VALID,
    WFCFS_FUNC_CHECK_HALL_STREAK_ACTIVE,
    WFCFS_FUNC_CHECK_HALL_STREAK_SPECIES,
    WFCFS_FUNC_GET_SELECTED_SPECIES,
    WFCFS_FUNC_CLEAR_ACTIVE_HALL_STREAK,
    WFCFS_FUNC_SET_SELECTED_FACILITY,
    WFCFS_FUNC_GET_PARTNERS_STREAK_DELETION_CHOICE,
    WFCFS_FUNC_GET_SELECTED_FACILITY,
    WFCFS_FUNC_CHECK_PARTNER_PLAYING_AGAIN,
    WFCFS_FUNC_CLEAR_STREAK_IF_NOT_MATCHING,
    WFCFS_FUNC_CLEAR_LATEST_STREAK,
    WFCFS_FUNC_CLEAR_PARTY_MENU_SELECTIONS,
};
#endif // POKEPLATINUM_CONSTANTS_WFC_FACILITY_SELECTOR_FUNCTIONS_H
