#ifndef POKEPLATINUM_CONSTANTS_WIRELESS_DRIVER_H
#define POKEPLATINUM_CONSTANTS_WIRELESS_DRIVER_H

#define WIRELESS_DRIVER_STATUS_DISCONNECTED 0
#define WIRELESS_DRIVER_STATUS_CONNECTING   1
#define WIRELESS_DRIVER_STATUS_CONNECTED    2

#endif // POKEPLATINUM_CONSTANTS_WIRELESS_DRIVER_H
