sseq_gen = generator(nitrosfx_exe,
    arguments: [ '@INPUT@', '@OUTPUT@', '@EXTRA_ARGS@', ],
    output: '@BASENAME@.sseq',
)

sound_sequence_files = files([
    'SEQ_ACCE.mid',
    'SEQ_AIF_FIELD.mid',
    'SEQ_ASA.mid',
    'SEQ_AUS.mid',
    'BATTLE_CYRUS.mid',
    'BATTLE_CHAMPION.mid',
    'SEQ_BADGE.mid',
    'BATTLE_LAKE_GUARDIAN.mid',
    'BATTLE_DIALGA_PALKIA.mid',
    'BATTLE_GALACTIC_CMDR.mid',
    'BATTLE_GALACTIC_GRUNT.mid',
    'BATTLE_GYM_LEADER.mid',
    'BATTLE_WILD_POKEMON.mid',
    'BATTLE_RIVAL.mid',
    'BATTLE_ARCEUS.mid',
    'BATTLE_LEGENDARY.mid',
    'BATTLE_ELITE_FOUR.mid',
    'SEQ_BA_TOWER.mid',
    'BATTLE_TRAINER.mid',
    'SEQ_BF_FACT.mid',
    'SEQ_BF_TOWWER.mid',
    'SEQ_BICYCLE.mid',
    'SEQ_BLD_BLD_GTC.mid',
    'SEQ_BLD_CON.mid',
    'SEQ_BLD_DENDO.mid',
    'SEQ_BLD_ENDING.mid',
    'SEQ_BLD_EV_DENDO2.mid',
    'SEQ_BLD_GAME.mid',
    'SEQ_BLD_LEGEND.mid',
    'SEQ_BLD_TV.mid',
    'SEQ_CITY01_D.mid',
    'SEQ_CITY01_N.mid',
    'SEQ_CITY02_D.mid',
    'SEQ_CITY02_N.mid',
    'SEQ_CITY03_D.mid',
    'SEQ_CITY03_N.mid',
    'SEQ_CITY04_D.mid',
    'SEQ_CITY04_N.mid',
    'SEQ_CITY05_D.mid',
    'SEQ_CITY05_N.mid',
    'SEQ_CITY06_D.mid',
    'SEQ_CITY06_N.mid',
    'SEQ_CITY07_D.mid',
    'SEQ_CITY07_N.mid',
    'SEQ_CITY08_D.mid',
    'SEQ_CITY08_N.mid',
    'SEQ_CITY09_D.mid',
    'SEQ_CITY09_N.mid',
    'SEQ_CITY10_D.mid',
    'SEQ_CITY10_N.mid',
    'SEQ_CITY11_D.mid',
    'SEQ_CITY11_N.mid',
    'SEQ_CO_DRESS.mid',
    'SEQ_CO_FANFA.mid',
    'SEQ_CO_KAKKO.mid',
    'SEQ_CO_KASHI.mid',
    'SEQ_CO_KAWAI.mid',
    'SEQ_CO_KEKKA.mid',
    'CONTEST_DRESSING_ROOM.mid',
    'SEQ_CO_TAKUMA.mid',
    'SEQ_CO_UTSUK.mid',
    'SEQ_D_01.mid',
    'SEQ_D_02.mid',
    'SEQ_D_03.mid',
    'SEQ_D_04.mid',
    'SEQ_D_05.mid',
    'SEQ_D_06.mid',
    'SEQ_D_AGITO.mid',
    'SEQ_D_CROAD.mid',
    'SEQ_D_GINLOBBY.mid',
    'SEQ_D_HARDMT.mid',
    'SEQ_D_ICE.mid',
    'SEQ_D_KOUEN.mid',
    'SEQ_D_LAKE.mid',
    'SEQ_D_LEAGUE.mid',
    'SEQ_D_MOUNT1.mid',
    'SEQ_D_MOUNT2.mid',
    'SEQ_D_RYAYHY.mid',
    'SEQ_D_SAFARI.mid',
    'SEQ_D_SECRET.mid',
    'SEQ_DUMMY.mid',
    'SEQ_D_UNKNOWN.mid',
    'SEQ_EV_DENDO1.mid',
    'SEQ_EV_LEGEND.mid',
    'SEQ_EYE_BOY.mid',
    'SEQ_EYE_CHAMP.mid',
    'SEQ_EYE_ELITE.mid',
    'SEQ_EYE_ENKA.mid',
    'SEQ_EYE_FIGHT.mid',
    'SEQ_EYE_FUN.mid',
    'SEQ_EYE_GINGA.mid',
    'SEQ_EYE_GIRL.mid',
    'SEQ_EYE_KID.mid',
    'SEQ_EYE_LADY.mid',
    'SEQ_EYE_MOUNT.mid',
    'SEQ_EYE_MYS.mid',
    'SEQ_EYE_RICH.mid',
    'SEQ_EYE_SPORT.mid',
    'SEQ_EYE_TENNO.mid',
    'SEQ_FANFA1.mid',
    'SEQ_FANFA2.mid',
    'SEQ_FANFA3.mid',
    'SEQ_FANFA4.mid',
    'SEQ_FANFA5.mid',
    'SEQ_FANFA6.mid',
    'SEQ_FIGHT0101.mid',
    'SEQ_FS.mid',
    'SEQ_FUE.mid',
    'SEQ_GONIN.mid',
    'SEQ_GYM.mid',
    'SEQ_HATANIGE.mid',
    'SEQ_KENKYUJO.mid',
    'SEQ_KINOMI1.mid',
    'SEQ_KINOMI2.mid',
    'SEQ_KINOMI.mid',
    'SEQ_KOUKAN.mid',
    'SEQ_KUSAGASA.mid',
    'SEQ_NAMINORI.mid',
    'SEQ_OPENING.mid',
    'SEQ_PC_01.mid',
    'SEQ_PC_02.mid',
    'SEQ_PL_AUDIO.mid',
    'BATTLE_FRONTIER_BRAIN.mid',
    'BATTLE_GIRATINA.mid',
    'BATTLE_REGI_TRIO.mid',
    'SEQ_PL_BF_CASTLE02.mid',
    'SEQ_PL_BF_CASTLE.mid',
    'SEQ_PL_BF_FACTORY.mid',
    'SEQ_PL_BF_ROULETTE.mid',
    'SEQ_PL_BF_STAGE.mid',
    'SEQ_PL_D_GIRATINA.mid',
    'SE_CONFIRM.mid',
    'SEQ_PL_DON2.mid',
    'SEQ_PL_EV_GIRA2.mid',
    'SEQ_PL_EV_GIRA.mid',
    'SEQ_PL_EYEBRAIN.mid',
    'SEQ_PL_FRO.mid',
    'SEQ_PL_GURUGURU.mid',
    'SEQ_PL_HANDSOME.mid',
    'SEQ_PL_MTKAKKO.mid',
    'SEQ_PL_MTKASHI.mid',
    'SEQ_PL_MTKAWA.mid',
    'SEQ_PL_MTTAKMA.mid',
    'SEQ_PL_MTUTSUK.mid',
    'SEQ_PL_PIANO.mid',
    'SEQ_PL_POINTGET3.mid',
    'SEQ_PL_PTHAIFU.mid',
    'SEQ_PL_TOWN02.mid',
    'SEQ_PL_WIFIGAME.mid',
    'SEQ_PL_WIFIPARADE.mid',
    'SEQ_PL_WIFITOWER.mid',
    'SEQ_PL_WIFIUNION.mid',
    'VICTORY_FRONTIER_BRAIN.mid',
    'SEQ_PL_WINMINI2.mid',
    'SEQ_POCKETCH.mid',
    'SEQ_POKEPARK.mid',
    'SEQ_PRESENT.mid',
    'SEQ_PV001.mid',
    'SEQ_REPORT.mid',
    'SEQ_ROAD_A_D.mid',
    'SEQ_ROAD_A_N.mid',
    'SEQ_ROAD_B_D.mid',
    'SEQ_ROAD_B_N.mid',
    'SEQ_ROAD_BZA_D.mid',
    'SEQ_ROAD_BZA_N.mid',
    'SEQ_ROAD_BZB_D.mid',
    'SEQ_ROAD_BZB_N.mid',
    'SEQ_ROAD_C_D.mid',
    'SEQ_ROAD_C_N.mid',
    'SEQ_ROAD_D_D.mid',
    'SEQ_ROAD_D_N.mid',
    'SEQ_ROAD_E_D.mid',
    'SEQ_ROAD_E_N.mid',
    'SEQ_ROAD_F_D.mid',
    'SEQ_ROAD_F_N.mid',
    'SEQ_ROAD_SNOW_D.mid',
    'SEQ_ROAD_SNOW_N.mid',
    'SEQ_SE_DP_000.mid',
    'SEQ_SE_DP_001.mid',
    'SEQ_SE_DP_003.mid',
    'SEQ_SE_DP_007.mid',
    'SEQ_SE_DP_020.mid',
    'SEQ_SE_DP_021.mid',
    'SEQ_SE_DP_023.mid',
    'SEQ_SE_DP_025.mid',
    'SEQ_SE_DP_030C.mid',
    'SEQ_SE_DP_030.mid',
    'SEQ_SE_DP_031.mid',
    'SEQ_SE_DP_032.mid',
    'SEQ_SE_DP_040.mid',
    'SEQ_SE_DP_041.mid',
    'SEQ_SE_DP_050.mid',
    'SEQ_SE_DP_051.mid',
    'SEQ_SE_DP_052.mid',
    'SEQ_SE_DP_053.mid',
    'SEQ_SE_DP_060.mid',
    'SEQ_SE_DP_061.mid',
    'SEQ_SE_DP_080.mid',
    'SEQ_SE_DP_081.mid',
    'SEQ_SE_DP_100.mid',
    'SEQ_SE_DP_110.mid',
    'SEQ_SE_DP_111.mid',
    'SEQ_SE_DP_112.mid',
    'SEQ_SE_DP_130.mid',
    'SEQ_SE_DP_131.mid',
    'SEQ_SE_DP_140.mid',
    'SEQ_SE_DP_141.mid',
    'SEQ_SE_DP_143.mid',
    'SEQ_SE_DP_145.mid',
    'SEQ_SE_DP_146.mid',
    'SEQ_SE_DP_150.mid',
    'SEQ_SE_DP_151.mid',
    'SEQ_SE_DP_152.mid',
    'SEQ_SE_DP_153.mid',
    'SEQ_SE_DP_154.mid',
    'SEQ_SE_DP_155.mid',
    'SEQ_SE_DP_160.mid',
    'SEQ_SE_DP_161.mid',
    'SEQ_SE_DP_162.mid',
    'SEQ_SE_DP_163.mid',
    'SEQ_SE_DP_164.mid',
    'SEQ_SE_DP_165.mid',
    'SEQ_SE_DP_166.mid',
    'SEQ_SE_DP_170.mid',
    'SEQ_SE_DP_171.mid',
    'SEQ_SE_DP_172.mid',
    'SEQ_SE_DP_180.mid',
    'SEQ_SE_DP_181.mid',
    'SEQ_SE_DP_182.mid',
    'SEQ_SE_DP_183.mid',
    'SEQ_SE_DP_184.mid',
    'SEQ_SE_DP_185.mid',
    'SEQ_SE_DP_186.mid',
    'SEQ_SE_DP_187.mid',
    'SEQ_SE_DP_200.mid',
    'SEQ_SE_DP_201.mid',
    'SEQ_SE_DP_202.mid',
    'SEQ_SE_DP_203.mid',
    'SEQ_SE_DP_204.mid',
    'SEQ_SE_DP_206.mid',
    'SEQ_SE_DP_207.mid',
    'SEQ_SE_DP_208.mid',
    'SEQ_SE_DP_209.mid',
    'SEQ_SE_DP_210.mid',
    'SEQ_SE_DP_211.mid',
    'SEQ_SE_DP_212.mid',
    'SEQ_SE_DP_213.mid',
    'SEQ_SE_DP_214.mid',
    'SEQ_SE_DP_280.mid',
    'SEQ_SE_DP_281.mid',
    'SEQ_SE_DP_282.mid',
    'SEQ_SE_DP_290.mid',
    'SEQ_SE_DP_291.mid',
    'SEQ_SE_DP_293.mid',
    'SEQ_SE_DP_300.mid',
    'SEQ_SE_DP_350.mid',
    'SEQ_SE_DP_351.mid',
    'SEQ_SE_DP_400.mid',
    'SEQ_SE_DP_401.mid',
    'SEQ_SE_DP_402.mid',
    'SEQ_SE_DP_480.mid',
    'SEQ_SE_DP_AWA.mid',
    'SEQ_SE_DP_BADGE_C.mid',
    'SEQ_SE_DP_BAG_004.mid',
    'SEQ_SE_DP_BAG_006.mid',
    'SEQ_SE_DP_BAG_011.mid',
    'SEQ_SE_DP_BAG_020.mid',
    'SEQ_SE_DP_BAG_030.mid',
    'SEQ_SE_DP_BAG_031.mid',
    'SEQ_SE_DP_BAN.mid',
    'SEQ_SE_DP_BASABASA.mid',
    'SEQ_SE_DP_BASI.mid',
    'SEQ_SE_DP_BEEP.mid',
    'SEQ_SE_DP_BFBRADE.mid',
    'SEQ_SE_DP_BOWA3.mid',
    'SEQ_SE_DP_BOWA4.mid',
    'SEQ_SE_DP_BOWA.mid',
    'SEQ_SE_DP_BOX01.mid',
    'SEQ_SE_DP_BOX02.mid',
    'SEQ_SE_DP_BOX03.mid',
    'SEQ_SE_DP_BRADE.mid',
    'SEQ_SE_DP_BT_001.mid',
    'SEQ_SE_DP_BUTTON01.mid',
    'SEQ_SE_DP_BUTTON3.mid',
    'SEQ_SE_DP_BUTTON9.mid',
    'SEQ_SE_DP_CARD10.mid',
    'SEQ_SE_DP_CARD11.mid',
    'SEQ_SE_DP_CARD2.mid',
    'SEQ_SE_DP_CARD3.mid',
    'SEQ_SE_DP_CARD5.mid',
    'SEQ_SE_DP_CARD7.mid',
    'SEQ_SE_DP_CLIMAX01.mid',
    'SEQ_SE_DP_CLIMAX03.mid',
    'SEQ_SE_DP_CLIMAX06.mid',
    'SEQ_SE_DP_CLIMAX09.mid',
    'SEQ_SE_DP_CLIMAX10.mid',
    'SEQ_SE_DP_CLIMAX12.mid',
    'SEQ_SE_DP_CLIMAX15.mid',
    'SEQ_SE_DP_CLOSE2.mid',
    'SEQ_SE_DP_CLOSE7.mid',
    'SEQ_SE_DP_CON_001.mid',
    'SEQ_SE_DP_CON_002.mid',
    'SEQ_SE_DP_CON_003.mid',
    'SEQ_SE_DP_CON_004.mid',
    'SEQ_SE_DP_CON_005.mid',
    'SEQ_SE_DP_CON_006.mid',
    'SEQ_SE_DP_CON_007.mid',
    'SEQ_SE_DP_CON_009.mid',
    'SEQ_SE_DP_CON_010.mid',
    'SEQ_SE_DP_CON_011.mid',
    'SEQ_SE_DP_CON_012.mid',
    'SEQ_SE_DP_CON_013.mid',
    'SEQ_SE_DP_CON_015.mid',
    'SEQ_SE_DP_CON_016.mid',
    'SEQ_SE_DP_CON_017.mid',
    'SEQ_SE_DP_CON_018.mid',
    'SEQ_SE_DP_CON_019.mid',
    'SEQ_SE_DP_CON_020.mid',
    'SEQ_SE_DP_CON_021.mid',
    'SEQ_SE_DP_CON_022.mid',
    'SEQ_SE_DP_CON_023.mid',
    'SEQ_SE_DP_CON_024.mid',
    'SEQ_SE_DP_CON_026.mid',
    'SEQ_SE_DP_CON_027_2.mid',
    'SEQ_SE_DP_CON_027_3.mid',
    'SEQ_SE_DP_CON_028.mid',
    'SEQ_SE_DP_CON_029.mid',
    'SEQ_SE_DP_CON_030.mid',
    'SEQ_SE_DP_CON_031.mid',
    'SEQ_SE_DP_CON_032.mid',
    'SEQ_SE_DP_CON_033.mid',
    'SEQ_SE_DP_CON_F007.mid',
    'SEQ_SE_DP_CUSTOM01.mid',
    'SEQ_SE_DP_CUSTOM02.mid',
    'SEQ_SE_DP_CUSTOM05.mid',
    'SEQ_SE_DP_CUSTOM06.mid',
    'SEQ_SE_DP_DANSA4.mid',
    'SEQ_SE_DP_DANSA.mid',
    'SEQ_SE_DP_DECIDE.mid',
    'SEQ_SE_DP_DENDOU.mid',
    'SEQ_SE_DP_DENSI01.mid',
    'SEQ_SE_DP_DENSI02.mid',
    'SEQ_SE_DP_DENSI04.mid',
    'SEQ_SE_DP_DENSI05.mid',
    'SEQ_SE_DP_DENSI06.mid',
    'SEQ_SE_DP_DENSI07.mid',
    'SEQ_SE_DP_DENSI08.mid',
    'SEQ_SE_DP_DENSI09.mid',
    'SEQ_SE_DP_DENSI10.mid',
    'SEQ_SE_DP_DENSI11.mid',
    'SEQ_SE_DP_DENSI12.mid',
    'SEQ_SE_DP_DENSI15.mid',
    'SEQ_SE_DP_DENSI16.mid',
    'SEQ_SE_DP_DODON.mid',
    'SEQ_SE_DP_DOKU2.mid',
    'SEQ_SE_DP_DOOR10.mid',
    'SEQ_SE_DP_DOOR_CLOSE2.mid',
    'SEQ_SE_DP_DOOR_CLOSE.mid',
    'SEQ_SE_DP_DOOR.mid',
    'SEQ_SE_DP_DOOR_OPEN.mid',
    'SEQ_SE_DP_DORIRU.mid',
    'SEQ_SE_DP_EGG01.mid',
    'SEQ_SE_DP_ELEBETA2.mid',
    'SEQ_SE_DP_ELEBETA4.mid',
    'SEQ_SE_DP_ELEBETA.mid',
    'SEQ_SE_DP_ESUKA.mid',
    'SEQ_SE_DP_EXPMAX2.mid',
    'SEQ_SE_DP_EXPMAX.mid',
    'SEQ_SE_DP_EXP.mid',
    'SEQ_SE_DP_F007.mid',
    'SEQ_SE_DP_F017.mid',
    'SEQ_SE_DP_F209.mid',
    'SEQ_SE_DP_FAWA.mid',
    'SEQ_SE_DP_FBRADE.mid',
    'SEQ_SE_DP_FOOT3_0.mid',
    'SEQ_SE_DP_FOOT3_1.mid',
    'SEQ_SE_DP_FPASA2.mid',
    'SEQ_SE_DP_FW015.mid',
    'SEQ_SE_DP_FW019.mid',
    'SEQ_SE_DP_FW056.mid',
    'SEQ_SE_DP_FW088.mid',
    'SEQ_SE_DP_FW089.mid',
    'SEQ_SE_DP_FW104.mid',
    'SEQ_SE_DP_FW230.mid',
    'SEQ_SE_DP_FW291.mid',
    'SEQ_SE_DP_FW367.mid',
    'SEQ_SE_DP_FW452.mid',
    'SEQ_SE_DP_FW463.mid',
    'SEQ_SE_DP_FW466.mid',
    'SEQ_SE_DP_GAGAGA.mid',
    'SEQ_SE_DP_GASA01.mid',
    'SEQ_SE_DP_GASA02.mid',
    'SEQ_SE_DP_GASA03.mid',
    'SEQ_SE_DP_GASHIN.mid',
    'SEQ_SE_DP_GEAR2.mid',
    'SEQ_SE_DP_GEAR.mid',
    'SEQ_SE_DP_GETTING.mid',
    'SEQ_SE_DP_GYURU.mid',
    'SEQ_SE_DP_HAMARU.mid',
    'SEQ_SE_DP_HINSI.mid',
    'SEQ_SE_DP_HURU2.mid',
    'SEQ_SE_DP_HURU.mid',
    'SEQ_SE_DP_HYUN2.mid',
    'SEQ_SE_DP_HYUN.mid',
    'SEQ_SE_DP_JIHANKI.mid',
    'SEQ_SE_DP_JITENSYA.mid',
    'SEQ_SE_DP_KAIDAN2.mid',
    'SEQ_SE_DP_KAIFUKU.mid',
    'SEQ_SE_DP_KAMI2.mid',
    'SEQ_SE_DP_KAMI.mid',
    'SEQ_SE_DP_KASYA.mid',
    'SEQ_SE_DP_KATI.mid',
    'SEQ_SE_DP_KAZE2.mid',
    'SEQ_SE_DP_KAZE.mid',
    'SEQ_SE_DP_KI_GASYAN.mid',
    'SEQ_SE_DP_KIRAKIRA2.mid',
    'SEQ_SE_DP_KIRAKIRA3.mid',
    'SEQ_SE_DP_KIRAKIRA4.mid',
    'SEQ_SE_DP_KIRAKIRA.mid',
    'SEQ_SE_DP_KIRAN.mid',
    'SEQ_SE_DP_KON2.mid',
    'SEQ_SE_DP_KON3.mid',
    'SEQ_SE_DP_KON4.mid',
    'SEQ_SE_DP_KON.mid',
    'SEQ_SE_DP_KOUKA_H.mid',
    'SEQ_SE_DP_KOUKA_L.mid',
    'SEQ_SE_DP_KOUKA_M.mid',
    'SEQ_SE_DP_KOUKAN01.mid',
    'SEQ_SE_DP_KOUKAN03.mid',
    'SEQ_SE_DP_KOUKAN04.mid',
    'SEQ_SE_DP_KOUKAN05.mid',
    'SEQ_SE_DP_KOUKAN06.mid',
    'SEQ_SE_DP_KOUKAN07.mid',
    'SEQ_SE_DP_KOUKAN08.mid',
    'SEQ_SE_DP_KOUKAN09.mid',
    'SEQ_SE_DP_KOUKAN10.mid',
    'SEQ_SE_DP_KUSA.mid',
    'SEQ_SE_DP_KYU01.mid',
    'SEQ_SE_DP_MARSH_WALK.mid',
    'SEQ_SE_DP_MAZYO2.mid',
    'SEQ_SE_DP_MAZYO3.mid',
    'SEQ_SE_DP_MAZYO4.mid',
    'SEQ_SE_DP_MAZYO.mid',
    'SEQ_SE_DP_MEKURU2.mid',
    'SEQ_SE_DP_MEKURU3.mid',
    'SEQ_SE_DP_MEKURU.mid',
    'SEQ_SE_DP_MIGAKU01.mid',
    'SEQ_SE_DP_MIGAKU02.mid',
    'SEQ_SE_DP_NAGERU.mid',
    'SEQ_SE_DP_NAMEIN_01.mid',
    'SEQ_SE_DP_NAMI.mid',
    'SEQ_SE_DP_NIGERU2.mid',
    'SEQ_SE_DP_NIGERU.mid',
    'SEQ_SE_DP_NM01.mid',
    'SEQ_SE_DP_NM02.mid',
    'SEQ_SE_DP_NM03_2.mid',
    'SEQ_SE_DP_NM03.mid',
    'SEQ_SE_DP_NM04_2.mid',
    'SEQ_SE_DP_NM04_3.mid',
    'SEQ_SE_DP_NM04.mid',
    'SEQ_SE_DP_NM05.mid',
    'SEQ_SE_DP_NM07_2.mid',
    'SEQ_SE_DP_NM07.mid',
    'SEQ_SE_DP_NM08.mid',
    'SEQ_SE_DP_NM09.mid',
    'SEQ_SE_DP_NM10_2.mid',
    'SEQ_SE_DP_NM10.mid',
    'SEQ_SE_DP_NM11.mid',
    'SEQ_SE_DP_NM12_2.mid',
    'SEQ_SE_DP_NM12.mid',
    'SEQ_SE_DP_NM13.mid',
    'SEQ_SE_DP_NM14.mid',
    'SEQ_SE_DP_OPEN2.mid',
    'SEQ_SE_DP_OPEN7.mid',
    'SEQ_SE_DP_PASA2.mid',
    'SEQ_SE_DP_PASA3.mid',
    'SEQ_SE_DP_PASA.mid',
    'SEQ_SE_DP_PASO2.mid',
    'SEQ_SE_DP_PASO.mid',
    'SEQ_SE_DP_PC_LOGIN.mid',
    'SEQ_SE_DP_PC_LOGOFF.mid',
    'SEQ_SE_DP_PC_ON.mid',
    'SEQ_SE_DP_PIKO2.mid',
    'SEQ_SE_DP_PINPON.mid',
    'SEQ_SE_DP_PIRORIRO2.mid',
    'SEQ_SE_DP_PIRORIRO.mid',
    'SEQ_SE_DP_POKE_DEAD3.mid',
    'SEQ_SE_DP_POKELIST_001.mid',
    'SEQ_SE_DP_POKETCH_003.mid',
    'SEQ_SE_DP_POKETCH_006.mid',
    'SEQ_SE_DP_POKETCH_007.mid',
    'SEQ_SE_DP_POKETCH_009.mid',
    'SEQ_SE_DP_POKETCH_010.mid',
    'SEQ_SE_DP_POKETCH_011.mid',
    'SEQ_SE_DP_POKETCH_012.mid',
    'SEQ_SE_DP_POKETCH_013.mid',
    'SEQ_SE_DP_POKETCH_014.mid',
    'SEQ_SE_DP_PYUU2.mid',
    'SEQ_SE_DP_PYUU.mid',
    'SEQ_SE_DP_REAPOKE.mid',
    'SEQ_SE_DP_REGI.mid',
    'SEQ_SE_DP_SAVE.mid',
    'SEQ_SE_DP_SELECT5.mid',
    'SEQ_SE_DP_SELECT78.mid',
    'SEQ_SE_DP_SELECT8.mid',
    'SEQ_SE_DP_SHIP01.mid',
    'SEQ_SE_DP_SHIP02.mid',
    'SEQ_SE_DP_SHIP03.mid',
    'SEQ_SE_DP_SHUSHU.mid',
    'SEQ_SE_DP_SLIDEIN.mid',
    'SEQ_SE_DP_SLOT01.mid',
    'SEQ_SE_DP_SLOT02.mid',
    'SEQ_SE_DP_START.mid',
    'SEQ_SE_DP_SUBERU.mid',
    'SEQ_SE_DP_SUIRYU.mid',
    'SEQ_SE_DP_SUNA.mid',
    'SEQ_SE_DP_SYARAAN.mid',
    'SEQ_SE_DP_SYU01.mid',
    'SEQ_SE_DP_SYU02.mid',
    'SEQ_SE_DP_SYU03.mid',
    'SEQ_SE_DP_T_AME.mid',
    'SEQ_SE_DP_TARARARAN.mid',
    'SEQ_SE_DP_TATA.mid',
    'SE_PARTY_GAUGE_BALL_EMPTY.mid',
    'SE_PARTY_GAUGE_BALL_IN.mid',
    'SE_PARTY_GAUGE_ARROW_IN.mid',
    'SEQ_SE_DP_TELE2.mid',
    'SEQ_SE_DP_TELE.mid',
    'SEQ_SE_DP_T_KAMI2.mid',
    'SEQ_SE_DP_T_KAMI.mid',
    'SEQ_SE_DP_T_KOAME.mid',
    'SEQ_SE_DP_T_OOAME.mid',
    'SEQ_SE_DP_TRAIN02.mid',
    'SEQ_SE_DP_TRAIN03.mid',
    'SEQ_SE_DP_TRAIN04.mid',
    'SEQ_SE_DP_TV_NOISE.mid',
    'SEQ_SE_DP_UG_001.mid',
    'SEQ_SE_DP_UG_002.mid',
    'SEQ_SE_DP_UG_003.mid',
    'SEQ_SE_DP_UG_004.mid',
    'SE_DP_VS_SEEKER_BEEP.mid',
    'SEQ_SE_DP_UG_006.mid',
    'SEQ_SE_DP_UG_007.mid',
    'SEQ_SE_DP_UG_008.mid',
    'SEQ_SE_DP_UG_020.mid',
    'SEQ_SE_DP_UG_021.mid',
    'SEQ_SE_DP_UG_022.mid',
    'SEQ_SE_DP_UG_023.mid',
    'SEQ_SE_DP_UG_024.mid',
    'SEQ_SE_DP_UG_025.mid',
    'SEQ_SE_DP_UG_026.mid',
    'SEQ_SE_DP_UG_027.mid',
    'SEQ_SE_DP_UP.mid',
    'SEQ_SE_DP_VSDEMO01.mid',
    'SEQ_SE_DP_VSDEMO02.mid',
    'SEQ_SE_DP_VSDEMO03.mid',
    'SEQ_SE_DP_VSDEMO04.mid',
    'SEQ_SE_DP_VSDEMO05.mid',
    'SEQ_SE_DP_VSDEMO06.mid',
    'SEQ_SE_DP_VSDEMO07.mid',
    'SEQ_SE_DP_W003.mid',
    'SEQ_SE_DP_W004.mid',
    'SEQ_SE_DP_W006.mid',
    'SEQ_SE_DP_W007.mid',
    'SEQ_SE_DP_W010.mid',
    'SEQ_SE_DP_W011.mid',
    'SEQ_SE_DP_W013B.mid',
    'SEQ_SE_DP_W013.mid',
    'SEQ_SE_DP_W014.mid',
    'SEQ_SE_DP_W015.mid',
    'SEQ_SE_DP_W016B.mid',
    'SEQ_SE_DP_W016.mid',
    'SEQ_SE_DP_W017.mid',
    'SEQ_SE_DP_W019.mid',
    'SEQ_SE_DP_W020B.mid',
    'SEQ_SE_DP_W020.mid',
    'SEQ_SE_DP_W025B.mid',
    'SEQ_SE_DP_W025C.mid',
    'SEQ_SE_DP_W025.mid',
    'SEQ_SE_DP_W026.mid',
    'SEQ_SE_DP_W028B.mid',
    'SEQ_SE_DP_W028.mid',
    'SEQ_SE_DP_W029.mid',
    'SEQ_SE_DP_W030.mid',
    'SEQ_SE_DP_W036.mid',
    'SEQ_SE_DP_W039.mid',
    'SEQ_SE_DP_W040.mid',
    'SEQ_SE_DP_W043B.mid',
    'SEQ_SE_DP_W043C.mid',
    'SEQ_SE_DP_W043D.mid',
    'SEQ_SE_DP_W043.mid',
    'SEQ_SE_DP_W044.mid',
    'SEQ_SE_DP_W047.mid',
    'SEQ_SE_DP_W048.mid',
    'SEQ_SE_DP_W052.mid',
    'SEQ_SE_DP_W053B.mid',
    'SEQ_SE_DP_W053.mid',
    'SEQ_SE_DP_W054.mid',
    'SEQ_SE_DP_W055.mid',
    'SEQ_SE_DP_W056B.mid',
    'SEQ_SE_DP_W056.mid',
    'SEQ_SE_DP_W057B.mid',
    'SEQ_SE_DP_W057.mid',
    'SEQ_SE_DP_W059B.mid',
    'SEQ_SE_DP_W059.mid',
    'SEQ_SE_DP_W060B.mid',
    'SEQ_SE_DP_W060C.mid',
    'SEQ_SE_DP_W060.mid',
    'SEQ_SE_DP_W062D.mid',
    'SEQ_SE_DP_W062.mid',
    'SEQ_SE_DP_W063B.mid',
    'SEQ_SE_DP_W063C.mid',
    'SEQ_SE_DP_W063.mid',
    'SEQ_SE_DP_W070.mid',
    'SEQ_SE_DP_W071B.mid',
    'SEQ_SE_DP_W071.mid',
    'SEQ_SE_DP_W076B.mid',
    'SEQ_SE_DP_W076.mid',
    'SEQ_SE_DP_W077B.mid',
    'SEQ_SE_DP_W077.mid',
    'SEQ_SE_DP_W080B.mid',
    'SEQ_SE_DP_W080C.mid',
    'SEQ_SE_DP_W080.mid',
    'SEQ_SE_DP_W081B.mid',
    'SEQ_SE_DP_W081.mid',
    'SEQ_SE_DP_W082B.mid',
    'SEQ_SE_DP_W082C.mid',
    'SEQ_SE_DP_W082.mid',
    'SEQ_SE_DP_W085B.mid',
    'SEQ_SE_DP_W085C.mid',
    'SEQ_SE_DP_W085.mid',
    'SEQ_SE_DP_W086.mid',
    'SEQ_SE_DP_W088.mid',
    'SEQ_SE_DP_W089B.mid',
    'SEQ_SE_DP_W089.mid',
    'SEQ_SE_DP_W090.mid',
    'SEQ_SE_DP_W091.mid',
    'SEQ_SE_DP_W092B.mid',
    'SEQ_SE_DP_W092D.mid',
    'SEQ_SE_DP_W092.mid',
    'SEQ_SE_DP_W100B.mid',
    'SEQ_SE_DP_W103.mid',
    'SEQ_SE_DP_W104.mid',
    'SEQ_SE_DP_W107.mid',
    'SEQ_SE_DP_W109B.mid',
    'SEQ_SE_DP_W109.mid',
    'SEQ_SE_DP_W112B.mid',
    'SEQ_SE_DP_W112.mid',
    'SEQ_SE_DP_W114.mid',
    'SEQ_SE_DP_W115.mid',
    'SEQ_SE_DP_W118B.mid',
    'SEQ_SE_DP_W118.mid',
    'SEQ_SE_DP_W120.mid',
    'SEQ_SE_DP_W122.mid',
    'SEQ_SE_DP_W127.mid',
    'SEQ_SE_DP_W129.mid',
    'SEQ_SE_DP_W145B.mid',
    'SEQ_SE_DP_W145C.mid',
    'SEQ_SE_DP_W145D.mid',
    'SEQ_SE_DP_W145.mid',
    'SEQ_SE_DP_W146.mid',
    'SEQ_SE_DP_W151.mid',
    'SEQ_SE_DP_W152.mid',
    'SEQ_SE_DP_W153.mid',
    'SEQ_SE_DP_W155.mid',
    'SEQ_SE_DP_W161B.mid',
    'SEQ_SE_DP_W161.mid',
    'SEQ_SE_DP_W166.mid',
    'SEQ_SE_DP_W171.mid',
    'SEQ_SE_DP_W172B.mid',
    'SEQ_SE_DP_W172.mid',
    'SEQ_SE_DP_W173B.mid',
    'SEQ_SE_DP_W173C.mid',
    'SEQ_SE_DP_W173.mid',
    'SEQ_SE_DP_W179.mid',
    'SEQ_SE_DP_W185.mid',
    'SEQ_SE_DP_W187.mid',
    'SEQ_SE_DP_W195.mid',
    'SEQ_SE_DP_W196.mid',
    'SEQ_SE_DP_W197.mid',
    'SEQ_SE_DP_W199.mid',
    'SEQ_SE_DP_W201.mid',
    'SEQ_SE_DP_W202B.mid',
    'SEQ_SE_DP_W202.mid',
    'SEQ_SE_DP_W204.mid',
    'SEQ_SE_DP_W207B.mid',
    'SEQ_SE_DP_W207C.mid',
    'SEQ_SE_DP_W207D.mid',
    'SEQ_SE_DP_W207.mid',
    'SEQ_SE_DP_W208.mid',
    'SEQ_SE_DP_W209.mid',
    'SEQ_SE_DP_W213.mid',
    'SEQ_SE_DP_W215.mid',
    'SEQ_SE_DP_W221B.mid',
    'SEQ_SE_DP_W227B.mid',
    'SEQ_SE_DP_W227.mid',
    'SEQ_SE_DP_W230.mid',
    'SEQ_SE_DP_W231.mid',
    'SEQ_SE_DP_W233B.mid',
    'SEQ_SE_DP_W233.mid',
    'SEQ_SE_DP_W234.mid',
    'SEQ_SE_DP_W236.mid',
    'SEQ_SE_DP_W239.mid',
    'SEQ_SE_DP_W240.mid',
    'SEQ_SE_DP_W250.mid',
    'SEQ_SE_DP_W253.mid',
    'SEQ_SE_DP_W255B.mid',
    'SEQ_SE_DP_W255E.mid',
    'SEQ_SE_DP_W255F.mid',
    'SEQ_SE_DP_W255.mid',
    'SEQ_SE_DP_W257.mid',
    'SEQ_SE_DP_W258.mid',
    'SEQ_SE_DP_W260.mid',
    'SEQ_SE_DP_W278.mid',
    'SEQ_SE_DP_W280B.mid',
    'SEQ_SE_DP_W280.mid',
    'SEQ_SE_DP_W281.mid',
    'SEQ_SE_DP_W287B.mid',
    'SEQ_SE_DP_W287.mid',
    'SEQ_SE_DP_W291.mid',
    'SEQ_SE_DP_W298.mid',
    'SEQ_SE_DP_W320.mid',
    'SEQ_SE_DP_W322.mid',
    'SEQ_SE_DP_W327.mid',
    'SEQ_SE_DP_W356.mid',
    'SEQ_SE_DP_W360B.mid',
    'SEQ_SE_DP_W360C.mid',
    'SEQ_SE_DP_W360.mid',
    'SEQ_SE_DP_W361.mid',
    'SEQ_SE_DP_W362.mid',
    'SEQ_SE_DP_W367.mid',
    'SEQ_SE_DP_W368.mid',
    'SEQ_SE_DP_W373.mid',
    'SEQ_SE_DP_W374.mid',
    'SEQ_SE_DP_W375.mid',
    'SEQ_SE_DP_W376B.mid',
    'SEQ_SE_DP_W376.mid',
    'SEQ_SE_DP_W377.mid',
    'SEQ_SE_DP_W380.mid',
    'SEQ_SE_DP_W381.mid',
    'SEQ_SE_DP_W383.mid',
    'SEQ_SE_DP_W387.mid',
    'SEQ_SE_DP_W392.mid',
    'SEQ_SE_DP_W399.mid',
    'SEQ_SE_DP_W405.mid',
    'SEQ_SE_DP_W408.mid',
    'SEQ_SE_DP_W411.mid',
    'SEQ_SE_DP_W412.mid',
    'SEQ_SE_DP_W413.mid',
    'SEQ_SE_DP_W419.mid',
    'SEQ_SE_DP_W426.mid',
    'SEQ_SE_DP_W428.mid',
    'SEQ_SE_DP_W434.mid',
    'SEQ_SE_DP_W436.mid',
    'SEQ_SE_DP_W443B.mid',
    'SEQ_SE_DP_W452.mid',
    'SEQ_SE_DP_W456.mid',
    'SEQ_SE_DP_W459.mid',
    'SEQ_SE_DP_W461.mid',
    'SEQ_SE_DP_W462.mid',
    'SEQ_SE_DP_W463.mid',
    'SEQ_SE_DP_W464.mid',
    'SEQ_SE_DP_W465.mid',
    'SEQ_SE_DP_W466.mid',
    'SEQ_SE_DP_W467.mid',
    'SEQ_SE_DP_WALL_HIT2.mid',
    'SEQ_SE_DP_WALL_HIT.mid',
    'SEQ_SE_DP_WIN_OPEN2.mid',
    'SEQ_SE_DP_WIN_OPEN.mid',
    'SEQ_SE_DP_YUKIASHI.mid',
    'SEQ_SE_DP_ZIZIZI.mid',
    'SEQ_SE_DP_Z_SEARCH.mid',
    'SEQ_SE_DP_ZUKAN01.mid',
    'SEQ_SE_DP_ZUKAN02.mid',
    'SEQ_SE_DP_ZUPO2.mid',
    'SEQ_SE_DP_ZUPO.mid',
    'SEQ_SE_PL_140_2_2.mid',
    'SEQ_SE_PL_140_2.mid',
    'SEQ_SE_PL_140_3.mid',
    'SEQ_SE_PL_140.mid',
    'SEQ_SE_PL_ALERT3.mid',
    'SEQ_SE_PL_ALERT4.mid',
    'SEQ_SE_PL_ALERT.mid',
    'SEQ_SE_PL_BAG3.mid',
    'SEQ_SE_PL_BALLOON01.mid',
    'SEQ_SE_PL_BALLOON02.mid',
    'SEQ_SE_PL_BALLOON03_2.mid',
    'SEQ_SE_PL_BALLOON03.mid',
    'SEQ_SE_PL_BALLOON04.mid',
    'SEQ_SE_PL_BALLOON05_2.mid',
    'SEQ_SE_PL_BALLOON05.mid',
    'SEQ_SE_PL_BALLOON07.mid',
    'SEQ_SE_PL_BOWABOWA.mid',
    'SEQ_SE_PL_BREC03.mid',
    'SEQ_SE_PL_BREC10.mid',
    'SEQ_SE_PL_BREC11_2.mid',
    'SEQ_SE_PL_BREC11.mid',
    'SEQ_SE_PL_BREC12.mid',
    'SEQ_SE_PL_BREC13.mid',
    'SEQ_SE_PL_BREC20.mid',
    'SEQ_SE_PL_BREC21.mid',
    'SEQ_SE_PL_BREC57.mid',
    'SEQ_SE_PL_BREC58.mid',
    'SEQ_SE_PL_BREC80.mid',
    'SEQ_SE_PL_BUTTON.mid',
    'SEQ_SE_PL_CALL.mid',
    'SEQ_SE_PL_COIN.mid',
    'SEQ_SE_PL_CON_034.mid',
    'SEQ_SE_PL_CPGET.mid',
    'SEQ_SE_PL_DANSA5.mid',
    'SEQ_SE_PL_DOOR_OPEN5.mid',
    'SEQ_SE_PL_EFF02.mid',
    'SEQ_SE_PL_EFF03_3.mid',
    'SEQ_SE_PL_EFF03_4.mid',
    'SEQ_SE_PL_EFF03.mid',
    'SEQ_SE_PL_EFF04.mid',
    'SEQ_SE_PL_EFF05.mid',
    'SEQ_SE_PL_ELECTRO.mid',
    'SEQ_SE_PL_FAC01.mid',
    'SEQ_SE_PL_FCALL.mid',
    'SEQ_SE_PL_fire01.mid',
    'SEQ_SE_PL_FIRE.mid',
    'SEQ_SE_PL_FLOAT01.mid',
    'SEQ_SE_PL_FLOAT02.mid',
    'SEQ_SE_PL_FLOAT03.mid',
    'SEQ_SE_PL_FLOAT04.mid',
    'SEQ_SE_PL_FLOAT05.mid',
    'SEQ_SE_PL_FLOAT06.mid',
    'SEQ_SE_PL_FLOAT07.mid',
    'SEQ_SE_PL_FLOAT10.mid',
    'SEQ_SE_PL_FLOAT11.mid',
    'SEQ_SE_PL_FLOAT12.mid',
    'SEQ_SE_PL_FLOAT13.mid',
    'SEQ_SE_PL_FR02.mid',
    'SEQ_SE_PL_FR03.mid',
    'SEQ_SE_PL_FR04.mid',
    'SEQ_SE_PL_FR05.mid',
    'SEQ_SE_PL_FW089_2.mid',
    'SEQ_SE_PL_FW089B.mid',
    'SEQ_SE_PL_FW089.mid',
    'SEQ_SE_PL_FW120.mid',
    'SEQ_SE_PL_FW463.mid',
    'SEQ_SE_PL_GIRA.mid',
    'SEQ_SE_PL_GYM01.mid',
    'SEQ_SE_PL_GYM02.mid',
    'SEQ_SE_PL_HAND.mid',
    'SEQ_SE_PL_HIROBA01_4.mid',
    'SEQ_SE_PL_HIROBA01_5.mid',
    'SEQ_SE_PL_HIROBA01_6.mid',
    'SEQ_SE_PL_HIROBA02_4.mid',
    'SEQ_SE_PL_HIROBA02_5.mid',
    'SEQ_SE_PL_HIROBA02_6.mid',
    'SEQ_SE_PL_HIROBA03_2.mid',
    'SEQ_SE_PL_HIROBA03_3.mid',
    'SEQ_SE_PL_HIROBA03.mid',
    'SEQ_SE_PL_HIROBA05_2.mid',
    'SEQ_SE_PL_HIROBA05_3.mid',
    'SEQ_SE_PL_HIROBA05.mid',
    'SEQ_SE_PL_HIROBA100_2.mid',
    'SEQ_SE_PL_HIROBA100_3.mid',
    'SEQ_SE_PL_HIROBA100.mid',
    'SEQ_SE_PL_HIROBA20.mid',
    'SEQ_SE_PL_HIROBA30.mid',
    'SEQ_SE_PL_HIROBA70_2.mid',
    'SEQ_SE_PL_HIROBA70_3.mid',
    'SEQ_SE_PL_HIROBA70.mid',
    'SEQ_SE_PL_HIROBA80.mid',
    'SEQ_SE_PL_HIROBA85.mid',
    'SEQ_SE_PL_HIROBA90.mid',
    'SEQ_SE_PL_JUMP2.mid',
    'SEQ_SE_PL_KEZURI.mid',
    'SEQ_SE_PL_KIN.mid',
    'SEQ_SE_PL_KIRAKIRA4.mid',
    'SEQ_SE_PL_KIRAKIRA.mid',
    'SEQ_SE_PL_KUSARI.mid',
    'SEQ_SE_PL_LO_ON.mid',
    'SEQ_SE_PL_LV_UP.mid',
    'SEQ_SE_PL_MEKI2.mid',
    'SEQ_SE_PL_MEKI.mid',
    'SEQ_SE_PL_MNGM_IN.mid',
    'SEQ_SE_PL_MNGM_OUT.mid',
    'SEQ_SE_PL_NOMI02.mid',
    'SEQ_SE_PL_PINPON2.mid',
    'SEQ_SE_PL_PINPON.mid',
    'SEQ_SE_PL_POINT1.mid',
    'SEQ_SE_PL_POINT2.mid',
    'SEQ_SE_PL_POINT3.mid',
    'SEQ_SE_PL_STAMP.mid',
    'SEQ_SE_PL_SUTYA2.mid',
    'SEQ_SE_PL_SYU03.mid',
    'SEQ_SE_PL_SYUWA2.mid',
    'SEQ_SE_PL_SYUWA3.mid',
    'SEQ_SE_PL_SYUWA.mid',
    'SEQ_SE_PL_TIMER01.mid',
    'SEQ_SE_PL_TIMER02.mid',
    'SEQ_SE_PL_TIMER03.mid',
    'SEQ_SE_PL_TIMER04.mid',
    'SEQ_SE_PL_TOKEI21.mid',
    'SEQ_SE_PL_TOKEI3.mid',
    'SEQ_SE_PL_UG_006.mid',
    'SEQ_SE_PL_UG_020.mid',
    'SEQ_SE_PL_W012.mid',
    'SEQ_SE_PL_W019_2.mid',
    'SEQ_SE_PL_W019_3.mid',
    'SEQ_SE_PL_W019.mid',
    'SEQ_SE_PL_W030_2.mid',
    'SEQ_SE_PL_W030_3.mid',
    'SEQ_SE_PL_W030.mid',
    'SEQ_SE_PL_W060.mid',
    'SEQ_SE_PL_W082C.mid',
    'SEQ_SE_PL_W097.mid',
    'SEQ_SE_PL_W100.mid',
    'SEQ_SE_PL_W363.mid',
    'SEQ_SE_PL_W392.mid',
    'SEQ_SE_PL_W436.mid',
    'SEQ_SE_PL_W460B.mid',
    'SEQ_SE_PL_W467109.mid',
    'SEQ_SE_PL_W467.mid',
    'SEQ_SE_PL_WARP.mid',
    'SEQ_SE_PL_WATER.mid',
    'SEQ_SE_PL_WHIP.mid',
    'SEQ_SE_PL_YUKI.mid',
    'SEQ_SHINKA.mid',
    'SEQ_SILENCE_FIELD.mid',
    'SEQ_SLOT_ATARI.mid',
    'SEQ_SLOT.mid',
    'SEQ_SLOT_OOATARI.mid',
    'SEQ_TANKOU.mid',
    'SEQ_TEST_TITLE.mid',
    'SEQ_THE_AKAGI.mid',
    'SEQ_THE_BOY.mid',
    'SEQ_THE_EVENT01.mid',
    'SEQ_THE_EVENT02.mid',
    'SEQ_THE_EVENT03.mid',
    'SEQ_THE_EVENT04.mid',
    'SEQ_THE_EVENT05.mid',
    'SEQ_THE_GIRL.mid',
    'SEQ_THE_RIV.mid',
    'SEQ_TITLE00.mid',
    'SEQ_TITLE01.mid',
    'SEQ_TOWN01_D.mid',
    'SEQ_TOWN01_N.mid',
    'SEQ_TOWN02_D.mid',
    'SEQ_TOWN02_N.mid',
    'SEQ_TOWN03_D.mid',
    'SEQ_TOWN03_N.mid',
    'SEQ_TOWN04_D.mid',
    'SEQ_TOWN04_N.mid',
    'SEQ_TOWN05_D.mid',
    'SEQ_TOWN05_N.mid',
    'SEQ_TOWN06_D.mid',
    'SEQ_TOWN06_N.mid',
    'SEQ_TOWN07_D.mid',
    'SEQ_TOWN07_N.mid',
    'SEQ_TSURETEKE.mid',
    'SEQ_TV_END.mid',
    'SEQ_TV_HOUSOU.mid',
    'SEQ_WASURE.mid',
    'SEQ_WAZA.mid',
    'SEQ_WIFILOBBY.mid',
    'VICTORY_CYRUS.mid',
    'VICTORY_CHAMPION.mid',
    'VICTORY_GALACTIC_GRUNT.mid',
    'VICTORY_WILD_POKEMON.mid',
    'VICTORY_ELITE_FOUR.mid',
    'VICTORY_GYM_LEADER.mid',
    'VICTORY_TRAINER.mid',
])
