#ifndef POKEPLATINUM_CONSTANTS_GBA_GLOBAL_H
#define POKEPLATINUM_CONSTANTS_GBA_GLOBAL_H

#define GBA_TRAINER_ID_LEN  4
#define GBA_PLAYER_NAME_LEN 7
#define GBA_MON_NAME_LEN    10

#endif // POKEPLATINUM_CONSTANTS_GBA_GLOBAL_H
