#ifndef POKEPLATINUM_CONSTANTS_GBA_ITEMS_H
#define POKEPLATINUM_CONSTANTS_GBA_ITEMS_H

#define GBA_ITEM_MASTER_BALL   1
#define GBA_ITEM_ULTRA_BALL    2
#define GBA_ITEM_GREAT_BALL    3
#define GBA_ITEM_POKE_BALL     4
#define GBA_ITEM_SAFARI_BALL   5
#define GBA_ITEM_NET_BALL      6
#define GBA_ITEM_DIVE_BALL     7
#define GBA_ITEM_NEST_BALL     8
#define GBA_ITEM_REPEAT_BALL   9
#define GBA_ITEM_TIMER_BALL    10
#define GBA_ITEM_LUXURY_BALL   11
#define GBA_ITEM_PREMIER_BALL  12
#define GBA_ITEM_POTION        13
#define GBA_ITEM_ANTIDOTE      14
#define GBA_ITEM_BURN_HEAL     15
#define GBA_ITEM_ICE_HEAL      16
#define GBA_ITEM_AWAKENING     17
#define GBA_ITEM_PARALYZE_HEAL 18
#define GBA_ITEM_FULL_RESTORE  19
#define GBA_ITEM_MAX_POTION    20
#define GBA_ITEM_HYPER_POTION  21
#define GBA_ITEM_SUPER_POTION  22
#define GBA_ITEM_FULL_HEAL     23
#define GBA_ITEM_REVIVE        24
#define GBA_ITEM_MAX_REVIVE    25
#define GBA_ITEM_FRESH_WATER   26
#define GBA_ITEM_SODA_POP      27
#define GBA_ITEM_LEMONADE      28
#define GBA_ITEM_MOOMOO_MILK   29
#define GBA_ITEM_ENERGY_POWDER 30
#define GBA_ITEM_ENERGY_ROOT   31
#define GBA_ITEM_HEAL_POWDER   32
#define GBA_ITEM_REVIVAL_HERB  33
#define GBA_ITEM_ETHER         34
#define GBA_ITEM_MAX_ETHER     35
#define GBA_ITEM_ELIXIR        36
#define GBA_ITEM_MAX_ELIXIR    37
#define GBA_ITEM_LAVA_COOKIE   38
#define GBA_ITEM_BLUE_FLUTE    39
#define GBA_ITEM_YELLOW_FLUTE  40
#define GBA_ITEM_RED_FLUTE     41
#define GBA_ITEM_BLACK_FLUTE   42
#define GBA_ITEM_WHITE_FLUTE   43
#define GBA_ITEM_BERRY_JUICE   44
#define GBA_ITEM_SACRED_ASH    45
#define GBA_ITEM_SHOAL_SALT    46
#define GBA_ITEM_SHOAL_SHELL   47
#define GBA_ITEM_RED_SHARD     48
#define GBA_ITEM_BLUE_SHARD    49
#define GBA_ITEM_YELLOW_SHARD  50
#define GBA_ITEM_GREEN_SHARD   51
#define GBA_ITEM_034           52
#define GBA_ITEM_035           53
#define GBA_ITEM_036           54
#define GBA_ITEM_037           55
#define GBA_ITEM_038           56
#define GBA_ITEM_039           57
#define GBA_ITEM_03A           58
#define GBA_ITEM_03B           59
#define GBA_ITEM_03C           60
#define GBA_ITEM_03D           61
#define GBA_ITEM_03E           62
#define GBA_ITEM_HP_UP         63
#define GBA_ITEM_PROTEIN       64
#define GBA_ITEM_IRON          65
#define GBA_ITEM_CARBOS        66
#define GBA_ITEM_CALCIUM       67
#define GBA_ITEM_RARE_CANDY    68
#define GBA_ITEM_PP_UP         69
#define GBA_ITEM_ZINC          70
#define GBA_ITEM_PP_MAX        71
#define GBA_ITEM_048           72
#define GBA_ITEM_GUARD_SPEC    73
#define GBA_ITEM_DIRE_HIT      74
#define GBA_ITEM_X_ATTACK      75
#define GBA_ITEM_X_DEFEND      76
#define GBA_ITEM_X_SPEED       77
#define GBA_ITEM_X_ACCURACY    78
#define GBA_ITEM_X_SPECIAL     79
#define GBA_ITEM_POKE_DOLL     80
#define GBA_ITEM_FLUFFY_TAIL   81
#define GBA_ITEM_052           82
#define GBA_ITEM_SUPER_REPEL   83
#define GBA_ITEM_MAX_REPEL     84
#define GBA_ITEM_ESCAPE_ROPE   85
#define GBA_ITEM_REPEL         86
#define GBA_ITEM_057           87
#define GBA_ITEM_058           88
#define GBA_ITEM_059           89
#define GBA_ITEM_05A           90
#define GBA_ITEM_05B           91
#define GBA_ITEM_05C           92
#define GBA_ITEM_SUN_STONE     93
#define GBA_ITEM_MOON_STONE    94
#define GBA_ITEM_FIRE_STONE    95
#define GBA_ITEM_THUNDER_STONE 96
#define GBA_ITEM_WATER_STONE   97
#define GBA_ITEM_LEAF_STONE    98
#define GBA_ITEM_063           99
#define GBA_ITEM_064           100
#define GBA_ITEM_065           101
#define GBA_ITEM_066           102
#define GBA_ITEM_TINY_MUSHROOM 103
#define GBA_ITEM_BIG_MUSHROOM  104
#define GBA_ITEM_069           105
#define GBA_ITEM_PEARL         106
#define GBA_ITEM_BIG_PEARL     107
#define GBA_ITEM_STARDUST      108
#define GBA_ITEM_STAR_PIECE    109
#define GBA_ITEM_NUGGET        110
#define GBA_ITEM_HEART_SCALE   111
#define GBA_ITEM_070           112
#define GBA_ITEM_071           113
#define GBA_ITEM_072           114
#define GBA_ITEM_073           115
#define GBA_ITEM_074           116
#define GBA_ITEM_075           117
#define GBA_ITEM_076           118
#define GBA_ITEM_077           119
#define GBA_ITEM_078           120
#define GBA_ITEM_ORANGE_MAIL   121
#define GBA_ITEM_HARBOR_MAIL   122
#define GBA_ITEM_GLITTER_MAIL  123
#define GBA_ITEM_MECH_MAIL     124
#define GBA_ITEM_WOOD_MAIL     125
#define GBA_ITEM_WAVE_MAIL     126
#define GBA_ITEM_BEAD_MAIL     127
#define GBA_ITEM_SHADOW_MAIL   128
#define GBA_ITEM_TROPIC_MAIL   129
#define GBA_ITEM_DREAM_MAIL    130
#define GBA_ITEM_FAB_MAIL      131
#define GBA_ITEM_RETRO_MAIL    132
#define GBA_ITEM_CHERI_BERRY   133
#define GBA_ITEM_CHESTO_BERRY  134
#define GBA_ITEM_PECHA_BERRY   135
#define GBA_ITEM_RAWST_BERRY   136
#define GBA_ITEM_ASPEAR_BERRY  137
#define GBA_ITEM_LEPPA_BERRY   138
#define GBA_ITEM_ORAN_BERRY    139
#define GBA_ITEM_PERSIM_BERRY  140
#define GBA_ITEM_LUM_BERRY     141
#define GBA_ITEM_SITRUS_BERRY  142
#define GBA_ITEM_FIGY_BERRY    143
#define GBA_ITEM_WIKI_BERRY    144
#define GBA_ITEM_MAGO_BERRY    145
#define GBA_ITEM_AGUAV_BERRY   146
#define GBA_ITEM_IAPAPA_BERRY  147
#define GBA_ITEM_RAZZ_BERRY    148
#define GBA_ITEM_BLUK_BERRY    149
#define GBA_ITEM_NANAB_BERRY   150
#define GBA_ITEM_WEPEAR_BERRY  151
#define GBA_ITEM_PINAP_BERRY   152
#define GBA_ITEM_POMEG_BERRY   153
#define GBA_ITEM_KELPSY_BERRY  154
#define GBA_ITEM_QUALOT_BERRY  155
#define GBA_ITEM_HONDEW_BERRY  156
#define GBA_ITEM_GREPA_BERRY   157
#define GBA_ITEM_TAMATO_BERRY  158
#define GBA_ITEM_CORNN_BERRY   159
#define GBA_ITEM_MAGOST_BERRY  160
#define GBA_ITEM_RABUTA_BERRY  161
#define GBA_ITEM_NOMEL_BERRY   162
#define GBA_ITEM_SPELON_BERRY  163
#define GBA_ITEM_PAMTRE_BERRY  164
#define GBA_ITEM_WATMEL_BERRY  165
#define GBA_ITEM_DURIN_BERRY   166
#define GBA_ITEM_BELUE_BERRY   167
#define GBA_ITEM_LIECHI_BERRY  168
#define GBA_ITEM_GANLON_BERRY  169
#define GBA_ITEM_SALAC_BERRY   170
#define GBA_ITEM_PETAYA_BERRY  171
#define GBA_ITEM_APICOT_BERRY  172
#define GBA_ITEM_LANSAT_BERRY  173
#define GBA_ITEM_STARF_BERRY   174
#define GBA_ITEM_ENIGMA_BERRY  175

#define GBA_ITEM_UNUSED_BERRY_1 176
#define GBA_ITEM_UNUSED_BERRY_2 177
#define GBA_ITEM_UNUSED_BERRY_3 178
#define GBA_ITEM_BRIGHT_POWDER  179
#define GBA_ITEM_WHITE_HERB     180
#define GBA_ITEM_MACHO_BRACE    181
#define GBA_ITEM_EXP_SHARE      182
#define GBA_ITEM_QUICK_CLAW     183
#define GBA_ITEM_SOOTHE_BELL    184
#define GBA_ITEM_MENTAL_HERB    185
#define GBA_ITEM_CHOICE_BAND    186
#define GBA_ITEM_KINGS_ROCK     187
#define GBA_ITEM_SILVER_POWDER  188
#define GBA_ITEM_AMULET_COIN    189
#define GBA_ITEM_CLEANSE_TAG    190
#define GBA_ITEM_SOUL_DEW       191
#define GBA_ITEM_DEEP_SEA_TOOTH 192
#define GBA_ITEM_DEEP_SEA_SCALE 193
#define GBA_ITEM_SMOKE_BALL     194
#define GBA_ITEM_EVERSTONE      195
#define GBA_ITEM_FOCUS_BAND     196
#define GBA_ITEM_LUCKY_EGG      197
#define GBA_ITEM_SCOPE_LENS     198
#define GBA_ITEM_METAL_COAT     199
#define GBA_ITEM_LEFTOVERS      200
#define GBA_ITEM_DRAGON_SCALE   201
#define GBA_ITEM_LIGHT_BALL     202
#define GBA_ITEM_SOFT_SAND      203
#define GBA_ITEM_HARD_STONE     204
#define GBA_ITEM_MIRACLE_SEED   205
#define GBA_ITEM_BLACK_GLASSES  206
#define GBA_ITEM_BLACK_BELT     207
#define GBA_ITEM_MAGNET         208
#define GBA_ITEM_MYSTIC_WATER   209
#define GBA_ITEM_SHARP_BEAK     210
#define GBA_ITEM_POISON_BARB    211
#define GBA_ITEM_NEVER_MELT_ICE 212
#define GBA_ITEM_SPELL_TAG      213
#define GBA_ITEM_TWISTED_SPOON  214
#define GBA_ITEM_CHARCOAL       215
#define GBA_ITEM_DRAGON_FANG    216
#define GBA_ITEM_SILK_SCARF     217
#define GBA_ITEM_UP_GRADE       218
#define GBA_ITEM_SHELL_BELL     219
#define GBA_ITEM_SEA_INCENSE    220
#define GBA_ITEM_LAX_INCENSE    221
#define GBA_ITEM_LUCKY_PUNCH    222
#define GBA_ITEM_METAL_POWDER   223
#define GBA_ITEM_THICK_CLUB     224
#define GBA_ITEM_STICK          225
#define GBA_ITEM_0E2            226
#define GBA_ITEM_0E3            227
#define GBA_ITEM_0E4            228
#define GBA_ITEM_0E5            229
#define GBA_ITEM_0E6            230
#define GBA_ITEM_0E7            231
#define GBA_ITEM_0E8            232
#define GBA_ITEM_0E9            233
#define GBA_ITEM_0EA            234
#define GBA_ITEM_0EB            235
#define GBA_ITEM_0EC            236
#define GBA_ITEM_0ED            237
#define GBA_ITEM_0EE            238
#define GBA_ITEM_0EF            239
#define GBA_ITEM_0F0            240
#define GBA_ITEM_0F1            241
#define GBA_ITEM_0F2            242
#define GBA_ITEM_0F3            243
#define GBA_ITEM_0F4            244
#define GBA_ITEM_0F5            245
#define GBA_ITEM_0F6            246
#define GBA_ITEM_0F7            247
#define GBA_ITEM_0F8            248
#define GBA_ITEM_0F9            249
#define GBA_ITEM_0FA            250
#define GBA_ITEM_0FB            251
#define GBA_ITEM_0FC            252
#define GBA_ITEM_0FD            253
#define GBA_ITEM_RED_SCARF      254
#define GBA_ITEM_BLUE_SCARF     255
#define GBA_ITEM_PINK_SCARF     256
#define GBA_ITEM_GREEN_SCARF    257
#define GBA_ITEM_YELLOW_SCARF   258
#define GBA_ITEM_MACH_BIKE      259
#define GBA_ITEM_COIN_CASE      260
#define GBA_ITEM_ITEMFINDER     261
#define GBA_ITEM_OLD_ROD        262
#define GBA_ITEM_GOOD_ROD       263
#define GBA_ITEM_SUPER_ROD      264
#define GBA_ITEM_SS_TICKET      265
#define GBA_ITEM_CONTEST_PASS   266
#define GBA_ITEM_10B            267
#define GBA_ITEM_WAILMER_PAIL   268
#define GBA_ITEM_DEVON_GOODS    269
#define GBA_ITEM_SOOT_SACK      270
#define GBA_ITEM_BASEMENT_KEY   271
#define GBA_ITEM_ACRO_BIKE      272
#define GBA_ITEM_POKEBLOCK_CASE 273
#define GBA_ITEM_LETTER         274
#define GBA_ITEM_EON_TICKET     275
#define GBA_ITEM_RED_ORB        276
#define GBA_ITEM_BLUE_ORB       277
#define GBA_ITEM_SCANNER        278
#define GBA_ITEM_GO_GOGGLES     279
#define GBA_ITEM_METEORITE      280
#define GBA_ITEM_ROOM_1_KEY     281
#define GBA_ITEM_ROOM_2_KEY     282
#define GBA_ITEM_ROOM_4_KEY     283
#define GBA_ITEM_ROOM_6_KEY     284
#define GBA_ITEM_STORAGE_KEY    285
#define GBA_ITEM_ROOT_FOSSIL    286
#define GBA_ITEM_CLAW_FOSSIL    287
#define GBA_ITEM_DEVON_SCOPE    288
#define GBA_ITEM_TM01           289
#define GBA_ITEM_TM02           290
#define GBA_ITEM_TM03           291
#define GBA_ITEM_TM04           292
#define GBA_ITEM_TM05           293
#define GBA_ITEM_TM06           294
#define GBA_ITEM_TM07           295
#define GBA_ITEM_TM08           296
#define GBA_ITEM_TM09           297
#define GBA_ITEM_TM10           298
#define GBA_ITEM_TM11           299
#define GBA_ITEM_TM12           300
#define GBA_ITEM_TM13           301
#define GBA_ITEM_TM14           302
#define GBA_ITEM_TM15           303
#define GBA_ITEM_TM16           304
#define GBA_ITEM_TM17           305
#define GBA_ITEM_TM18           306
#define GBA_ITEM_TM19           307
#define GBA_ITEM_TM20           308
#define GBA_ITEM_TM21           309
#define GBA_ITEM_TM22           310
#define GBA_ITEM_TM23           311
#define GBA_ITEM_TM24           312
#define GBA_ITEM_TM25           313
#define GBA_ITEM_TM26           314
#define GBA_ITEM_TM27           315
#define GBA_ITEM_TM28           316
#define GBA_ITEM_TM29           317
#define GBA_ITEM_TM30           318
#define GBA_ITEM_TM31           319
#define GBA_ITEM_TM32           320
#define GBA_ITEM_TM33           321
#define GBA_ITEM_TM34           322
#define GBA_ITEM_TM35           323
#define GBA_ITEM_TM36           324
#define GBA_ITEM_TM37           325
#define GBA_ITEM_TM38           326
#define GBA_ITEM_TM39           327
#define GBA_ITEM_TM40           328
#define GBA_ITEM_TM41           329
#define GBA_ITEM_TM42           330
#define GBA_ITEM_TM43           331
#define GBA_ITEM_TM44           332
#define GBA_ITEM_TM45           333
#define GBA_ITEM_TM46           334
#define GBA_ITEM_TM47           335
#define GBA_ITEM_TM48           336
#define GBA_ITEM_TM49           337
#define GBA_ITEM_TM50           338
#define GBA_ITEM_HM01           339
#define GBA_ITEM_HM02           340
#define GBA_ITEM_HM03           341
#define GBA_ITEM_HM04           342
#define GBA_ITEM_HM05           343
#define GBA_ITEM_HM06           344
#define GBA_ITEM_HM07           345
#define GBA_ITEM_HM08           346
#define GBA_ITEM_15B            347
#define GBA_ITEM_15C            348
#define GBA_ITEM_OAKS_PARCEL    349
#define GBA_ITEM_POKE_FLUTE     350
#define GBA_ITEM_SECRET_KEY     351
#define GBA_ITEM_BIKE_VOUCHER   352
#define GBA_ITEM_GOLD_TEETH     353
#define GBA_ITEM_OLD_AMBER      354
#define GBA_ITEM_CARD_KEY       355
#define GBA_ITEM_LIFT_KEY       356
#define GBA_ITEM_HELIX_FOSSIL   357
#define GBA_ITEM_DOME_FOSSIL    358
#define GBA_ITEM_SILPH_SCOPE    359
#define GBA_ITEM_BICYCLE        360
#define GBA_ITEM_TOWN_MAP       361
#define GBA_ITEM_VS_SEEKER      362
#define GBA_ITEM_FAME_CHECKER   363
#define GBA_ITEM_TM_CASE        364
#define GBA_ITEM_BERRY_POUCH    365
#define GBA_ITEM_TEACHY_TV      366
#define GBA_ITEM_TRI_PASS       367
#define GBA_ITEM_RAINBOW_PASS   368
#define GBA_ITEM_TEA            369
#define GBA_ITEM_MYSTIC_TICKET  370
#define GBA_ITEM_AURORA_TICKET  371
#define GBA_ITEM_POWDER_JAR     372
#define GBA_ITEM_RUBY           373
#define GBA_ITEM_SAPPHIRE       374
#define GBA_ITEM_MAGMA_EMBLEM   375
#define GBA_ITEM_OLD_SEA_MAP    376
#define ITEMS_COUNT             377

#endif // POKEPLATINUM_CONSTANTS_GBA_ITEMS_H
