#ifndef POKEPLATINUM_CONSTANTS_GBA_POKEMON_STORAGE_SYSTEM_H
#define POKEPLATINUM_CONSTANTS_GBA_POKEMON_STORAGE_SYSTEM_H

#define GBA_MAX_PC_BOXES     14
#define GBA_MAX_PC_ROWS      5
#define GBA_MAX_PC_COLS      6
#define GBA_MAX_MONS_PER_BOX (GBA_MAX_PC_ROWS * GBA_MAX_PC_COLS)

#endif // POKEPLATINUM_CONSTANTS_GBA_POKEMON_STORAGE_SYSTEM_H
