#ifndef POKEPLATINUM_EASY_CHAT_DEFS_H
#define POKEPLATINUM_EASY_CHAT_DEFS_H

enum EasyChatType {
    EASY_CHAT_TYPE_ONE_WORD = 0,
    EASY_CHAT_TYPE_TWO_WORDS,
    EASY_CHAT_TYPE_SENTENCE,
};

enum EasyChatGroup {
    GROUP_POKEMON = 0,
    GROUP_POKEMON_2,
    GROUP_MOVE,
    GROUP_MOVE_2,
    GROUP_STATUS,
    GROUP_TRAINER,
    GROUP_PEOPLE,
    GROUP_GREETINGS,
    GROUP_LIFESTYLE,
    GROUP_FEELINGS,
    GROUP_TOUGH_WORDS,
    GROUP_UNION,
    EASY_CHAT_GROUP_COUNT,
    GROUP_MODE_CANCEL_INDEX = EASY_CHAT_GROUP_COUNT,
};

enum EasyChatMode {
    GROUP_MODE = 0,
    ABC_MODE,
};

#define MAX_EASY_CHAT_WORDS 2

#define EASY_CHAT_NOTHING_CHOSEN 0xFF
#define EASY_CHAT_CANCEL         0xFE

#endif // POKEPLATINUM_EASY_CHAT_DEFS_H
