#include "overlay104/battle_hall_helpers.h"

#include <nitro.h>

#include "constants/battle_frontier.h"
#include "generated/ai_flags.h"
#include "generated/frontier_trainers.h"
#include "generated/trainer_classes.h"

#include "overlay104/battle_hall.h"
#include "overlay104/ov104_0222DCE0.h"
#include "overlay104/struct_ov104_02230BE4.h"

#include "battle_hall_save.h"
#include "communication_information.h"
#include "communication_system.h"
#include "field_battle_data_transfer.h"
#include "heap.h"
#include "item_use_pokemon.h"
#include "math_util.h"
#include "party.h"
#include "pokemon.h"

#define GROUP_1_START 1
#define GROUP_2_START 155
#define GROUP_3_START 271
#define GROUP_4_START 376

typedef struct {
    u16 min;
    u16 max;
} BattleHallGroupRange;

static u32 BattleHall_GetBattleType(u8 challengeType);
static void BattleHall_LoadOpponentMonData(FrontierPokemonDataDTO *monDto, u8 typeRank, u16 trainerID, u16 opponentIndices[], int partySize, int heapID, int narcID);
static u32 BattleHall_GetOpponentLevel(BattleHall *battleHall, u8 unused);
static u8 BattleHall_GetIVsOfOpponentAtRank(u8 typeRank);
static u16 BattleHall_GetAIMask(BattleHall *battleHall, u8 battleNum, u8 rank);
static u16 BattleHall_CheckTypeRank(u8 typeRank);
static BOOL BattleHall_SetMonsPersonality(BattleHall *battleHall, u8 index);

static const u16 sHallTrainerClassesByRank[HALL_MAX_TYPE_RANK][8] = {
    {
        TRAINER_CLASS_YOUNGSTER,
        TRAINER_CLASS_LASS,
        TRAINER_CLASS_POKEFAN_MALE,
        TRAINER_CLASS_POKEFAN_FEMALE,
        TRAINER_CLASS_COLLECTOR,
        TRAINER_CLASS_BEAUTY,
        TRAINER_CLASS_POKE_KID,
        TRAINER_CLASS_NINJA_BOY,
    },
    {
        TRAINER_CLASS_YOUNGSTER,
        TRAINER_CLASS_LASS,
        TRAINER_CLASS_WAITER,
        TRAINER_CLASS_WAITRESS,
        TRAINER_CLASS_JOGGER,
        TRAINER_CLASS_PARASOL_LADY,
        TRAINER_CLASS_POKE_KID,
        TRAINER_CLASS_NINJA_BOY,
    },
    {
        TRAINER_CLASS_RICH_BOY,
        TRAINER_CLASS_LADY,
        TRAINER_CLASS_POKEFAN_MALE,
        TRAINER_CLASS_POKEFAN_FEMALE,
        TRAINER_CLASS_COLLECTOR,
        TRAINER_CLASS_BEAUTY,
        TRAINER_CLASS_CLOWN,
        TRAINER_CLASS_IDOL,
    },
    {
        TRAINER_CLASS_RICH_BOY,
        TRAINER_CLASS_LADY,
        TRAINER_CLASS_WAITER,
        TRAINER_CLASS_WAITRESS,
        TRAINER_CLASS_JOGGER,
        TRAINER_CLASS_PARASOL_LADY,
        TRAINER_CLASS_CLOWN,
        TRAINER_CLASS_IDOL,
    },
    {
        TRAINER_CLASS_CAMPER,
        TRAINER_CLASS_PICNICKER,
        TRAINER_CLASS_RANCHER,
        TRAINER_CLASS_COWGIRL,
        TRAINER_CLASS_GENTLEMAN,
        TRAINER_CLASS_SOCIALITE,
        TRAINER_CLASS_COLLECTOR,
        TRAINER_CLASS_BEAUTY,
    },
    {
        TRAINER_CLASS_CAMPER,
        TRAINER_CLASS_PICNICKER,
        TRAINER_CLASS_BREEDER_MALE,
        TRAINER_CLASS_BREEDER_FEMALE,
        TRAINER_CLASS_GENTLEMAN,
        TRAINER_CLASS_SOCIALITE,
        TRAINER_CLASS_ROUGHNECK,
        TRAINER_CLASS_GUITARIST,
    },
    {
        TRAINER_CLASS_SCHOOL_KID_MALE,
        TRAINER_CLASS_SCHOOL_KID_FEMALE,
        TRAINER_CLASS_RANCHER,
        TRAINER_CLASS_COWGIRL,
        TRAINER_CLASS_POKEFAN_MALE,
        TRAINER_CLASS_POKEFAN_FEMALE,
        TRAINER_CLASS_JOGGER,
        TRAINER_CLASS_PARASOL_LADY,
    },
    {
        TRAINER_CLASS_SCHOOL_KID_MALE,
        TRAINER_CLASS_SCHOOL_KID_FEMALE,
        TRAINER_CLASS_BREEDER_MALE,
        TRAINER_CLASS_BREEDER_FEMALE,
        TRAINER_CLASS_POKEFAN_MALE,
        TRAINER_CLASS_POKEFAN_FEMALE,
        TRAINER_CLASS_ROUGHNECK,
        TRAINER_CLASS_GUITARIST,
    },
    {
        TRAINER_CLASS_ACE_TRAINER_MALE,
        TRAINER_CLASS_ACE_TRAINER_FEMALE,
        TRAINER_CLASS_RANCHER,
        TRAINER_CLASS_COWGIRL,
        TRAINER_CLASS_RANGER_MALE,
        TRAINER_CLASS_RANGER_FEMALE,
        TRAINER_CLASS_PI,
        TRAINER_CLASS_VETERAN,
    },
    {
        TRAINER_CLASS_ACE_TRAINER_MALE,
        TRAINER_CLASS_ACE_TRAINER_FEMALE,
        TRAINER_CLASS_BREEDER_MALE,
        TRAINER_CLASS_BREEDER_FEMALE,
        TRAINER_CLASS_RANGER_MALE,
        TRAINER_CLASS_RANGER_FEMALE,
        TRAINER_CLASS_PI,
        TRAINER_CLASS_VETERAN,
    }
};

static const u16 sHallTrainerClassesBySelectedType[NUM_POKEMON_TYPES][4] = {
    { TRAINER_CLASS_POKEFAN_MALE, TRAINER_CLASS_POKEFAN_FEMALE, TRAINER_CLASS_YOUNGSTER, TRAINER_CLASS_LASS },
    { TRAINER_CLASS_VETERAN, TRAINER_CLASS_VETERAN, TRAINER_CLASS_POLICEMAN, TRAINER_CLASS_POLICEMAN },
    { TRAINER_CLASS_TUBER_MALE, TRAINER_CLASS_TUBER_FEMALE, TRAINER_CLASS_SAILOR, TRAINER_CLASS_FISHERMAN },
    { TRAINER_CLASS_POKE_KID, TRAINER_CLASS_POKE_KID, TRAINER_CLASS_WORKER, TRAINER_CLASS_WORKER },
    { TRAINER_CLASS_AROMA_LADY, TRAINER_CLASS_AROMA_LADY, TRAINER_CLASS_CAMPER, TRAINER_CLASS_PICNICKER },
    { TRAINER_CLASS_ACE_TRAINER_SNOW_MALE, TRAINER_CLASS_ACE_TRAINER_SNOW_MALE, TRAINER_CLASS_ACE_TRAINER_SNOW_FEMALE, TRAINER_CLASS_ACE_TRAINER_SNOW_FEMALE },
    { TRAINER_CLASS_BLACK_BELT, TRAINER_CLASS_BLACK_BELT, TRAINER_CLASS_BATTLE_GIRL, TRAINER_CLASS_BATTLE_GIRL },
    { TRAINER_CLASS_NINJA_BOY, TRAINER_CLASS_NINJA_BOY, TRAINER_CLASS_SCIENTIST, TRAINER_CLASS_SCIENTIST },
    { TRAINER_CLASS_HIKER, TRAINER_CLASS_HIKER, TRAINER_CLASS_RUIN_MANIAC, TRAINER_CLASS_RUIN_MANIAC },
    { TRAINER_CLASS_BIRD_KEEPER, TRAINER_CLASS_BIRD_KEEPER, TRAINER_CLASS_BIRD_KEEPER, TRAINER_CLASS_BIRD_KEEPER },
    { TRAINER_CLASS_PSYCHIC_MALE, TRAINER_CLASS_PSYCHIC_MALE, TRAINER_CLASS_PSYCHIC_FEMALE, TRAINER_CLASS_PSYCHIC_FEMALE },
    { TRAINER_CLASS_BUG_CATCHER, TRAINER_CLASS_BUG_CATCHER, TRAINER_CLASS_BUG_CATCHER, TRAINER_CLASS_BUG_CATCHER },
    { TRAINER_CLASS_HIKER, TRAINER_CLASS_HIKER, TRAINER_CLASS_RUIN_MANIAC, TRAINER_CLASS_RUIN_MANIAC },
    { TRAINER_CLASS_PSYCHIC_MALE, TRAINER_CLASS_PSYCHIC_MALE, TRAINER_CLASS_PSYCHIC_FEMALE, TRAINER_CLASS_PSYCHIC_FEMALE },
    { TRAINER_CLASS_DRAGON_TAMER, TRAINER_CLASS_DRAGON_TAMER, TRAINER_CLASS_DRAGON_TAMER, TRAINER_CLASS_DRAGON_TAMER },
    { TRAINER_CLASS_ROUGHNECK, TRAINER_CLASS_ROUGHNECK, TRAINER_CLASS_GUITARIST, TRAINER_CLASS_GUITARIST },
    { TRAINER_CLASS_REPORTER, TRAINER_CLASS_CAMERAMAN, TRAINER_CLASS_CYCLIST_MALE, TRAINER_CLASS_CYCLIST_FEMALE },
    { TRAINER_CLASS_IDOL, TRAINER_CLASS_CLOWN, TRAINER_CLASS_WAITER, TRAINER_CLASS_WAITRESS }
};

#include "res/trainers/frontier/frontier_trainer_classes.h"

static const u16 sBattleHallPotentialOpponentTypes[][2] = {
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_POISON, TYPE_FLYING },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_BUG, TYPE_GRASS },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_WATER, TYPE_POISON },
    { TYPE_ROCK, TYPE_GROUND },
    { TYPE_WATER, TYPE_PSYCHIC },
    { TYPE_ELECTRIC, TYPE_STEEL },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GHOST, TYPE_POISON },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_GRASS, TYPE_PSYCHIC },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_DRAGON, TYPE_DRAGON },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_WATER, TYPE_ELECTRIC },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_PSYCHIC, TYPE_FLYING },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GRASS, TYPE_FLYING },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_ICE, TYPE_GROUND },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ICE, TYPE_FLYING },
    { TYPE_DARK, TYPE_FIRE },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_ICE, TYPE_PSYCHIC },
    { TYPE_ROCK, TYPE_GROUND },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_DARK, TYPE_DARK },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_WATER, TYPE_GRASS },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_FLYING },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_BUG, TYPE_WATER },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_BUG, TYPE_GROUND },
    { TYPE_BUG, TYPE_GHOST },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_STEEL, TYPE_ROCK },
    { TYPE_FIGHTING, TYPE_PSYCHIC },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_WATER, TYPE_DARK },
    { TYPE_FIRE, TYPE_GROUND },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GROUND, TYPE_PSYCHIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_ICE, TYPE_ICE },
    { TYPE_ICE, TYPE_WATER },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_DRAGON, TYPE_DRAGON },
    { TYPE_STEEL, TYPE_PSYCHIC },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_POISON, TYPE_DARK },
    { TYPE_STEEL, TYPE_PSYCHIC },
    { TYPE_ROCK, TYPE_ROCK },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_DRAGON, TYPE_GROUND },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_POISON, TYPE_BUG },
    { TYPE_POISON, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GRASS, TYPE_ICE },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_BUG, TYPE_GRASS },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_ROCK, TYPE_GROUND },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_GHOST, TYPE_POISON },
    { TYPE_ROCK, TYPE_GROUND },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_GROUND, TYPE_ROCK },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_ROCK, TYPE_WATER },
    { TYPE_ROCK, TYPE_WATER },
    { TYPE_DRAGON, TYPE_DRAGON },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ROCK, TYPE_ROCK },
    { TYPE_GRASS, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_DARK, TYPE_FLYING },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GROUND, TYPE_FLYING },
    { TYPE_WATER, TYPE_POISON },
    { TYPE_DARK, TYPE_ICE },
    { TYPE_FIRE, TYPE_ROCK },
    { TYPE_WATER, TYPE_ROCK },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_ROCK, TYPE_GROUND },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_DARK, TYPE_DARK },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_WATER, TYPE_GRASS },
    { TYPE_GRASS, TYPE_DARK },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_FLYING },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_ROCK, TYPE_ROCK },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_DARK, TYPE_GHOST },
    { TYPE_STEEL, TYPE_STEEL },
    { TYPE_STEEL, TYPE_ROCK },
    { TYPE_FIGHTING, TYPE_PSYCHIC },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GROUND, TYPE_DRAGON },
    { TYPE_ROCK, TYPE_GRASS },
    { TYPE_ROCK, TYPE_BUG },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_ICE, TYPE_WATER },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_DRAGON, TYPE_DRAGON },
    { TYPE_STEEL, TYPE_PSYCHIC },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_WATER },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_ROCK, TYPE_ROCK },
    { TYPE_ROCK, TYPE_STEEL },
    { TYPE_BUG, TYPE_GRASS },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_GHOST, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_DRAGON, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_WATER, TYPE_FLYING },
    { TYPE_BUG, TYPE_GROUND },
    { TYPE_BUG, TYPE_STEEL },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_POISON, TYPE_GROUND },
    { TYPE_POISON, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_POISON, TYPE_FLYING },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_BUG, TYPE_POISON },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_ROCK, TYPE_GROUND },
    { TYPE_WATER, TYPE_PSYCHIC },
    { TYPE_ELECTRIC, TYPE_STEEL },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_ICE },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_GROUND, TYPE_ROCK },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_ICE, TYPE_PSYCHIC },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_ROCK, TYPE_WATER },
    { TYPE_ROCK, TYPE_WATER },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_ELECTRIC },
    { TYPE_PSYCHIC, TYPE_FLYING },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_GRASS, TYPE_FLYING },
    { TYPE_WATER, TYPE_PSYCHIC },
    { TYPE_NORMAL, TYPE_PSYCHIC },
    { TYPE_BUG, TYPE_STEEL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_ICE, TYPE_GROUND },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_WATER, TYPE_FLYING },
    { TYPE_STEEL, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_WATER, TYPE_GRASS },
    { TYPE_GRASS, TYPE_DARK },
    { TYPE_GRASS, TYPE_FIGHTING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_WATER, TYPE_DARK },
    { TYPE_FIRE, TYPE_GROUND },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_GRASS, TYPE_DARK },
    { TYPE_DRAGON, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_ROCK, TYPE_PSYCHIC },
    { TYPE_ROCK, TYPE_PSYCHIC },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_WATER, TYPE_DARK },
    { TYPE_ROCK, TYPE_GRASS },
    { TYPE_ROCK, TYPE_BUG },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_GRASS, TYPE_FLYING },
    { TYPE_DARK, TYPE_DARK },
    { TYPE_ICE, TYPE_ICE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_WATER, TYPE_ROCK },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_ROCK, TYPE_ROCK },
    { TYPE_ROCK, TYPE_STEEL },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GHOST, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_POISON, TYPE_DARK },
    { TYPE_GHOST, TYPE_DARK },
    { TYPE_POISON, TYPE_FIGHTING },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GRASS, TYPE_ICE },
    { TYPE_ICE, TYPE_GHOST },
    { TYPE_ELECTRIC, TYPE_GHOST },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_FIGHTING },
    { TYPE_FIGHTING, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_POISON },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_POISON, TYPE_POISON },
    { TYPE_WATER, TYPE_ICE },
    { TYPE_GHOST, TYPE_POISON },
    { TYPE_GRASS, TYPE_PSYCHIC },
    { TYPE_WATER, TYPE_PSYCHIC },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_BUG, TYPE_BUG },
    { TYPE_WATER, TYPE_FLYING },
    { TYPE_WATER, TYPE_ICE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_ROCK, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_ICE, TYPE_FLYING },
    { TYPE_ELECTRIC, TYPE_FLYING },
    { TYPE_FIRE, TYPE_FLYING },
    { TYPE_DRAGON, TYPE_FLYING },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_POISON, TYPE_FLYING },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_DARK, TYPE_DARK },
    { TYPE_STEEL, TYPE_GROUND },
    { TYPE_BUG, TYPE_STEEL },
    { TYPE_BUG, TYPE_ROCK },
    { TYPE_BUG, TYPE_FIGHTING },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_DARK, TYPE_FIRE },
    { TYPE_WATER, TYPE_DRAGON },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ROCK, TYPE_DARK },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_FIRE, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_GROUND },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_STEEL, TYPE_ROCK },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_GROUND, TYPE_DRAGON },
    { TYPE_GROUND, TYPE_PSYCHIC },
    { TYPE_WATER, TYPE_WATER },
    { TYPE_ICE, TYPE_WATER },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_DRAGON, TYPE_FLYING },
    { TYPE_STEEL, TYPE_PSYCHIC },
    { TYPE_ROCK, TYPE_ROCK },
    { TYPE_ICE, TYPE_ICE },
    { TYPE_STEEL, TYPE_STEEL },
    { TYPE_DRAGON, TYPE_PSYCHIC },
    { TYPE_DRAGON, TYPE_PSYCHIC },
    { TYPE_GRASS, TYPE_GROUND },
    { TYPE_FIRE, TYPE_FIGHTING },
    { TYPE_WATER, TYPE_STEEL },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_DARK, TYPE_FLYING },
    { TYPE_STEEL, TYPE_PSYCHIC },
    { TYPE_DRAGON, TYPE_GROUND },
    { TYPE_FIGHTING, TYPE_STEEL },
    { TYPE_GROUND, TYPE_GROUND },
    { TYPE_POISON, TYPE_DARK },
    { TYPE_DARK, TYPE_ICE },
    { TYPE_ELECTRIC, TYPE_STEEL },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_GROUND, TYPE_ROCK },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_ELECTRIC, TYPE_ELECTRIC },
    { TYPE_FIRE, TYPE_FIRE },
    { TYPE_NORMAL, TYPE_FLYING },
    { TYPE_BUG, TYPE_FLYING },
    { TYPE_GRASS, TYPE_GRASS },
    { TYPE_ICE, TYPE_ICE },
    { TYPE_GROUND, TYPE_FLYING },
    { TYPE_ICE, TYPE_GROUND },
    { TYPE_NORMAL, TYPE_NORMAL },
    { TYPE_PSYCHIC, TYPE_FIGHTING },
    { TYPE_ROCK, TYPE_STEEL },
    { TYPE_GHOST, TYPE_GHOST },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_PSYCHIC, TYPE_PSYCHIC },
    { TYPE_FIRE, TYPE_STEEL },
    { TYPE_GRASS, TYPE_POISON },
    { TYPE_FIRE, TYPE_FLYING },
    { TYPE_NORMAL, TYPE_NORMAL }
};

// TODO unpack pl_bsdpm.narc and generate this list from it
static const u16 sBattleHallPotentialOpponents[] = {
    SPECIES_BULBASAUR,
    SPECIES_CHARMANDER,
    SPECIES_SQUIRTLE,
    SPECIES_CATERPIE,
    SPECIES_METAPOD,
    SPECIES_WEEDLE,
    SPECIES_KAKUNA,
    SPECIES_PIDGEY,
    SPECIES_RATTATA,
    SPECIES_SPEAROW,
    SPECIES_EKANS,
    SPECIES_PIKACHU,
    SPECIES_SANDSHREW,
    SPECIES_NIDORAN_F,
    SPECIES_NIDORAN_M,
    SPECIES_CLEFAIRY,
    SPECIES_VULPIX,
    SPECIES_JIGGLYPUFF,
    SPECIES_ZUBAT,
    SPECIES_ODDISH,
    SPECIES_PARAS,
    SPECIES_VENONAT,
    SPECIES_DIGLETT,
    SPECIES_MEOWTH,
    SPECIES_PSYDUCK,
    SPECIES_MANKEY,
    SPECIES_POLIWAG,
    SPECIES_ABRA,
    SPECIES_MACHOP,
    SPECIES_BELLSPROUT,
    SPECIES_TENTACOOL,
    SPECIES_GEODUDE,
    SPECIES_SLOWPOKE,
    SPECIES_MAGNEMITE,
    SPECIES_DODUO,
    SPECIES_SEEL,
    SPECIES_GRIMER,
    SPECIES_SHELLDER,
    SPECIES_GASTLY,
    SPECIES_DROWZEE,
    SPECIES_KRABBY,
    SPECIES_VOLTORB,
    SPECIES_EXEGGCUTE,
    SPECIES_CUBONE,
    SPECIES_HORSEA,
    SPECIES_GOLDEEN,
    SPECIES_MAGIKARP,
    SPECIES_DITTO,
    SPECIES_EEVEE,
    SPECIES_DRATINI,
    SPECIES_CHIKORITA,
    SPECIES_CYNDAQUIL,
    SPECIES_TOTODILE,
    SPECIES_SENTRET,
    SPECIES_HOOTHOOT,
    SPECIES_LEDYBA,
    SPECIES_SPINARAK,
    SPECIES_CHINCHOU,
    SPECIES_PICHU,
    SPECIES_CLEFFA,
    SPECIES_IGGLYBUFF,
    SPECIES_TOGEPI,
    SPECIES_NATU,
    SPECIES_MAREEP,
    SPECIES_MARILL,
    SPECIES_HOPPIP,
    SPECIES_SUNKERN,
    SPECIES_WOOPER,
    SPECIES_UNOWN,
    SPECIES_PINECO,
    SPECIES_SNUBBULL,
    SPECIES_TEDDIURSA,
    SPECIES_SLUGMA,
    SPECIES_SWINUB,
    SPECIES_REMORAID,
    SPECIES_DELIBIRD,
    SPECIES_HOUNDOUR,
    SPECIES_PHANPY,
    SPECIES_SMEARGLE,
    SPECIES_TYROGUE,
    SPECIES_SMOOCHUM,
    SPECIES_LARVITAR,
    SPECIES_TREECKO,
    SPECIES_TORCHIC,
    SPECIES_MUDKIP,
    SPECIES_POOCHYENA,
    SPECIES_ZIGZAGOON,
    SPECIES_WURMPLE,
    SPECIES_SILCOON,
    SPECIES_CASCOON,
    SPECIES_LOTAD,
    SPECIES_SEEDOT,
    SPECIES_TAILLOW,
    SPECIES_WINGULL,
    SPECIES_RALTS,
    SPECIES_KIRLIA,
    SPECIES_SURSKIT,
    SPECIES_SHROOMISH,
    SPECIES_SLAKOTH,
    SPECIES_NINCADA,
    SPECIES_SHEDINJA,
    SPECIES_WHISMUR,
    SPECIES_MAKUHITA,
    SPECIES_AZURILL,
    SPECIES_SKITTY,
    SPECIES_ARON,
    SPECIES_MEDITITE,
    SPECIES_ELECTRIKE,
    SPECIES_GULPIN,
    SPECIES_CARVANHA,
    SPECIES_NUMEL,
    SPECIES_SPOINK,
    SPECIES_TRAPINCH,
    SPECIES_CACNEA,
    SPECIES_SWABLU,
    SPECIES_BARBOACH,
    SPECIES_CORPHISH,
    SPECIES_BALTOY,
    SPECIES_FEEBAS,
    SPECIES_SHUPPET,
    SPECIES_DUSKULL,
    SPECIES_WYNAUT,
    SPECIES_SNORUNT,
    SPECIES_SPHEAL,
    SPECIES_LUVDISC,
    SPECIES_BAGON,
    SPECIES_BELDUM,
    SPECIES_TURTWIG,
    SPECIES_CHIMCHAR,
    SPECIES_PIPLUP,
    SPECIES_STARLY,
    SPECIES_BIDOOF,
    SPECIES_KRICKETOT,
    SPECIES_SHINX,
    SPECIES_BUDEW,
    SPECIES_BURMY,
    SPECIES_COMBEE,
    SPECIES_BUIZEL,
    SPECIES_CHERUBI,
    SPECIES_SHELLOS,
    SPECIES_GLAMEOW,
    SPECIES_CHINGLING,
    SPECIES_STUNKY,
    SPECIES_BRONZOR,
    SPECIES_BONSLY,
    SPECIES_MIME_JR,
    SPECIES_HAPPINY,
    SPECIES_GIBLE,
    SPECIES_RIOLU,
    SPECIES_HIPPOPOTAS,
    SPECIES_SKORUPI,
    SPECIES_CROAGUNK,
    SPECIES_FINNEON,
    SPECIES_SNOVER,
    SPECIES_IVYSAUR,
    SPECIES_CHARMELEON,
    SPECIES_WARTORTLE,
    SPECIES_BUTTERFREE,
    SPECIES_BEEDRILL,
    SPECIES_PIDGEOTTO,
    SPECIES_RATICATE,
    SPECIES_ARBOK,
    SPECIES_NIDORINA,
    SPECIES_NIDORINO,
    SPECIES_WIGGLYTUFF,
    SPECIES_GLOOM,
    SPECIES_PARASECT,
    SPECIES_DUGTRIO,
    SPECIES_GROWLITHE,
    SPECIES_POLIWHIRL,
    SPECIES_KADABRA,
    SPECIES_MACHOKE,
    SPECIES_WEEPINBELL,
    SPECIES_GRAVELER,
    SPECIES_PONYTA,
    SPECIES_FARFETCHD,
    SPECIES_HAUNTER,
    SPECIES_ONIX,
    SPECIES_MAROWAK,
    SPECIES_LICKITUNG,
    SPECIES_KOFFING,
    SPECIES_RHYHORN,
    SPECIES_TANGELA,
    SPECIES_STARYU,
    SPECIES_PORYGON,
    SPECIES_OMANYTE,
    SPECIES_KABUTO,
    SPECIES_DRAGONAIR,
    SPECIES_BAYLEEF,
    SPECIES_QUILAVA,
    SPECIES_CROCONAW,
    SPECIES_FURRET,
    SPECIES_LEDIAN,
    SPECIES_ARIADOS,
    SPECIES_TOGETIC,
    SPECIES_FLAAFFY,
    SPECIES_AZUMARILL,
    SPECIES_SUDOWOODO,
    SPECIES_SKIPLOOM,
    SPECIES_AIPOM,
    SPECIES_SUNFLORA,
    SPECIES_YANMA,
    SPECIES_QUAGSIRE,
    SPECIES_MURKROW,
    SPECIES_MISDREAVUS,
    SPECIES_WOBBUFFET,
    SPECIES_DUNSPARCE,
    SPECIES_GLIGAR,
    SPECIES_QWILFISH,
    SPECIES_SNEASEL,
    SPECIES_MAGCARGO,
    SPECIES_CORSOLA,
    SPECIES_ELEKID,
    SPECIES_MAGBY,
    SPECIES_PUPITAR,
    SPECIES_GROVYLE,
    SPECIES_COMBUSKEN,
    SPECIES_MARSHTOMP,
    SPECIES_MIGHTYENA,
    SPECIES_LINOONE,
    SPECIES_BEAUTIFLY,
    SPECIES_DUSTOX,
    SPECIES_LOMBRE,
    SPECIES_NUZLEAF,
    SPECIES_SWELLOW,
    SPECIES_PELIPPER,
    SPECIES_MASQUERAIN,
    SPECIES_LOUDRED,
    SPECIES_NOSEPASS,
    SPECIES_DELCATTY,
    SPECIES_SABLEYE,
    SPECIES_MAWILE,
    SPECIES_LAIRON,
    SPECIES_MEDICHAM,
    SPECIES_PLUSLE,
    SPECIES_MINUN,
    SPECIES_VOLBEAT,
    SPECIES_ILLUMISE,
    SPECIES_ROSELIA,
    SPECIES_WAILMER,
    SPECIES_SPINDA,
    SPECIES_VIBRAVA,
    SPECIES_LILEEP,
    SPECIES_ANORITH,
    SPECIES_CASTFORM,
    SPECIES_CHIMECHO,
    SPECIES_SEALEO,
    SPECIES_CLAMPERL,
    SPECIES_SHELGON,
    SPECIES_METANG,
    SPECIES_GROTLE,
    SPECIES_MONFERNO,
    SPECIES_PRINPLUP,
    SPECIES_STARAVIA,
    SPECIES_BIBAREL,
    SPECIES_KRICKETUNE,
    SPECIES_LUXIO,
    SPECIES_CRANIDOS,
    SPECIES_SHIELDON,
    SPECIES_WORMADAM,
    SPECIES_MOTHIM,
    SPECIES_PACHIRISU,
    SPECIES_DRIFLOON,
    SPECIES_BUNEARY,
    SPECIES_CHATOT,
    SPECIES_GABITE,
    SPECIES_MUNCHLAX,
    SPECIES_MANTYKE,
    SPECIES_WORMADAM,
    SPECIES_WORMADAM,
    SPECIES_RAICHU,
    SPECIES_SANDSLASH,
    SPECIES_NIDOQUEEN,
    SPECIES_NIDOKING,
    SPECIES_CLEFABLE,
    SPECIES_GOLBAT,
    SPECIES_VILEPLUME,
    SPECIES_VENOMOTH,
    SPECIES_PERSIAN,
    SPECIES_PRIMEAPE,
    SPECIES_ALAKAZAM,
    SPECIES_VICTREEBEL,
    SPECIES_GOLEM,
    SPECIES_SLOWBRO,
    SPECIES_MAGNETON,
    SPECIES_DODRIO,
    SPECIES_DEWGONG,
    SPECIES_HYPNO,
    SPECIES_KINGLER,
    SPECIES_ELECTRODE,
    SPECIES_HITMONLEE,
    SPECIES_HITMONCHAN,
    SPECIES_WEEZING,
    SPECIES_RHYDON,
    SPECIES_CHANSEY,
    SPECIES_KANGASKHAN,
    SPECIES_SEADRA,
    SPECIES_SEAKING,
    SPECIES_MR_MIME,
    SPECIES_JYNX,
    SPECIES_ELECTABUZZ,
    SPECIES_MAGMAR,
    SPECIES_TAUROS,
    SPECIES_OMASTAR,
    SPECIES_KABUTOPS,
    SPECIES_NOCTOWL,
    SPECIES_LANTURN,
    SPECIES_XATU,
    SPECIES_BELLOSSOM,
    SPECIES_JUMPLUFF,
    SPECIES_SLOWKING,
    SPECIES_GIRAFARIG,
    SPECIES_FORRETRESS,
    SPECIES_GRANBULL,
    SPECIES_PILOSWINE,
    SPECIES_OCTILLERY,
    SPECIES_MANTINE,
    SPECIES_SKARMORY,
    SPECIES_STANTLER,
    SPECIES_HITMONTOP,
    SPECIES_MILTANK,
    SPECIES_LUDICOLO,
    SPECIES_SHIFTRY,
    SPECIES_BRELOOM,
    SPECIES_VIGOROTH,
    SPECIES_NINJASK,
    SPECIES_EXPLOUD,
    SPECIES_HARIYAMA,
    SPECIES_MANECTRIC,
    SPECIES_SWALOT,
    SPECIES_SHARPEDO,
    SPECIES_CAMERUPT,
    SPECIES_TORKOAL,
    SPECIES_GRUMPIG,
    SPECIES_CACTURNE,
    SPECIES_ALTARIA,
    SPECIES_ZANGOOSE,
    SPECIES_SEVIPER,
    SPECIES_LUNATONE,
    SPECIES_SOLROCK,
    SPECIES_WHISCASH,
    SPECIES_CRAWDAUNT,
    SPECIES_CRADILY,
    SPECIES_ARMALDO,
    SPECIES_KECLEON,
    SPECIES_BANETTE,
    SPECIES_DUSCLOPS,
    SPECIES_TROPIUS,
    SPECIES_ABSOL,
    SPECIES_GLALIE,
    SPECIES_HUNTAIL,
    SPECIES_GOREBYSS,
    SPECIES_RELICANTH,
    SPECIES_STARAPTOR,
    SPECIES_RAMPARDOS,
    SPECIES_BASTIODON,
    SPECIES_VESPIQUEN,
    SPECIES_FLOATZEL,
    SPECIES_CHERRIM,
    SPECIES_GASTRODON,
    SPECIES_AMBIPOM,
    SPECIES_DRIFBLIM,
    SPECIES_LOPUNNY,
    SPECIES_MISMAGIUS,
    SPECIES_PURUGLY,
    SPECIES_SKUNTANK,
    SPECIES_SPIRITOMB,
    SPECIES_TOXICROAK,
    SPECIES_CARNIVINE,
    SPECIES_LUMINEON,
    SPECIES_ABOMASNOW,
    SPECIES_FROSLASS,
    SPECIES_ROTOM,
    SPECIES_PIDGEOT,
    SPECIES_FEAROW,
    SPECIES_BLASTOISE,
    SPECIES_NINETALES,
    SPECIES_GOLDUCK,
    SPECIES_ARCANINE,
    SPECIES_POLIWRATH,
    SPECIES_MACHAMP,
    SPECIES_TENTACRUEL,
    SPECIES_RAPIDASH,
    SPECIES_MUK,
    SPECIES_CLOYSTER,
    SPECIES_GENGAR,
    SPECIES_EXEGGUTOR,
    SPECIES_STARMIE,
    SPECIES_SCYTHER,
    SPECIES_PINSIR,
    SPECIES_GYARADOS,
    SPECIES_LAPRAS,
    SPECIES_VAPOREON,
    SPECIES_JOLTEON,
    SPECIES_FLAREON,
    SPECIES_AERODACTYL,
    SPECIES_SNORLAX,
    SPECIES_ARTICUNO,
    SPECIES_ZAPDOS,
    SPECIES_MOLTRES,
    SPECIES_DRAGONITE,
    SPECIES_MEGANIUM,
    SPECIES_TYPHLOSION,
    SPECIES_FERALIGATR,
    SPECIES_CROBAT,
    SPECIES_AMPHAROS,
    SPECIES_POLITOED,
    SPECIES_ESPEON,
    SPECIES_UMBREON,
    SPECIES_STEELIX,
    SPECIES_SCIZOR,
    SPECIES_SHUCKLE,
    SPECIES_HERACROSS,
    SPECIES_URSARING,
    SPECIES_HOUNDOOM,
    SPECIES_KINGDRA,
    SPECIES_DONPHAN,
    SPECIES_PORYGON2,
    SPECIES_BLISSEY,
    SPECIES_RAIKOU,
    SPECIES_ENTEI,
    SPECIES_SUICUNE,
    SPECIES_TYRANITAR,
    SPECIES_SCEPTILE,
    SPECIES_BLAZIKEN,
    SPECIES_SWAMPERT,
    SPECIES_GARDEVOIR,
    SPECIES_SLAKING,
    SPECIES_AGGRON,
    SPECIES_WAILORD,
    SPECIES_FLYGON,
    SPECIES_CLAYDOL,
    SPECIES_MILOTIC,
    SPECIES_WALREIN,
    SPECIES_CRESSELIA,
    SPECIES_SALAMENCE,
    SPECIES_METAGROSS,
    SPECIES_REGIROCK,
    SPECIES_REGICE,
    SPECIES_REGISTEEL,
    SPECIES_LATIAS,
    SPECIES_LATIOS,
    SPECIES_TORTERRA,
    SPECIES_INFERNAPE,
    SPECIES_EMPOLEON,
    SPECIES_LUXRAY,
    SPECIES_ROSERADE,
    SPECIES_HONCHKROW,
    SPECIES_BRONZONG,
    SPECIES_GARCHOMP,
    SPECIES_LUCARIO,
    SPECIES_HIPPOWDON,
    SPECIES_DRAPION,
    SPECIES_WEAVILE,
    SPECIES_MAGNEZONE,
    SPECIES_LICKILICKY,
    SPECIES_RHYPERIOR,
    SPECIES_TANGROWTH,
    SPECIES_ELECTIVIRE,
    SPECIES_MAGMORTAR,
    SPECIES_TOGEKISS,
    SPECIES_YANMEGA,
    SPECIES_LEAFEON,
    SPECIES_GLACEON,
    SPECIES_GLISCOR,
    SPECIES_MAMOSWINE,
    SPECIES_PORYGON_Z,
    SPECIES_GALLADE,
    SPECIES_PROBOPASS,
    SPECIES_DUSKNOIR,
    SPECIES_UXIE,
    SPECIES_MESPRIT,
    SPECIES_AZELF,
    SPECIES_HEATRAN,
    SPECIES_VENUSAUR,
    SPECIES_CHARIZARD,
    SPECIES_REGIGIGAS,
};

static const struct {
    u8 unused;
    u8 ivs;
    u16 unused2;
} sIVsPerTypeRank[HALL_MAX_TYPE_RANK] = {
    { 0, 8, 0 },
    { 0, 10, 0 },
    { 0, 12, 0 },
    { 0, 14, 0 },
    { 0, 16, 0 },
    { 0, 18, 0 },
    { 0, 20, 0 },
    { 0, 22, 0 },
    { 0, 24, 0 },
    { 0, 26, 0 }
};

void BattleHall_PickOpponentTrainerClasses(u8 selectedTypeIdx, u8 numTrainers, u8 typeRank, u8 currentBattle, u16 trainerIDs[])
{
    int i = 0;

    u8 offset = currentBattle * 2;
    typeRank = BattleHall_CheckTypeRank(typeRank);

    do {
        u16 rand = LCRNG_Next() % (8 + 4);

        if (rand < 8) {
            trainerIDs[offset + i] = sHallTrainerClassesByRank[typeRank][rand];
        } else {
            trainerIDs[offset + i] = sHallTrainerClassesBySelectedType[selectedTypeIdx][rand - 8];
        }

        i++;
    } while (i < numTrainers);
}

void BattleHall_PickOpponentTrainers(u8 challengeType, u8 numTrainers, int currentRound, u8 rank, u8 currentBattle, u16 trainerIDs[])
{
    int startingIndex;
    int selectedTrainers = 0;
    u8 offset = currentBattle * 2;
    u8 typeRank = BattleHall_CheckTypeRank(rank);

    if (challengeType == FRONTIER_CHALLENGE_SINGLE) {
        int currentStreak = (currentRound * HALL_BATTLES_PER_ROUND) + (currentBattle + 1);

        if (currentStreak == HALL_STREAK_SILVER_BATTLE) {
            trainerIDs[offset] = FRONTIER_TRAINER_HALL_MATRON_ARGENTA_SILVER;
            return;
        } else if (currentStreak == HALL_STREAK_GOLD_BATTLE) {
            trainerIDs[offset] = FRONTIER_TRAINER_HALL_MATRON_ARGENTA_GOLD;
            return;
        }
    }

    do {
        u16 trainerID = LCRNG_Next() % NELEMS(sFrontierTrainerClasses);
        startingIndex = trainerID;

        while (TRUE) {
            int trainerClass = trainerIDs[offset + selectedTrainers];

            if (trainerClass == sFrontierTrainerClasses[trainerID]) {
                int pastTrainersIdx;
                for (pastTrainersIdx = 0; pastTrainersIdx < (offset + selectedTrainers); pastTrainersIdx++) {
                    if (trainerIDs[pastTrainersIdx] == trainerID) {
                        break;
                    }
                }

                if (pastTrainersIdx == (offset + selectedTrainers)) {
                    trainerIDs[offset + selectedTrainers] = trainerID;
                    selectedTrainers++;
                    break;
                }
            }

            trainerID++;

            if (trainerID >= NELEMS(sFrontierTrainerClasses)) {
                trainerID = 0;
            }

            if (trainerID == startingIndex) {
                while (TRUE) {
                    u16 newIdx = LCRNG_Next() % 8;

                    if (trainerClass != sHallTrainerClassesByRank[typeRank][newIdx]) {
                        trainerIDs[offset + selectedTrainers] = sHallTrainerClassesByRank[typeRank][newIdx];
                        break;
                    }
                }
            }
        }
    } while (selectedTrainers < numTrainers);
}

static const BattleHallGroupRange sPotentialMatchupRangesByRank[HALL_MAX_TYPE_RANK] = {
    { GROUP_1_START, GROUP_2_START - 1 },
    { GROUP_1_START, GROUP_2_START - 1 },
    { GROUP_1_START, GROUP_3_START - 1 },
    { GROUP_1_START, GROUP_3_START - 1 },
    { GROUP_1_START, GROUP_3_START - 1 },
    { GROUP_2_START, GROUP_4_START - 1 },
    { GROUP_2_START, GROUP_4_START - 1 },
    { GROUP_2_START, GROUP_4_START - 1 },
    { GROUP_3_START, NELEMS(sBattleHallPotentialOpponents) },
    { GROUP_3_START, NELEMS(sBattleHallPotentialOpponents) }
};

static const BattleHallGroupRange sMatchupGroupRanges[] = {
    { GROUP_1_START, GROUP_2_START - 1 },
    { GROUP_2_START, GROUP_3_START - 1 },
    { GROUP_3_START, GROUP_4_START - 1 },
    { GROUP_4_START, NELEMS(sBattleHallPotentialOpponents) }
};

void BattleHall_PickNextOpponentPokemon(u8 numOpponentsToPick, u8 selectedType, u8 typeRank, u8 currentBattle, u16 playersSpecies, u16 opponentIndices[], u8 battleType)
{
    const BattleHallGroupRange *matchupRange;
    int opponentsFound = 0;

    u8 loopedThrough = FALSE;
    u8 currentBattleIndex = currentBattle * 2;
    typeRank = BattleHall_CheckTypeRank(typeRank);

    // For normal battles, the group of potential opponents is determined by
    // the rank of the next battle
    // For the Silver print battle, the opponent is selected from the group in
    // which the player's species is
    // For the Gold print battle, the opponent is from Group 4
    if (battleType != HALL_NEXT_BATTLE_NORMAL) {
        u16 i, playersMonIndex;
        for (i = 0; i < NELEMS(sBattleHallPotentialOpponents); i++) {
            if (playersSpecies == sBattleHallPotentialOpponents[i]) {
                playersMonIndex = i;
                break;
            }
        }

        if (i == NELEMS(sBattleHallPotentialOpponents)) {
            playersMonIndex = sMatchupGroupRanges[NELEMS(sMatchupGroupRanges) - 1].min;
        }

        u16 playersMonsGroup;
        for (playersMonsGroup = 0; playersMonsGroup < NELEMS(sMatchupGroupRanges); playersMonsGroup++) {
            if (playersMonIndex < sMatchupGroupRanges[playersMonsGroup].max) {
                break;
            }
        }

        if (playersMonsGroup == NELEMS(sMatchupGroupRanges)) {
            playersMonsGroup = NELEMS(sMatchupGroupRanges) - 1;
        }

        if (battleType == HALL_NEXT_BATTLE_GOLD) {
            matchupRange = &sMatchupGroupRanges[NELEMS(sMatchupGroupRanges) - 1];
        } else {
            matchupRange = &sMatchupGroupRanges[playersMonsGroup];
        }
    } else {
        matchupRange = &sPotentialMatchupRangesByRank[typeRank];
    }

    u16 groupSize = matchupRange->max - matchupRange->min + 1;
    u16 opponentIndex = matchupRange->min + LCRNG_Next() % groupSize;
    opponentIndex -= 1;
    u16 startingIndex = opponentIndex;

    while (opponentsFound < numOpponentsToPick) {
        // First try to select a pokemon that has not been fought yet this
        // round. If no such pokemon is found after a full search through the
        // group, then just make sure the next opponent is not the same as the
        // previous one.
        u16 pastOpponentsIndex;
        if (!loopedThrough) {
            for (pastOpponentsIndex = 0; pastOpponentsIndex < currentBattleIndex; pastOpponentsIndex++) {
                if (opponentIndices[pastOpponentsIndex] == (opponentIndex + 1)) {
                    break;
                }
            }
        } else {
            if (opponentIndices[currentBattleIndex - 2] == (opponentIndex + 1)) {
                pastOpponentsIndex = 0;
            } else {
                pastOpponentsIndex = currentBattleIndex;
            }
        }

        if (pastOpponentsIndex == currentBattleIndex) {
            if (battleType != 0) {
                if (playersSpecies != sBattleHallPotentialOpponents[opponentIndex]) {
                    opponentIndices[currentBattleIndex + opponentsFound] = opponentIndex + 1;
                    opponentsFound++;
                }
            } else if (selectedType == sBattleHallPotentialOpponentTypes[opponentIndex][0] || selectedType == sBattleHallPotentialOpponentTypes[opponentIndex][1]) {
                if (playersSpecies != sBattleHallPotentialOpponents[opponentIndex]) {
                    opponentIndices[currentBattleIndex + opponentsFound] = opponentIndex + 1;

                    opponentsFound++;
                }
            }
        }

        opponentIndex++;

        if (opponentIndex + 1 >= matchupRange->max) {
            opponentIndex = matchupRange->min - 1;
        }

        if (opponentIndex == startingIndex) {
            loopedThrough = TRUE;
        }
    }
}

FieldBattleDTO *BattleHall_SetupBattle(BattleHall *battleHall, FieldFrontierDTO *fieldData)
{
    int i;
    u8 rank;
    Pokemon *mon;
    FrontierTrainerDataDTO trDataDTO;

    u8 offset = battleHall->currentBattle * 2;
    u8 playerPartySize = BattleHall_GetPlayerPartySize(battleHall->challengeType);
    u8 opponentPartySize = BattleHall_GetOpponentPartySize(battleHall->challengeType);
    Party *party = SaveData_GetParty(battleHall->saveData);

    Party_HealAllMembers(party);

    FieldBattleDTO *battleDTO = FieldBattleDTO_New(HEAP_ID_FIELD2, BattleHall_GetBattleType(battleHall->challengeType));
    FieldBattleDTO_InitFromGameState(battleDTO, NULL, fieldData->saveData, fieldData->mapHeaderID, fieldData->journalEntry, fieldData->bagCursor, fieldData->subscreenCursorOn);

    battleDTO->background = BACKGROUND_BATTLE_HALL;
    battleDTO->terrain = TERRAIN_BATTLE_HALL;
    Party_InitWithCapacity(battleDTO->parties[BATTLER_PLAYER_1], playerPartySize);

    mon = Pokemon_New(HEAP_ID_FIELD2);

    for (i = 0; i < playerPartySize; i++) {
        Pokemon_Copy(Party_GetPokemonBySlotIndex(party, battleHall->partySlots[i]), mon);
        FieldBattleDTO_AddPokemonToBattler(battleDTO, mon, BATTLER_PLAYER_1);
    }

    Heap_Free(mon);
    FieldBattleDTO_CopyPlayerInfoToTrainerData(battleDTO);

    Heap_Free(BattleFrontier_GetTrainerData(&trDataDTO, battleHall->trainerIDs[offset], HEAP_ID_FIELD2, NARC_INDEX_BATTLE__B_PL_TOWER__PL_BTDTR));
    FieldBattleDTO_InitFrontierTrainer(battleDTO, &trDataDTO, opponentPartySize, BATTLER_ENEMY_1, HEAP_ID_FIELD2);
    Party_InitWithCapacity(battleDTO->parties[BATTLER_ENEMY_1], opponentPartySize);

    rank = BattleHall_GetRankOfType(battleHall->selectedTypeIdx, &battleHall->typeRanks[battleHall->challengeType][0]);

    if (battleHall->challengeType == FRONTIER_CHALLENGE_MULTI) {
        rank = HALL_MAX_TYPE_RANK - 1;
    }

    u16 aiMask = BattleHall_GetAIMask(battleHall, offset, rank);

    for (i = 0; i < MAX_BATTLERS; i++) {
        battleDTO->trainer[i].header.aiMask = aiMask;
    }

    BattleHall_LoadOpponentMonData(&battleHall->opponentMons[offset], rank, battleHall->trainerIDs[offset], &battleHall->monIndices[offset], opponentPartySize, HEAP_ID_FIELD2, NARC_INDEX_BATTLE__B_PL_STAGE__PL_BSDPM);

    mon = Pokemon_New(HEAP_ID_FIELD2);

    for (i = 0; i < opponentPartySize; i++) {
        while (BattleHall_SetMonsPersonality(battleHall, offset) != 0) {}

        FrontierPokemonDataDTO_InitPokemon(&battleHall->opponentMons[offset], mon, BattleHall_GetOpponentLevel(battleHall, rank));

        Pokemon_CalcAbility(mon);
        FieldBattleDTO_AddPokemonToBattler(battleDTO, mon, BATTLER_ENEMY_1);
    }

    Heap_Free(mon);

    switch (battleHall->challengeType) {
    case FRONTIER_CHALLENGE_MULTI:
    case FRONTIER_CHALLENGE_MULTI_WFC:
        FieldBattleDTO_CopyPlayerInfoToTrainerData(battleDTO);

        TrainerInfo_Copy(CommInfo_TrainerInfo(1 - CommSys_CurNetId()), battleDTO->trainerInfo[BATTLER_PLAYER_2]);

        Heap_Free(BattleFrontier_GetTrainerData(&trDataDTO, battleHall->trainerIDs[offset + 1], HEAP_ID_FIELD2, NARC_INDEX_BATTLE__B_PL_TOWER__PL_BTDTR));

        FieldBattleDTO_InitFrontierTrainer(battleDTO, &trDataDTO, opponentPartySize, BATTLER_ENEMY_2, HEAP_ID_FIELD2);
        Party_InitWithCapacity(battleDTO->parties[BATTLER_ENEMY_2], opponentPartySize);

        mon = Pokemon_New(HEAP_ID_FIELD2);

        while (BattleHall_SetMonsPersonality(battleHall, offset) != 0) {}

        FrontierPokemonDataDTO_InitPokemon(&battleHall->opponentMons[offset], mon, BattleHall_GetOpponentLevel(battleHall, rank));

        Pokemon_CalcAbility(mon);
        FieldBattleDTO_AddPokemonToBattler(battleDTO, mon, BATTLER_ENEMY_2);
        Heap_Free(mon);
        break;
    }

    return battleDTO;
}

static BOOL BattleHall_SetMonsPersonality(BattleHall *battleHall, u8 index)
{
    if (battleHall->opponentMons[index].personality > ((24 + 1) * 10001)) {
        battleHall->opponentMons[index].personality -= ((24 + 1) * 10001);
    } else {
        battleHall->opponentMons[index].personality += ((24 + 1) * 10001);
    }

    return Pokemon_IsPersonalityShiny(battleHall->opponentMons[index].otID, battleHall->opponentMons[index].personality);
}

static u32 BattleHall_GetBattleType(u8 challengeType)
{
    switch (challengeType) {
    case FRONTIER_CHALLENGE_SINGLE:
        return BATTLE_TYPE_FRONTIER_SINGLES;
    case FRONTIER_CHALLENGE_DOUBLE:
        return BATTLE_TYPE_FRONTIER_DOUBLES;
    case FRONTIER_CHALLENGE_MULTI:
        return BATTLE_TYPE_FRONTIER_LINK | BATTLE_TYPE_TRAINER_DOUBLES | BATTLE_TYPE_2vs2;
    case FRONTIER_CHALLENGE_MULTI_WFC:
        return BATTLE_TYPE_FRONTIER_LINK | BATTLE_TYPE_TRAINER_DOUBLES | BATTLE_TYPE_2vs2;
    }

    return BATTLE_TYPE_FRONTIER_SINGLES;
}

u8 BattleHall_GetPlayerPartySize(u8 challengeType)
{
    if (challengeType == FRONTIER_CHALLENGE_DOUBLE) {
        return 2;
    }
    return 1;
}

u8 BattleHall_GetOpponentPartySize(u8 challengeType)
{
    if (challengeType == FRONTIER_CHALLENGE_DOUBLE) {
        return 2;
    }
    return 1;
}

static void BattleHall_LoadOpponentMonData(FrontierPokemonDataDTO *frontierMon, u8 typeRank, u16 trainerID, u16 opponentIndices[], int partySize, int heapID, int narcID)
{
    u32 ivs;
    if (trainerID == FRONTIER_TRAINER_HALL_MATRON_ARGENTA_SILVER) {
        ivs = MAX_IVS_SINGLE_STAT;
    } else if (trainerID == FRONTIER_TRAINER_HALL_MATRON_ARGENTA_GOLD) {
        ivs = MAX_IVS_SINGLE_STAT;
    } else {
        ivs = BattleHall_GetIVsOfOpponentAtRank(typeRank);
    }

    for (int i = 0; i < partySize; i++) {
        BattleFrontier_LoadOpponentMonData(&frontierMon[i], opponentIndices[i], i, ivs, 0, heapID, narcID);
    }
}

static u32 BattleHall_GetOpponentLevel(BattleHall *battleHall, u8 unused)
{
    u32 level;

    u8 offset = battleHall->currentBattle * 2;

    if (battleHall->trainerIDs[offset] == FRONTIER_TRAINER_HALL_MATRON_ARGENTA_SILVER
        || battleHall->trainerIDs[offset] == FRONTIER_TRAINER_HALL_MATRON_ARGENTA_GOLD) {
        level = BattleHall_GetHighestLevelInParty(battleHall);
    } else {
        level = battleHall->opponentsLevel;
    }

    return level;
}

static const u8 sBattleHallAppGridOrder[20] = {
    TYPE_NORMAL,
    TYPE_FIRE,
    TYPE_WATER,
    TYPE_ELECTRIC,
    TYPE_GRASS,
    TYPE_ICE,
    TYPE_FIGHTING,
    TYPE_POISON,
    TYPE_GROUND,
    TYPE_FLYING,
    TYPE_PSYCHIC,
    TYPE_BUG,
    TYPE_ROCK,
    TYPE_GHOST,
    TYPE_DRAGON,
    TYPE_DARK,
    TYPE_STEEL,
    BATTLE_HALL_MON_SUMMARY,
    BATTLE_HALL_MON_SUMMARY,
    TYPE_MYSTERY
};

u8 BattleHall_CursorPosToType(u8 cursorPos)
{
    return sBattleHallAppGridOrder[cursorPos];
}

BOOL BattleHall_IsMultiPlayerChallenge(u8 challengeType)
{
    return challengeType == FRONTIER_CHALLENGE_MULTI || challengeType == FRONTIER_CHALLENGE_MULTI_WFC;
}

u8 BattleHall_GetHallMatronTypeRank(BattleHall *battleHall)
{
    Party *party = SaveData_GetParty(battleHall->saveData);
    Pokemon *mon = Party_GetPokemonBySlotIndex(party, battleHall->partySlots[0]);
    int level = Pokemon_GetValue(mon, MON_DATA_LEVEL, NULL);

    return level / 10;
}

static u8 BattleHall_GetIVsOfOpponentAtRank(u8 typeRank)
{
    return sIVsPerTypeRank[BattleHall_CheckTypeRank(typeRank)].ivs;
}

static u16 BattleHall_GetAIMask(BattleHall *battleHall, u8 battleNum, u8 rank)
{
    u16 aiMask;

    if (rank + 1 >= 8) {
        aiMask = AI_FLAG_BASIC | AI_FLAG_EVAL_ATTACK | AI_FLAG_EXPERT;
    } else if (rank + 1 >= 4) {
        aiMask = AI_FLAG_BASIC;
    } else {
        aiMask = 0;
    }

    if (battleHall->challengeType == FRONTIER_CHALLENGE_SINGLE) {
        u8 offset = battleNum * 2;

        if (battleHall->trainerIDs[offset] == FRONTIER_TRAINER_HALL_MATRON_ARGENTA_SILVER
            || battleHall->trainerIDs[offset] == FRONTIER_TRAINER_HALL_MATRON_ARGENTA_GOLD) {
            aiMask = AI_FLAG_BASIC | AI_FLAG_EVAL_ATTACK | AI_FLAG_EXPERT;
        }
    }

    if (battleHall->challengeType == FRONTIER_CHALLENGE_MULTI) {
        aiMask = AI_FLAG_BASIC | AI_FLAG_EVAL_ATTACK | AI_FLAG_EXPERT;
    }

    return aiMask;
}

static u16 BattleHall_CheckTypeRank(u8 typeRank)
{
    if (typeRank >= HALL_MAX_TYPE_RANK) {
        typeRank = HALL_MAX_TYPE_RANK - 1;
    }

    return typeRank;
}

u16 BattleHall_GetHighestLevelInParty(BattleHall *battleHall)
{
    Party *party = SaveData_GetParty(battleHall->saveData);
    Pokemon *mon = Party_GetPokemonBySlotIndex(party, battleHall->partySlots[0]);
    u16 firstMonsLevel = Pokemon_GetValue(mon, MON_DATA_LEVEL, NULL);

    if (BattleHall_GetPlayerPartySize(battleHall->challengeType) == 2) {
        mon = Party_GetPokemonBySlotIndex(party, battleHall->partySlots[1]);
        u16 secondMonsLevel = Pokemon_GetValue(mon, MON_DATA_LEVEL, NULL);

        if (firstMonsLevel > secondMonsLevel) {
            return firstMonsLevel;
        } else {
            return secondMonsLevel;
        }
    } else {
        if (BattleHall_IsMultiPlayerChallenge(battleHall->challengeType) == TRUE) {
            if (firstMonsLevel > battleHall->unk_D84[0]) {
                return firstMonsLevel;
            } else {
                return battleHall->unk_D84[0];
            }
        }
    }

    return firstMonsLevel;
}

fx32 BattleHall_GetLevelSquareRoot(u32 level)
{
    return FX_Sqrt(FX32_CONST(level));
}
