#ifndef POKEPLATINUM_APPLICATIONS_BATTLE_CASTLE_WINDOWS_H
#define POKEPLATINUM_APPLICATIONS_BATTLE_CASTLE_WINDOWS_H

#include "bg_window.h"

enum BattleCastleSelfAppWindow {
    SELF_APP_WINDOW_HEADER = 0,
    SELF_APP_WINDOW_EXIT,
    SELF_APP_WINDOW_LEVELS,
    SELF_APP_WINDOW_HP_BARS,
    SELF_APP_WINDOW_SUMMARY_SCREEN,
    SELF_APP_WINDOW_ITEM_SELECT_MENU,
    SELF_APP_WINDOW_MSG_BOX,
    SELF_APP_WINDOW_MON_SELECTION_MSG_BOX,
    SELF_APP_WINDOW_MON_OPTIONS_MSG_BOX,
    SELF_APP_WINDOW_MON_OPTIONS_MENU,
    SELF_APP_WINDOW_HEAL_MENU,
    SELF_APP_WINDOW_RENTAL_MENU,
    SELF_APP_WINDOW_SELECTED_ITEM_NAME,
    SELF_APP_WINDOW_YES_NO_MENU,
    SELF_APP_WINDOW_UNUSED,
    SELF_APP_WINDOW_ITEM_SELECT_PLAYER_INFO,
    SELF_APP_WINDOW_ITEM_SELECT_MON_INFO,
    SELF_APP_WINDOW_ITEM_SELECT_MON_HP,
    NUM_SELF_APP_WINDOWS,
};

enum BattleCastleOpponentAppWindow {
    OPPONENT_APP_WINDOW_HEADER = 0,
    OPPONENT_APP_WINDOW_EXIT,
    OPPONENT_APP_WINDOW_LEVELS,
    OPPONENT_APP_WINDOW_HP_BARS,
    OPPONENT_APP_WINDOW_SUMMARY_SCREEN,
    OPPONENT_APP_WINDOW_MON_OPTIONS_MENU,
    OPPONENT_APP_WINDOW_SUMMARY_MENU,
    OPPONENT_APP_WINDOW_MSG_BOX,
    OPPONENT_APP_WINDOW_MON_SELECTION_MSG_BOX,
    OPPONENT_APP_WINDOW_MON_OPTION_MSG_BOX,
    OPPONENT_APP_WINDOW_YES_NO_MENU,
    OPPONENT_APP_WINDOW_LEVEL_MENU,
    NUM_OPPONENT_APP_WINDOWS,
};

void BattleCastleApp_InitWindows(BgConfig *bgConfigs, Window *windows, u8 isOpponentApp);
void BattleCastleApp_FreeWindows(Window *windows, u8 isOpponentApp);
void BattleCastleApp_DrawWindow(BgConfig *bgConfig, Window *window);
void BattleCastleApp_DrawMessageBox(Window *window, int frame);

#endif // POKEPLATINUM_APPLICATIONS_BATTLE_CASTLE_WINDOWS_H
