#ifndef POKEPLATINUM_OV84_0223B5A0_H
#define POKEPLATINUM_OV84_0223B5A0_H

#include "overlay084/struct_ov84_0223B5A0.h"

#include "overlay_manager.h"

enum BagInterfaceState {
    BAG_INTERFACE_STATE_WAIT_INITIAL_SCREEN_FADE = 0,
    BAG_INTERFACE_STATE_WAIT_SELECT_ITEM_GENERAL,
    BAG_INTERFACE_STATE_2,
    BAG_INTERFACE_STATE_MOVING_ITEM,
    BAG_INTERFACE_STATE_WAIT_SELECT_ITEM_ACTION,
    BAG_INTERFACE_STATE_5,
    BAG_INTERFACE_STATE_6,
    BAG_INTERFACE_STATE_7,
    BAG_INTERFACE_STATE_8,
    BAG_INTERFACE_STATE_9,
    BAG_INTERFACE_STATE_10,
    BAG_INTERFACE_STATE_11,
    BAG_INTERFACE_STATE_12,
    BAG_INTERFACE_STATE_13,
    BAG_INTERFACE_STATE_SELECT_ITEM_TO_GIVE,
    BAG_INTERFACE_STATE_15,
    BAG_INTERFACE_STATE_SELECT_ITEM_TO_SELL,
    BAG_INTERFACE_STATE_17,
    BAG_INTERFACE_STATE_18,
    BAG_INTERFACE_STATE_19,
    BAG_INTERFACE_STATE_20,
    BAG_INTERFACE_STATE_21,
    BAG_INTERFACE_STATE_22,
    BAG_INTERFACE_STATE_SELECT_ITEM_BERRY_CARE,
    BAG_INTERFACE_STATE_EXIT,
};

enum BagInterfaceContext {
    BAG_CONTEXT_FROM_START_MENU = 0,
    BAG_CONTEXT_GIVE_TO_MON,
    BAG_CONTEXT_SELL_ITEMS,
    BAG_CONTEXT_GARDENING,
    BAG_CONTEXT_POFFIN_SINGLEPLAYER,
    BAG_CONTEXT_POFFIN_MULTIPLAYER,
};

enum BagInterfaceExitCode {
    BAG_EXIT_CODE_0 = 0,
    BAG_EXIT_CODE_1,
    BAG_EXIT_CODE_2,
    BAG_EXIT_CODE_3,
    BAG_EXIT_CODE_4,
    BAG_EXIT_CODE_5,
};

enum ItemAction {
    ITEM_ACTION_USE = 0,
    ITEM_ACTION_WALK,
    ITEM_ACTION_CHECK,
    ITEM_ACTION_PLANT,
    ITEM_ACTION_OPEN,
    ITEM_ACTION_TRASH,
    ITEM_ACTION_REGISTER,
    ITEM_ACTION_DESELECT,
    ITEM_ACTION_GIVE,
    ITEM_ACTION_CHECK_TAG,
    ITEM_ACTION_CONFIRM,
    ITEM_ACTION_CANCEL,
    NUM_ITEM_ACTIONS
};

enum BagInterfaceSprite {
    BAG_SPRITE_BAG = 0,
    BAG_SPRITE_POCKET_HIGHLIGHT,
    BAG_SPRITE_POCKET_INDICATOR_LEFT_ARROW,
    BAG_SPRITE_POCKET_INDICATOR_RIGHT_ARROW,
    BAG_SPRITE_ITEM_HIGHLIGHT,
    BAG_SPRITE_ITEM_SORTING_POS,
    BAG_SPRITE_PRESSED_BUTTON_SHOCKWAVE,
    BAG_SPRITE_ITEM,
    BAG_SPRITE_ITEM_COUNT_ARROW_UP,
    BAG_SPRITE_ITEM_COUNT_ARROW_DOWN,
    BAG_SPRITE_MOVE_TYPE,
    BAG_SPRITE_MOVE_CATEGORY,
    NUM_BAG_INTERFACE_SPRITES,
};

enum BagInterfaceWindow {
    BAG_INTERFACE_WINDOW_ITEM_LIST = 0,
    BAG_INTERFACE_WINDOW_ITEM_DESCRIPTION,
    BAG_INTERFACE_WINDOW_POCKET_NAMES,
    BAG_INTERFACE_WINDOW_MSG_BOX,
    BAG_INTERFACE_WINDOW_MSG_BOX_NARROW,
    BAG_INTERFACE_WINDOW_POCKET_INDICATOR,
    BAG_INTERFACE_WINDOW_MSG_BOX_WIDE,
    BAG_INTERFACE_WINDOW_SELL_COUNT_VALUE,
    BAG_INTERFACE_WINDOW_MONEY,
    BAG_INTERFACE_WINDOW_THROW_AWAY_COUNT,
    BAG_INTERFACE_WINDOW_POFFIN_COUNT,
    NUM_BAG_INTERFACE_WINDOWS,
};

enum ItemSlotProperty {
    ITEM_SLOT_ITEM = 0,
    ITEM_SLOT_QUANTITY,
};

int BagInterface_Init(ApplicationManager *appMan, int *state);
int BagInterface_Main(ApplicationManager *appMan, int *state);
int BagInterface_Exit(ApplicationManager *appMan, int *state);
u16 BagInterface_GetItemSlotProperty(BagInterfaceManager *param0, u16 param1, u16 param2);
const u32 GetItemActionFunc(u32 param0);

#endif // POKEPLATINUM_OV84_0223B5A0_H
