#ifndef POKEPLATINUM_STRUCT_OV84_0223B5A0_H
#define POKEPLATINUM_STRUCT_OV84_0223B5A0_H

#include "struct_decls/struct_0207CB08_decl.h"

#include "overlay084/struct_ov84_0223B5A0_sub1.h"
#include "overlay084/struct_ov84_0223C920.h"

#include "bag.h"
#include "bg_window.h"
#include "font_special_chars.h"
#include "game_options.h"
#include "list_menu.h"
#include "menu.h"
#include "message.h"
#include "narc.h"
#include "sprite_system.h"
#include "strbuf.h"
#include "string_list.h"
#include "string_template.h"
#include "trainer_info.h"

typedef struct {
    BgConfig *bgConfig;
    Window windows[11];
    Window itemActionsWindow;
    BagInterfaceArguments *appArguments;
    Bag *bag;
    TrainerInfo *trainerInfo;
    Options *options;
    NARC *bagGraphicsNARC;
    SpriteSystem *spriteSystem;
    SpriteManager *spriteMan;
    ManagedSprite *sprites[12];
    FontSpecialCharsContext *specialChars;
    MessageLoader *bagStringsLoader;
    StringTemplate *strTemplate;
    MessageLoader *itemNamesLoader;
    MessageLoader *moveNamesLoader;
    Strbuf *itemActionStrings[12];
    StringList *itemActionsStringList;
    Menu *itemActionsMenu;
    ListMenu *itemsListMenu;
    StringList *itemsListMenuStringList;
    Strbuf *itemNamesBuffers[165];
    Strbuf *msgBoxText;
    Strbuf *itemCountX;
    Strbuf *itemCountNumberFmt;
    Strbuf *pocketNames[8];
    u8 numPockets;
    u8 trainerGender;
    u8 msgBoxPrinter;
    u8 pocketIndicatorLeftX;
    u8 pocketIndicatorSpacing;
    UnkStruct_ov84_0223C920 unk_429;
    u8 padding_431[35];
    UnkStruct_ov84_0223B5A0_sub1 unk_454;
    u8 nextPocketIdx;
    u8 unk_479;
    u8 movingItem;
    u8 movingItemIndex;
    u32 movingItemID;
    u8 pocketIndicatorArrowsAnimCyclePos;
    u8 pocketIndicatorArrowsAnimTimer;
    u8 unk_482;
    u8 unk_483;
    u32 unk_484;
    s16 selectedItemCount;
    u16 unk_48A;
    u32 soldItemPrice;
    u8 pokeballButtonAnimStep;
    u8 pokeballButtonAnimFrameCount;
    u8 unk_492;
    u8 padding_493;
    s32 unk_494;
    s16 unk_498;
    s16 unk_49A;
    u8 padding_49C[2];
    u16 unk_49E;
    u16 unk_4A0;
    u8 padding_4A2[2];
} BagInterfaceManager;

#endif // POKEPLATINUM_STRUCT_OV84_0223B5A0_H
