swar_gen = generator(nitrosfx_exe,
    arguments: [ '@INPUT@', '@OUTPUT@', '@EXTRA_ARGS@', ],
    output: '@BASENAME@.swar',
)

subdir('WAVE_ARC_BASIC')
subdir('WAVE_ARC_BGM_BATTLE')
subdir('WAVE_ARC_BGM_DEMO01')
subdir('WAVE_ARC_BGM_DUNGEON')
subdir('WAVE_ARC_BGM_FIELD')
subdir('WAVE_ARC_BGM_OPEND')
subdir('WAVE_ARC_SE_BAG')
subdir('WAVE_ARC_SE_BATTLE')
subdir('WAVE_ARC_SE_CLIMAX')
subdir('WAVE_ARC_SE_CONTEST')
subdir('WAVE_ARC_SE_CUSTOM')
subdir('WAVE_ARC_SE_DIG')
subdir('WAVE_ARC_SE_FIELD')
subdir('WAVE_ARC_SE_HIROBA')
subdir('WAVE_ARC_SE_IMAGE')
subdir('WAVE_ARC_SE_NAMEIN')
subdir('WAVE_ARC_SE_NUTMIXER')
subdir('WAVE_ARC_SE_POKELIST')
subdir('WAVE_ARC_SE_SCRATCH')
subdir('WAVE_ARC_SE_SHINKA')
subdir('WAVE_ARC_SE_SHIP')
subdir('WAVE_ARC_SE_SLOT')
subdir('WAVE_ARC_SE_TOWNMAP')
subdir('WAVE_ARC_SE_TRADE')
subdir('WAVE_ARC_SE_TRAIN')
subdir('WAVE_ARC_SE_TRCARD')
subdir('WAVE_ARC_SE_ZUKAN')
