#ifndef POKEPLATINUM_CONSTANTS_COMM_COMMAND_H
#define POKEPLATINUM_CONSTANTS_COMM_COMMAND_H

/*
 * Base Communication Commands used globally.
 */

enum CommCommand_Common {
    COMM_CMD_NONE = 0,
    COMM_CMD_1,
    COMM_CMD_2,
    COMM_CMD_RECV_PLAYER_INFO,
    COMM_CMD_RECV_PLAYER_INFO_ARRAY,
    COMM_CMD_RECV_PLAYER_INFO_FINISH,
    COMM_CMD_VALIDATE_CONFIRMATION,
    COMM_CMD_VALIDATE_CONFIRMATION_RESPONSE,
    COMM_CMD_8,
    COMM_CMD_9,
    COMM_CMD_10,
    COMM_CMD_11,
    COMM_CMD_12,
    COMM_CMD_SWAP_CMD_TABLE,
    COMM_CMD_DEINIT_MANAGER,
    COMM_CMD_FINISH_SWAP_CMD_TABLE,
    COMM_CMD_16,
    COMM_CMD_17,
    COMM_CMD_18,
    COMM_CMD_19,
    COMM_CMD_20,
    COMM_CMD_DISCONNECT_WIFI,
    COMM_CMD_MAX_COMMON,
};

#endif
