#ifndef POKEPLATINUM_CONSTANTS_COMM_AVAILABLE_CONNECTIONS_H
#define POKEPLATINUM_CONSTANTS_COMM_AVAILABLE_CONNECTIONS_H

#define AV_CONNECT_MYSTERY_GIFT (1 << 0)
#define AV_CONNECT_RANGER_LINK  (1 << 1)
#define AV_CONNECT_WII          (1 << 2)

#endif // POKEPLATINUM_CONSTANTS_COMM_AVAILABLE_CONNECTIONS_H
