#ifndef POKEPLATINUM_CONSTANTS_COMM_TYPE_H
#define POKEPLATINUM_CONSTANTS_COMM_TYPE_H

#define COMM_TYPE_TRADE              0
#define COMM_TYPE_SINGLE_BATTLE      1
#define COMM_TYPE_DOUBLE_BATTLE      2
#define COMM_TYPE_MIX_BATTLE         3
#define COMM_TYPE_MULTI_BATTLE_1     4
#define COMM_TYPE_MULTI_BATTLE_2     5
#define COMM_TYPE_POFFIN_MAKING      6
#define COMM_TYPE_MIX_RECORDS        7
#define COMM_TYPE_CONTEST            8

#endif
