#ifndef POKEPLATINUM_CONSTANTS_COMM_SYNC_H
#define POKEPLATINUM_CONSTANTS_COMM_SYNC_H

enum CommSync {
    SYNC_INIT_VS_LINK_BATTLE = 3,
    SYNC_START_VS_LINK_BATTLE,
    SYNC_5,

    SYNC_BATTLE_ROOM_RETURN = 30,

    SYNC_BATTLE_END_CONNECTION = 91,
    SYNC_PAUSE_BATTLE,

    SYNC_94 = 94,
    SYNC_SEND_TRAINER_CASE,

    SYNC_SWITCH_TRANSITION = 97,
    SYNC_CHANGE_TO_BATTLE_ROOM,
};

#endif POKEPLATINUM_CONSTANTS_COMM_SYNC_H
