#ifndef POKEPLATINUM_CONSTANTS_COMM_COMMAND_H
#define POKEPLATINUM_CONSTANTS_COMM_COMMAND_H

// Base Communication Commands used globally.
enum CommCommand_Common {
    COMM_CMD_NONE = 0,
    COMM_CMD_1,
    COMM_CMD_2,
    COMM_CMD_RECV_PLAYER_INFO,
    COMM_CMD_RECV_PLAYER_INFO_ARRAY,
    COMM_CMD_RECV_PLAYER_INFO_FINISH, // 5
    COMM_CMD_VALIDATE_CONFIRMATION,
    COMM_CMD_VALIDATE_CONFIRMATION_RESPONSE,
    COMM_CMD_8,
    COMM_CMD_9,
    COMM_CMD_10, // 10
    COMM_CMD_11,
    COMM_CMD_12,
    COMM_CMD_SWAP_CMD_TABLE,
    COMM_CMD_DEINIT_MANAGER,
    COMM_CMD_FINISH_SWAP_CMD_TABLE,
    COMM_CMD_16,
    COMM_CMD_17,
    COMM_CMD_18,
    COMM_CMD_19,
    COMM_CMD_20,
    COMM_CMD_DISCONNECT_WIFI,
    COMM_CMD_MAX_COMMON,
};

// Communication Commands used for the Frontier
enum CommCommand_Frontier {
    COMM_CMD_F_22 = COMM_CMD_MAX_COMMON,
    COMM_CMD_F_23,
    COMM_CMD_F_24,
    COMM_CMD_F_25,
    COMM_CMD_F_26,
    COMM_CMD_F_27,
    COMM_CMD_F_28,
    COMM_CMD_FACTORY_DUMMY,
    COMM_CMD_FACTORY_SELECTION_UPDATE, // 30
    COMM_CMD_FACTORY_DUMMY2,
    COMM_CMD_FACTORY_TRADE_RESULT,
    COMM_CMD_F_33,
    COMM_CMD_F_34,
    COMM_CMD_F_35,
    COMM_CMD_F_36,
    COMM_CMD_F_37,
    COMM_CMD_F_38,
    COMM_CMD_HALL_DUMMY,
    COMM_CMD_HALL_TYPE_SELECTION_MSG, // 40
    COMM_CMD_HALL_PARTNER_DECISION,
    COMM_CMD_F_42,
    COMM_CMD_F_43,
    COMM_CMD_F_44,
    COMM_CMD_F_45,
    COMM_CMD_F_46,
    COMM_CMD_F_47,
    COMM_CMD_F_48,
    COMM_CMD_CASTLE_PLAYER_INFO,
    COMM_CMD_CASTLE_PURCHASE_INFO, // 50
    COMM_CMD_CASTLE_UPDATE_CURSOR,
    COMM_CMD_CASTLE_EXIT,
    COMM_CMD_CASTLE_OPP_PLAYER_INFO,
    COMM_CMD_CASTLE_OPP_PURCHASE_INFO,
    COMM_CMD_CASTLE_OPP_UPDATE_CURSOR, // 55
    COMM_CMD_CASTLE_OPP_EXIT,
    COMM_CMD_F_57,
    COMM_CMD_F_58,
    COMM_CMD_F_59,
    COMM_CMD_F_60,
    COMM_CMD_F_61,
    COMM_CMD_F_62,
    COMM_CMD_F_63,
    COMM_CMD_F_64,
    COMM_CMD_F_65,
    COMM_CMD_F_66,
    COMM_CMD_F_67,
    COMM_CMD_F_68,
    COMM_CMD_F_69,
    COMM_CMD_F_70,
    COMM_CMD_ARCADE_INIT_LAYOUT,
    COMM_CMD_ARCADE_RESULT,
    COMM_CMD_ARCADE_UNUSED,
    COMM_CMD_MAX_FRONTIER,
};

// Communication Commands used for Overlay 117

enum CommCommand_Ov117 {
    COMM_CMD_OV117_NONE = COMM_CMD_MAX_COMMON,
    COMM_CMD_OV117_23,
    COMM_CMD_OV117_24,
    COMM_CMD_OV117_25,
    COMM_CMD_MAX_OV117,
};

#endif
