#ifndef POKEPLATINUM_CONSTANTS_COMM_PACKETS_H
#define POKEPLATINUM_CONSTANTS_COMM_PACKETS_H

//Comm Packet Sizes
#define COMM_PACKET_SIZE_LOCATION       5
#define COMM_PACKET_SIZE_POS_NETID      4


#endif
