#ifndef POKEPLATINUM_CONSTANTS_COMM_TYPE_H
#define POKEPLATINUM_CONSTANTS_COMM_TYPE_H

#define COMM_TYPE_TRADE          0
#define COMM_TYPE_SINGLE_BATTLE  1
#define COMM_TYPE_DOUBLE_BATTLE  2
#define COMM_TYPE_MIX_BATTLE     3
#define COMM_TYPE_MULTI_BATTLE_1 4
#define COMM_TYPE_MULTI_BATTLE_2 5
#define COMM_TYPE_POFFIN_MAKING  6
#define COMM_TYPE_MIX_RECORDS    7
#define COMM_TYPE_CONTEST        8
#define COMM_TYPE_UNION          9
#define COMM_TYPE_UNDERGROUND   10
#define COMM_TYPE_11            11
#define COMM_TYPE_12            12
#define COMM_TYPE_DRAW            13
#define COMM_TYPE_POKETCH            14
#define COMM_TYPE_MYSTERY_GIFT  15
#define COMM_TYPE_MULTI_BATTLE_FRONTIER  16
#define COMM_TYPE_PARTY  17
#define COMM_TYPE_UNION_APP  18
#define COMM_TYPE_SINGLE_BATTLE_WIFI  19

#define COMM_TYPE_LOGIN_WIFI 23
#define COMM_TYPE_24 24
#define COMM_TYPE_25 25
#define COMM_TYPE_SPIN_TRADE 26

#define COMM_TYPE_POFFIN_WIFI 29

#define COMM_TYPE_LOBBY_WIFI 33
#define COMM_TYPE_FRONTIER_WIFI 34
#define COMM_TYPE_CLUB_WIFI 35
#define COMM_TYPE_EMAIL_WIFI 36

#endif
