#include "main_menu/gba_convert_string.h"

#include <nitro.h>
#include <string.h>

#include "constants/charcode.h"

#include "charcode.h"

#define GBA_EOS 0xFF

// Japanese, International
static const charcode_t sGBACharToDSChars[][2] = {
    { CHAR_WIDE_SPACE, CHAR_WIDE_SPACE },
    { CHAR_HIRAGANA_A, CHAR_HIRAGANA_A },
    { CHAR_HIRAGANA_I, CHAR_HIRAGANA_I },
    { CHAR_HIRAGANA_U, CHAR_HIRAGANA_U },
    { CHAR_HIRAGANA_E, CHAR_HIRAGANA_E },
    { CHAR_HIRAGANA_O, CHAR_HIRAGANA_O },
    { CHAR_HIRAGANA_KA, CHAR_HIRAGANA_KA },
    { CHAR_HIRAGANA_KI, CHAR_HIRAGANA_KI },
    { CHAR_HIRAGANA_KU, CHAR_HIRAGANA_KU },
    { CHAR_HIRAGANA_KE, CHAR_HIRAGANA_KE },
    { CHAR_HIRAGANA_KO, CHAR_HIRAGANA_KO },
    { CHAR_HIRAGANA_SA, CHAR_HIRAGANA_SA },
    { CHAR_HIRAGANA_SHI, CHAR_HIRAGANA_SHI },
    { CHAR_HIRAGANA_SU, CHAR_HIRAGANA_SU },
    { CHAR_HIRAGANA_SE, CHAR_HIRAGANA_SE },
    { CHAR_HIRAGANA_SO, CHAR_HIRAGANA_SO },
    { CHAR_HIRAGANA_TA, CHAR_HIRAGANA_TA },
    { CHAR_HIRAGANA_CHI, CHAR_HIRAGANA_CHI },
    { CHAR_HIRAGANA_TSU, CHAR_HIRAGANA_TSU },
    { CHAR_HIRAGANA_TE, CHAR_HIRAGANA_TE },
    { CHAR_HIRAGANA_TO, CHAR_HIRAGANA_TO },
    { CHAR_HIRAGANA_NA, CHAR_HIRAGANA_NA },
    { CHAR_HIRAGANA_NI, CHAR_HIRAGANA_NI },
    { CHAR_HIRAGANA_NU, CHAR_HIRAGANA_NU },
    { CHAR_HIRAGANA_NE, CHAR_HIRAGANA_NE },
    { CHAR_HIRAGANA_NO, CHAR_HIRAGANA_NO },
    { CHAR_HIRAGANA_HA, CHAR_HIRAGANA_HA },
    { CHAR_HIRAGANA_HI, CHAR_HIRAGANA_HI },
    { CHAR_HIRAGANA_FU, CHAR_HIRAGANA_FU },
    { CHAR_HIRAGANA_HE, CHAR_HIRAGANA_HE },
    { CHAR_HIRAGANA_HO, CHAR_HIRAGANA_HO },
    { CHAR_HIRAGANA_MA, CHAR_HIRAGANA_MA },
    { CHAR_HIRAGANA_MI, CHAR_HIRAGANA_MI },
    { CHAR_HIRAGANA_MU, CHAR_HIRAGANA_MU },
    { CHAR_HIRAGANA_ME, CHAR_HIRAGANA_ME },
    { CHAR_HIRAGANA_MO, CHAR_HIRAGANA_MO },
    { CHAR_HIRAGANA_YA, CHAR_HIRAGANA_YA },
    { CHAR_HIRAGANA_YU, CHAR_HIRAGANA_YU },
    { CHAR_HIRAGANA_YO, CHAR_HIRAGANA_YO },
    { CHAR_HIRAGANA_RA, CHAR_HIRAGANA_RA },
    { CHAR_HIRAGANA_RI, CHAR_HIRAGANA_RI },
    { CHAR_HIRAGANA_RU, CHAR_HIRAGANA_RU },
    { CHAR_HIRAGANA_RE, CHAR_HIRAGANA_RE },
    { CHAR_HIRAGANA_RO, CHAR_HIRAGANA_RO },
    { CHAR_HIRAGANA_WA, CHAR_HIRAGANA_WA },
    { CHAR_HIRAGANA_WO, CHAR_HIRAGANA_WO },
    { CHAR_HIRAGANA_N, CHAR_HIRAGANA_N },
    { CHAR_HIRAGANA_SMALL_A, CHAR_HIRAGANA_SMALL_A },
    { CHAR_HIRAGANA_SMALL_I, CHAR_HIRAGANA_SMALL_I },
    { CHAR_HIRAGANA_SMALL_U, CHAR_HIRAGANA_SMALL_U },
    { CHAR_HIRAGANA_SMALL_E, CHAR_HIRAGANA_SMALL_E },
    { CHAR_HIRAGANA_SMALL_O, CHAR_HIRAGANA_SMALL_O },
    { CHAR_HIRAGANA_SMALL_YA, CHAR_HIRAGANA_SMALL_YA },
    { CHAR_HIRAGANA_SMALL_YU, CHAR_HIRAGANA_SMALL_YU },
    { CHAR_HIRAGANA_SMALL_YO, CHAR_HIRAGANA_SMALL_YO },
    { CHAR_HIRAGANA_GA, CHAR_HIRAGANA_GA },
    { CHAR_HIRAGANA_GI, CHAR_HIRAGANA_GI },
    { CHAR_HIRAGANA_GU, CHAR_HIRAGANA_GU },
    { CHAR_HIRAGANA_GE, CHAR_HIRAGANA_GE },
    { CHAR_HIRAGANA_GO, CHAR_HIRAGANA_GO },
    { CHAR_HIRAGANA_ZA, CHAR_HIRAGANA_ZA },
    { CHAR_HIRAGANA_JI, CHAR_HIRAGANA_JI },
    { CHAR_HIRAGANA_ZU, CHAR_HIRAGANA_ZU },
    { CHAR_HIRAGANA_ZE, CHAR_HIRAGANA_ZE },
    { CHAR_HIRAGANA_ZO, CHAR_HIRAGANA_ZO },
    { CHAR_HIRAGANA_DA, CHAR_HIRAGANA_DA },
    { CHAR_HIRAGANA_DJI, CHAR_HIRAGANA_DJI },
    { CHAR_HIRAGANA_DZU, CHAR_HIRAGANA_DZU },
    { CHAR_HIRAGANA_DE, CHAR_HIRAGANA_DE },
    { CHAR_HIRAGANA_DO, CHAR_HIRAGANA_DO },
    { CHAR_HIRAGANA_BA, CHAR_HIRAGANA_BA },
    { CHAR_HIRAGANA_BI, CHAR_HIRAGANA_BI },
    { CHAR_HIRAGANA_BU, CHAR_HIRAGANA_BU },
    { CHAR_HIRAGANA_BE, CHAR_HIRAGANA_BE },
    { CHAR_HIRAGANA_BO, CHAR_HIRAGANA_BO },
    { CHAR_HIRAGANA_PA, CHAR_HIRAGANA_PA },
    { CHAR_HIRAGANA_PI, CHAR_HIRAGANA_PI },
    { CHAR_HIRAGANA_PU, CHAR_HIRAGANA_PU },
    { CHAR_HIRAGANA_PE, CHAR_HIRAGANA_PE },
    { CHAR_HIRAGANA_PO, CHAR_HIRAGANA_PO },
    { CHAR_HIRAGANA_SOKUON, CHAR_HIRAGANA_SOKUON },
    { CHAR_KATAKANA_A, CHAR_KATAKANA_A },
    { CHAR_KATAKANA_I, CHAR_KATAKANA_I },
    { CHAR_KATAKANA_U, CHAR_KATAKANA_U },
    { CHAR_KATAKANA_E, CHAR_KATAKANA_E },
    { CHAR_KATAKANA_O, CHAR_KATAKANA_O },
    { CHAR_KATAKANA_KA, CHAR_KATAKANA_KA },
    { CHAR_KATAKANA_KI, CHAR_KATAKANA_KI },
    { CHAR_KATAKANA_KU, CHAR_KATAKANA_KU },
    { CHAR_KATAKANA_KE, CHAR_KATAKANA_KE },
    { CHAR_KATAKANA_KO, CHAR_KATAKANA_KO },
    { CHAR_KATAKANA_SA, CHAR_KATAKANA_SA },
    { CHAR_KATAKANA_SHI, CHAR_KATAKANA_SHI },
    { CHAR_KATAKANA_SU, CHAR_KATAKANA_SU },
    { CHAR_KATAKANA_SE, CHAR_KATAKANA_SE },
    { CHAR_KATAKANA_SO, CHAR_KATAKANA_SO },
    { CHAR_KATAKANA_TA, CHAR_KATAKANA_TA },
    { CHAR_KATAKANA_CHI, CHAR_KATAKANA_CHI },
    { CHAR_KATAKANA_TSU, CHAR_KATAKANA_TSU },
    { CHAR_KATAKANA_TE, CHAR_KATAKANA_TE },
    { CHAR_KATAKANA_TO, CHAR_KATAKANA_TO },
    { CHAR_KATAKANA_NA, CHAR_KATAKANA_NA },
    { CHAR_KATAKANA_NI, CHAR_KATAKANA_NI },
    { CHAR_KATAKANA_NU, CHAR_KATAKANA_NU },
    { CHAR_KATAKANA_NE, CHAR_KATAKANA_NE },
    { CHAR_KATAKANA_NO, CHAR_KATAKANA_NO },
    { CHAR_KATAKANA_HA, CHAR_KATAKANA_HA },
    { CHAR_KATAKANA_HI, CHAR_KATAKANA_HI },
    { CHAR_KATAKANA_FU, CHAR_KATAKANA_FU },
    { CHAR_KATAKANA_HE, CHAR_KATAKANA_HE },
    { CHAR_KATAKANA_HO, CHAR_KATAKANA_HO },
    { CHAR_KATAKANA_MA, CHAR_KATAKANA_MA },
    { CHAR_KATAKANA_MI, CHAR_KATAKANA_MI },
    { CHAR_KATAKANA_MU, CHAR_KATAKANA_MU },
    { CHAR_KATAKANA_ME, CHAR_KATAKANA_ME },
    { CHAR_KATAKANA_MO, CHAR_KATAKANA_MO },
    { CHAR_KATAKANA_YA, CHAR_KATAKANA_YA },
    { CHAR_KATAKANA_YU, CHAR_KATAKANA_YU },
    { CHAR_KATAKANA_YO, CHAR_KATAKANA_YO },
    { CHAR_KATAKANA_RA, CHAR_KATAKANA_RA },
    { CHAR_KATAKANA_RI, CHAR_KATAKANA_RI },
    { CHAR_KATAKANA_RU, CHAR_KATAKANA_RU },
    { CHAR_KATAKANA_RE, CHAR_KATAKANA_RE },
    { CHAR_KATAKANA_RO, CHAR_KATAKANA_RO },
    { CHAR_KATAKANA_WA, CHAR_KATAKANA_WA },
    { CHAR_KATAKANA_WO, CHAR_KATAKANA_WO },
    { CHAR_KATAKANA_N, CHAR_KATAKANA_N },
    { CHAR_KATAKANA_SMALL_A, CHAR_KATAKANA_SMALL_A },
    { CHAR_KATAKANA_SMALL_I, CHAR_KATAKANA_SMALL_I },
    { CHAR_KATAKANA_SMALL_U, CHAR_KATAKANA_SMALL_U },
    { CHAR_KATAKANA_SMALL_E, CHAR_KATAKANA_SMALL_E },
    { CHAR_KATAKANA_SMALL_O, CHAR_KATAKANA_SMALL_O },
    { CHAR_KATAKANA_SMALL_YA, CHAR_KATAKANA_SMALL_YA },
    { CHAR_KATAKANA_SMALL_YU, CHAR_KATAKANA_SMALL_YU },
    { CHAR_KATAKANA_SMALL_YO, CHAR_KATAKANA_SMALL_YO },
    { CHAR_KATAKANA_GA, CHAR_KATAKANA_GA },
    { CHAR_KATAKANA_GI, CHAR_KATAKANA_GI },
    { CHAR_KATAKANA_GU, CHAR_KATAKANA_GU },
    { CHAR_KATAKANA_GE, CHAR_KATAKANA_GE },
    { CHAR_KATAKANA_GO, CHAR_KATAKANA_GO },
    { CHAR_KATAKANA_ZA, CHAR_KATAKANA_ZA },
    { CHAR_KATAKANA_JI, CHAR_KATAKANA_JI },
    { CHAR_KATAKANA_ZU, CHAR_KATAKANA_ZU },
    { CHAR_KATAKANA_ZE, CHAR_KATAKANA_ZE },
    { CHAR_KATAKANA_ZO, CHAR_KATAKANA_ZO },
    { CHAR_KATAKANA_DA, CHAR_KATAKANA_DA },
    { CHAR_KATAKANA_DJI, CHAR_KATAKANA_DJI },
    { CHAR_KATAKANA_DZU, CHAR_KATAKANA_DZU },
    { CHAR_KATAKANA_DE, CHAR_KATAKANA_DE },
    { CHAR_KATAKANA_DO, CHAR_KATAKANA_DO },
    { CHAR_KATAKANA_BA, CHAR_KATAKANA_BA },
    { CHAR_KATAKANA_BI, CHAR_KATAKANA_BI },
    { CHAR_KATAKANA_BU, CHAR_KATAKANA_BU },
    { CHAR_KATAKANA_BE, CHAR_KATAKANA_BE },
    { CHAR_KATAKANA_BO, CHAR_KATAKANA_BO },
    { CHAR_KATAKANA_PA, CHAR_KATAKANA_PA },
    { CHAR_KATAKANA_PI, CHAR_KATAKANA_PI },
    { CHAR_KATAKANA_PU, CHAR_KATAKANA_PU },
    { CHAR_KATAKANA_PE, CHAR_KATAKANA_PE },
    { CHAR_KATAKANA_PO, CHAR_KATAKANA_PO },
    { CHAR_KATAKANA_SOKUON, CHAR_KATAKANA_SOKUON },
    { CHAR_WIDE_0, CHAR_0 },
    { CHAR_WIDE_1, CHAR_1 },
    { CHAR_WIDE_2, CHAR_2 },
    { CHAR_WIDE_3, CHAR_3 },
    { CHAR_WIDE_4, CHAR_4 },
    { CHAR_WIDE_5, CHAR_5 },
    { CHAR_WIDE_6, CHAR_6 },
    { CHAR_WIDE_7, CHAR_7 },
    { CHAR_WIDE_8, CHAR_8 },
    { CHAR_WIDE_9, CHAR_9 },
    { CHAR_WIDE_EXCLAMATION, CHAR_EXCLAMATION },
    { CHAR_WIDE_QUESTION, CHAR_QUESTION },
    { CHAR_JP_PERIOD, CHAR_PERIOD },
    { CHAR_WIDE_MINUS, CHAR_MINUS },
    { CHAR_JP_DOT, CHAR_DOT },
    { CHAR_JP_ELLIPSIS, CHAR_ELLIPSIS },
    { CHAR_JP_DOUBLE_QUOTE_OPEN, CHAR_JP_DOUBLE_QUOTE_OPEN },
    { CHAR_JP_DOUBLE_QUOTE_CLOSE, CHAR_JP_DOUBLE_QUOTE_CLOSE },
    { CHAR_JP_SINGLE_QUOTE_OPEN, CHAR_SINGLE_QUOTE_OPEN },
    { CHAR_JP_SINGLE_QUOTE_CLOSE, CHAR_SINGLE_QUOTE_CLOSE },
    { CHAR_WIDE_MALE, CHAR_MALE },
    { CHAR_WIDE_FEMALE, CHAR_FEMALE },
    { CHAR_YEN, CHAR_YEN },
    { CHAR_JP_COMMA, CHAR_COMMA },
    { CHAR_WIDE_MULTIPLY, CHAR_MULTIPLY },
    { CHAR_WIDE_SLASH, CHAR_SLASH },
    { CHAR_WIDE_A, CHAR_A },
    { CHAR_WIDE_B, CHAR_B },
    { CHAR_WIDE_C, CHAR_C },
    { CHAR_WIDE_D, CHAR_D },
    { CHAR_WIDE_E, CHAR_E },
    { CHAR_WIDE_F, CHAR_F },
    { CHAR_WIDE_G, CHAR_G },
    { CHAR_WIDE_H, CHAR_H },
    { CHAR_WIDE_I, CHAR_I },
    { CHAR_WIDE_J, CHAR_J },
    { CHAR_WIDE_K, CHAR_K },
    { CHAR_WIDE_L, CHAR_L },
    { CHAR_WIDE_M, CHAR_M },
    { CHAR_WIDE_N, CHAR_N },
    { CHAR_WIDE_O, CHAR_O },
    { CHAR_WIDE_P, CHAR_P },
    { CHAR_WIDE_Q, CHAR_Q },
    { CHAR_WIDE_R, CHAR_R },
    { CHAR_WIDE_S, CHAR_S },
    { CHAR_WIDE_T, CHAR_T },
    { CHAR_WIDE_U, CHAR_U },
    { CHAR_WIDE_V, CHAR_V },
    { CHAR_WIDE_W, CHAR_W },
    { CHAR_WIDE_X, CHAR_X },
    { CHAR_WIDE_Y, CHAR_Y },
    { CHAR_WIDE_Z, CHAR_Z },
    { CHAR_WIDE_a, CHAR_a },
    { CHAR_WIDE_b, CHAR_b },
    { CHAR_WIDE_c, CHAR_c },
    { CHAR_WIDE_d, CHAR_d },
    { CHAR_WIDE_e, CHAR_e },
    { CHAR_WIDE_f, CHAR_f },
    { CHAR_WIDE_g, CHAR_g },
    { CHAR_WIDE_h, CHAR_h },
    { CHAR_WIDE_i, CHAR_i },
    { CHAR_WIDE_j, CHAR_j },
    { CHAR_WIDE_k, CHAR_k },
    { CHAR_WIDE_l, CHAR_l },
    { CHAR_WIDE_m, CHAR_m },
    { CHAR_WIDE_n, CHAR_n },
    { CHAR_WIDE_o, CHAR_o },
    { CHAR_WIDE_p, CHAR_p },
    { CHAR_WIDE_q, CHAR_q },
    { CHAR_WIDE_r, CHAR_r },
    { CHAR_WIDE_s, CHAR_s },
    { CHAR_WIDE_t, CHAR_t },
    { CHAR_WIDE_u, CHAR_u },
    { CHAR_WIDE_v, CHAR_v },
    { CHAR_WIDE_w, CHAR_w },
    { CHAR_WIDE_x, CHAR_x },
    { CHAR_WIDE_y, CHAR_y },
    { CHAR_WIDE_z, CHAR_z },
    { CHAR_ARROW_MENU, CHAR_ARROW_MENU },
    { CHAR_WIDE_COLON, CHAR_COLON },
    { CHAR_A_DIERESIS, CHAR_A_DIERESIS },
    { CHAR_O_DIERSIS, CHAR_O_DIERSIS },
    { CHAR_U_DIERESIS, CHAR_U_DIERESIS },
    { CHAR_a_DIERESIS, CHAR_a_DIERESIS },
    { CHAR_o_DIERSIS, CHAR_o_DIERSIS },
    { CHAR_u_DIERESIS, CHAR_u_DIERESIS }
};

static u16 GetSpaceChar(u32 language)
{
    return (language == JAPANESE) ? CHAR_WIDE_SPACE : CHAR_SPACE;
}

static u16 GetDoubleQuoteOpenChar(u32 language)
{
    switch (language) {
    case JAPANESE:
    default:
        return CHAR_JP_DOUBLE_QUOTE_OPEN;
    case ENGLISH:
    case ITALIAN:
    case SPANISH:
        return CHAR_DOUBLE_QUOTE_OPEN;
    case FRENCH:
        return CHAR_DOUBLE_PAREN_OPEN;
    case GERMAN:
        return CHAR_DOUBLE_QUOTE_CLOSE_INVERTED;
    }
}

static u16 GetDoubleQuoteCloseChar(u32 language)
{
    switch (language) {
    case JAPANESE:
    default:
        return CHAR_JP_DOUBLE_QUOTE_CLOSE;
    case ENGLISH:
    case ITALIAN:
    case SPANISH:
        return CHAR_DOUBLE_QUOTE_CLOSE;
    case FRENCH:
        return CHAR_DOUBLE_PAREN_CLOSE;
    case GERMAN:
        return CHAR_DOUBLE_QUOTE_OPEN;
    }
}

BOOL GBA_ConvertStringToDS(const u8 *src, charcode_t *dst, u32 length, u32 language)
{
    BOOL nonJa = (language != JAPANESE);

    u32 i;
    for (i = 0; i < (length - 1); i++) {
        if (src[i] == GBA_EOS) {
            break;
        }

        if (src[i] >= NELEMS(sGBACharToDSChars)) {
            int invalidStrLen = min(length - 1, 10);

            int j;
            for (j = 0; j < invalidStrLen; j++) {
                dst[j] = CHAR_QUESTION;
            }

            dst[j] = CHAR_EOS;
            return FALSE;
        }

        switch (sGBACharToDSChars[src[i]][nonJa]) {
        case CHAR_WIDE_SPACE:
            dst[i] = GetSpaceChar(language);
            break;
        case CHAR_JP_DOUBLE_QUOTE_OPEN:
            dst[i] = GetDoubleQuoteOpenChar(language);
            break;
        case CHAR_JP_DOUBLE_QUOTE_CLOSE:
            dst[i] = GetDoubleQuoteCloseChar(language);
            break;
        default:
            dst[i] = sGBACharToDSChars[src[i]][nonJa];
            break;
        }
    }

    dst[i] = CHAR_EOS;
    return TRUE;
}
