#ifndef POKEPLATINUM_GTS_SCREENS_SEARCH_H
#define POKEPLATINUM_GTS_SCREENS_SEARCH_H

#include "gts_application/gts.h"

int GTSApplication_Search_Init(GTSApplicationState *appState, int unused);
int GTSApplication_Search_Main(GTSApplicationState *appState, int unused);
int GTSApplication_Search_Exit(GTSApplicationState *appState, int unused);

enum GTSSearchStateHandlers {
    GTS_SEARCH_SHOW_PROMPT,
    GTS_SEARCH_HANDLE_INPUT,
    GTS_SEARCH_FADE_AND_EXIT,
    GTS_SEARCH_SHOW_SPECIES_SEARCH_PROMPT,
    GTS_SEARCH_CREATE_CHARPAD,
    GTS_SEARCH_HANDLE_CHARPAD_INPUT,
    GTS_SEARCH_CREATE_SPECIES_MENU,
    GTS_SEARCH_HANDLE_SPECIES_MENU_INPUT,
    GTS_SEARCH_SHOW_GENDER_SEARCH_PROMPT,
    GTS_SEARCH_CREATE_GENDER_MENU,
    GTS_SEARCH_HANDLE_GENDER_MENU_INPUT,
    GTS_SEARCH_SHOW_LEVEL_SEARCH_PROMPT,
    GTS_SEARCH_CREATE_LEVEL_MENU,
    GTS_SEARCH_HANDLE_LEVEL_MENU_INPUT,
    GTS_SEARCH_SHOW_COUNTRY_SEARCH_PROMPT,
    GTS_SEARCH_CREATE_COUNTRY_MENU,
    GTS_SEARCH_HANDLE_COUNTRY_MENU_INPUT,
    GTS_SEARCH_SUBMIT_SEARCH,
    GTS_SEARCH_SEND_SEARCH_REQUEST,
    GTS_SEARCH_WAIT_FOR_SEARCH_RESULTS,
    GTS_SEARCH_SHOW_RESULTS_MESSAGE,
    GTS_SEARCH_WAIT_FOR_RESULTS_REVEAL,
    GTS_SEARCH_SHOW_INVALID_SEARCH_MESSAGE,
    GTS_SEARCH_WAIT_FOR_TEXT,
    GTS_SEARCH_WAIT_FOR_TEXT_WITH_DELAY,
    GTS_SEARCH_CREATE_EXIT_CONFIRM_MENU,
    GTS_SEARCH_HANDLE_EXIT_CONFIRM,
    GTS_SEARCH_IDLE,
    GTS_SEARCH_SHOW_SEARCH_PROMPT_AGAIN,
    GTS_SEARCH_SHOW_SERVER_MAINTENANCE_MESSAGE,
    GTS_SEARCH_DISCONNECT_AND_EXIT
};

enum GTSSearchCursorIndex {
    GTS_SEARCH_CURSOR_SPECIES,
    GTS_SEARCH_CURSOR_GENDER,
    GTS_SEARCH_CURSOR_LEVEL,
    GTS_SEARCH_CURSOR_LOCATION,
    GTS_SEARCH_CURSOR_SEARCH,
    GTS_SEARCH_CURSOR_BACK
};

#endif // POKEPLATINUM_GTS_SCREENS_SEARCH_H
