#ifndef POKEPLATINUM_HTTP_HTTP_H
#define POKEPLATINUM_HTTP_HTTP_H

void HTTP_Init(void);
int HTTP_PrepareRequest(const u8 *url, int dwcProfileID, const void *data, int dataSize, u8 *response, int maxResponseLength);
int HTTP_GetRequestStatus(void);
void HTTP_Shutdown(void);
int HTTP_GetErrorCode(void);
int HTTP_GetResponseLength(void);

enum HttpRequestStatus {
    HTTP_STATUS_NONE,
    HTTP_STATUS_IDLE,
    HTTP_STATUS_INITIALIZED,
    HTTP_STATUS_TOKEN_READY,
    HTTP_STATUS_TOKEN_PENDING,
    HTTP_STATUS_REQUEST_READY,
    HTTP_STATUS_REQUEST_PENDING,
    HTTP_STATUS_COMPLETE,
};

enum DwcError {
    DWC_ERROR_GHTTP_IN_ERROR,
    DWC_ERROR_GHTTP_INVALID_POST,
    DWC_ERROR_GHTTP_INSUFFICIENT_MEMORY,
    DWC_ERROR_GHTTP_INVALID_FILE_NAME,
    DWC_ERROR_GHTTP_INVALID_BUFFER_SIZE,
    DWC_ERROR_GHTTP_INVALID_URL,
    DWC_ERROR_GHTTP_UNSPECIFIED_ERROR,
    DWC_ERROR_GHTTP_7,
    DWC_ERROR_GHTTP_OUT_OF_MEMORY,
    DWC_ERROR_GHTTP_BUFFER_OVERFLOW,
    DWC_ERROR_GHTTP_PARSE_URL_FAILED,
    DWC_ERROR_GHTTP_HOST_LOOKUP_FAILED,
    DWC_ERROR_GHTTP_SOCKET_FAILED,
    DWC_ERROR_GHTTP_CONNECT_FAILED,
    DWC_ERROR_GHTTP_BAD_RESPONSE,
    DWC_ERROR_GHTTP_REQUEST_REJECTED,
    DWC_ERROR_GHTTP_UNAUTHORIZED,
    DWC_ERROR_GHTTP_FORBIDDEN,
    DWC_ERROR_GHTTP_FILE_NOT_FOUND,
    DWC_ERROR_GHTTP_SERVER_ERROR,
    DWC_ERROR_GHTTP_20,
    DWC_ERROR_GHTTP_21,
    DWC_ERROR_GHTTP_FILE_INCOMPLETE,
    DWC_ERROR_GHTTP_FILE_TOO_BIG,
    DWC_ERROR_GHTTP_24,
    DWC_ERROR_GHTTP_MEMORY_ERROR,
    DWC_ERROR_GHTTP_26,
    DWC_ERROR_GHTTP_27,
    DWC_ERROR_GHTTP_28,
    DWC_ERROR_GHTTP_29,
    DWC_ERROR_GHTTP_30,
    DWC_ERROR_GHTTP_31,
    DWC_ERROR_GHTTP_32,
};

#endif // POKEPLATINUM_HTTP_HTTP_H
