sbnk_gen = generator(nitrosfx_exe,
    arguments: [ '@INPUT@', '@OUTPUT@', '@EXTRA_ARGS@', ],
    output: '@BASENAME@.sbnk',
)

sound_bank_files = files([
    'BANK_BASIC.txt',
    'BANK_BGM_BATTLE.txt',
    'BANK_BGM_DEMO01.txt',
    'BANK_BGM_DUNGEON.txt',
    'BANK_BGM_FIELD.txt',
    'BANK_BGM_OPEND.txt',
    'BANK_SE_BAG.txt',
    'BANK_SE_BATTLE.txt',
    'BANK_SE_CLIMAX.txt',
    'BANK_SE_CONTEST.txt',
    'BANK_SE_CUSTOM.txt',
    'BANK_SE_DIG.txt',
    'BANK_SE_FIELD.txt',
    'BANK_SE_HIROBA.txt',
    'BANK_SE_IMAGE.txt',
    'BANK_SE_NAMEIN.txt',
    'BANK_SE_NUTMIXER.txt',
    'BANK_SE_POKELIST.txt',
    'BANK_SE_SCRATCH.txt',
    'BANK_SE_SHINKA.txt',
    'BANK_SE_SHIP.txt',
    'BANK_SE_SLOT.txt',
    'BANK_SE_TOWNMAP.txt',
    'BANK_SE_TRADE.txt',
    'BANK_SE_TRAIN.txt',
    'BANK_SE_TRCARD.txt',
    'BANK_SE_ZUKAN.txt',
])
