#ifndef POKEPLATINUM_CONSTANTS_FIELD_DYNAMIC_MAP_FEATURES_H
#define POKEPLATINUM_CONSTANTS_FIELD_DYNAMIC_MAP_FEATURES_H

enum DynamicMapFeatureID {
    DYNAMIC_MAP_FEATURES_NONE = 0,
    DYNAMIC_MAP_FEATURES_PASTORIA_GYM,
    DYNAMIC_MAP_FEATURES_HEARTHOME_GYM,
    DYNAMIC_MAP_FEATURES_CANALAVE_GYM,
    DYNAMIC_MAP_FEATURES_VEILSTONE_GYM,
    DYNAMIC_MAP_FEATURES_SUNYSHORE_GYM,
    DYNAMIC_MAP_FEATURES_GREAT_MARSH,
    DYNAMIC_MAP_FEATURES_PLATFORM_LIFT_ROOM,
    DYNAMIC_MAP_FEATURES_ETERNA_GYM,
    DYNAMIC_MAP_FEATURES_DISTORTION_WORLD,
    DYNAMIC_MAP_FEATURES_VILLA,
    DYNAMIC_MAP_FEATURES_COUNT
};

#endif // POKEPLATINUM_CONSTANTS_FIELD_DYNAMIC_MAP_FEATURES_H
