#ifndef POKEPLATINUM_CONSTANTS_FIELD_MAP_H
#define POKEPLATINUM_CONSTANTS_FIELD_MAP_H

#include <nitro/fx/fx_const.h>

#define MAP_OBJECT_TILE_SIZE (16 * FX32_ONE)

#define MAP_TILES_COUNT_X 32
#define MAP_TILES_COUNT_Y 32

#endif // POKEPLATINUM_CONSTANTS_FIELD_MAP_H
