#ifndef POKEPLATINUM_CONSTANTS_FIELD_MAP_MATRIX_H
#define POKEPLATINUM_CONSTANTS_FIELD_MAP_MATRIX_H

#define MAP_MATRIX_MAX_WIDTH  30
#define MAP_MATRIX_MAX_HEIGHT 30
#define MAP_MATRIX_MAX_SIZE   (MAP_MATRIX_MAX_WIDTH * MAP_MATRIX_MAX_HEIGHT)

#define MAP_MATRIX_MAX_NAME_LENGTH 16

#endif // POKEPLATINUM_CONSTANTS_FIELD_MAP_MATRIX_H
