#ifndef POKEPLATINUM_CONSTANTS_FIELD_MAP_LOAD_H
#define POKEPLATINUM_CONSTANTS_FIELD_MAP_LOAD_H

enum {
    MAP_LOAD_TYPE_OVERWORLD = 0,
    MAP_LOAD_TYPE_UNDERGROUND,
    MAP_LOAD_TYPE_UNION,
    MAP_LOAD_TYPE_COLOSSEUM,
    MAP_LOAD_TYPE_BATTLE_TOWER,
    MAP_LOAD_TYPE_MAX
};

#endif
