#ifndef POKEPLATINUM_CONSTANTS_FIELD_WINDOW_H
#define POKEPLATINUM_CONSTANTS_FIELD_WINDOW_H

#define FIELD_WINDOW_PALETTE_INDEX  11
#define FIELD_MESSAGE_PALETTE_INDEX 13

#endif // POKEPLATINUM_CONSTANTS_FIELD_WINDOW_H
