#ifndef POKEPLATINUM_BATTLE_PARTY_TEXT_H
#define POKEPLATINUM_BATTLE_PARTY_TEXT_H

#include "overlay013/battle_party.h"

enum BattlePartyPokemonPartyScreenWindow {
    BATTLE_PARTY_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_1 = 0,
    BATTLE_PARTY_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_2,
    BATTLE_PARTY_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_3,
    BATTLE_PARTY_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_4,
    BATTLE_PARTY_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_5,
    BATTLE_PARTY_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_6,
};

enum BattlePartySelectPokemonScreenWindow {
    BATTLE_PARTY_SELECT_POKEMON_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_SELECT_POKEMON_SCREEN_WINDOW_SHIFT,
    BATTLE_PARTY_SELECT_POKEMON_SCREEN_WINDOW_SUMMARY,
    BATTLE_PARTY_SELECT_POKEMON_SCREEN_WINDOW_CHECK_MOVES,
};

enum BattlePartyPokemonSummaryScreenWindow {
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ABILITY_NAME,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ABILITY_DESC,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_HELD_ITEM,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_HP,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ATTACK,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_DEFENSE,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_SPEED,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_SP_ATK,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_SP_DEF,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_HEALTH_BAR,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_LEVEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_EXP_TO_NEXT_LVL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_HP_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ATTACK_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_DEFENSE_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_SPEED_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_SP_ATK_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_SP_DEF_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_LEVEL_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_EXP_TO_NEXT_LVL_LABEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_CHECK_MOVES,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_POKEMON_NAME,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_ABILITY_NAME,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_ABILITY_DESC,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_HELD_ITEM,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_HP,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_ATTACK,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_DEFENSE,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_SPEED,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_SP_ATK,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_SP_DEF,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_HEALTH_BAR,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_LEVEL,
    BATTLE_PARTY_POKEMON_SUMMARY_SCREEN_WINDOW_ALT_EXP_TO_NEXT_LVL,
};

enum BattlePartyPokemonMovesScreenWindow {
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_MOVE_1,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_MOVE_2,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_MOVE_3,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_MOVE_4,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_SUMMARY,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_ALT_POKEMON_NAME,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_1,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_2,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_3,
    BATTLE_PARTY_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_4,
};

enum BattlePartyMoveSummaryScreenWindow {
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_MOVE_NAME = 0,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_PP,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ACCURACY,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_POWER,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_DESCRIPTION,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_CATEGORY,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_POKEMON_NAME,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_PP_LABEL,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ACCURACY_LABEL,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_POWER_LABEL,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_CATEGORY_LABEL,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_MOVE_NAME,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_PP,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_ACCURACY,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_POWER,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_DESCRIPTION,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_CATEGORY,
    BATTLE_PARTY_MOVE_SUMMARY_SCREEN_WINDOW_ALT_POKEMON_NAME,
};

enum BattlePartyRestoreMovePPScreenWindow {
    BATTLE_PARTY_RESTORE_MOVE_PP_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_1,
    BATTLE_PARTY_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_2,
    BATTLE_PARTY_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_3,
    BATTLE_PARTY_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_4,
};

enum BattlePartyLearnMoveScreenWindow {
    BATTLE_PARTY_LEARN_MOVE_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_LEARN_MOVE_SCREEN_WINDOW_MOVE_1,
    BATTLE_PARTY_LEARN_MOVE_SCREEN_WINDOW_MOVE_2,
    BATTLE_PARTY_LEARN_MOVE_SCREEN_WINDOW_MOVE_3,
    BATTLE_PARTY_LEARN_MOVE_SCREEN_WINDOW_MOVE_4,
    BATTLE_PARTY_LEARN_MOVE_SCREEN_WINDOW_MOVE_TO_LEARN,
};

enum BattlePartyConfirmLearnMoveScreenWindow {
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_MOVE_NAME,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_PP_LABEL,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_PP,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_ACCURACY_LABEL,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_POWER_LABEL,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_ACCURACY,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_POWER,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_DESCRIPTION,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_CATEGORY_LABEL,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_CATEGORY,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_CONFIRM,
};

enum BattlePartyConfirmLearnMoveContestStatsScreenWindow {
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_POKEMON_NAME = 0,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_MOVE_NAME,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_PP_LABEL,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_PP,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_APPEAL_PTS,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_CONTEST_EFFECT,
    BATTLE_PARTY_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_CONFIRM,
};

void BattlePartyText_InitializeWindows(BattleParty *battleParty);
void BattlePartyText_InitializeScreenWindows(BattleParty *battleParty, enum BattlePartyScreen screen);
void BattlePartyText_ClearScreenWindows(BattleParty *battleParty);
void BattlePartyText_ClearWindows(BattleParty *battleParty);
void BattlePartyText_ChangeScreen(BattleParty *battleParty, enum BattlePartyScreen screen);
void BattlePartyText_PrintHMMovesCantBeForgottenText(BattleParty *battleParty);
void BattlePartyText_RenderPartyPokemonStats(BattleParty *battleParty, u8 windowIndex);
void BattlePartyText_PrintPartyPokemonLevel(BattleParty *battleParty, u8 partyIndex);
void BattlePartyText_PrintSelectedMoveCurrentPP(BattleParty *battleParty, u16 windowIndex, u16 moveIndex);
void BattlePartyText_DisplayErrorMessage(BattleParty *battleParty);
void BattlePartyText_PrintToErrorMessageBox(BattleParty *battleParty);
void BattlePartyText_PrintUseItemEffect(BattleParty *battleParty);
void BattlePartyText_PrintEmbargoPreventingItemUse(BattleParty *battleParty);

#endif // POKEPLATINUM_BATTLE_PARTY_TEXT_H
