#ifndef POKEPLATINUM_BATTLE_SUB_MENU_BUTTONS_DEFS_H
#define POKEPLATINUM_BATTLE_SUB_MENU_BUTTONS_DEFS_H

enum BattleSubMenuButtonState {
    BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED = 0,
    BATTLE_SUB_MENU_BUTTON_STATE_PRESSING,
    BATTLE_SUB_MENU_BUTTON_STATE_PRESSED,
    BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, // WARN: This state MUST be the last in the sequence!

    BATTLE_SUB_MENU_BUTTON_STATE_MAX,
    BATTLE_SUB_MENU_BUTTON_STATE_MAX_CANNOT_DISABLE = BATTLE_SUB_MENU_BUTTON_STATE_DISABLED,
};

typedef struct BattleSubMenuButtonDimensions {
    u8 xCoord;
    u8 yCoord;
    u8 width;
    u8 height;
} BattleSubMenuButtonDimensions;

#define BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH  5
#define BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT 5
#define BATTLE_SUB_MENU_CANCEL_BUTTON_SIZE   (BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH * BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT)

#define BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH  5
#define BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT 5
#define BATTLE_SUB_MENU_PREV_NEXT_BUTTON_SIZE   (BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH * BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT)

#define BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH  26
#define BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT 5
#define BATTLE_SUB_MENU_CONFIRM_BUTTON_SIZE   (BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH * BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT)

#define BATTLE_SUB_MENU_SPRITE_Y_POSITION_DEFAULT  2
#define BATTLE_SUB_MENU_SPRITE_Y_POSITION_PRESSING -4

#define BATTLE_SUB_MENU_WINDOW_SCROLL_DEFAULT    2
#define BATTLE_SUB_MENU_WINDOW_SCROLL_PRESSING   4
#define BATTLE_SUB_MENU_MAX_SCROLLABLE_WINDOWS   8
#define BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR 255

#endif // POKEPLATINUM_BATTLE_SUB_MENU_BUTTONS_DEFS_H
