#ifndef POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H
#define POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H

enum NARCFilesBattleSubSeq {
    BATTLE_SUBSEQ_START_ENCOUNTER = 0,

    BATTLE_SUBSEQ_FALL_ASLEEP = 18,
    BATTLE_SUBSEQ_WAKE_UP,

    BATTLE_SUBSEQ_POISON_DAMAGE = 23,

    BATTLE_SUBSEQ_BURN_DAMAGE = 26,

    BATTLE_SUBSEQ_TRAINER_MESSAGE = 41,

    BATTLE_SUBSEQ_MOVE_EFFECT_END = 50,
    BATTLE_SUBSEQ_THRASH_END,

    BATTLE_SUBSEQ_BIND_EFFECT = 59,
    BATTLE_SUBSEQ_BIND_END,

    BATTLE_SUBSEQ_LEECH_SEED_EFFECT = 69,

    BATTLE_SUBSEQ_DISABLE_END = 72,

    BATTLE_SUBSEQ_ENCORE_END = 74,

    BATTLE_SUBSEQ_NIGHTMARE_EFFECT = 94,

    BATTLE_SUBSEQ_CURSE_DAMAGE = 98,

    BATTLE_SUBSEQ_CONTINUE_PERISH_SONG = 102,

    BATTLE_SUBSEQ_WEATHER_CONTINUES = 104,

    BATTLE_SUBSEQ_SAFEGUARD_END = 110,

    BATTLE_SUBSEQ_FUTURE_SIGHT_DAMAGE = 121,

    BATTLE_SUBSEQ_WISH_HEAL = 136,
    BATTLE_SUBSEQ_INGRAIN_HEAL,

    BATTLE_SUBSEQ_AQUA_RING_HEAL = 169,

    BATTLE_SUBSEQ_TIGHTEN_FOCUS = 232,
    BATTLE_SUBSEQ_TAILWIND_END,
    BATTLE_SUBSEQ_RAINING_END,
    BATTLE_SUBSEQ_SANDSTORM_END,
    BATTLE_SUBSEQ_SUNNY_END,
    BATTLE_SUBSEQ_HAILING_END,
    BATTLE_SUBSEQ_GRAVITY_END,
    BATTLE_SUBSEQ_CANNOT_HEAL,
    BATTLE_SUBSEQ_UPROAR_CONTINUES,
    BATTLE_SUBSEQ_UPROAR_END,
    BATTLE_SUBSEQ_MAGNET_RISE_END,
    BATTLE_SUBSEQ_HEAL_BLOCK_END,
    BATTLE_SUBSEQ_EMBARGO_END,

    BATTLE_SUBSEQ_LUCKY_CHANT_END = 250,
    BATTLE_SUBSEQ_TRICK_ROOM_END,

    BATTLE_SUBSEQ_BAD_DREAMS = 263,

    BATTLE_SUBSEQ_TAUNT_END = 288,
};

#endif // POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H