#ifndef POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H
#define POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H

enum NARCFilesBattleSubSeq {
    BATTLE_SUBSEQ_START_ENCOUNTER = 0,
    BATTLE_SUBSEQ_USE_MOVE,
    BATTLE_SUBSEQ_UPDATE_HP,
    BATTLE_SUBSEQ_ESCAPE,
    BATTLE_SUBSEQ_BATTLE_WON,
    BATTLE_SUBSEQ_BATTLE_LOST,
    BATTLE_SUBSEQ_FAINT_MON,
    BATTLE_SUBSEQ_MISSED,
    BATTLE_SUBSEQ_ESCAPE_FAILED,
    BATTLE_SUBSEQ_SWITCH_POKEMON,
    BATTLE_SUBSEQ_SHOW_PARTY_LIST,
    BATTLE_SUBSEQ_THROW_POKEBALL,

    BATTLE_SUBSEQ_FLINCH_MON = 14,
    BATTLE_SUBSEQ_FLINCHED,
    BATTLE_SUBSEQ_CRITICAL_HIT,
    BATTLE_SUBSEQ_HIT_X_TIMES,
    BATTLE_SUBSEQ_FALL_ASLEEP,
    BATTLE_SUBSEQ_WAKE_UP,
    BATTLE_SUBSEQ_SLEEPING,
    BATTLE_SUBSEQ_MOVE_FOLLOWUP_MESSAGE,
    BATTLE_SUBSEQ_POISON,
    BATTLE_SUBSEQ_POISON_DAMAGE,

    BATTLE_SUBSEQ_BURN = 25,
    BATTLE_SUBSEQ_BURN_DAMAGE,

    BATTLE_SUBSEQ_FROZEN = 28,
    BATTLE_SUBSEQ_THAW_OUT,
    BATTLE_SUBSEQ_DEFROSTED_BY_MOVE,
    BATTLE_SUBSEQ_PARALYZE,
    BATTLE_SUBSEQ_FULLY_PARALYZED,

    BATTLE_SUBSEQ_BIDE_END = 36,

    BATTLE_SUBSEQ_CONFUSED = 38,
    BATTLE_SUBSEQ_HURT_SELF_IN_CONFUSION,
    BATTLE_SUBSEQ_SNAP_OUT_OF_CONFUSION,
    BATTLE_SUBSEQ_TRAINER_MESSAGE,
    BATTLE_SUBSEQ_NO_PP,

    BATTLE_SUBSEQ_BADLY_POISON = 47,

    BATTLE_SUBSEQ_MOVE_EFFECT_END = 50,
    BATTLE_SUBSEQ_THRASH_END,

    BATTLE_SUBSEQ_BIND_EFFECT = 59,
    BATTLE_SUBSEQ_BIND_END,

    BATTLE_SUBSEQ_RECHARGING = 65,

    BATTLE_SUBSEQ_LEECH_SEED_EFFECT = 69,

    BATTLE_SUBSEQ_MOVE_IS_DISABLED = 71,
    BATTLE_SUBSEQ_DISABLE_END,

    BATTLE_SUBSEQ_ENCORE_END = 74,

    BATTLE_SUBSEQ_FAINT_CHECK_DESTINY_BOND = 83,

    BATTLE_SUBSEQ_HIT_SUBSTITUTE = 90,

    BATTLE_SUBSEQ_NIGHTMARE_EFFECT = 94,

    BATTLE_SUBSEQ_CURSE_DAMAGE = 98,

    BATTLE_SUBSEQ_CONTINUE_PERISH_SONG = 102,

    BATTLE_SUBSEQ_WEATHER_CONTINUES = 104,

    BATTLE_SUBSEQ_INFATUATE = 106,
    BATTLE_SUBSEQ_INFATUATED,
    BATTLE_SUBSEQ_IMMOBILIZED_BY_LOVE,

    BATTLE_SUBSEQ_SAFEGUARD_END = 110,

    BATTLE_SUBSEQ_BREAK_BIND_EFFECT = 116,
    BATTLE_SUBSEQ_BLOW_AWAY_HAZARDS,

    BATTLE_SUBSEQ_FUTURE_SIGHT_DAMAGE = 121,

    BATTLE_SUBSEQ_MOVE_FAIL_TAUNTED = 133,

    BATTLE_SUBSEQ_WISH_HEAL = 136,
    BATTLE_SUBSEQ_INGRAIN_HEAL,

    BATTLE_SUBSEQ_MAGIC_COAT = 139,

    BATTLE_SUBSEQ_MOVE_IS_IMPRISONED = 144,

    BATTLE_SUBSEQ_SNATCH = 146,

    BATTLE_SUBSEQ_MOVE_FAIL_GRAVITY = 157,

    BATTLE_SUBSEQ_AQUA_RING_HEAL = 169,

    BATTLE_SUBSEQ_MOVE_IS_HEAL_BLOCKED = 174,

    BATTLE_SUBSEQ_LIGHTNING_ROD_REDIRECTED = 180,
    BATTLE_SUBSEQ_BLOCKED_BY_SOUNDPROOF,

    BATTLE_SUBSEQ_COLOR_CHANGE = 188,
    BATTLE_SUBSEQ_ROUGH_SKIN,

    BATTLE_SUBSEQ_LOAFING_AROUND = 191,

    BATTLE_SUBSEQ_AFTERMATH = 193,

    BATTLE_SUBSEQ_HELD_ITEM_HP_RESTORE = 198,
    BATTLE_SUBSEQ_HELD_ITEM_PRZ_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_SLP_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_PSN_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_BRN_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_FRZ_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_PP_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_CNF_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_MULTI_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_DISLIKE_FLAVOR,
    BATTLE_SUBSEQ_HELD_ITEM_RAISE_STAT,
    BATTLE_SUBSEQ_HELD_ITEM_RAISE_CRIT,
    BATTLE_SUBSEQ_HELD_ITEM_SHARPLY_RAISE_STAT,
    BATTLE_SUBSEQ_HELD_ITEM_STATDOWN_RESTORE,
    BATTLE_SUBSEQ_HELD_ITEM_HEAL_INFATUATION,
    BATTLE_SUBSEQ_RESTORE_A_LITTLE_HP,
    BATTLE_SUBSEQ_LOSE_HP_FROM_ITEM,

    BATTLE_SUBSEQ_TRANSFER_STICKY_BARB = 216,

    BATTLE_SUBSEQ_ESCAPE_ITEM = 222,
    BATTLE_SUBSEQ_BATTLE_ITEM,
    
    BATTLE_SUBSEQ_SAFARI_THROW_BAIT = 227,
    BATTLE_SUBSEQ_SAFARI_THROW_ROCK,
    BATTLE_SUBSEQ_SAFARI_ESCAPE,
    BATTLE_SUBSEQ_ENEMY_ESCAPE,
    BATTLE_SUBSEQ_REPLACE_FAINTED,
    BATTLE_SUBSEQ_TIGHTEN_FOCUS,
    BATTLE_SUBSEQ_TAILWIND_END,
    BATTLE_SUBSEQ_RAINING_END,
    BATTLE_SUBSEQ_SANDSTORM_END,
    BATTLE_SUBSEQ_SUNNY_END,
    BATTLE_SUBSEQ_HAILING_END,
    BATTLE_SUBSEQ_GRAVITY_END,
    BATTLE_SUBSEQ_CANNOT_HEAL,
    BATTLE_SUBSEQ_UPROAR_CONTINUES,
    BATTLE_SUBSEQ_UPROAR_END,
    BATTLE_SUBSEQ_MAGNET_RISE_END,
    BATTLE_SUBSEQ_HEAL_BLOCK_END,
    BATTLE_SUBSEQ_EMBARGO_END,
    BATTLE_SUBSEQ_RAGE_IS_BUILDING,

    BATTLE_SUBSEQ_LUCKY_CHANT_END = 250,
    BATTLE_SUBSEQ_TRICK_ROOM_END,

    BATTLE_SUBSEQ_DISOBEY_WHILE_ASLEEP = 254,
    BATTLE_SUBSEQ_DISOBEY_DO_NOTHING,
    BATTLE_SUBSEQ_DISOBEY_ORDERS,
    BATTLE_SUBSEQ_DISOBEY_SLEEP,
    BATTLE_SUBSEQ_DISOBEY_HIT_SELF,

    BATTLE_SUBSEQ_BAD_DREAMS = 263,

    BATTLE_SUBSEQ_HELD_ITEM_TEMP_ACC_UP = 265,
    BATTLE_SUBSEQ_HELD_ITEM_RECOIL_WHEN_HIT,
    BATTLE_SUBSEQ_USE_POTION,
    BATTLE_SUBSEQ_USE_STATUS_RECOVERY,
    BATTLE_SUBSEQ_USE_STAT_BOOSTER,
    BATTLE_SUBSEQ_USE_GUARD_SPEC,

    BATTLE_SUBSEQ_THROW_SAFARI_BALL = 275,
    BATTLE_SUBSEQ_GRANT_EXP,
    BATTLE_SUBSEQ_AFTER_SELFDESTRUCT,
    BATTLE_SUBSEQ_CHECK_QUICK_CLAW,

    BATTLE_SUBSEQ_NO_TARGET = 281,
    BATTLE_SUBSEQ_BIDE_NO_TARGET,

    BATTLE_SUBSEQ_ENEMY_ESCAPE_FAILED = 286,
    BATTLE_SUBSEQ_VANISH_OFF,

    BATTLE_SUBSEQ_TAUNT_END = 288,
    BATTLE_SUBSEQ_USE_FULL_RESTORE,

    BATTLE_SUBSEQ_WAIT_MOVE_ANIMATION = 291,

    BATTLE_SUBSEQ_CHECK_SHAYMIN_FORM = 293,
};

#endif // POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H
