#ifndef POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H
#define POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H

enum NARCFilesBattleSubSeq {
    BATTLE_SUBSEQ_START_ENCOUNTER = 0,

    BATTLE_SUBSEQ_TRAINER_MESSAGE = 41,
};

#endif // POKEPLATINUM_NARC_FILES_BATTLE_SKILL_SUBSEQ_H