#ifndef POKEPLATINUM_STRUCT_OV5_021EDDAC_H
#define POKEPLATINUM_STRUCT_OV5_021EDDAC_H

typedef struct {
    int unk_00;
    int unk_04;
} UnkStruct_ov5_021EDDAC;

#endif // POKEPLATINUM_STRUCT_OV5_021EDDAC_H
