#ifndef POKEPLATINUM_GBA_CONVERT_STRING_H
#define POKEPLATINUM_GBA_CONVERT_STRING_H

BOOL GBAStringToDSString(const u8 *src, u16 *dst, u32 length, u32 language);

#endif // POKEPLATINUM_GBA_CONVERT_STRING_H
