#include "overlay013/battle_party_buttons.h"

#include "generated/species.h"

#include "overlay013/battle_party_text.h"

#define ALT_PARTY_POKEMON_BUTTON_DATA_X_OFFSET        16
#define SUMMARY_CHECK_MOVES_BUTTON_DATA_Y_OFFSET      39
#define PREV_POKEMON_BUTTON_DATA_Y_OFFSET             49
#define NEXT_POKEMON_BUTTON_DATA_Y_OFFSET             54
#define CANCEL_BUTTON_DATA_X_OFFSET                   26
#define CANCEL_BUTTON_DATA_Y_OFFSET                   24
#define LEARN_MOVE_CONFIRM_BUTTON_DATA_Y_OFFSET       24
#define CONTEST_STATS_BUTTON_DATA_X_OFFSET            20
#define CONTEST_STATS_BUTTON_DATA_Y_OFFSET            49
#define MOVE_SUMMARY_SCREEN_MOVE_BUTTON_DATA_Y_OFFSET 59
#define MOVE_BUTTON_DATA_Y_OFFSET                     51

#define POKEMON_PARTY_MENU_SPRITE_Y_POSITION_PRESSING -3
#define POKEMON_PARTY_MENU_SPRITE_Y_POSITION_PRESSED  1

#define POKEMON_PARTY_MENU_WINDOW_SCROLL_PRESSING 3
#define POKEMON_PARTY_MENU_WINDOW_SCROLL_PRESSED  1

enum Button {
    BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1 = BATTLE_POKEMON_PARTY_SCREEN_BUTTON_POKEMON_1,
    BUTTON_POKEMON_PARTY_SCREEN_POKEMON_2 = BATTLE_POKEMON_PARTY_SCREEN_BUTTON_POKEMON_2,
    BUTTON_POKEMON_PARTY_SCREEN_POKEMON_3 = BATTLE_POKEMON_PARTY_SCREEN_BUTTON_POKEMON_3,
    BUTTON_POKEMON_PARTY_SCREEN_POKEMON_4 = BATTLE_POKEMON_PARTY_SCREEN_BUTTON_POKEMON_4,
    BUTTON_POKEMON_PARTY_SCREEN_POKEMON_5 = BATTLE_POKEMON_PARTY_SCREEN_BUTTON_POKEMON_5,
    BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6 = BATTLE_POKEMON_PARTY_SCREEN_BUTTON_POKEMON_6,
    BUTTON_CANCEL = BATTLE_PARTY_CANCEL_BUTTON_OFFSET,
    BUTTON_SELECT_POKEMON_SCREEN_SHIFT = BATTLE_SELECT_POKEMON_SCREEN_BUTTON_OFFSET + BATTLE_POKEMON_SELECT_POKEMON_SCREEN_BUTTON_SHIFT,
    BUTTON_SELECT_POKEMON_SCREEN_SUMMARY = BATTLE_PARTY_SUMMARY_BUTTON_OFFSET,
    BUTTON_POKEMON_MOVES_SCREEN_SUMMARY,
    BUTTON_SELECT_POKEMON_SCREEN_CHECK_MOVES = BATTLE_PARTY_CHECK_MOVES_BUTTON_OFFSET,
    BUTTON_POKEMON_SUMMARY_SCREEN_CHECK_MOVES,
    BUTTON_PREV_POKEMON = BATTLE_POKEMON_PREV_NEXT_BUTTON_OFFSET,
    BUTTON_NEXT_POKEMON,
    BUTTON_POKEMON_MOVES_SCREEN_MOVE_1 = BATTLE_POKEMON_MOVES_SCREEN_BUTTON_OFFSET + BATTLE_POKEMON_MOVES_SCREEN_BUTTON_MOVE_1,
    BUTTON_POKEMON_MOVES_SCREEN_MOVE_2 = BATTLE_POKEMON_MOVES_SCREEN_BUTTON_OFFSET + BATTLE_POKEMON_MOVES_SCREEN_BUTTON_MOVE_2,
    BUTTON_POKEMON_MOVES_SCREEN_MOVE_3 = BATTLE_POKEMON_MOVES_SCREEN_BUTTON_OFFSET + BATTLE_POKEMON_MOVES_SCREEN_BUTTON_MOVE_3,
    BUTTON_POKEMON_MOVES_SCREEN_MOVE_4 = BATTLE_POKEMON_MOVES_SCREEN_BUTTON_OFFSET + BATTLE_POKEMON_MOVES_SCREEN_BUTTON_MOVE_4,
    BUTTON_CONTEST_STATS = BATTLE_PARTY_CONTEST_STATS_BUTTON_OFFSET,
    BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1 = BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_OFFSET + BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_MOVE_1,
    BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_2 = BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_OFFSET + BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_MOVE_2,
    BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_3 = BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_OFFSET + BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_MOVE_3,
    BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_4 = BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_OFFSET + BATTLE_RESTORE_MOVE_PP_SCREEN_BUTTON_MOVE_4,
    BUTTON_LEARN_MOVE_SCREEN_MOVE_1 = BATTLE_LEARN_MOVE_SCREEN_BUTTON_OFFSET + BATTLE_LEARN_MOVE_SCREEN_BUTTON_MOVE_1,
    BUTTON_LEARN_MOVE_SCREEN_MOVE_2 = BATTLE_LEARN_MOVE_SCREEN_BUTTON_OFFSET + BATTLE_LEARN_MOVE_SCREEN_BUTTON_MOVE_2,
    BUTTON_LEARN_MOVE_SCREEN_MOVE_3 = BATTLE_LEARN_MOVE_SCREEN_BUTTON_OFFSET + BATTLE_LEARN_MOVE_SCREEN_BUTTON_MOVE_3,
    BUTTON_LEARN_MOVE_SCREEN_MOVE_4 = BATTLE_LEARN_MOVE_SCREEN_BUTTON_OFFSET + BATTLE_LEARN_MOVE_SCREEN_BUTTON_MOVE_4,
    BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN = BATTLE_LEARN_MOVE_SCREEN_BUTTON_OFFSET + BATTLE_LEARN_MOVE_SCREEN_BUTTON_MOVE_TO_LEARN,
    BUTTON_CONFIRM_LEARN_MOVE_SCREEN_CONFIRM = BATTLE_CONFIRM_LEARN_MOVE_SCREEN_BUTTON_OFFSET,
    BUTTON_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_CONFIRM,
    BUTTON_MOVE_SUMMARY_SCREEN_MOVE_1 = BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_OFFSET + BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_MOVE_1,
    BUTTON_MOVE_SUMMARY_SCREEN_MOVE_2 = BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_OFFSET + BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_MOVE_2,
    BUTTON_MOVE_SUMMARY_SCREEN_MOVE_3 = BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_OFFSET + BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_MOVE_3,
    BUTTON_MOVE_SUMMARY_SCREEN_MOVE_4 = BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_OFFSET + BATTLE_MOVE_SUMMARY_SCREEN_BUTTON_MOVE_4,
};

static void LoadButtonData(u16 *buttonData, u16 *screenData, u8 xOffset, u8 yOffset, u8 width, u8 height);
static u8 CheckMultipleSelectablePokemon(BattleParty *battleParty);

static const BattleSubMenuButtonDimensions sButtonDimensions[] = {
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1] = { .xCoord = 0, .yCoord = 0, .width = PARTY_POKEMON_BUTTON_WIDTH_TILES, .height = PARTY_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_2] = { .xCoord = 16, .yCoord = 1, .width = PARTY_POKEMON_BUTTON_WIDTH_TILES, .height = PARTY_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_3] = { .xCoord = 0, .yCoord = 6, .width = PARTY_POKEMON_BUTTON_WIDTH_TILES, .height = PARTY_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_4] = { .xCoord = 16, .yCoord = 7, .width = PARTY_POKEMON_BUTTON_WIDTH_TILES, .height = PARTY_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_5] = { .xCoord = 0, .yCoord = 12, .width = PARTY_POKEMON_BUTTON_WIDTH_TILES, .height = PARTY_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6] = { .xCoord = 16, .yCoord = 13, .width = PARTY_POKEMON_BUTTON_WIDTH_TILES, .height = PARTY_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_CANCEL] = { .xCoord = 27, .yCoord = 19, .width = BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES },
    [BUTTON_SELECT_POKEMON_SCREEN_SHIFT] = { .xCoord = 1, .yCoord = 1, .width = SHIFT_POKEMON_BUTTON_WIDTH_TILES, .height = SHIFT_POKEMON_BUTTON_HEIGHT_TILES },
    [BUTTON_SELECT_POKEMON_SCREEN_SUMMARY] = { .xCoord = 0, .yCoord = 19, .width = SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, .height = SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_MOVES_SCREEN_SUMMARY] = { .xCoord = 12, .yCoord = 19, .width = SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, .height = SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES },
    [BUTTON_SELECT_POKEMON_SCREEN_CHECK_MOVES] = { .xCoord = 13, .yCoord = 19, .width = SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, .height = SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_SUMMARY_SCREEN_CHECK_MOVES] = { .xCoord = 12, .yCoord = 19, .width = SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, .height = SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES },
    [BUTTON_PREV_POKEMON] = { .xCoord = 0, .yCoord = 19, .width = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES },
    [BUTTON_NEXT_POKEMON] = { .xCoord = 5, .yCoord = 19, .width = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_1] = { .xCoord = 0, .yCoord = 6, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_2] = { .xCoord = 16, .yCoord = 6, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_3] = { .xCoord = 0, .yCoord = 12, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_4] = { .xCoord = 16, .yCoord = 12, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_CONTEST_STATS] = { .xCoord = 23, .yCoord = 0, .width = CONTEST_STATS_BUTTON_WIDTH_TILES, .height = CONTEST_STATS_BUTTON_HEIGHT_TILES },
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1] = { .xCoord = 0, .yCoord = 6, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_2] = { .xCoord = 16, .yCoord = 6, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_3] = { .xCoord = 0, .yCoord = 12, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_4] = { .xCoord = 16, .yCoord = 12, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_1] = { .xCoord = 0, .yCoord = 6, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_2] = { .xCoord = 16, .yCoord = 6, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_3] = { .xCoord = 0, .yCoord = 12, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_4] = { .xCoord = 16, .yCoord = 12, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN] = { .xCoord = 8, .yCoord = 18, .width = MOVE_BUTTON_WIDTH_TILES, .height = MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_CONFIRM_LEARN_MOVE_SCREEN_CONFIRM] = { .xCoord = 0, .yCoord = 19, .width = BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES },
    [BUTTON_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_CONFIRM] = { .xCoord = 0, .yCoord = 19, .width = BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, .height = BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES },
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_1] = { .xCoord = 11, .yCoord = 19, .width = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, .height = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_2] = { .xCoord = 16, .yCoord = 19, .width = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, .height = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_3] = { .xCoord = 11, .yCoord = 21, .width = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, .height = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES },
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_4] = { .xCoord = 16, .yCoord = 21, .width = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, .height = MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES }
};

static const u8 PartyPokemon1ButtonWindows[] = {
    BATTLE_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_1,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PartyPokemon2ButtonWindows[] = {
    BATTLE_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_2,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PartyPokemon3ButtonWindows[] = {
    BATTLE_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_3,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PartyPokemon4ButtonWindows[] = {
    BATTLE_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_4,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PartyPokemon5ButtonWindows[] = {
    BATTLE_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_5,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PartyPokemon6ButtonWindows[] = {
    BATTLE_POKEMON_PARTY_SCREEN_WINDOW_PARTY_SLOT_6,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 ShiftPokemonButtonWindows[] = {
    BATTLE_SELECT_POKEMON_SCREEN_WINDOW_POKEMON_NAME,
    BATTLE_SELECT_POKEMON_SCREEN_WINDOW_SHIFT,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 SelectPokemonScreenSummaryButtonWindows[] = {
    BATTLE_SELECT_POKEMON_SCREEN_WINDOW_SUMMARY,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 SelectPokemonScreenCheckMovesButtonWindows[] = {
    BATTLE_SELECT_POKEMON_SCREEN_WINDOW_CHECK_MOVES,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PokemonSummaryScreenCheckMovesButtonWindows[] = {
    BATTLE_POKEMON_SUMMARY_SCREEN_WINDOW_CHECK_MOVES,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PokemonMovesScreenSummaryButtonWindows[] = {
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_SUMMARY,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PokemonMovesScreenMove1ButtonWindows[] = {
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_1,
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_MOVE_1,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PokemonMovesScreenMove2ButtonWindows[] = {
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_2,
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_MOVE_2,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PokemonMovesScreenMove3ButtonWindows[] = {
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_3,
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_MOVE_3,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 PokemonMovesScreenMove4ButtonWindows[] = {
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_ALT_MOVE_4,
    BATTLE_POKEMON_MOVES_SCREEN_WINDOW_MOVE_4,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 RestoreMovePPScreenMove1ButtonWindows[] = {
    BATTLE_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_1,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 RestoreMovePPScreenMove2ButtonWindows[] = {
    BATTLE_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_2,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 RestoreMovePPScreenMove3ButtonWindows[] = {
    BATTLE_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_3,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 RestoreMovePPScreenMove4ButtonWindows[] = {
    BATTLE_RESTORE_MOVE_PP_SCREEN_WINDOW_MOVE_4,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveScreenMove1ButtonWindows[] = {
    BATTLE_LEARN_MOVE_SCREEN_WINDOW_MOVE_1,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveScreenMove2ButtonWindows[] = {
    BATTLE_LEARN_MOVE_SCREEN_WINDOW_MOVE_2,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveScreenMove3ButtonWindows[] = {
    BATTLE_LEARN_MOVE_SCREEN_WINDOW_MOVE_3,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveScreenMove4ButtonWindows[] = {
    BATTLE_LEARN_MOVE_SCREEN_WINDOW_MOVE_4,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveScreenMoveToLearnButtonWindows[] = {
    BATTLE_LEARN_MOVE_SCREEN_WINDOW_MOVE_TO_LEARN,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveConfirmButtonWindows[] = {
    BATTLE_CONFIRM_LEARN_MOVE_SCREEN_WINDOW_CONFIRM,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 LearnMoveContestStatsConfirmButtonWindows[] = {
    BATTLE_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_WINDOW_CONFIRM,
    BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR
};

static const u8 *const sScrollableWindows[] = {
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1] = PartyPokemon1ButtonWindows,
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_2] = PartyPokemon2ButtonWindows,
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_3] = PartyPokemon3ButtonWindows,
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_4] = PartyPokemon4ButtonWindows,
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_5] = PartyPokemon5ButtonWindows,
    [BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6] = PartyPokemon6ButtonWindows,
    [BUTTON_CANCEL] = NULL,
    [BUTTON_SELECT_POKEMON_SCREEN_SHIFT] = ShiftPokemonButtonWindows,
    [BUTTON_SELECT_POKEMON_SCREEN_SUMMARY] = SelectPokemonScreenSummaryButtonWindows,
    [BUTTON_POKEMON_MOVES_SCREEN_SUMMARY] = PokemonMovesScreenSummaryButtonWindows,
    [BUTTON_SELECT_POKEMON_SCREEN_CHECK_MOVES] = SelectPokemonScreenCheckMovesButtonWindows,
    [BUTTON_POKEMON_SUMMARY_SCREEN_CHECK_MOVES] = PokemonSummaryScreenCheckMovesButtonWindows,
    [BUTTON_PREV_POKEMON] = NULL,
    [BUTTON_NEXT_POKEMON] = NULL,
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_1] = PokemonMovesScreenMove1ButtonWindows,
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_2] = PokemonMovesScreenMove2ButtonWindows,
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_3] = PokemonMovesScreenMove3ButtonWindows,
    [BUTTON_POKEMON_MOVES_SCREEN_MOVE_4] = PokemonMovesScreenMove4ButtonWindows,
    [BUTTON_CONTEST_STATS] = NULL,
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1] = RestoreMovePPScreenMove1ButtonWindows,
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_2] = RestoreMovePPScreenMove2ButtonWindows,
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_3] = RestoreMovePPScreenMove3ButtonWindows,
    [BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_4] = RestoreMovePPScreenMove4ButtonWindows,
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_1] = LearnMoveScreenMove1ButtonWindows,
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_2] = LearnMoveScreenMove2ButtonWindows,
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_3] = LearnMoveScreenMove3ButtonWindows,
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_4] = LearnMoveScreenMove4ButtonWindows,
    [BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN] = LearnMoveScreenMoveToLearnButtonWindows,
    [BUTTON_CONFIRM_LEARN_MOVE_SCREEN_CONFIRM] = LearnMoveConfirmButtonWindows,
    [BUTTON_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_CONFIRM] = LearnMoveContestStatsConfirmButtonWindows,
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_1] = NULL,
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_2] = NULL,
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_3] = NULL,
    [BUTTON_MOVE_SUMMARY_SCREEN_MOVE_4] = NULL
};

static const s16 sPartyPokemonSpriteYPositions[] = {
    [BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED] = BATTLE_SUB_MENU_SPRITE_Y_POSITION_DEFAULT,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSING] = POKEMON_PARTY_MENU_SPRITE_Y_POSITION_PRESSING,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSED] = POKEMON_PARTY_MENU_SPRITE_Y_POSITION_PRESSED
};

static const s16 sSelectedPokemonSpriteYPositions[] = {
    [BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED] = BATTLE_SUB_MENU_SPRITE_Y_POSITION_DEFAULT,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSING] = BATTLE_SUB_MENU_SPRITE_Y_POSITION_PRESSING,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSED] = BATTLE_SUB_MENU_SPRITE_Y_POSITION_DEFAULT
};

static const u8 sPartyPokemonWindowScrollDistances[] = {
    [BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED] = BATTLE_SUB_MENU_WINDOW_SCROLL_DEFAULT,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSING] = POKEMON_PARTY_MENU_WINDOW_SCROLL_PRESSING,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSED] = POKEMON_PARTY_MENU_WINDOW_SCROLL_PRESSED
};

static const u8 sWindowScrollDistances[] = {
    [BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED] = BATTLE_SUB_MENU_WINDOW_SCROLL_DEFAULT,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSING] = BATTLE_SUB_MENU_WINDOW_SCROLL_PRESSING,
    [BATTLE_SUB_MENU_BUTTON_STATE_PRESSED] = BATTLE_SUB_MENU_WINDOW_SCROLL_DEFAULT
};

void BattlePartyButtons_InitializeButtonData(BattleParty *battleParty, u16 *screenData)
{
    LoadButtonData(battleParty->partyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, 0, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->partyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, 0, PARTY_POKEMON_BUTTON_HEIGHT_TILES, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->partyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, 0, PARTY_POKEMON_BUTTON_HEIGHT_TILES * 2, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->partyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, 0, PARTY_POKEMON_BUTTON_HEIGHT_TILES * 3, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->altPartyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, ALT_PARTY_POKEMON_BUTTON_DATA_X_OFFSET, 0, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->altPartyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, ALT_PARTY_POKEMON_BUTTON_DATA_X_OFFSET, PARTY_POKEMON_BUTTON_HEIGHT_TILES, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->altPartyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, ALT_PARTY_POKEMON_BUTTON_DATA_X_OFFSET, PARTY_POKEMON_BUTTON_HEIGHT_TILES * 2, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->altPartyPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, ALT_PARTY_POKEMON_BUTTON_DATA_X_OFFSET, PARTY_POKEMON_BUTTON_HEIGHT_TILES * 3, PARTY_POKEMON_BUTTON_WIDTH_TILES, PARTY_POKEMON_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->summaryCheckMovesButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, SUMMARY_CHECK_MOVES_BUTTON_DATA_Y_OFFSET, SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->summaryCheckMovesButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, 0, SUMMARY_CHECK_MOVES_BUTTON_DATA_Y_OFFSET + SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES, SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->summaryCheckMovesButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, SUMMARY_CHECK_MOVES_BUTTON_DATA_Y_OFFSET, SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->summaryCheckMovesButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, SUMMARY_CHECK_MOVES_BUTTON_DATA_Y_OFFSET + SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES, SUMMARY_CHECK_MOVES_BUTTON_WIDTH_TILES, SUMMARY_CHECK_MOVES_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->prevPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, PREV_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->prevPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, PREV_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->prevPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 2, PREV_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->prevPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 3, PREV_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->nextPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, NEXT_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->nextPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, NEXT_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->nextPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 2, NEXT_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->nextPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES * 3, NEXT_POKEMON_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_PREV_NEXT_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, CANCEL_BUTTON_DATA_X_OFFSET, CANCEL_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, CANCEL_BUTTON_DATA_X_OFFSET, CANCEL_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, CANCEL_BUTTON_DATA_X_OFFSET, CANCEL_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES * 2, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->cancelButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, CANCEL_BUTTON_DATA_X_OFFSET, CANCEL_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES * 3, BATTLE_SUB_MENU_CANCEL_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CANCEL_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->learnMoveConfirmButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, LEARN_MOVE_CONFIRM_BUTTON_DATA_Y_OFFSET, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->learnMoveConfirmButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, 0, LEARN_MOVE_CONFIRM_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->learnMoveConfirmButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, 0, LEARN_MOVE_CONFIRM_BUTTON_DATA_Y_OFFSET + BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES * 2, BATTLE_SUB_MENU_CONFIRM_BUTTON_WIDTH_TILES, BATTLE_SUB_MENU_CONFIRM_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->contestStatsButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, CONTEST_STATS_BUTTON_DATA_X_OFFSET, CONTEST_STATS_BUTTON_DATA_Y_OFFSET, CONTEST_STATS_BUTTON_WIDTH_TILES, CONTEST_STATS_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->contestStatsButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, CONTEST_STATS_BUTTON_DATA_X_OFFSET, CONTEST_STATS_BUTTON_DATA_Y_OFFSET + CONTEST_STATS_BUTTON_HEIGHT_TILES, CONTEST_STATS_BUTTON_WIDTH_TILES, CONTEST_STATS_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->contestStatsButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, CONTEST_STATS_BUTTON_DATA_X_OFFSET, CONTEST_STATS_BUTTON_DATA_Y_OFFSET + CONTEST_STATS_BUTTON_HEIGHT_TILES * 2, CONTEST_STATS_BUTTON_WIDTH_TILES, CONTEST_STATS_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->moveSummaryScreenMoveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_DATA_Y_OFFSET, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->moveSummaryScreenMoveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_DATA_Y_OFFSET, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->moveSummaryScreenMoveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES * 2, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_DATA_Y_OFFSET, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_WIDTH_TILES, MOVE_SUMMARY_SCREEN_MOVE_BUTTON_HEIGHT_TILES);
}

void BattlePartyButtons_InitializeAdditionalButtonData(BattleParty *battleParty, u16 *screenData)
{
    LoadButtonData(battleParty->shiftPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, 0, SHIFT_POKEMON_BUTTON_WIDTH_TILES, SHIFT_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->shiftPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, 0, SHIFT_POKEMON_BUTTON_HEIGHT_TILES, SHIFT_POKEMON_BUTTON_WIDTH_TILES, SHIFT_POKEMON_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->shiftPokemonButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, 0, SHIFT_POKEMON_BUTTON_HEIGHT_TILES * 2, SHIFT_POKEMON_BUTTON_WIDTH_TILES, SHIFT_POKEMON_BUTTON_HEIGHT_TILES);

    LoadButtonData(battleParty->moveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED], screenData, 0, MOVE_BUTTON_DATA_Y_OFFSET, MOVE_BUTTON_WIDTH_TILES, MOVE_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->moveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSING], screenData, MOVE_BUTTON_WIDTH_TILES, MOVE_BUTTON_DATA_Y_OFFSET, MOVE_BUTTON_WIDTH_TILES, MOVE_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->moveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_PRESSED], screenData, 0, MOVE_BUTTON_DATA_Y_OFFSET + MOVE_BUTTON_HEIGHT_TILES, MOVE_BUTTON_WIDTH_TILES, MOVE_BUTTON_HEIGHT_TILES);
    LoadButtonData(battleParty->moveButtonData[BATTLE_SUB_MENU_BUTTON_STATE_DISABLED], screenData, MOVE_BUTTON_WIDTH_TILES, MOVE_BUTTON_DATA_Y_OFFSET + MOVE_BUTTON_HEIGHT_TILES, MOVE_BUTTON_WIDTH_TILES, MOVE_BUTTON_HEIGHT_TILES);
}

static void LoadButtonData(u16 *buttonData, u16 *screenData, u8 xOffset, u8 yOffset, u8 width, u8 height)
{
    for (u16 i = 0; i < height; i++) {
        for (u16 l = 0; l < width; l++) {
            buttonData[i * width + l] = screenData[(yOffset + i) * TILE_SIZE_4BPP + xOffset + l];
        }
    }
}

static u16 *RetrieveRawButtonData(BattleParty *battleParty, u8 button, u8 buttonState, u8 isAltButton)
{
    switch (button) {
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_2:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_3:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_4:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_5:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6:
        if (isAltButton == FALSE) {
            return battleParty->partyPokemonButtonData[buttonState];
        } else {
            return battleParty->altPartyPokemonButtonData[buttonState];
        }
    case BUTTON_CANCEL:
        return battleParty->cancelButtonData[buttonState];
    case BUTTON_SELECT_POKEMON_SCREEN_SHIFT:
        return battleParty->shiftPokemonButtonData[buttonState];
    case BUTTON_SELECT_POKEMON_SCREEN_SUMMARY:
    case BUTTON_POKEMON_MOVES_SCREEN_SUMMARY:
    case BUTTON_SELECT_POKEMON_SCREEN_CHECK_MOVES:
    case BUTTON_POKEMON_SUMMARY_SCREEN_CHECK_MOVES:
        return battleParty->summaryCheckMovesButtonData[buttonState];
    case BUTTON_PREV_POKEMON:
        return battleParty->prevPokemonButtonData[buttonState];
    case BUTTON_NEXT_POKEMON:
        return battleParty->nextPokemonButtonData[buttonState];
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_1:
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_2:
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_3:
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_4:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_2:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_3:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_4:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_1:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_2:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_3:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_4:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN:
        return battleParty->moveButtonData[buttonState];
    case BUTTON_CONFIRM_LEARN_MOVE_SCREEN_CONFIRM:
    case BUTTON_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_CONFIRM:
        return battleParty->learnMoveConfirmButtonData[buttonState];
    case BUTTON_CONTEST_STATS:
        return battleParty->contestStatsButtonData[buttonState];
    case BUTTON_MOVE_SUMMARY_SCREEN_MOVE_1:
    case BUTTON_MOVE_SUMMARY_SCREEN_MOVE_2:
    case BUTTON_MOVE_SUMMARY_SCREEN_MOVE_3:
    case BUTTON_MOVE_SUMMARY_SCREEN_MOVE_4:
        return battleParty->moveSummaryScreenMoveButtonData[buttonState];
    }

    return NULL;
}

static void RetrieveButtonData(BattleParty *battleParty, u16 *buttonData, u8 button, u8 buttonState, u8 isAltButton)
{
    u16 *rawButtonData = RetrieveRawButtonData(battleParty, button, buttonState, isAltButton);
    u8 width = sButtonDimensions[button].width;
    u8 height = sButtonDimensions[button].height;

    memcpy(buttonData, rawButtonData, width * height * 2);

    switch (button) {
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_2:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_3:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_4:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_5:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6:
        if (battleParty->partyPokemon[button].species == SPECIES_NONE) {
            break;
        }

        if (battleParty->partyPokemon[button].isEgg != FALSE) {
            u16 replacementButtonData[2];

            replacementButtonData[0] = buttonData[2 * width + 5];
            replacementButtonData[1] = buttonData[3 * width + 5];

            for (u8 i = 0; i < 2; i++) {
                for (u8 l = 0; l < 9; l++) {
                    buttonData[(2 + i) * width + 6 + l] = replacementButtonData[i];
                }
            }
        } else {
            if (battleParty->partyPokemon[button].curHP == 0) {
                for (u8 i = 0; i < width * height; i++) {
                    buttonData[i] = (buttonData[i] & 0xfff) | (2 << 12);
                }
            } else if (BattlePartyTask_CheckIfSwitchingWithPartnersPokemon(battleParty, button - 0) == TRUE) {
                for (u8 i = 0; i < width * height; i++) {
                    buttonData[i] = (buttonData[i] & 0xfff) | (1 << 12);
                }
            }
        }
        break;
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN:
        for (u8 i = 0; i < width * height; i++) {
            buttonData[i] = (buttonData[i] & 0xfff) | (10 << 12);
        }
        break;
    }
}

static void DrawButton(BattleParty *battleParty, u8 button, u8 buttonState, u8 isAltButton)
{
    u16 *buttonData = Heap_Alloc(battleParty->context->heapID, sButtonDimensions[button].width * sButtonDimensions[button].height * sizeof(u16));

    RetrieveButtonData(battleParty, buttonData, button, buttonState, isAltButton);

    Bg_LoadToTilemapRect(battleParty->background, BG_LAYER_SUB_2, buttonData, sButtonDimensions[button].xCoord, sButtonDimensions[button].yCoord, sButtonDimensions[button].width, sButtonDimensions[button].height);
    Bg_ScheduleTilemapTransfer(battleParty->background, BG_LAYER_SUB_2);
    Heap_Free(buttonData);
}

static void UpdateWindowScroll(BattleParty *battleParty, u8 button, u8 buttonState)
{
    const u8 *windowsToScroll = sScrollableWindows[button];
    u8 scrollDirection, scrollDistance;

    if (windowsToScroll == NULL) {
        return;
    }

    if (button >= BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1 && button <= BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6) {
        scrollDistance = sPartyPokemonWindowScrollDistances[buttonState];
    } else {
        scrollDistance = sWindowScrollDistances[buttonState];
    }

    switch (buttonState) {
    case BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED:
        scrollDirection = SCROLL_DIRECTION_DOWN;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSING:
        scrollDirection = SCROLL_DIRECTION_UP;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSED:
        scrollDirection = SCROLL_DIRECTION_DOWN;
        break;
    }

    if (button >= BUTTON_POKEMON_MOVES_SCREEN_MOVE_1 && button <= BUTTON_POKEMON_MOVES_SCREEN_MOVE_4) {
        Window_Scroll(&battleParty->windows[windowsToScroll[battleParty->useAltSummaryWindows]], scrollDirection, scrollDistance, 0);
        Window_ScheduleCopyToVRAM(&battleParty->windows[windowsToScroll[battleParty->useAltSummaryWindows]]);
    } else {
        for (u16 i = 0; i < BATTLE_SUB_MENU_MAX_SCROLLABLE_WINDOWS; i++) {
            if (windowsToScroll[i] == BATTLE_SUB_MENU_WINDOWS_ARRAY_TERMINATOR) {
                break;
            }

            Window_Scroll(&battleParty->windows[windowsToScroll[i]], scrollDirection, scrollDistance, 0);
            Window_ScheduleCopyToVRAM(&battleParty->windows[windowsToScroll[i]]);
        }
    }
}

static void UpdateSpritePositions(BattleParty *battleParty, u8 button, u8 buttonState)
{
    switch (button) {
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_2:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_3:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_4:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_5:
    case BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6:
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[13 + button], 0, sPartyPokemonSpriteYPositions[buttonState]);
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[button], 0, sPartyPokemonSpriteYPositions[buttonState]);
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[7 + button], 0, sPartyPokemonSpriteYPositions[buttonState]);
        break;
    case BUTTON_SELECT_POKEMON_SCREEN_SHIFT:
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[battleParty->context->selectedPartyIndex], 0, sSelectedPokemonSpriteYPositions[buttonState]);
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[7 + battleParty->context->selectedPartyIndex], 0, sSelectedPokemonSpriteYPositions[buttonState]);
        break;
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_1:
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_2:
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_3:
    case BUTTON_POKEMON_MOVES_SCREEN_MOVE_4:
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[7 + button], 0, sSelectedPokemonSpriteYPositions[buttonState]);
        break;
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_2:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_3:
    case BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_4:
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[2 + button], 0, sSelectedPokemonSpriteYPositions[buttonState]);
        break;
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_1:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_2:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_3:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_4:
    case BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN:
        ManagedSprite_OffsetPositionXY(battleParty->unk_1FB4[button - 2], 0, sSelectedPokemonSpriteYPositions[buttonState]);
        break;
    }
}

void BattlePartyButtons_PressButton(BattleParty *battleParty, u8 button)
{
    battleParty->useAltButtons = FALSE;

    if (button >= BUTTON_POKEMON_PARTY_SCREEN_POKEMON_1 && button <= BUTTON_POKEMON_PARTY_SCREEN_POKEMON_6) {
        if (BattlePartyTask_CheckCanPartySlotBeSelected(battleParty, button) == PARTY_SLOT_SELECTABLE_NOT_IN_BATTLE) {
            battleParty->useAltButtons = TRUE;
        }
    }

    battleParty->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED;
    battleParty->unused1 = 0;
    battleParty->pressedButton = button;
    battleParty->isAButtonPressed = TRUE;
}

void BattlePartyButtons_Tick(BattleParty *battleParty)
{
    if (battleParty->isAButtonPressed == FALSE) {
        return;
    }

    switch (battleParty->pressedButtonState) {
    case BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED:
        DrawButton(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSING, battleParty->useAltButtons);
        UpdateWindowScroll(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSING);
        UpdateSpritePositions(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSING);
        battleParty->unused1 = 0;
        battleParty->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_PRESSING;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSING:
        DrawButton(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED, battleParty->useAltButtons);
        UpdateWindowScroll(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED);
        UpdateSpritePositions(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED);
        battleParty->unused1 = 0;
        battleParty->pressedButtonState = BATTLE_SUB_MENU_BUTTON_STATE_PRESSED;
        break;
    case BATTLE_SUB_MENU_BUTTON_STATE_PRESSED:
        DrawButton(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, battleParty->useAltButtons);
        UpdateWindowScroll(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED);
        UpdateSpritePositions(battleParty, battleParty->pressedButton, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED);
        battleParty->unused1 = 0;
        battleParty->isAButtonPressed = FALSE;
        break;
    }
}

void BattlePartyButtons_InitializeButtons(BattleParty *battleParty, u8 screen)
{
    switch (screen) {
    case BATTLE_PARTY_SCREEN_POKEMON_PARTY:
        for (u16 i = 0; i < MAX_PARTY_SIZE; i++) {
            u16 partySlotSelectable = BattlePartyTask_CheckCanPartySlotBeSelected(battleParty, i);

            if (partySlotSelectable == FALSE) {
                DrawButton(battleParty, i, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, TRUE);
            } else if (partySlotSelectable == PARTY_SLOT_SELECTABLE_IN_BATTLE) {
                DrawButton(battleParty, i, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            } else if (partySlotSelectable == PARTY_SLOT_SELECTABLE_NOT_IN_BATTLE) {
                DrawButton(battleParty, i, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, TRUE);
            }
        }

        if (battleParty->context->battlePartyMode == BATTLE_PARTY_MODE_SELECT_POKEMON_NO_CANCEL) {
            DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
        } else {
            DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        }
        break;
    case BATTLE_PARTY_SCREEN_SELECT_POKEMON:
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_SELECT_POKEMON_SCREEN_SHIFT, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);

        if (battleParty->partyPokemon[battleParty->context->selectedPartyIndex].isEgg != FALSE) {
            DrawButton(battleParty, BUTTON_SELECT_POKEMON_SCREEN_SUMMARY, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
            DrawButton(battleParty, BUTTON_SELECT_POKEMON_SCREEN_CHECK_MOVES, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
        } else {
            DrawButton(battleParty, BUTTON_SELECT_POKEMON_SCREEN_SUMMARY, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            DrawButton(battleParty, BUTTON_SELECT_POKEMON_SCREEN_CHECK_MOVES, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        }
        break;
    case BATTLE_PARTY_SCREEN_POKEMON_SUMMARY:
        if (CheckMultipleSelectablePokemon(battleParty) == TRUE) {
            DrawButton(battleParty, BUTTON_PREV_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            DrawButton(battleParty, BUTTON_NEXT_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        } else {
            DrawButton(battleParty, BUTTON_PREV_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
            DrawButton(battleParty, BUTTON_NEXT_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
        }

        DrawButton(battleParty, BUTTON_POKEMON_SUMMARY_SCREEN_CHECK_MOVES, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        break;
    case BATTLE_PARTY_SCREEN_POKEMON_MOVES:
        if (CheckMultipleSelectablePokemon(battleParty) == TRUE) {
            DrawButton(battleParty, BUTTON_PREV_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            DrawButton(battleParty, BUTTON_NEXT_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        } else {
            DrawButton(battleParty, BUTTON_PREV_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
            DrawButton(battleParty, BUTTON_NEXT_POKEMON, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
        }

        for (u16 i = 0; i < LEARNED_MOVES_MAX; i++) {
            if (battleParty->partyPokemon[battleParty->context->selectedPartyIndex].moves[i].move != MOVE_NONE) {
                DrawButton(battleParty, BUTTON_POKEMON_MOVES_SCREEN_MOVE_1 + i, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            } else {
                DrawButton(battleParty, BUTTON_POKEMON_MOVES_SCREEN_MOVE_1 + i, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
            }
        }

        DrawButton(battleParty, BUTTON_POKEMON_MOVES_SCREEN_SUMMARY, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        break;
    case BATTLE_PARTY_SCREEN_MOVE_SUMMARY:
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);

        for (u16 i = 0; i < LEARNED_MOVES_MAX; i++) {
            if (battleParty->context->selectedMoveSlot == i) {
                DrawButton(battleParty, BUTTON_MOVE_SUMMARY_SCREEN_MOVE_1 + i, BATTLE_SUB_MENU_BUTTON_STATE_PRESSED, FALSE);
            } else {
                DrawButton(battleParty, BUTTON_MOVE_SUMMARY_SCREEN_MOVE_1 + i, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            }
        }
        break;
    case BATTLE_PARTY_SCREEN_RESTORE_MOVE_PP:
        for (u16 i = 0; i < LEARNED_MOVES_MAX; i++) {
            if (battleParty->partyPokemon[battleParty->context->selectedPartyIndex].moves[i].move != MOVE_NONE) {
                DrawButton(battleParty, BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1 + i, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
            } else {
                DrawButton(battleParty, BUTTON_RESTORE_MOVE_PP_SCREEN_MOVE_1 + i, BATTLE_SUB_MENU_BUTTON_STATE_DISABLED, FALSE);
            }
        }

        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        break;
    case BATTLE_PARTY_SCREEN_LEARN_MOVE:
    case BATTLE_PARTY_SCREEN_LEARN_MOVE_CONTEST_STATS:
        DrawButton(battleParty, BUTTON_LEARN_MOVE_SCREEN_MOVE_1, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_LEARN_MOVE_SCREEN_MOVE_2, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_LEARN_MOVE_SCREEN_MOVE_3, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_LEARN_MOVE_SCREEN_MOVE_4, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_LEARN_MOVE_SCREEN_MOVE_TO_LEARN, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);

        if (battleParty->hasVisitedContestHall == TRUE) {
            DrawButton(battleParty, BUTTON_CONTEST_STATS, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        }
        break;
    case BATTLE_PARTY_SCREEN_CONFIRM_LEARN_MOVE:
        DrawButton(battleParty, BUTTON_CONFIRM_LEARN_MOVE_SCREEN_CONFIRM, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);

        if (battleParty->hasVisitedContestHall == TRUE) {
            DrawButton(battleParty, BUTTON_CONTEST_STATS, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        }
        break;
    case BATTLE_PARTY_SCREEN_CONFIRM_LEARN_MOVE_CONTEST_STATS:
        DrawButton(battleParty, BUTTON_CONFIRM_LEARN_MOVE_CONTEST_STATS_SCREEN_CONFIRM, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        DrawButton(battleParty, BUTTON_CANCEL, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);

        if (battleParty->hasVisitedContestHall == TRUE) {
            DrawButton(battleParty, BUTTON_CONTEST_STATS, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
        }
        break;
    }
}

void BattlePartyButtons_LoadScreenPaletteData(BattleParty *battleParty, u8 screen)
{
    if (screen == BATTLE_PARTY_SCREEN_POKEMON_MOVES) {
        PaletteData_LoadBuffer(battleParty->palette, &battleParty->screenPaletteData[PALETTE_SIZE], PLTTBUF_SUB_BG, 192, PALETTE_SIZE_BYTES);
    } else {
        PaletteData_LoadBuffer(battleParty->palette, &battleParty->screenPaletteData[0], PLTTBUF_SUB_BG, 192, PALETTE_SIZE_BYTES);
    }
}

static u8 CheckMultipleSelectablePokemon(BattleParty *battleParty)
{
    u16 i, numSelectablePartyPokemon = 0;

    for (i = 0; i < MAX_PARTY_SIZE; i++) {
        if (battleParty->partyPokemon[i].species != SPECIES_NONE && battleParty->partyPokemon[i].isEgg == FALSE) {
            numSelectablePartyPokemon++;
        }
    }

    if (numSelectablePartyPokemon >= 2) {
        return TRUE;
    }

    return FALSE;
}

void BattlePartyButtons_DrawSelectedPartyPokemonButton(BattleParty *battleParty)
{
    if (BattlePartyTask_CheckCanPartySlotBeSelected(battleParty, battleParty->context->selectedPartyIndex) == PARTY_SLOT_SELECTABLE_NOT_IN_BATTLE) {
        DrawButton(battleParty, battleParty->context->selectedPartyIndex, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, TRUE);
    } else {
        DrawButton(battleParty, battleParty->context->selectedPartyIndex, BATTLE_SUB_MENU_BUTTON_STATE_UNPRESSED, FALSE);
    }
}
