#ifndef POKEPLATINUM_STRUCT_DEF_CHATOT_CRY_H
#define POKEPLATINUM_STRUCT_DEF_CHATOT_CRY_H

#define CHATOT_CRY_SIZE 1000

typedef struct ChatotCry {
    BOOL valid;
    s8 audioData[CHATOT_CRY_SIZE];
} ChatotCry;

#endif // POKEPLATINUM_STRUCT_DEF_CHATOT_CRY_H
