#ifndef POKEPLATINUM_ETERNA_GYM_CLOCK_PERSISTED_FEATURE_H
#define POKEPLATINUM_ETERNA_GYM_CLOCK_PERSISTED_FEATURE_H

enum EternaClockState {
    ETERNA_CLOCK_INITIAL,
    ETERNA_CLOCK_DEFEATED_FIRST_TRAINER,
    ETERNA_CLOCK_DEFEATED_SECOND_TRAINER,
    ETERNA_CLOCK_DEFEATED_THIRD_TRAINER,
    ETERNA_CLOCK_DEFEATED_GYM_LEADER,
    ETERNA_CLOCK_MAX,
};

typedef struct {
    u32 clockState;
} EternaGymClockPersistedFeature;

#endif // POKEPLATINUM_ETERNA_GYM_CLOCK_PERSISTED_FEATURE_H
