#ifndef NNS_SND_OUTPUT_EFFECT_H_
#define NNS_SND_OUTPUT_EFFECT_H_

typedef enum {
    NNS_SND_CAPTURE_OUTPUT_EFFECT_NORMAL,
    NNS_SND_CAPTURE_OUTPUT_EFFECT_SURROUND,
    NNS_SND_CAPTURE_OUTPUT_EFFECT_HEADPHONE,
    NNS_SND_CAPTURE_OUTPUT_EFFECT_MONO
} NNSSndCaptureOutputEffectType;

#endif //NNS_SND_OUTPUT_EFFECT_H_
