[binaries]
c       = ['/opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc']
cpp     = ['/opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++']
ar      = ['/opt/devkitpro/devkitA64/bin/aarch64-none-elf-ar']
strip   = ['false']

[host_machine]
system      = 'bare metal'
# Workaround for a meson issue. This is so cursed, but yes, the NX build is actually aarch64
cpu_family  = 'x86_64'
cpu         = 'x86_64'
endian      = 'little'
