#ifndef POKEPLATINUM_GAME_START_H
#define POKEPLATINUM_GAME_START_H

#include "overlay_manager.h"

extern const ApplicationManagerTemplate gGameStartLoadSaveOverlayTemplate;
extern const ApplicationManagerTemplate gGameStartNewSaveOverlayTemplate;
extern const ApplicationManagerTemplate gGameStartRowanIntroOverlayTemplate;

#endif // POKEPLATINUM_GAME_START_H
