#ifndef POKEPLATINUM_UNK_020655F4_H
#define POKEPLATINUM_UNK_020655F4_H

#include "generated/movement_actions.h"

#include "struct_decls/struct_02061AB4_decl.h"

#include "overlay005/map_object_anim_cmd.h"

#include "sys_task_manager.h"

BOOL LocalMapObj_IsAnimationSet(const MapObject *mapObj);
void LocalMapObj_SetAnimationCode(MapObject *mapObj, enum MovementAction movementAction);
void sub_02065668(MapObject *mapObj, enum MovementAction movementAction);
BOOL LocalMapObj_CheckAnimationFinished(const MapObject *mapObj);
BOOL sub_020656AC(MapObject *mapObj);
void sub_020656DC(MapObject *mapObj);
SysTask *MapObject_StartAnimation(MapObject *mapObj, const MapObjectAnimCmd *animCmd);
BOOL MapObject_HasAnimationEnded(SysTask *task);
void MapObject_FinishAnimation(SysTask *task);
enum MovementAction MovementAction_TurnActionTowardsDir(int targetDir, enum MovementAction movementAction);
int MovementAction_GetDirFromAction(enum MovementAction movementAction);
void MapObject_DoMovementAction(MapObject *mapObj);
BOOL sub_020658DC(MapObject *mapObj);

extern BOOL (*const gMovementActionFuncs_FaceNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_FaceSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_FaceWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_FaceEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowerNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowerSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowerWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowerEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlowEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkNormalNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkNormalSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkNormalWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkNormalEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFasterNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFasterSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFasterWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFasterEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastestNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastestSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastestWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkFastestEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_RunNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_RunSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_RunWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_RunEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowerNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowerSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowerWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowerEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotSlowEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotNormalNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotNormalSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotNormalWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotNormalEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFasterNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFasterSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFasterWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkOnSpotFasterEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotSlowNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotSlowSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotSlowWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotSlowEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpOnSpotFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpNearFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpNearFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpNearFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpNearFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpFarNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpFarSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpFarWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpFarEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpNearSlowWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpNearSlowEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpFartherWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpFartherEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpDoubleNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpDoubleSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpDoubleWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_JumpDoubleEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay1[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay2[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay4[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay8[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay15[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay16[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_Delay32[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WarpOut[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WarpIn[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_SetInvisible[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_SetVisible[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_LockDir[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_UnlockDir[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_PauseAnimation[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_ResumeAnimation[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_EmoteExclamationMark[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_EmoteDoubleExclamationMark[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFasterNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFasterSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFasterWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkSlightlyFasterEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkEverSoSlightlyFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkEverSoSlightlyFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkEverSoSlightlyFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_WalkEverSoSlightlyFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_PokecenterNurseBow[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_RevealTrainer[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_PlayerGive[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_PlayerReceive[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallWalkNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallWalkSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallWalkWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallWalkEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallWalkNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallWalkSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallWalkWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallWalkEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingWalkNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingWalkSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingWalkWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingWalkEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnSlowNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnSlowSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnSlowWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnSlowEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionTurnFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallRunNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallRunSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallRunWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionWestWallRunEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallRunNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallRunSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallRunWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionEastWallRunEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingRunNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingRunSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingRunWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionCeilingRunEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingSlowNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingSlowSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingSlowWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingSlowEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingMediumNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingMediumSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingMediumWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingMediumEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingFastNorth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingFastSouth[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingFastWest[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_DistortionSurfingFastEast[])(MapObject *);
extern BOOL (*const gMovementActionFuncs_EmoteQuestionMark[])(MapObject *);

#endif // POKEPLATINUM_UNK_020655F4_H
