#ifndef POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_CONTROLLER_H
#define POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_CONTROLLER_H

enum BattleCommand {
    BATTLE_COMMAND_NONE,
    BATTLE_COMMAND_SETUP_UI,
    BATTLE_COMMAND_SET_ENCOUNTER,
    BATTLE_COMMAND_SHOW_ENCOUNTER,
    BATTLE_COMMAND_SHOW_POKEMON,
    BATTLE_COMMAND_RETURN_POKEMON,
    BATTLE_COMMAND_OPEN_CAPTURE_BALL,
    BATTLE_COMMAND_DELETE_POKEMON,
    BATTLE_COMMAND_SET_TRAINER_ENCOUNTER,
    BATTLE_COMMAND_THROW_TRAINER_BALL,
    BATTLE_COMMAND_SLIDE_TRAINER_OUT, // 10
    BATTLE_COMMAND_SLIDE_TRAINER_IN,
    BATTLE_COMMAND_SLIDE_HEALTHBAR_IN,
    BATTLE_COMMAND_SLIDE_HEALTHBAR_OUT,
    BATTLE_COMMAND_SET_COMMAND_SELECTION,
    BATTLE_COMMAND_SHOW_MOVE_SELECT_MENU,
    BATTLE_COMMAND_SHOW_TARGET_SELECT_MENU,
    BATTLE_COMMAND_SHOW_BAG_MENU,
    BATTLE_COMMAND_SHOW_PARTY_MENU,
    BATTLE_COMMAND_SHOW_YES_NO_MENU,
    BATTLE_COMMAND_PRINT_ATTACK_MESSAGE, // 20
    BATTLE_COMMAND_PRINT_MESSAGE,
    BATTLE_COMMAND_SET_MOVE_ANIMATION,
    BATTLE_COMMAND_FLICKER_BATTLER,
    BATTLE_COMMAND_UPDATE_HP_GAUGE,
    BATTLE_COMMAND_UPDATE_EXP_GAUGE,
    BATTLE_COMMAND_PLAY_FAINTING_SEQUENCE,
    BATTLE_COMMAND_PLAY_SOUND,
    BATTLE_COMMAND_FADE_OUT,
    BATTLE_COMMAND_TOGGLE_VANISH,
    BATTLE_COMMAND_SET_STATUS_ICON, // 30
    BATTLE_COMMAND_TRAINER_MESSAGE,
    BATTLE_COMMAND_PRINT_RECALL_MESSAGE,
    BATTLE_COMMAND_PRINT_SEND_OUT_MESSAGE,
    BATTLE_COMMAND_PRINT_BATTLE_START_MESSAGE,
    BATTLE_COMMAND_PRINT_LEAD_MON_MESSAGE,
    BATTLE_COMMAND_PLAY_LEVEL_UP_ANIMATION,
    BATTLE_COMMAND_SET_ALERT_MESSAGE,
    BATTLE_COMMAND_REFRESH_HP_GAUGE,
    BATTLE_COMMAND_UPDATE_PARTY_MON,
    BATTLE_COMMAND_40, // 40
    BATTLE_COMMAND_STOP_GAUGE_ANIMATION,
    BATTLE_COMMAND_REFRESH_PARTY_STATUS,
    BATTLE_COMMAND_FORGET_MOVE,
    BATTLE_COMMAND_SET_MOSAIC,
    BATTLE_COMMAND_CHANGE_WEATHER_FORM,
    BATTLE_COMMAND_UPDATE_BG,
    BATTLE_COMMAND_CLEAR_TOUCH_SCREEN,
    BATTLE_COMMAND_SHOW_BATTLE_START_PARTY_GAUGE,
    BATTLE_COMMAND_HIDE_BATTLE_START_PARTY_GAUGE,
    BATTLE_COMMAND_SHOW_PARTY_GAUGE, // 50
    BATTLE_COMMAND_HIDE_PARTY_GAUGE,
    BATTLE_COMMAND_LOAD_PARTY_GAUGE_GRAPHICS,
    BATTLE_COMMAND_FREE_PARTY_GAUGE_GRAPHICS,
    BATTLE_COMMAND_INCREMENT_RECORD,
    BATTLE_COMMAND_LINK_WAIT_MESSAGE,
    BATTLE_COMMAND_RESTORE_SPRITE,
    BATTLE_COMMAND_SPRITE_TO_OAM,
    BATTLE_COMMAND_OAM_TO_SPRITE,
    BATTLE_COMMAND_RESULT_MESSAGE,
    BATTLE_COMMAND_ESCAPE_MESSAGE, // 60
    BATTLE_COMMAND_FORFEIT_MESSAGE,
    BATTLE_COMMAND_REFRESH_SPRITE,
    BATTLE_COMMAND_FLY_MOVE_HIT_SOUND_EFFECT,
    BATTLE_COMMAND_PLAY_MUSIC,
    BATTLE_COMMAND_SUBMIT_RESULT,
    BATTLE_COMMAND_CLEAR_MESSAGE_BOX,
};

enum BattleCommRecipient {
    COMM_RECIPIENT_SERVER,
    COMM_RECIPIENT_CLIENT,
    COMM_RECIPIENT_QUEUE,
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_CONTROLLER_H
