#ifndef POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_INPUT_H
#define POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_INPUT_H

enum BattleInputRunCommandType {
    BI_RUNCMD_RUN = 0,
    BI_RUNCMD_CANCEL
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_INPUT_H
