#ifndef POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_SCRIPT_H
#define POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_SCRIPT_H

#define MIN_STAT_STAGE     0
#define DEFAULT_STAT_STAGE 6
#define MAX_STAT_STAGE     12

#define BALL_3_SHAKES_SUCCESS 4

#endif // POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_SCRIPT_H
