#ifndef POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_IO_H
#define POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_IO_H

enum BattleIOCommand {
    BTLIOCMD_PRINT_MESSAGE = 21,

    BTLIOCMD_SHOW_BATTLE_START_PARTY_GAUGE = 48,
    BTLIOCMD_HIDE_BATTLE_START_PARTY_GAUGE,
    BTLIOCMD_SHOW_PARTY_GAUGE,
    BTLIOCMD_HIDE_PARTY_GAUGE,
    BTLIOCMD_LOAD_PARTY_GAUGE_GRAPHICS,
    BTLIOCMD_FREE_PARTY_GAUGE_GRAPHICS,
};

enum BattleIORecipient {
    BTLIO_RECIPIENT_ENQUEUE = 1,
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_BATTLE_IO_H
