#ifndef POKEPLATINUM_CONSTANTS_BATTLE_SCRIPTS_H
#define POKEPLATINUM_CONSTANTS_BATTLE_SCRIPTS_H

enum {
    BATTLE_SCRIPT_ANIMATION_DEEP_FOG = 18,
    BATTLE_SCRIPT_ANIMATION_RAINING,
    BATTLE_SCRIPT_ANIMATION_HAILING,
    BATTLE_SCRIPT_ANIMATION_SANDSTORM,
    BATTLE_SCRIPT_ANIMATION_SUNNY,
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_SCRIPTS_H