#ifndef POKEPLATINUM_CONSTANTS_BATTLE_SIDE_EFFECTS_H
#define POKEPLATINUM_CONSTANTS_BATTLE_SIDE_EFFECTS_H

#define MOVE_SIDE_EFFECT_BREAK_SCREENS              (1 << 23)
#define MOVE_SIDE_EFFECT_CHECK_SUBSTITUTE           (1 << 24)
#define MOVE_SIDE_EFFECT_CHECK_HP_AND_SUBSTITUTE    (1 << 25)
#define MOVE_SIDE_EFFECT_PROBABILISTIC              (1 << 26)
#define MOVE_SIDE_EFFECT_CANNOT_PREVENT             (1 << 27)
#define MOVE_SIDE_EFFECT_CHECK_HP                   (1 << 28)
#define MOVE_SIDE_EFFECT_ON_HIT                     (1 << 29)
#define MOVE_SIDE_EFFECT_TO_ATTACKER                (1 << 30)
#define MOVE_SIDE_EFFECT_TO_DEFENDER                (1 << 31)

#define MOVE_SIDE_EFFECT_FLAGS                      (MOVE_SIDE_EFFECT_BREAK_SCREENS \
                                                     | MOVE_SIDE_EFFECT_CHECK_SUBSTITUTE \
                                                     | MOVE_SIDE_EFFECT_CHECK_HP_AND_SUBSTITUTE \
                                                     | MOVE_SIDE_EFFECT_PROBABILISTIC \
                                                     | MOVE_SIDE_EFFECT_CANNOT_PREVENT \
                                                     | MOVE_SIDE_EFFECT_CHECK_HP \
                                                     | MOVE_SIDE_EFFECT_ON_HIT \
                                                     | MOVE_SIDE_EFFECT_TO_ATTACKER \
                                                     | MOVE_SIDE_EFFECT_TO_DEFENDER)
#define MOVE_SIDE_EFFECT_SUBSCRIPT_POINTER          (~MOVE_SIDE_EFFECT_FLAGS)

enum {
    MOVE_SUBSCRIPT_PTR_NONE = 0,
    MOVE_SUBSCRIPT_PTR_SLEEP,
    MOVE_SUBSCRIPT_PTR_POISON,
    MOVE_SUBSCRIPT_PTR_BURN,
    MOVE_SUBSCRIPT_PTR_FREEZE,
    MOVE_SUBSCRIPT_PTR_PARALYZE,
    MOVE_SUBSCRIPT_PTR_BADLY_POISON,
    MOVE_SUBSCRIPT_PTR_CONFUSE,
    MOVE_SUBSCRIPT_PTR_FLINCH,
    MOVE_SUBSCRIPT_PTR_REST,
    MOVE_SUBSCRIPT_PTR_UPROAR,
    MOVE_SUBSCRIPT_PTR_PAY_DAY,
    MOVE_SUBSCRIPT_PTR_VANISH_CHARGE_TURN,
    MOVE_SUBSCRIPT_PTR_BIND_TARGET,
    MOVE_SUBSCRIPT_PTR_QUARTER_RECOIL,
    MOVE_SUBSCRIPT_PTR_ATTACK_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_DEFENSE_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_SPEED_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_SP_ATTACK_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_SP_DEFENSE_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_ACCURACY_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_EVASION_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_ATTACK_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_DEFENSE_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_SPEED_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_SP_ATTACK_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_SP_DEFENSE_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_ACCURACY_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_EVASION_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_RECHARGE_TURN,
    MOVE_SUBSCRIPT_PTR_SET_RAGE_FLAG,
    MOVE_SUBSCRIPT_PTR_STEAL_ITEM,
    MOVE_SUBSCRIPT_PTR_MEAN_LOOK,
    MOVE_SUBSCRIPT_PTR_NIGHTMARE_START,
    MOVE_SUBSCRIPT_PTR_BOOST_ALL_STATS,
    MOVE_SUBSCRIPT_PTR_RAPID_SPIN,
    MOVE_SUBSCRIPT_PTR_HEAL_TARGET_PARALYSIS,
    MOVE_SUBSCRIPT_PTR_USER_ATK_AND_DEF_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_RECOIL_1_3,
    MOVE_SUBSCRIPT_PTR_ATTACK_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_DEFENSE_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_SPEED_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_SP_ATTACK_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_SP_DEFENSE_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_ACCURACY_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_EVASION_UP_2_STAGES,
    MOVE_SUBSCRIPT_PTR_ATTACK_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_DEFENSE_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_SPEED_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_SP_ATTACK_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_SP_DEFENSE_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_ACCURACY_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_EVASION_DOWN_2_STAGES,
    MOVE_SUBSCRIPT_PTR_THRASH,
    MOVE_SUBSCRIPT_PTR_KNOCK_OFF,
    MOVE_SUBSCRIPT_PTR_USER_DEF_AND_SPDEF_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_USER_ATK_AND_DEF_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_TARGET_ATK_AND_DEF_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_USER_SPATK_AND_SPDEF_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_USER_ATK_AND_SPEED_UP_1_STAGE,
    MOVE_SUBSCRIPT_PTR_DRAIN_HALF_DAMAGE_DEALT,
    MOVE_SUBSCRIPT_PTR_DREAM_EATER,
    MOVE_SUBSCRIPT_PTR_RESET_ALL_STAT_STAGES,
    MOVE_SUBSCRIPT_PTR_BIDE_START,
    MOVE_SUBSCRIPT_PTR_STRUGGLE,
    MOVE_SUBSCRIPT_PTR_CONVERSION,
    MOVE_SUBSCRIPT_PTR_RECOVER_HALF_MAX_HP,
    MOVE_SUBSCRIPT_PTR_LIGHT_SCREEN,
    MOVE_SUBSCRIPT_PTR_REFLECT,
    MOVE_SUBSCRIPT_PTR_MIST,
    MOVE_SUBSCRIPT_PTR_FOCUS_ENERGY,
    MOVE_SUBSCRIPT_PTR_MIMIC,
    MOVE_SUBSCRIPT_PTR_LEECH_SEED_START,
    MOVE_SUBSCRIPT_PTR_DISABLE_START,
    MOVE_SUBSCRIPT_PTR_ENCORE_START,
    MOVE_SUBSCRIPT_PTR_PAIN_SPLIT,
    MOVE_SUBSCRIPT_PTR_CONVERSION_2,
    MOVE_SUBSCRIPT_PTR_LOCK_ON,
    MOVE_SUBSCRIPT_PTR_SKETCH,
    MOVE_SUBSCRIPT_PTR_FEINT,
    MOVE_SUBSCRIPT_PTR_DESTINY_BOND,
    MOVE_SUBSCRIPT_PTR_REDUCE_TARGET_PP,
    MOVE_SUBSCRIPT_PTR_PROTECT,
    MOVE_SUBSCRIPT_PTR_HEAL_BELL,
    MOVE_SUBSCRIPT_PTR_TRY_SUBSTITUTE,
    MOVE_SUBSCRIPT_PTR_FORCE_TARGET_TO_SWITCH_OR_FLEE,
    MOVE_SUBSCRIPT_PTR_TRANSFORM_INTO_TARGET,
    MOVE_SUBSCRIPT_PTR_MINIMIZE,
    MOVE_SUBSCRIPT_PTR_CURSE_NORMAL,
    MOVE_SUBSCRIPT_PTR_CURSE_GHOST,
    MOVE_SUBSCRIPT_PTR_PRINT_MESSAGE_AND_PLAY_ANIMATION,
    MOVE_SUBSCRIPT_PTR_FORESIGHT,
    MOVE_SUBSCRIPT_PTR_PERISH_SONG_START,
    MOVE_SUBSCRIPT_PTR_WEATHER_START,
    MOVE_SUBSCRIPT_PTR_SWAGGER,
    MOVE_SUBSCRIPT_PTR_INFATUATE,
    MOVE_SUBSCRIPT_PTR_SAFEGUARD_START,
    MOVE_SUBSCRIPT_PTR_PRESENT_HEAL,
    MOVE_SUBSCRIPT_PTR_MAGNITUDE,
    MOVE_SUBSCRIPT_PTR_BATON_PASS,
    MOVE_SUBSCRIPT_PTR_BELLY_DRUM,
    MOVE_SUBSCRIPT_PTR_TELEPORT,
    MOVE_SUBSCRIPT_PTR_FUTURE_SIGHT_START,
    MOVE_SUBSCRIPT_PTR_STOCKPILE,
    MOVE_SUBSCRIPT_PTR_SWALLOW,
    MOVE_SUBSCRIPT_PTR_TORMENT_START,
    MOVE_SUBSCRIPT_PTR_FLATTER,
    MOVE_SUBSCRIPT_PTR_MEMENTO,
    MOVE_SUBSCRIPT_PTR_CHARGE,
    MOVE_SUBSCRIPT_PTR_TAUNT_START,
    MOVE_SUBSCRIPT_PTR_EXCHANGE_ITEMS,
    MOVE_SUBSCRIPT_PTR_COPY_ABILITY,
    MOVE_SUBSCRIPT_PTR_BREAK_SCREENS,
    MOVE_SUBSCRIPT_PTR_YAWN,
    MOVE_SUBSCRIPT_PTR_EXCHANGE_ABILITIES,
    MOVE_SUBSCRIPT_PTR_RECOVER_PSN_PRZ_BRN,
    MOVE_SUBSCRIPT_PTR_ROOST,
    MOVE_SUBSCRIPT_PTR_HEAL_TARGET_SLEEP,
    MOVE_SUBSCRIPT_PTR_GRAVITY_START,
    MOVE_SUBSCRIPT_PTR_MIRACLE_EYE,
    MOVE_SUBSCRIPT_PTR_HEALING_WISH,
    MOVE_SUBSCRIPT_PTR_TAILWIND_START,
    MOVE_SUBSCRIPT_PTR_USER_DEF_AND_SPDEF_DOWN_1_STAGE,
    MOVE_SUBSCRIPT_PTR_USER_SWAP_ATK_AND_DEF,
    MOVE_SUBSCRIPT_PTR_SUPPRESS_TARGET_ABILITY,
    MOVE_SUBSCRIPT_PTR_LUCKY_CHANT_START,
    MOVE_SUBSCRIPT_PTR_EXCHANGE_ATK_AND_SPATK_STAGES,
    MOVE_SUBSCRIPT_PTR_EXCHANGE_DEF_AND_SPDEF_STAGES,
    MOVE_SUBSCRIPT_PTR_GIVE_TARGET_INSOMNIA,
    MOVE_SUBSCRIPT_PTR_EXCHANGE_ALL_STAT_STAGES,
    MOVE_SUBSCRIPT_PTR_RECOIL_1_3_CHANCE_TO_BURN,
    MOVE_SUBSCRIPT_PTR_DEFOG,
    MOVE_SUBSCRIPT_PTR_HEAL_BLOCK_START,
    MOVE_SUBSCRIPT_PTR_ATTACK_THEN_SWITCH_OUT,
    MOVE_SUBSCRIPT_PTR_EMBARGO_START,
    MOVE_SUBSCRIPT_PTR_PLUCK,
    MOVE_SUBSCRIPT_PTR_FLING,
    MOVE_SUBSCRIPT_PTR_RECOIL_1_3_CHANCE_TO_PARALYZE,
    MOVE_SUBSCRIPT_PTR_RECOIL_1_2,
    MOVE_SUBSCRIPT_PTR_BURN_OR_FLINCH,
    MOVE_SUBSCRIPT_PTR_FREEZE_OR_FLINCH,
    MOVE_SUBSCRIPT_PTR_PARALYZE_OR_FLINCH,
    MOVE_SUBSCRIPT_PTR_CHATTER,
    MOVE_SUBSCRIPT_PTR_LUNAR_DANCE,
    MOVE_SUBSCRIPT_PTR_GIVE_TARGET_OWN_STATUS,

    MOVE_SUBSCRIPT_PTR_MAX = MOVE_SIDE_EFFECT_SUBSCRIPT_POINTER,
};

enum SideEffectType {
    SIDE_EFFECT_TYPE_NONE = 0, //< No side effect to apply
    SIDE_EFFECT_TYPE_DIRECT, //< A direct side effect; used for, e.g., status moves whose only purpose is the effect
    SIDE_EFFECT_TYPE_INDIRECT, //< An indirect side effect; used for moves which deal damage and have some secondary effect
    SIDE_EFFECT_TYPE_ABILITY, //< An effect applied from an ability, e.g. Effect Spore or Static
    SIDE_EFFECT_TYPE_MOVE_EFFECT, //< An effect which comes from another move's effect, e.g. Yawn, where the sleep is delayed
    SIDE_EFFECT_TYPE_HELD_ITEM, //< An effect which comes from a held item, e.g. Flame Orb
    SIDE_EFFECT_TYPE_TOXIC_SPIKES, //< An effect which comes from specifically Toxic Spikes
    SIDE_EFFECT_TYPE_DISOBEDIENCE, //< An effect which comes from a Pokemon disobeying its trainer
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_SIDE_EFFECTS_H

