#ifndef POKEPLATINUM_CONSTANTS_BATTLE_TERRAIN_H
#define POKEPLATINUM_CONSTANTS_BATTLE_TERRAIN_H

enum Terrain {
    TERRAIN_PLAIN = 0,
    TERRAIN_SAND,
    TERRAIN_GRASS,
    TERRAIN_PUDDLE,
    TERRAIN_MOUNTAIN,
    TERRAIN_CAVE,
    TERRAIN_SNOW,
    TERRAIN_WATER,
    TERRAIN_ICE,
    TERRAIN_BUILDING,
    TERRAIN_GREAT_MARSH,
    TERRAIN_BRIDGE,
    
    TERRAIN_AARON,
    TERRAIN_BERTHA,
    TERRAIN_FLINT,
    TERRAIN_LUCIAN,
    TERRAIN_CYNTHIA,

    TERRAIN_DISTORTION_WORLD,
    TERRAIN_BATTLE_TOWER,
    TERRAIN_BATTLE_FACTORY,
    TERRAIN_BATTLE_ARCADE,
    TERRAIN_BATTLE_CASTLE,
    TERRAIN_BATTLE_HALL,
    TERRAIN_GIRATINA,

    TERRAIN_MAX
};

#endif // POKEPLATINUM_CONSTANTS_BATTLE_TERRAIN_H