#ifndef POKEPLATINUM_CONSTANTS_BATTLE_TURN_FLAGS_H
#define POKEPLATINUM_CONSTANTS_BATTLE_TURN_FLAGS_H

// unused: 1 << 0
#define SELF_TURN_FLAG_PLUCK_BERRY    (1 << 1)
#define SELF_TURN_FLAG_INFATUATED     (1 << 2)
#define SELF_TURN_FLAG_SUBSTITUTE_HIT (1 << 3)

#endif // POKEPLATINUM_CONSTANTS_BATTLE_TURN_FLAGS_H
