#ifndef POKEPLATINUM_FRSCRCMD_BATTLE_CASTLE_H
#define POKEPLATINUM_FRSCRCMD_BATTLE_CASTLE_H

#include "overlay104/defs.h"

BOOL FrontierScrCmd_InitBattleCastle(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_LoadTrainersForRound(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_FreeBattleCastle(FrontierScriptContext *param0);
BOOL FrontierScrCmd_OpenBattleCastleSelfApp(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_DummyOpenBattleCastleApp(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_CleanupBattle(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_StartBattle(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_OpenBattleCastleOpponentApp(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_SetupFirstOpponent(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_SetupNextOpponent(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_CallBattleCastleFunction(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_CheckWonBattle(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_SendCommMessage(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_WaitForCommResponses(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_A5(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_ShowCastlePointsWindows(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_ClearCastlePointsWindows(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_ReprintCastlePointsInfo(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_GetCurrentCastlePoints(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_SpendCastlePoints(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_ReceiveCastlePoints(FrontierScriptContext *ctx);
BOOL FrontierScrCmd_BattleCastle_PrintTrainerIntro(FrontierScriptContext *ctx);

#endif // POKEPLATINUM_FRSCRCMD_BATTLE_CASTLE_H
