prebuilt_files = copy_gen.process(files(
    'ending_0.RGCN',
    'ending_1.RECN',
    'ending_2.RNAN',
    'ending_3.RCSN',
    'ending_4.RCSN',
    'ending_5.RCSN',
    'ending_6.RCSN',
    'ending_7.RCSN',
    'ending_8.RCSN',
    'ending_9.RGCN',
    'ending_10.RGCN',
    'ending_11.RGCN',
    'ending_12.RGCN',
    'ending_13.RGCN',
    'ending_14.RGCN',
    'ending_15.RLCN',
    'ending_16.RLCN',
    'ending_17.RLCN',
    'ending_18.RLCN',
    'ending_19.RLCN',
    'ending_20.RLCN',
    'ending_21.RLCN',
    'ending_22.RLCN',
    'ending_23.RLCN',
    'ending_24.RCSN',
    'ending_25.RGCN',
    'ending_26.RLCN',
    'ending_27.RGCN',
    'ending_28.RGCN',
    'ending_29.RECN',
    'ending_30.RNAN',
    'ending_31.RLCN',
    'ending_32.RGCN',
    'ending_33.RGCN',
    'ending_34.RECN',
    'ending_35.RNAN',
    'ending_36.RLCN',
    'ending_37.RCSN',
    'ending_38.RGCN',
    'ending_39.RGCN',
    'ending_40.RGCN',
    'ending_41.RGCN',
    'ending_42.RGCN',
    'ending_43.RGCN',
    'ending_44.RGCN',
    'ending_45.RGCN',
    'ending_46.RGCN',
    'ending_47.RGCN',
    'ending_48.RLCN',
    'ending_49.RLCN',
    'ending_50.RLCN',
    'ending_51.RLCN',
    'ending_52.RLCN',
    'ending_53.RLCN',
    'ending_54.RLCN',
    'ending_55.RLCN',
    'ending_56.RLCN',
    'ending_57.RLCN',
    'ending_58.RGCN',
    'ending_59.RGCN',
    'ending_60.RGCN',
    'ending_61.RGCN',
    'ending_62.RGCN',
    'ending_63.RGCN',
    'ending_64.RGCN',
    'ending_65.RGCN',
    'ending_66.RGCN',
    'ending_67.RGCN',
    'ending_68.RLCN',
    'ending_69.RLCN',
    'ending_70.RLCN',
    'ending_71.RLCN',
    'ending_72.RLCN',
    'ending_73.RLCN',
    'ending_74.RLCN',
    'ending_75.RLCN',
    'ending_76.RLCN',
    'ending_77.RLCN',
    'ending_78.BMD0',
    'ending_79.BMD0',
    'ending_80.BMD0',
    'ending_81.BMD0',
    'ending_82.BMD0',
    'ending_83.BMD0',
    'ending_84.BMD0',
    'ending_85.RLCN',
    'ending_86.RCSN',
    'ending_87.RGCN',
    'ending_88.RGCN',
    'ending_89.RGCN',
    'ending_90.RGCN',
    'ending_91.RLCN',
    'ending_92.RLCN',
    'ending_93.RLCN',
    'ending_94.RLCN',
    'ending_95.RGCN',
    'ending_96.RGCN',
    'ending_97.RGCN',
    'ending_98.RGCN',
    'ending_99.RLCN',
    'ending_100.RLCN',
    'ending_101.RLCN',
    'ending_102.RLCN',
))

ending_narc = custom_target('ending.narc',
    output: [
        'ending.narc',
        'ending.naix',
    ],
    input: [
        prebuilt_files,
    ],
    command: [
        nitroarc_exe,
        '--create',
        '--index',
        '--files-from', files('ending.order'),
        '--file', '@OUTPUT0@',
        '@PRIVATE_DIR@',
    ],
)

nitrofs_files += ending_narc
naix_headers += ending_narc[1]
