    .include "consts/movement.inc"

    .macro MoveAction_000 length=1
    .short MOVEMENT_ACTION_000
    .short \length
    .endm

    .macro MoveAction_001 length=1
    .short MOVEMENT_ACTION_001
    .short \length
    .endm

    .macro MoveAction_002 length=1
    .short MOVEMENT_ACTION_002
    .short \length
    .endm

    .macro MoveAction_003 length=1
    .short MOVEMENT_ACTION_003
    .short \length
    .endm

    .macro MoveAction_004 length=1
    .short MOVEMENT_ACTION_004
    .short \length
    .endm

    .macro MoveAction_005 length=1
    .short MOVEMENT_ACTION_005
    .short \length
    .endm

    .macro MoveAction_006 length=1
    .short MOVEMENT_ACTION_006
    .short \length
    .endm

    .macro MoveAction_007 length=1
    .short MOVEMENT_ACTION_007
    .short \length
    .endm

    .macro MoveAction_008 length=1
    .short MOVEMENT_ACTION_008
    .short \length
    .endm

    .macro MoveAction_009 length=1
    .short MOVEMENT_ACTION_009
    .short \length
    .endm

    .macro MoveAction_010 length=1
    .short MOVEMENT_ACTION_010
    .short \length
    .endm

    .macro MoveAction_011 length=1
    .short MOVEMENT_ACTION_011
    .short \length
    .endm

    .macro MoveAction_012 length=1
    .short MOVEMENT_ACTION_012
    .short \length
    .endm

    .macro MoveAction_013 length=1
    .short MOVEMENT_ACTION_013
    .short \length
    .endm

    .macro MoveAction_014 length=1
    .short MOVEMENT_ACTION_014
    .short \length
    .endm

    .macro MoveAction_015 length=1
    .short MOVEMENT_ACTION_015
    .short \length
    .endm

    .macro MoveAction_016 length=1
    .short MOVEMENT_ACTION_016
    .short \length
    .endm

    .macro MoveAction_017 length=1
    .short MOVEMENT_ACTION_017
    .short \length
    .endm

    .macro MoveAction_018 length=1
    .short MOVEMENT_ACTION_018
    .short \length
    .endm

    .macro MoveAction_019 length=1
    .short MOVEMENT_ACTION_019
    .short \length
    .endm

    .macro MoveAction_020 length=1
    .short MOVEMENT_ACTION_020
    .short \length
    .endm

    .macro MoveAction_021 length=1
    .short MOVEMENT_ACTION_021
    .short \length
    .endm

    .macro MoveAction_022 length=1
    .short MOVEMENT_ACTION_022
    .short \length
    .endm

    .macro MoveAction_023 length=1
    .short MOVEMENT_ACTION_023
    .short \length
    .endm

    .macro MoveAction_024 length=1
    .short MOVEMENT_ACTION_024
    .short \length
    .endm

    .macro MoveAction_025 length=1
    .short MOVEMENT_ACTION_025
    .short \length
    .endm

    .macro MoveAction_026 length=1
    .short MOVEMENT_ACTION_026
    .short \length
    .endm

    .macro MoveAction_027 length=1
    .short MOVEMENT_ACTION_027
    .short \length
    .endm

    .macro MoveAction_028 length=1
    .short MOVEMENT_ACTION_028
    .short \length
    .endm

    .macro MoveAction_029 length=1
    .short MOVEMENT_ACTION_029
    .short \length
    .endm

    .macro MoveAction_030 length=1
    .short MOVEMENT_ACTION_030
    .short \length
    .endm

    .macro MoveAction_031 length=1
    .short MOVEMENT_ACTION_031
    .short \length
    .endm

    .macro MoveAction_032 length=1
    .short MOVEMENT_ACTION_032
    .short \length
    .endm

    .macro MoveAction_033 length=1
    .short MOVEMENT_ACTION_033
    .short \length
    .endm

    .macro MoveAction_034 length=1
    .short MOVEMENT_ACTION_034
    .short \length
    .endm

    .macro MoveAction_035 length=1
    .short MOVEMENT_ACTION_035
    .short \length
    .endm

    .macro MoveAction_036 length=1
    .short MOVEMENT_ACTION_036
    .short \length
    .endm

    .macro MoveAction_037 length=1
    .short MOVEMENT_ACTION_037
    .short \length
    .endm

    .macro MoveAction_038 length=1
    .short MOVEMENT_ACTION_038
    .short \length
    .endm

    .macro MoveAction_039 length=1
    .short MOVEMENT_ACTION_039
    .short \length
    .endm

    .macro MoveAction_040 length=1
    .short MOVEMENT_ACTION_040
    .short \length
    .endm

    .macro MoveAction_041 length=1
    .short MOVEMENT_ACTION_041
    .short \length
    .endm

    .macro MoveAction_042 length=1
    .short MOVEMENT_ACTION_042
    .short \length
    .endm

    .macro MoveAction_043 length=1
    .short MOVEMENT_ACTION_043
    .short \length
    .endm

    .macro MoveAction_044 length=1
    .short MOVEMENT_ACTION_044
    .short \length
    .endm

    .macro MoveAction_045 length=1
    .short MOVEMENT_ACTION_045
    .short \length
    .endm

    .macro MoveAction_046 length=1
    .short MOVEMENT_ACTION_046
    .short \length
    .endm

    .macro MoveAction_047 length=1
    .short MOVEMENT_ACTION_047
    .short \length
    .endm

    .macro MoveAction_048 length=1
    .short MOVEMENT_ACTION_048
    .short \length
    .endm

    .macro MoveAction_049 length=1
    .short MOVEMENT_ACTION_049
    .short \length
    .endm

    .macro MoveAction_050 length=1
    .short MOVEMENT_ACTION_050
    .short \length
    .endm

    .macro MoveAction_051 length=1
    .short MOVEMENT_ACTION_051
    .short \length
    .endm

    .macro MoveAction_052 length=1
    .short MOVEMENT_ACTION_052
    .short \length
    .endm

    .macro MoveAction_053 length=1
    .short MOVEMENT_ACTION_053
    .short \length
    .endm

    .macro MoveAction_054 length=1
    .short MOVEMENT_ACTION_054
    .short \length
    .endm

    .macro MoveAction_055 length=1
    .short MOVEMENT_ACTION_055
    .short \length
    .endm

    .macro MoveAction_056 length=1
    .short MOVEMENT_ACTION_056
    .short \length
    .endm

    .macro MoveAction_057 length=1
    .short MOVEMENT_ACTION_057
    .short \length
    .endm

    .macro MoveAction_058 length=1
    .short MOVEMENT_ACTION_058
    .short \length
    .endm

    .macro MoveAction_059 length=1
    .short MOVEMENT_ACTION_059
    .short \length
    .endm

    .macro MoveAction_060 length=1
    .short MOVEMENT_ACTION_060
    .short \length
    .endm

    .macro MoveAction_061 length=1
    .short MOVEMENT_ACTION_061
    .short \length
    .endm

    .macro MoveAction_062 length=1
    .short MOVEMENT_ACTION_062
    .short \length
    .endm

    .macro MoveAction_063 length=1
    .short MOVEMENT_ACTION_063
    .short \length
    .endm

    .macro MoveAction_064 length=1
    .short MOVEMENT_ACTION_064
    .short \length
    .endm

    .macro MoveAction_065 length=1
    .short MOVEMENT_ACTION_065
    .short \length
    .endm

    .macro MoveAction_066 length=1
    .short MOVEMENT_ACTION_066
    .short \length
    .endm

    .macro MoveAction_067 length=1
    .short MOVEMENT_ACTION_067
    .short \length
    .endm

    .macro MoveAction_068 length=1
    .short MOVEMENT_ACTION_068
    .short \length
    .endm

    .macro MoveAction_069 length=1
    .short MOVEMENT_ACTION_069
    .short \length
    .endm

    .macro MoveAction_070 length=1
    .short MOVEMENT_ACTION_070
    .short \length
    .endm

    .macro MoveAction_071 length=1
    .short MOVEMENT_ACTION_071
    .short \length
    .endm

    .macro MoveAction_072 length=1
    .short MOVEMENT_ACTION_072
    .short \length
    .endm

    .macro MoveAction_073 length=1
    .short MOVEMENT_ACTION_073
    .short \length
    .endm

    .macro MoveAction_074 length=1
    .short MOVEMENT_ACTION_074
    .short \length
    .endm

    .macro MoveAction_075 length=1
    .short MOVEMENT_ACTION_075
    .short \length
    .endm

    .macro MoveAction_076 length=1
    .short MOVEMENT_ACTION_076
    .short \length
    .endm

    .macro MoveAction_077 length=1
    .short MOVEMENT_ACTION_077
    .short \length
    .endm

    .macro MoveAction_078 length=1
    .short MOVEMENT_ACTION_078
    .short \length
    .endm

    .macro MoveAction_079 length=1
    .short MOVEMENT_ACTION_079
    .short \length
    .endm

    .macro MoveAction_080 length=1
    .short MOVEMENT_ACTION_080
    .short \length
    .endm

    .macro MoveAction_081 length=1
    .short MOVEMENT_ACTION_081
    .short \length
    .endm

    .macro MoveAction_082 length=1
    .short MOVEMENT_ACTION_082
    .short \length
    .endm

    .macro MoveAction_083 length=1
    .short MOVEMENT_ACTION_083
    .short \length
    .endm

    .macro MoveAction_084 length=1
    .short MOVEMENT_ACTION_084
    .short \length
    .endm

    .macro MoveAction_085 length=1
    .short MOVEMENT_ACTION_085
    .short \length
    .endm

    .macro MoveAction_086 length=1
    .short MOVEMENT_ACTION_086
    .short \length
    .endm

    .macro MoveAction_087 length=1
    .short MOVEMENT_ACTION_087
    .short \length
    .endm

    .macro MoveAction_088 length=1
    .short MOVEMENT_ACTION_088
    .short \length
    .endm

    .macro MoveAction_089 length=1
    .short MOVEMENT_ACTION_089
    .short \length
    .endm

    .macro MoveAction_090 length=1
    .short MOVEMENT_ACTION_090
    .short \length
    .endm

    .macro MoveAction_091 length=1
    .short MOVEMENT_ACTION_091
    .short \length
    .endm

    .macro MoveAction_092 length=1
    .short MOVEMENT_ACTION_092
    .short \length
    .endm

    .macro MoveAction_093 length=1
    .short MOVEMENT_ACTION_093
    .short \length
    .endm

    .macro MoveAction_094 length=1
    .short MOVEMENT_ACTION_094
    .short \length
    .endm

    .macro MoveAction_095 length=1
    .short MOVEMENT_ACTION_095
    .short \length
    .endm

    .macro MoveAction_096 length=1
    .short MOVEMENT_ACTION_096
    .short \length
    .endm

    .macro MoveAction_097 length=1
    .short MOVEMENT_ACTION_097
    .short \length
    .endm

    .macro MoveAction_098 length=1
    .short MOVEMENT_ACTION_098
    .short \length
    .endm

    .macro MoveAction_099 length=1
    .short MOVEMENT_ACTION_099
    .short \length
    .endm

    .macro MoveAction_100 length=1
    .short MOVEMENT_ACTION_100
    .short \length
    .endm

    .macro MoveAction_101 length=1
    .short MOVEMENT_ACTION_101
    .short \length
    .endm

    .macro MoveAction_102 length=1
    .short MOVEMENT_ACTION_102
    .short \length
    .endm

    .macro MoveAction_103 length=1
    .short MOVEMENT_ACTION_103
    .short \length
    .endm

    .macro MoveAction_104 length=1
    .short MOVEMENT_ACTION_104
    .short \length
    .endm

    .macro MoveAction_105 length=1
    .short MOVEMENT_ACTION_105
    .short \length
    .endm

    .macro MoveAction_106 length=1
    .short MOVEMENT_ACTION_106
    .short \length
    .endm

    .macro MoveAction_107 length=1
    .short MOVEMENT_ACTION_107
    .short \length
    .endm

    .macro MoveAction_108 length=1
    .short MOVEMENT_ACTION_108
    .short \length
    .endm

    .macro MoveAction_109 length=1
    .short MOVEMENT_ACTION_109
    .short \length
    .endm

    .macro MoveAction_110 length=1
    .short MOVEMENT_ACTION_110
    .short \length
    .endm

    .macro MoveAction_111 length=1
    .short MOVEMENT_ACTION_111
    .short \length
    .endm

    .macro MoveAction_112 length=1
    .short MOVEMENT_ACTION_112
    .short \length
    .endm

    .macro MoveAction_113 length=1
    .short MOVEMENT_ACTION_113
    .short \length
    .endm

    .macro MoveAction_114 length=1
    .short MOVEMENT_ACTION_114
    .short \length
    .endm

    .macro MoveAction_115 length=1
    .short MOVEMENT_ACTION_115
    .short \length
    .endm

    .macro MoveAction_116 length=1
    .short MOVEMENT_ACTION_116
    .short \length
    .endm

    .macro MoveAction_117 length=1
    .short MOVEMENT_ACTION_117
    .short \length
    .endm

    .macro MoveAction_118 length=1
    .short MOVEMENT_ACTION_118
    .short \length
    .endm

    .macro MoveAction_119 length=1
    .short MOVEMENT_ACTION_119
    .short \length
    .endm

    .macro MoveAction_120 length=1
    .short MOVEMENT_ACTION_120
    .short \length
    .endm

    .macro MoveAction_121 length=1
    .short MOVEMENT_ACTION_121
    .short \length
    .endm

    .macro MoveAction_122 length=1
    .short MOVEMENT_ACTION_122
    .short \length
    .endm

    .macro MoveAction_123 length=1
    .short MOVEMENT_ACTION_123
    .short \length
    .endm

    .macro MoveAction_124 length=1
    .short MOVEMENT_ACTION_124
    .short \length
    .endm

    .macro MoveAction_125 length=1
    .short MOVEMENT_ACTION_125
    .short \length
    .endm

    .macro MoveAction_126 length=1
    .short MOVEMENT_ACTION_126
    .short \length
    .endm

    .macro MoveAction_127 length=1
    .short MOVEMENT_ACTION_127
    .short \length
    .endm

    .macro MoveAction_128 length=1
    .short MOVEMENT_ACTION_128
    .short \length
    .endm

    .macro MoveAction_129 length=1
    .short MOVEMENT_ACTION_129
    .short \length
    .endm

    .macro MoveAction_130 length=1
    .short MOVEMENT_ACTION_130
    .short \length
    .endm

    .macro MoveAction_131 length=1
    .short MOVEMENT_ACTION_131
    .short \length
    .endm

    .macro MoveAction_132 length=1
    .short MOVEMENT_ACTION_132
    .short \length
    .endm

    .macro MoveAction_133 length=1
    .short MOVEMENT_ACTION_133
    .short \length
    .endm

    .macro MoveAction_134 length=1
    .short MOVEMENT_ACTION_134
    .short \length
    .endm

    .macro MoveAction_135 length=1
    .short MOVEMENT_ACTION_135
    .short \length
    .endm

    .macro MoveAction_136 length=1
    .short MOVEMENT_ACTION_136
    .short \length
    .endm

    .macro MoveAction_137 length=1
    .short MOVEMENT_ACTION_137
    .short \length
    .endm

    .macro MoveAction_138 length=1
    .short MOVEMENT_ACTION_138
    .short \length
    .endm

    .macro MoveAction_139 length=1
    .short MOVEMENT_ACTION_139
    .short \length
    .endm

    .macro MoveAction_140 length=1
    .short MOVEMENT_ACTION_140
    .short \length
    .endm

    .macro MoveAction_141 length=1
    .short MOVEMENT_ACTION_141
    .short \length
    .endm

    .macro MoveAction_142 length=1
    .short MOVEMENT_ACTION_142
    .short \length
    .endm

    .macro MoveAction_143 length=1
    .short MOVEMENT_ACTION_143
    .short \length
    .endm

    .macro MoveAction_144 length=1
    .short MOVEMENT_ACTION_144
    .short \length
    .endm

    .macro MoveAction_145 length=1
    .short MOVEMENT_ACTION_145
    .short \length
    .endm

    .macro MoveAction_146 length=1
    .short MOVEMENT_ACTION_146
    .short \length
    .endm

    .macro MoveAction_147 length=1
    .short MOVEMENT_ACTION_147
    .short \length
    .endm

    .macro MoveAction_148 length=1
    .short MOVEMENT_ACTION_148
    .short \length
    .endm

    .macro MoveAction_149 length=1
    .short MOVEMENT_ACTION_149
    .short \length
    .endm

    .macro MoveAction_150 length=1
    .short MOVEMENT_ACTION_150
    .short \length
    .endm

    .macro MoveAction_151 length=1
    .short MOVEMENT_ACTION_151
    .short \length
    .endm

    .macro MoveAction_152 length=1
    .short MOVEMENT_ACTION_152
    .short \length
    .endm

    .macro MoveAction_153 length=1
    .short MOVEMENT_ACTION_153
    .short \length
    .endm

    .macro EndMovement
    .short MOVEMENT_ACTION_END
    .short 0
    .endm
