    .include "consts/movement.inc"

    .macro MoveAction_000 length=1
    .short MOVEMENT_ACTION_0
    .short \length
    .endm

    .macro MoveAction_001 length=1
    .short MOVEMENT_ACTION_1
    .short \length
    .endm

    .macro MoveAction_002 length=1
    .short MOVEMENT_ACTION_2
    .short \length
    .endm

    .macro MoveAction_003 length=1
    .short MOVEMENT_ACTION_3
    .short \length
    .endm

    .macro MoveAction_004 length=1
    .short MOVEMENT_ACTION_4
    .short \length
    .endm

    .macro MoveAction_005 length=1
    .short MOVEMENT_ACTION_5
    .short \length
    .endm

    .macro MoveAction_006 length=1
    .short MOVEMENT_ACTION_6
    .short \length
    .endm

    .macro MoveAction_007 length=1
    .short MOVEMENT_ACTION_7
    .short \length
    .endm

    .macro MoveAction_008 length=1
    .short MOVEMENT_ACTION_8
    .short \length
    .endm

    .macro MoveAction_009 length=1
    .short MOVEMENT_ACTION_9
    .short \length
    .endm

    .macro MoveAction_00A length=1
    .short MOVEMENT_ACTION_A
    .short \length
    .endm

    .macro MoveAction_00B length=1
    .short MOVEMENT_ACTION_B
    .short \length
    .endm

    .macro MoveAction_00C length=1
    .short MOVEMENT_ACTION_C
    .short \length
    .endm

    .macro MoveAction_00D length=1
    .short MOVEMENT_ACTION_D
    .short \length
    .endm

    .macro MoveAction_00E length=1
    .short MOVEMENT_ACTION_E
    .short \length
    .endm

    .macro MoveAction_00F length=1
    .short MOVEMENT_ACTION_F
    .short \length
    .endm

    .macro MoveAction_010 length=1
    .short MOVEMENT_ACTION_10
    .short \length
    .endm

    .macro MoveAction_011 length=1
    .short MOVEMENT_ACTION_11
    .short \length
    .endm

    .macro MoveAction_012 length=1
    .short MOVEMENT_ACTION_12
    .short \length
    .endm

    .macro MoveAction_013 length=1
    .short MOVEMENT_ACTION_13
    .short \length
    .endm

    .macro MoveAction_014 length=1
    .short MOVEMENT_ACTION_14
    .short \length
    .endm

    .macro MoveAction_015 length=1
    .short MOVEMENT_ACTION_15
    .short \length
    .endm

    .macro MoveAction_016 length=1
    .short MOVEMENT_ACTION_16
    .short \length
    .endm

    .macro MoveAction_017 length=1
    .short MOVEMENT_ACTION_17
    .short \length
    .endm

    .macro MoveAction_018 length=1
    .short MOVEMENT_ACTION_18
    .short \length
    .endm

    .macro MoveAction_019 length=1
    .short MOVEMENT_ACTION_19
    .short \length
    .endm

    .macro MoveAction_01A length=1
    .short MOVEMENT_ACTION_1A
    .short \length
    .endm

    .macro MoveAction_01B length=1
    .short MOVEMENT_ACTION_1B
    .short \length
    .endm

    .macro MoveAction_01C length=1
    .short MOVEMENT_ACTION_1C
    .short \length
    .endm

    .macro MoveAction_01D length=1
    .short MOVEMENT_ACTION_1D
    .short \length
    .endm

    .macro MoveAction_01E length=1
    .short MOVEMENT_ACTION_1E
    .short \length
    .endm

    .macro MoveAction_01F length=1
    .short MOVEMENT_ACTION_1F
    .short \length
    .endm

    .macro MoveAction_020 length=1
    .short MOVEMENT_ACTION_20
    .short \length
    .endm

    .macro MoveAction_021 length=1
    .short MOVEMENT_ACTION_21
    .short \length
    .endm

    .macro MoveAction_022 length=1
    .short MOVEMENT_ACTION_22
    .short \length
    .endm

    .macro MoveAction_023 length=1
    .short MOVEMENT_ACTION_23
    .short \length
    .endm

    .macro MoveAction_024 length=1
    .short MOVEMENT_ACTION_24
    .short \length
    .endm

    .macro MoveAction_025 length=1
    .short MOVEMENT_ACTION_25
    .short \length
    .endm

    .macro MoveAction_026 length=1
    .short MOVEMENT_ACTION_26
    .short \length
    .endm

    .macro MoveAction_027 length=1
    .short MOVEMENT_ACTION_27
    .short \length
    .endm

    .macro MoveAction_028 length=1
    .short MOVEMENT_ACTION_28
    .short \length
    .endm

    .macro MoveAction_029 length=1
    .short MOVEMENT_ACTION_29
    .short \length
    .endm

    .macro MoveAction_02A length=1
    .short MOVEMENT_ACTION_2A
    .short \length
    .endm

    .macro MoveAction_02B length=1
    .short MOVEMENT_ACTION_2B
    .short \length
    .endm

    .macro MoveAction_02C length=1
    .short MOVEMENT_ACTION_2C
    .short \length
    .endm

    .macro MoveAction_02D length=1
    .short MOVEMENT_ACTION_2D
    .short \length
    .endm

    .macro MoveAction_02E length=1
    .short MOVEMENT_ACTION_2E
    .short \length
    .endm

    .macro MoveAction_02F length=1
    .short MOVEMENT_ACTION_2F
    .short \length
    .endm

    .macro MoveAction_030 length=1
    .short MOVEMENT_ACTION_30
    .short \length
    .endm

    .macro MoveAction_031 length=1
    .short MOVEMENT_ACTION_31
    .short \length
    .endm

    .macro MoveAction_032 length=1
    .short MOVEMENT_ACTION_32
    .short \length
    .endm

    .macro MoveAction_033 length=1
    .short MOVEMENT_ACTION_33
    .short \length
    .endm

    .macro MoveAction_034 length=1
    .short MOVEMENT_ACTION_34
    .short \length
    .endm

    .macro MoveAction_035 length=1
    .short MOVEMENT_ACTION_35
    .short \length
    .endm

    .macro MoveAction_036 length=1
    .short MOVEMENT_ACTION_36
    .short \length
    .endm

    .macro MoveAction_037 length=1
    .short MOVEMENT_ACTION_37
    .short \length
    .endm

    .macro MoveAction_038 length=1
    .short MOVEMENT_ACTION_38
    .short \length
    .endm

    .macro MoveAction_039 length=1
    .short MOVEMENT_ACTION_39
    .short \length
    .endm

    .macro MoveAction_03A length=1
    .short MOVEMENT_ACTION_3A
    .short \length
    .endm

    .macro MoveAction_03B length=1
    .short MOVEMENT_ACTION_3B
    .short \length
    .endm

    .macro MoveAction_03C length=1
    .short MOVEMENT_ACTION_3C
    .short \length
    .endm

    .macro MoveAction_03D length=1
    .short MOVEMENT_ACTION_3D
    .short \length
    .endm

    .macro MoveAction_03E length=1
    .short MOVEMENT_ACTION_3E
    .short \length
    .endm

    .macro MoveAction_03F length=1
    .short MOVEMENT_ACTION_3F
    .short \length
    .endm

    .macro MoveAction_040 length=1
    .short MOVEMENT_ACTION_40
    .short \length
    .endm

    .macro MoveAction_041 length=1
    .short MOVEMENT_ACTION_41
    .short \length
    .endm

    .macro MoveAction_042 length=1
    .short MOVEMENT_ACTION_42
    .short \length
    .endm

    .macro MoveAction_043 length=1
    .short MOVEMENT_ACTION_43
    .short \length
    .endm

    .macro MoveAction_044 length=1
    .short MOVEMENT_ACTION_44
    .short \length
    .endm

    .macro MoveAction_045 length=1
    .short MOVEMENT_ACTION_45
    .short \length
    .endm

    .macro MoveAction_046 length=1
    .short MOVEMENT_ACTION_46
    .short \length
    .endm

    .macro MoveAction_047 length=1
    .short MOVEMENT_ACTION_47
    .short \length
    .endm

    .macro MoveAction_048 length=1
    .short MOVEMENT_ACTION_48
    .short \length
    .endm

    .macro MoveAction_049 length=1
    .short MOVEMENT_ACTION_49
    .short \length
    .endm

    .macro MoveAction_04A length=1
    .short MOVEMENT_ACTION_4A
    .short \length
    .endm

    .macro MoveAction_04B length=1
    .short MOVEMENT_ACTION_4B
    .short \length
    .endm

    .macro MoveAction_04C length=1
    .short MOVEMENT_ACTION_4C
    .short \length
    .endm

    .macro MoveAction_04D length=1
    .short MOVEMENT_ACTION_4D
    .short \length
    .endm

    .macro MoveAction_04E length=1
    .short MOVEMENT_ACTION_4E
    .short \length
    .endm

    .macro MoveAction_04F length=1
    .short MOVEMENT_ACTION_4F
    .short \length
    .endm

    .macro MoveAction_050 length=1
    .short MOVEMENT_ACTION_50
    .short \length
    .endm

    .macro MoveAction_051 length=1
    .short MOVEMENT_ACTION_51
    .short \length
    .endm

    .macro MoveAction_052 length=1
    .short MOVEMENT_ACTION_52
    .short \length
    .endm

    .macro MoveAction_053 length=1
    .short MOVEMENT_ACTION_53
    .short \length
    .endm

    .macro MoveAction_054 length=1
    .short MOVEMENT_ACTION_54
    .short \length
    .endm

    .macro MoveAction_055 length=1
    .short MOVEMENT_ACTION_55
    .short \length
    .endm

    .macro MoveAction_056 length=1
    .short MOVEMENT_ACTION_56
    .short \length
    .endm

    .macro MoveAction_057 length=1
    .short MOVEMENT_ACTION_57
    .short \length
    .endm

    .macro MoveAction_058 length=1
    .short MOVEMENT_ACTION_58
    .short \length
    .endm

    .macro MoveAction_059 length=1
    .short MOVEMENT_ACTION_59
    .short \length
    .endm

    .macro MoveAction_05A length=1
    .short MOVEMENT_ACTION_5A
    .short \length
    .endm

    .macro MoveAction_05B length=1
    .short MOVEMENT_ACTION_5B
    .short \length
    .endm

    .macro MoveAction_05C length=1
    .short MOVEMENT_ACTION_5C
    .short \length
    .endm

    .macro MoveAction_05D length=1
    .short MOVEMENT_ACTION_5D
    .short \length
    .endm

    .macro MoveAction_05E length=1
    .short MOVEMENT_ACTION_5E
    .short \length
    .endm

    .macro MoveAction_05F length=1
    .short MOVEMENT_ACTION_5F
    .short \length
    .endm

    .macro MoveAction_060 length=1
    .short MOVEMENT_ACTION_60
    .short \length
    .endm

    .macro MoveAction_061 length=1
    .short MOVEMENT_ACTION_61
    .short \length
    .endm

    .macro MoveAction_062 length=1
    .short MOVEMENT_ACTION_62
    .short \length
    .endm

    .macro MoveAction_063 length=1
    .short MOVEMENT_ACTION_63
    .short \length
    .endm

    .macro MoveAction_064 length=1
    .short MOVEMENT_ACTION_64
    .short \length
    .endm

    .macro MoveAction_065 length=1
    .short MOVEMENT_ACTION_65
    .short \length
    .endm

    .macro MoveAction_066 length=1
    .short MOVEMENT_ACTION_66
    .short \length
    .endm

    .macro MoveAction_067 length=1
    .short MOVEMENT_ACTION_67
    .short \length
    .endm

    .macro MoveAction_068 length=1
    .short MOVEMENT_ACTION_68
    .short \length
    .endm

    .macro MoveAction_069 length=1
    .short MOVEMENT_ACTION_69
    .short \length
    .endm

    .macro MoveAction_06A length=1
    .short MOVEMENT_ACTION_6A
    .short \length
    .endm

    .macro MoveAction_06B length=1
    .short MOVEMENT_ACTION_6B
    .short \length
    .endm

    .macro MoveAction_06C length=1
    .short MOVEMENT_ACTION_6C
    .short \length
    .endm

    .macro MoveAction_06D length=1
    .short MOVEMENT_ACTION_6D
    .short \length
    .endm

    .macro MoveAction_06E length=1
    .short MOVEMENT_ACTION_6E
    .short \length
    .endm

    .macro MoveAction_06F length=1
    .short MOVEMENT_ACTION_6F
    .short \length
    .endm

    .macro MoveAction_070 length=1
    .short MOVEMENT_ACTION_70
    .short \length
    .endm

    .macro MoveAction_071 length=1
    .short MOVEMENT_ACTION_71
    .short \length
    .endm

    .macro MoveAction_072 length=1
    .short MOVEMENT_ACTION_72
    .short \length
    .endm

    .macro MoveAction_073 length=1
    .short MOVEMENT_ACTION_73
    .short \length
    .endm

    .macro MoveAction_074 length=1
    .short MOVEMENT_ACTION_74
    .short \length
    .endm

    .macro MoveAction_075 length=1
    .short MOVEMENT_ACTION_75
    .short \length
    .endm

    .macro MoveAction_076 length=1
    .short MOVEMENT_ACTION_76
    .short \length
    .endm

    .macro MoveAction_077 length=1
    .short MOVEMENT_ACTION_77
    .short \length
    .endm

    .macro MoveAction_078 length=1
    .short MOVEMENT_ACTION_78
    .short \length
    .endm

    .macro MoveAction_079 length=1
    .short MOVEMENT_ACTION_79
    .short \length
    .endm

    .macro MoveAction_07A length=1
    .short MOVEMENT_ACTION_7A
    .short \length
    .endm

    .macro MoveAction_07B length=1
    .short MOVEMENT_ACTION_7B
    .short \length
    .endm

    .macro MoveAction_07C length=1
    .short MOVEMENT_ACTION_7C
    .short \length
    .endm

    .macro MoveAction_07D length=1
    .short MOVEMENT_ACTION_7D
    .short \length
    .endm

    .macro MoveAction_07E length=1
    .short MOVEMENT_ACTION_7E
    .short \length
    .endm

    .macro MoveAction_07F length=1
    .short MOVEMENT_ACTION_7F
    .short \length
    .endm

    .macro MoveAction_080 length=1
    .short MOVEMENT_ACTION_80
    .short \length
    .endm

    .macro MoveAction_081 length=1
    .short MOVEMENT_ACTION_81
    .short \length
    .endm

    .macro MoveAction_082 length=1
    .short MOVEMENT_ACTION_82
    .short \length
    .endm

    .macro MoveAction_083 length=1
    .short MOVEMENT_ACTION_83
    .short \length
    .endm

    .macro MoveAction_084 length=1
    .short MOVEMENT_ACTION_84
    .short \length
    .endm

    .macro MoveAction_085 length=1
    .short MOVEMENT_ACTION_85
    .short \length
    .endm

    .macro MoveAction_086 length=1
    .short MOVEMENT_ACTION_86
    .short \length
    .endm

    .macro MoveAction_087 length=1
    .short MOVEMENT_ACTION_87
    .short \length
    .endm

    .macro MoveAction_088 length=1
    .short MOVEMENT_ACTION_88
    .short \length
    .endm

    .macro MoveAction_089 length=1
    .short MOVEMENT_ACTION_89
    .short \length
    .endm

    .macro MoveAction_08A length=1
    .short MOVEMENT_ACTION_8A
    .short \length
    .endm

    .macro MoveAction_08B length=1
    .short MOVEMENT_ACTION_8B
    .short \length
    .endm

    .macro MoveAction_08C length=1
    .short MOVEMENT_ACTION_8C
    .short \length
    .endm

    .macro MoveAction_08D length=1
    .short MOVEMENT_ACTION_8D
    .short \length
    .endm

    .macro MoveAction_08E length=1
    .short MOVEMENT_ACTION_8E
    .short \length
    .endm

    .macro MoveAction_08F length=1
    .short MOVEMENT_ACTION_8F
    .short \length
    .endm

    .macro MoveAction_090 length=1
    .short MOVEMENT_ACTION_90
    .short \length
    .endm

    .macro MoveAction_091 length=1
    .short MOVEMENT_ACTION_91
    .short \length
    .endm

    .macro MoveAction_092 length=1
    .short MOVEMENT_ACTION_92
    .short \length
    .endm

    .macro MoveAction_093 length=1
    .short MOVEMENT_ACTION_93
    .short \length
    .endm

    .macro MoveAction_094 length=1
    .short MOVEMENT_ACTION_94
    .short \length
    .endm

    .macro MoveAction_095 length=1
    .short MOVEMENT_ACTION_95
    .short \length
    .endm

    .macro MoveAction_096 length=1
    .short MOVEMENT_ACTION_96
    .short \length
    .endm

    .macro MoveAction_097 length=1
    .short MOVEMENT_ACTION_97
    .short \length
    .endm

    .macro MoveAction_098 length=1
    .short MOVEMENT_ACTION_98
    .short \length
    .endm

    .macro MoveAction_099 length=1
    .short MOVEMENT_ACTION_99
    .short \length
    .endm

    .macro EndMovement
    .short MOVEMENT_ACTION_END
    .short 0
    .endm
