#ifndef DWC_LOBBY_H_
#define DWC_LOBBY_H_

#include <dwc.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef WIN32
#pragma pack(push, 4)
#endif

#define DWC_LOBBY_INVALID_USER_ID -1
#define DWC_LOBBY_INVALID_TIME 0
#define DWC_LOBBY_MAX_STRING_SIZE 400
#define DWC_LOBBY_MAX_CHANNEL_NAME_SIZE 20
#define DWC_LOBBY_MAX_CHANNEL_TOPIC_SIZE DWC_LOBBY_MAX_STRING_SIZE
#define DWC_LOBBY_MAX_CHANNEL_KEY_SIZE 20
#define DWC_LOBBY_MAX_CHANNEL_PASSWORD_SIZE 20

typedef enum DWC_LOBBY_CHANNEL_PREFIX {
    DWC_LOBBY_CHANNEL_PREFIX_RELEASE,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG1,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG2,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG3,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG4,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG5,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG6,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG7,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG8,
    DWC_LOBBY_CHANNEL_PREFIX_DEBUG9,
    DWC_LOBBY_CHANNEL_PREFIX_TEST
} DWC_LOBBY_CHANNEL_PREFIX;

#ifdef WIN32
#pragma pack(pop)
#endif

#ifdef __cplusplus
}
#endif

#endif
