#include "goods.h"

#include <nitro.h>
#include <string.h>

#include "constants/goods.h"

#include "overlay023/underground_defs.h"

#include "res/text/bank/underground_records.h"

typedef struct SpherePrice {
    u8 sphereType;
    u8 minSize;
    u8 maxSize;
} SpherePrice;

typedef struct Good {
    u8 width;
    u8 depth;
    u8 collision[9];
    SpherePrice spherePrice;
    int moneyPrice;
    int interactMessageID;
    u8 natDexRequired;
    u8 ungiftable;
} Good;

// clang-format off
static const Good sGoods[] = {
    [GOOD_NONE] = {
        .width = 0,
        .depth = 0,
        .collision = { 
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PC_NORMAL_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PC_BRONZE_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PC_SILVER_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PC_GOLD_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PC_PLATINUM_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BIG_BOULDER] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_YELLOW_CUSHION] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 500,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BLUE_CUSHION] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_WOODEN_CHAIR] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BIG_TABLE] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 1, 1,
            1, 1, 1,
            1, 1, 1,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PLAIN_TABLE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_SMALL_TABLE] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_LONG_TABLE] = {
        .width = 1,
        .depth = 3,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            1, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_WIDE_TABLE] = {
        .width = 3,
        .depth = 1,
        .collision = {
            1, 1, 1,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_POKE_TABLE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BIG_BOOKSHELF] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00037,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_SMALL_BOOKSHELF] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00037,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_RESEARCH_SHELF] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00036,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BIKE_RACK] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 35,
            .maxSize = 49,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00038,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_SHOP_SHELF] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 35,
            .maxSize = 49,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00034,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_DISPLAY_SHELF] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00041,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_CUPBOARD] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 1000,
        .interactMessageID = pl_msg_00000640_00040,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_WOOD_DRESSER] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PINK_DRESSER] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 50,
            .maxSize = 60,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_TV] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 9,
            .maxSize = 10,
        },
        .moneyPrice = 4500,
        .interactMessageID = pl_msg_00000640_00032,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_REFRIGERATOR] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 1000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PRETTY_SINK] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 9,
            .maxSize = 10,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_FEATHERY_BED] = {
        .width = 3,
        .depth = 3,
        .collision = {
            0, 1, 0,
            0, 0, 0,
            0, 1, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_TRASH_CAN] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00039,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_CARDBOARD_BOX] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00044,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_CRATE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00044,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_CONTAINER] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00044,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_OIL_DRUM] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BIG_OIL_DRUM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_IRON_BEAM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 9,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_POTTED_PLANT] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_POKE_FLOWER] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_HEALING_MACHINE] = {
        .width = 2,
        .depth = 3,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            1, 1, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 90,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00045,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_LAB_MACHINE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 28,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00043,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_TEST_MACHINE] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 28,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00042,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_GAME_SYSTEM] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00032,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_VENDING_MACHINE] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_RED_BIKE] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_GREEN_BIKE] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BINOCULARS] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_GLOBE] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 1, 1,
            1, 1, 1,
            1, 1, 1,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00033,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_GYM_STATUE] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = pl_msg_00000640_00035,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_RED_TENT] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BLUE_TENT] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_CLEAR_TENT] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_MAZE_BLOCK_1] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 1, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_MAZE_BLOCK_2] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 1,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_MAZE_BLOCK_3] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 1, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_MAZE_BLOCK_4] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            1, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_MAZE_BLOCK_5] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_HOLE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 10,
            .maxSize = 12,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_PIT_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_SMOKE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 12,
            .maxSize = 14,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_BIG_SMOKE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 28,
            .maxSize = 32,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_ROCK_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 10,
            .maxSize = 12,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_ROCKFALL_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_FOAM_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 14,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_BUBBLE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 28,
            .maxSize = 32,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_ALERT_TOOL_1] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_ALERT_TOOL_2] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_ALERT_TOOL_3] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_ALERT_TOOL_4] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_LEAF_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 30,
            .maxSize = 38,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_FLOWER_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 65,
            .maxSize = 80,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_EMBER_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 15,
            .maxSize = 18,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_FIRE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [GOOD_CUTE_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_COOL_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BEAUTY_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_TOUGH_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_CLEVER_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BLUE_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_PINK_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_RED_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_YELLOW_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_PRETTY_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_SHINY_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_MYSTIC_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_GLITTER_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BRONZE_TROPHY] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_SILVER_TROPHY] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_GOLD_TROPHY] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_GREAT_TROPHY_UNUSED] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BALL_ORNAMENT_UNUSED] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_ROUND_ORNAMENT_UNUSED] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_CLEAR_ORNAMENT_UNUSED] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_CHARMANDER_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_BULBASAUR_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_SQUIRTLE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_CYNDAQUIL_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_CHIKORITA_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_TOTODILE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_TORCHIC_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_TREECKO_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_MUDKIP_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_CHIMCHAR_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_TURTWIG_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 35,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_PIPLUP_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 35,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_PIKACHU_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 70,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_PLUSLE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 60,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_MINUN_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 60,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_CLEFAIRY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_JIGGLYPUFF_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_WOBBUFFET_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 80,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_MEOWTH_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 15,
            .maxSize = 20,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_SKITTY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 15,
            .maxSize = 20,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_GLAMEOW_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 15,
            .maxSize = 20,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BUNEARY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 15,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_WEAVILE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 28,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_MUNCHLAX_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 2000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BONSLY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 2000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_MIME_JR_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 2000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_LUCARIO_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_MANTYKE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BUIZEL_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_CHATOT_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_MANAPHY_DOLL_UNUSED] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_SNORLAX_DOLL] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 80,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_WAILORD_DOLL] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 80,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [GOOD_MAGNEZONE_DOLL_UNUSED] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_DRIFLOON_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_HAPPINY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_PACHIRISU_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 70,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [GOOD_BASE_ENTRANCE_SOUTH] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BASE_ENTRANCE_NORTH] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BASE_ENTRANCE_EAST] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BASE_ENTRANCE_WEST] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_WIDE_SOFA] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_BONSAI] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_DAINTY_FLOWERS] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_LOVELY_FLOWERS] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_PRETTY_FLOWERS] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [GOOD_LAVISH_FLOWERS] = {
        .width = 3,
        .depth = 1,
        .collision = {
            1, 1, 1,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
};
// clang-format on

u8 Good_GetWidth(int goodID)
{
    return sGoods[goodID].width;
}

u8 Good_GetDepth(int goodID)
{
    return sGoods[goodID].depth;
}

const u8 *Good_GetCollision(int goodID)
{
    return sGoods[goodID].collision;
}

u8 Good_GetSpherePriceType(int goodID)
{
    return sGoods[goodID].spherePrice.sphereType;
}

u8 Good_GetSpherePriceMinSize(int goodID)
{
    return sGoods[goodID].spherePrice.minSize;
}

u8 Good_GetSpherePriceMaxSize(int goodID)
{
    return sGoods[goodID].spherePrice.maxSize;
}

int Good_GetMoneyPrice(int goodID)
{
    return sGoods[goodID].moneyPrice;
}

int Good_GetInteractMessageID(int goodID)
{
    return sGoods[goodID].interactMessageID;
}

BOOL Good_IsNatDexRequired(int goodID)
{
    return sGoods[goodID].natDexRequired;
}

BOOL Good_IsUngiftable(int goodID)
{
    return sGoods[goodID].ungiftable;
}
