#include "goods.h"

#include <nitro.h>
#include <string.h>

#include "generated/goods.h"

#include "overlay023/underground_defs.h"

#include "res/text/bank/underground_records.h"

typedef struct GoodData {
    u8 width;
    u8 depth;
    u8 collision[9];
    SpherePrice spherePrice;
    int moneyPrice;
    int interactMessageID;
    u8 natDexRequired;
    u8 ungiftable;
} GoodData;

// clang-format off
static const GoodData sGoodData[] = {
    [UG_GOOD_NONE] = {
        .width = 0,
        .depth = 0,
        .collision = { 
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PC_NORMAL_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PC_BRONZE_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PC_SILVER_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PC_GOLD_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PC_PLATINUM_FLAG] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BIG_BOULDER] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_YELLOW_CUSHION] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 500,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BLUE_CUSHION] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_WOODEN_CHAIR] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BIG_TABLE] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 1, 1,
            1, 1, 1,
            1, 1, 1,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PLAIN_TABLE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_SMALL_TABLE] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_LONG_TABLE] = {
        .width = 1,
        .depth = 3,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            1, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_WIDE_TABLE] = {
        .width = 3,
        .depth = 1,
        .collision = {
            1, 1, 1,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_POKE_TABLE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BIG_BOOKSHELF] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenFossilsDug,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_SMALL_BOOKSHELF] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenFossilsDug,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_RESEARCH_SHELF] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenSpheresDug,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BIKE_RACK] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 35,
            .maxSize = 49,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTrapHits,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_SHOP_SHELF] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 35,
            .maxSize = 49,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenGiftsGiven,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_DISPLAY_SHELF] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenGiftsReceived,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_CUPBOARD] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 1000,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenOthersHelped,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_WOOD_DRESSER] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PINK_DRESSER] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 50,
            .maxSize = 60,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_TV] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 9,
            .maxSize = 10,
        },
        .moneyPrice = 4500,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTotalScore,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_REFRIGERATOR] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 12,
            .maxSize = 15,
        },
        .moneyPrice = 1000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PRETTY_SINK] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 9,
            .maxSize = 10,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_FEATHERY_BED] = {
        .width = 3,
        .depth = 3,
        .collision = {
            0, 1, 0,
            0, 0, 0,
            0, 1, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_TRASH_CAN] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTrapsHit,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_CARDBOARD_BOX] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTimesBaseMoved,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_CRATE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTimesBaseMoved,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_CONTAINER] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTimesBaseMoved,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_OIL_DRUM] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BIG_OIL_DRUM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_IRON_BEAM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 9,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_POTTED_PLANT] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_POKE_FLOWER] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_HEALING_MACHINE] = {
        .width = 2,
        .depth = 3,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            1, 1, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 90,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenFlagsRegistered,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_LAB_MACHINE] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 28,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenRecoveredFlags,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_TEST_MACHINE] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 28,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenOwnFlagsTaken,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_GAME_SYSTEM] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenTotalScore,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_VENDING_MACHINE] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_RED_BIKE] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_GREEN_BIKE] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BINOCULARS] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 10,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_GLOBE] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 1, 1,
            1, 1, 1,
            1, 1, 1,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenPeopleMet,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_GYM_STATUE] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = UndergroundRecords_Text_SomethingWrittenFlagsObtained,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_RED_TENT] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BLUE_TENT] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_CLEAR_TENT] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_MAZE_BLOCK_1] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 1, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_MAZE_BLOCK_2] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 1,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_MAZE_BLOCK_3] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 1, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_MAZE_BLOCK_4] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            1, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_MAZE_BLOCK_5] = {
        .width = 3,
        .depth = 3,
        .collision = {
            1, 0, 1,
            0, 0, 0,
            1, 0, 1,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 48,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_HOLE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 10,
            .maxSize = 12,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PIT_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_SMOKE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 12,
            .maxSize = 14,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BIG_SMOKE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 28,
            .maxSize = 32,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_ROCK_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 10,
            .maxSize = 12,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_ROCKFALL_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_FOAM_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 12,
            .maxSize = 14,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BUBBLE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 28,
            .maxSize = 32,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_ALERT_TOOL_1] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_ALERT_TOOL_2] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_ALERT_TOOL_3] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_ALERT_TOOL_4] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 20,
            .maxSize = 50,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_LEAF_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 30,
            .maxSize = 38,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_FLOWER_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 65,
            .maxSize = 80,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_EMBER_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 15,
            .maxSize = 18,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_FIRE_TOOL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            0, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_CUTE_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_COOL_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BEAUTY_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_TOUGH_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CLEVER_CUP] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BLUE_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_PINK_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_RED_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_YELLOW_CRYSTAL] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_PRETTY_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_SHINY_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MYSTIC_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_GLITTER_GEM] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BRONZE_TROPHY] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_SILVER_TROPHY] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_GOLD_TROPHY] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_GREAT_TROPHY_UNUSED] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BALL_ORNAMENT_UNUSED] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_ROUND_ORNAMENT_UNUSED] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CLEAR_ORNAMENT_UNUSED] = {
        .width = 2,
        .depth = 2,
        .collision = {
            1, 1, 0,
            1, 1, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CHARMANDER_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BULBASAUR_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_SQUIRTLE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CYNDAQUIL_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CHIKORITA_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_TOTODILE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_TORCHIC_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_TREECKO_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MUDKIP_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 25,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CHIMCHAR_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 25,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_TURTWIG_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 35,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_PIPLUP_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 35,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_PIKACHU_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 70,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_PLUSLE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 60,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MINUN_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 60,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CLEFAIRY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_JIGGLYPUFF_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_WOBBUFFET_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 80,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MEOWTH_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 15,
            .maxSize = 20,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_SKITTY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 15,
            .maxSize = 20,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_GLAMEOW_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 15,
            .maxSize = 20,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BUNEARY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 15,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_WEAVILE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PRISM_SPHERE,
            .minSize = 28,
            .maxSize = 30,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MUNCHLAX_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 2000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BONSLY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 2000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MIME_JR_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 2000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_LUCARIO_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MANTYKE_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BUIZEL_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_CHATOT_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 3000,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MANAPHY_DOLL_UNUSED] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_SNORLAX_DOLL] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = RED_SPHERE,
            .minSize = 80,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_WAILORD_DOLL] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 80,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = TRUE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_MAGNEZONE_DOLL_UNUSED] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_DRIFLOON_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 33,
            .maxSize = 40,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_HAPPINY_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 40,
            .maxSize = 70,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_PACHIRISU_DOLL] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = PALE_SPHERE,
            .minSize = 70,
            .maxSize = 99,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = TRUE,
    },
    [UG_GOOD_BASE_ENTRANCE_NORTH] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BASE_ENTRANCE_SOUTH] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BASE_ENTRANCE_WEST] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BASE_ENTRANCE_EAST] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = SPHERE_NONE,
            .minSize = 0,
            .maxSize = 0,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_WIDE_SOFA] = {
        .width = 2,
        .depth = 1,
        .collision = {
            1, 1, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = BLUE_SPHERE,
            .minSize = 20,
            .maxSize = 25,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_BONSAI] = {
        .width = 1,
        .depth = 1,
        .collision = {
            1, 0, 0,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_DAINTY_FLOWERS] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_LOVELY_FLOWERS] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_PRETTY_FLOWERS] = {
        .width = 1,
        .depth = 2,
        .collision = {
            1, 0, 0,
            1, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
    [UG_GOOD_LAVISH_FLOWERS] = {
        .width = 3,
        .depth = 1,
        .collision = {
            1, 1, 1,
            0, 0, 0,
            0, 0, 0,
        },
        .spherePrice = {
            .sphereType = GREEN_SPHERE,
            .minSize = 8,
            .maxSize = 10,
        },
        .moneyPrice = 0,
        .interactMessageID = 0,
        .natDexRequired = FALSE,
        .ungiftable = FALSE,
    },
};
// clang-format on

u8 Good_GetWidth(enum Good goodID)
{
    return sGoodData[goodID].width;
}

u8 Good_GetDepth(enum Good goodID)
{
    return sGoodData[goodID].depth;
}

const u8 *Good_GetCollision(enum Good goodID)
{
    return sGoodData[goodID].collision;
}

u8 Good_GetSpherePriceType(enum Good goodID)
{
    return sGoodData[goodID].spherePrice.sphereType;
}

u8 Good_GetSpherePriceMinSize(enum Good goodID)
{
    return sGoodData[goodID].spherePrice.minSize;
}

u8 Good_GetSpherePriceMaxSize(enum Good goodID)
{
    return sGoodData[goodID].spherePrice.maxSize;
}

int Good_GetMoneyPrice(enum Good goodID)
{
    return sGoodData[goodID].moneyPrice;
}

int Good_GetInteractMessageID(enum Good goodID)
{
    return sGoodData[goodID].interactMessageID;
}

BOOL Good_IsNatDexRequired(enum Good goodID)
{
    return sGoodData[goodID].natDexRequired;
}

BOOL Good_IsUngiftable(enum Good goodID)
{
    return sGoodData[goodID].ungiftable;
}
