#include "common.h"

#include <assert.h>
#include <errno.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "dataproc.h"
#include "enum.h"
#include "nitroarc.h"

#define MAX_LOADED_ENUMS 128

static enum_t loaded_enums[MAX_LOADED_ENUMS] = { 0 };
static size_t num_loaded_enums = 0;

static void   unload_enums(void);
static void   finish_headers(void);
static FILE*  open_depfile(const char *depfile_path);
static void   load_header_template(header_template_t *h, FILE *depfile);
static enum_t dp_include(
    const char *from_file,
    const char *with_prefix,
    const char *for_type,
    bool        from_defs,
    FILE       *depfile
);

static archive_template_t *s_archives   = NULL;
static header_template_t  *s_headers    = NULL;
static order_template_t   *s_orders     = NULL;
static const char         *s_output_dir = NULL;

static void* crt_malloc(void *ctx, unsigned items, unsigned size) {
    (void)ctx;
    return malloc(items * size);
}

static void* crt_realloc(void *ctx, void *p, unsigned items, unsigned size) {
    (void)ctx;
    return realloc(p, items * size);
}

static void crt_free(void *ctx, void *p, unsigned items, unsigned size) {
    (void)ctx;
    (void)items;
    (void)size;
    free(p);
}

#define default_packer() (nitroarc_packer_t){ \
    .malloc  = crt_malloc,                    \
    .realloc = crt_realloc,                   \
    .free    = crt_free,                      \
}

static const char *header_comment = ""
    "/*\n"
    " * This header was generated by %s\n"
    " * DO NOT MODIFY IT!!!\n"
    " */\n";

static FILE* open_depfile(const char *depfile_path) {
    FILE *depfile = fopen(depfile_path, "wb");
    if (depfile == NULL) {
        fprintf(stderr, "error opening depfile '%s': %s\n",
                depfile_path, strerror(errno));
        exit(EXIT_FAILURE);
    }

    return depfile;
}

void common_init(
    enum format         format,
    enum_template_t    *lookups,
    archive_template_t *archives,
    header_template_t  *headers,
    order_template_t   *orders,
    const char         *source_name,
    const char         *depfile_path,
    const char         *output_dir,
    void              (*pre_init_hook)(void),
    void              (*post_init_hook)(void)
) {
    dp_init(format);
    if (pre_init_hook) pre_init_hook();

    s_archives   = archives;
    s_headers    = headers;
    s_orders     = orders;
    s_output_dir = output_dir;
    atexit(unload_enums);
    atexit(finish_headers);

    FILE *depfile = open_depfile(depfile_path);

    // Initialize all the requested iteratively-packed archives
    for (archive_template_t *to_init = archives; to_init && to_init->out_filename; to_init++) {
        to_init->packer = default_packer();
        int errc = nitroarc_pinit(
            &to_init->packer,
            to_init->num_files,
            to_init->named,
            to_init->stripped
        );

        if (errc) {
            fprintf(stderr, "nitroarc initialization error: %s\n",
                    nitroarc_errs(errc));
            exit(EXIT_FAILURE);
        }

        char *full_path = pathjoin(output_dir, NULL, to_init->out_filename);
        fputs(full_path, depfile);
        fputc(' ',       depfile);
        free(full_path);
    }

    // Prepare iteratively-written headers
    for (header_template_t *to_init = headers; to_init && to_init->out_filename; to_init++) {
        char *full_path   = pathjoin(output_dir, NULL, to_init->out_filename);
        to_init->out_file = fopen(full_path, "wb");
        if (to_init->out_file == NULL) {
            fprintf(stderr, "could not open output file '%s': %s",
                    full_path, strerror(errno));
            exit(EXIT_FAILURE);
        }

        fprintf(to_init->out_file, header_comment, source_name);

        fputs(full_path, depfile);
        fputc(' ',       depfile);
        free(full_path);
    }

    // Prepare iteratively-written order files
    for (order_template_t *to_init = orders; to_init && to_init->out_filename; to_init++) {
        char *full_path   = pathjoin(output_dir, NULL, to_init->out_filename);
        to_init->out_file = fopen(full_path, "wb");
        if (to_init->out_file == NULL) {
            fprintf(stderr, "could not open output file '%s': %s",
                    full_path, strerror(errno));
            exit(EXIT_FAILURE);
        }

        fputs(full_path, depfile);
        fputc(' ',       depfile);
        free(full_path);
    }

    fputs(": ", depfile);

    // Load all the requested lookup-tables from their sources
    for (enum_template_t *to_load = lookups; to_load && to_load->from_file; to_load++) {
        loaded_enums[num_loaded_enums++] = dp_include(
            to_load->from_file,
            to_load->with_prefix,
            to_load->for_type,
            to_load->from_defs,
            depfile
        );
    }

    // Second pass: load a header template as a dependency
    for (header_template_t *to_init = headers; to_init && to_init->out_filename; to_init++) {
        load_header_template(to_init, depfile);
        fputs(to_init->header, to_init->out_file);
    }

    if (post_init_hook) post_init_hook();
    fclose(depfile);
}

#define HEADER_TEMPLATE_SUFFIX ".template"
#define HEADER_TEMPLATE_MAGIC  "/* =========== MAGIC CONTENT MARKER =========== */"

static void load_header_template(header_template_t *h, FILE *depfile) {
    size_t len_out_fname  = strlen(h->out_filename);
    char  *template_fname = calloc(len_out_fname + sizeof(HEADER_TEMPLATE_SUFFIX) + 1, 1);
    assert(template_fname);

    if (template_fname == NULL) exit(EXIT_FAILURE);
    memcpy(template_fname, h->out_filename, len_out_fname);
    memcpy(template_fname + len_out_fname, HEADER_TEMPLATE_SUFFIX, sizeof(HEADER_TEMPLATE_SUFFIX));

    char *full_path = pathjoin(TEMPLATES_DIR, NULL, template_fname);
    char *template  = fload(full_path);
    char *marker    = strstr(template, HEADER_TEMPLATE_MAGIC);
    char *footer    = marker + sizeof(HEADER_TEMPLATE_MAGIC);
    *marker         = '\0';

    h->header = template;
    h->footer = footer;

    fputs(full_path, depfile);
    fputc(' ',       depfile);

    free(full_path);
    free(template_fname);
}

static void unload_enums(void) {
    for (size_t i = 0; i < num_loaded_enums; i++) enum_free(&loaded_enums[i]);
}

static void finish_headers(void) {
    for (header_template_t *h = s_headers; h && h->out_filename; h++) {
        if (h->out_file) {
            fputs(h->footer, h->out_file);
            fclose(h->out_file);
            free(h->header);
        }
    }
}

int common_done(int errc, int (*addl_done_hook)(void)) {
    for (archive_template_t *a = s_archives; a && a->out_filename; a++) {
        if (fdump_narc(&a->packer, a->out_filename, errc == 0)) errc = EXIT_FAILURE;
    }

    for (order_template_t *o = s_orders; o && o->out_filename; o++) {
        if (fclose(o->out_file)) errc = EXIT_FAILURE;
    }

    if (addl_done_hook) errc = addl_done_hook() || errc;
    return errc;
}

char* strremove(char *s, const char *sub) {
    size_t len = strlen(sub);
    if (len == 0) return s;

    char *p = s;
    while ((p = strstr(p, sub)) != NULL) {
        memmove(p, p + len, strlen(p + len) + 1);
    }

    return s;
}

char* strreplace(char *s, char r, char c) {
    for (char *p = s; *p; p++) {
        if (*p == r) *p = c;
    }

    return s;
}

char* strupper(const char *s) {
    char *capped = calloc(strlen(s) + 1, 1);
    for (size_t i = 0; i < strlen(s); i++) {
        capped[i] = s[i];
        if (capped[i] >= 'a' && capped[i] <= 'z') capped[i] -= ('a' - 'A');
    }

    return capped;
}

void splitenv(const char *name, char ***target, size_t *target_len, const char **extra, size_t extra_len) {
    char *envvar = getenv(name);
    if (envvar == NULL) {
        fprintf(stderr, "environment variable %s is undefined\n", name);
        exit(EXIT_FAILURE);
    }

    *target_len = 1;
    for (char *p = envvar; *p; p++) {
        if (*p == ';') (*target_len)++;
    }

    char *envcopy = malloc(strlen(envvar) + 1);
    memcpy(envcopy, envvar, strlen(envvar) + 1);

    *target = calloc(*target_len + extra_len, sizeof(char*));
    char *p = envcopy;
    for (size_t i = 0; i < *target_len; i++) {
        (*target)[i] = p;

        while (*p != ';' && *p != 0) p++;
        *p = 0;
        p++;
    }

    if (extra) {
        for (size_t i = 0; i < extra_len; i++) {
            (*target)[*target_len + i] = (char *)extra[i];
        }

        *target_len += extra_len;
    }

    if (*target_len > UINT16_MAX) {
        fprintf(stderr, "too many values defined; max: %u, got: %zu\n", UINT16_MAX, *target_len);
        exit(EXIT_FAILURE);
    }
}

char* fload(const char *filename) {
    char *buf = NULL;
    FILE *f   = fopen(filename, "rb");
    if (f == NULL) {
        fprintf(stderr, "could not open file '%s': %s\n", filename, strerror(errno));
        return NULL;
    }

    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (fsize < 0)  {
        fprintf(stderr, "could not open file '%s': %s\n", filename, strerror(errno));
        goto cleanup;
    }

    if ((buf = malloc(fsize + 1)) == NULL) {
        fprintf(stderr, "allocation failure for file '%s': %s", filename, strerror(errno));
        goto cleanup;
    }

    fread(buf, 1, fsize, f);
    buf[fsize] = 0;

cleanup:
    fclose(f);
    return buf;
}

char* pathjoin(const char *basedir, const char *subdir, const char *file) {
    size_t size = strlen(basedir) + 1 + strlen(file) + 1 + (subdir ? strlen(subdir) + 1 : 0);
    char  *path = malloc(size);
    if (subdir) snprintf(path, size, "%s/%s/%s", basedir, subdir, file);
    else        snprintf(path, size, "%s/%s", basedir, file);
    return path;
}

char* guardify(const char *path) {
    char *guarded = strupper(path);
    for (size_t i = 0; i < strlen(guarded); i++) {
        if (guarded[i] >= '0' && guarded[i] <= '9') continue;
        if (guarded[i] >= 'A' && guarded[i] <= 'Z') continue;
        guarded[i] = '_';
    }

    return guarded;
}

int fdump_blob(const void *data, size_t size, const char *dest) {
    char *full_path = pathjoin(s_output_dir, NULL, dest);
    FILE *outf      = fopen(full_path, "wb");
    if (!outf) {
        fprintf(stderr, "error opening '%s': %s\n", full_path, strerror(errno));
        return EXIT_FAILURE;
    }

    long written = fwrite(data, 1, size, outf);
    if (written != (long)size) {
        fprintf(stderr, "incomplete write to '%s': %s\n", full_path, strerror(errno));
        fclose(outf);
        return EXIT_FAILURE;
    }

    fclose(outf);
    free(full_path);
    return EXIT_SUCCESS;
}

int fdump_narc(nitroarc_packer_t *p, const char *dest, bool ok) {
    char *data = NULL;
    u32   size = 0;

    int errc = nitroarc_pseal(p, (void **)&data, &size);
    if (errc) {
        fprintf(stderr, "error sealing archive '%s': %s\n", dest, nitroarc_errs(errc));
        return errc;
    }

    if (ok) errc = fdump_blob(data, size, dest);

    free(data);
    return errc;
}

int fdump_blobnarc(const void *data, u32 size, const char *name) {
    nitroarc_packer_t p = default_packer();
    nitroarc_pinit(&p, 1, false, false);
    nitroarc_ppack(&p, (void *)data, size, NULL);
    return fdump_narc(&p, name, true);
}

#define MAX_INCLUDES 16

static const char *include_paths[MAX_INCLUDES] = {
    REPO_INCLUDE,
    REPO_BUILD,
};

static enum_t dp_include(
    const char *from_file,
    const char *with_prefix,
    const char *for_type,
    bool        from_defs,
    FILE       *depfile
) {
    assert(from_file && "included filename must not be NULL");

    char *found_file = NULL;
    for (int i = 0; i < MAX_INCLUDES && include_paths[i]; i++) {
        char *full_path = pathjoin(include_paths[i], NULL, from_file);
        if (access(full_path, F_OK) == 0) { found_file = full_path; break; }
        else free(full_path);
    }

    if (!found_file) {
        fprintf(stderr, "could not find included file '%s'\n", from_file);
        exit(EXIT_FAILURE);
    }

    char  *buf    = fload(found_file);
    enum_t result = from_defs
        ? enum_parse_def(buf, with_prefix, ENUM_F_SORT | ENUM_F_CONVERT)
        : enum_parse_one(buf, ENUM_F_SORT | ENUM_F_CONVERT, NULL);

    dp_register((lookup_t *)result.syms, result.len, for_type);
    fputs(found_file, depfile);
    fputc(' ',        depfile);

    free(buf);
    free(found_file);
    return result;
}
