#ifndef POKEPLATINUM_GTS_SCREENS_NETWORK_HANDLER_H
#define POKEPLATINUM_GTS_SCREENS_NETWORK_HANDLER_H

#include "overlay094/gts_application_state.h"

int GTSApplication_NetworkHandler_Init(GTSApplicationState *appState, int unused);
int GTSApplication_NetworkHandler_Main(GTSApplicationState *appState, int unused);
int GTSApplication_NetworkHandler_Exit(GTSApplicationState *appState, int unused);

enum GTSNetworkHandlerScreenStates {
    GTS_NETHANDLER_PARSE_SCREEN_ARGUMENT,
    GTS_NETHANDLER_IDLE,
    GTS_NETHANDLER_BEGIN_POST_LISTING,
    GTS_NETHANDLER_WAIT_FOR_POST_RESPONSE,
    GTS_NETHANDLER_FINISH_POST,
    GTS_NETHANDLER_POST_FINISH_RESPONSE,
    GTS_NETHANDLER_TRADE_DEPOSIT,
    GTS_NETHANDLER_GET_LISTED_POKEMON_REQUEST,
    GTS_NETHANDLER_GET_LISTED_POKEMON_RESPONSE,
    GTS_NETHANDLER_RETURN_REQUEST,
    GTS_NETHANDLER_RETURN_RESPONSE,
    GTS_NETHANDLER_TRADE_TAKE_BACK,
    GTS_NETHANDLER_EXCHANGE_REQUEST,
    GTS_NETHANDLER_EXCHANGE_RESPONSE,
    GTS_NETHANDLER_EXCHANGE_FINISH_REQUEST,
    GTS_NETHANDLER_EXCHANGE_FINISH_RESPONSE,
    GTS_NETHANDLER_GO_TO_TRADE_DEPOSIT,
    GTS_NETHANDLER_SHOW_ALREADY_TRADED_ERROR,
    GTS_NETHANDLER_PERFORM_DEPOSIT_TRADE,
    GTS_NETHANDLER_DELETE_RECEIVED_POKEMON_REQUEST,
    GTS_NETHANDLER_DELETE_RECEIVED_POKEMON_RESPONSE,
    GTS_NETHANDLER_GO_TO_TRADE_TAKE_BACK,
    GTS_NETHANDLER_DELETE_DESYNCED_POKEMON_REQUEST,
    GTS_NETHANDLER_DELETE_DESYNCED_POKEMON_RESPONSE,
    GTS_NETHANDLER_GET_LISTING_STATUS_REQUEST,
    GTS_NETHANDLER_GET_LISTING_STATUS_RESPONSE,
    GTS_NETHANDLER_GET_LISTED_POKEMON_REQUEST_2,
    GTS_NETHANDLER_GET_LISTED_POKEMON_RESPONSE_2,
    GTS_NETHANDLER_RETURN_TO_MAIN_MENU,
    GTS_NETHANDLER_BEGIN_SAVE_SEQUENCE,
    GTS_NETHANDLER_PREPARE_FULL_SAVE,
    GTS_NETHANDLER_WAIT_FOR_FRAME_DELAY,
    GTS_NETHANDLER_WAIT_FOR_SAVE_PROCEED,
    GTS_NETHANDLER_WAIT_FOR_SAVE_COMPLETE,
    GTS_NETHANDLER_FULL_SAVE,
    GTS_NETHANDLER_WAIT_FOR_SUCCESSFUL_SAVE,
    GTS_NETHANDLER_FADE_AND_EXIT,
    GTS_NETHANDLER_WAIT_FOR_TEXT,
    GTS_NETHANDLER_SHOW_COMMS_ERROR_AND_DISCONNECT,
    GTS_NETHANDLER_SHOW_COMMS_ERROR_AND_RETURN_TO_MENU,
};

#endif // POKEPLATINUM_GTS_SCREENS_NETWORK_HANDLER_H
