name: build_win

on:
  push:
    branches: [ pc_port ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install MSys2
        run: .\Install_MSys2.ps1
        shell: powershell

      - name: Build (win64)
        run: .\Launch_Msys2.ps1 make win64
        shell: powershell

      - name: Package release artifact (win64)
        run: .\Launch_Msys2.ps1 ./tools/scripts/package_artifacts_win64.sh
        shell: powershell

      - name: Upload release artifact (win64)
        uses: actions/upload-artifact@v2
        with:
          name: release_win64
          path: build_win64/pokeplatinum/release_win64.zip