#ifndef POKEPLATINUM_CONSTANTS_SAVEDATA_MISC_H
#define POKEPLATINUM_CONSTANTS_SAVEDATA_MISC_H

#define RIVAL_NAME_LEN      7
#define TABLET_NAME_LEN     10

#endif // POKEPLATINUM_CONSTANTS_SAVEDATA_MISC_H
