#ifndef POKEPLATINUM_CONSTANTS_VARS_AND_FLAGS_H
#define POKEPLATINUM_CONSTANTS_VARS_AND_FLAGS_H

#include "generated/vars_flags.h"

#define NUM_VARS (VARS_END - VARS_START)

#endif // POKEPLATINUM_CONSTANTS_VARS_AND_FLAGS_H
